#!/usr/bin/env sage
"""Exact logarithmic reduction for the summed terminal CT packet.

This checker uses the certified Apéry Laurent polynomial

    Lambda = (1+x)(1+y)(1+z)((1+y)(1+z)+xyz)/(xyz).

It proves:

1. two twisted logarithmic projectors kill the restriction of an
   arbitrary Laurent numerator on every nonempty pairwise divisor
   intersection in the algebraic torus, at denominator cost
   ``(M+1)^2``;
2. the residual smooth logarithmic critical algebra has dimension two;
3. the projected terminal packet has a stable order-66 recurrence in
   that quotient, with primitive endpoints ``-2^6*7^3`` and ``2^24``.

The last result is a quotient recurrence, not yet a constant-term
annihilator.  Lifting a Jacobian remainder gives an explicit
moment-(M+1) source; see ``JACOBIAN_SOURCE_IDENTITY`` below.
"""

from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from q32_cartier_packet_audit import polytope_points


R.<x, y, z> = PolynomialRing(QQ, order="degrevlex")
A = 1 + x
B = 1 + y
C = 1 + z
D = (1 + y) * (1 + z) + x * y * z
F = A * B * C * D


def theta(polynomial, variable):
    return variable * polynomial.derivative(variable)


def vector_field(data, polynomial):
    coefficients, _ = data
    return sum(
        coefficient * theta(polynomial, variable)
        for coefficient, variable in zip(coefficients, (x, y, z))
    )


def divergence(data):
    coefficients, _ = data
    return sum(
        theta(coefficient, variable)
        for coefficient, variable in zip(coefficients, (x, y, z))
    )


def logarithmic_weight(data):
    coefficients, multiplier = data
    return multiplier - sum(coefficients)


# Column 1 in an exact Singular syzygy basis of
# [x*F_x,y*F_y,z*F_z,-F].  Its projector kills AB, AC, and AD at once.
G_ABC = (
    (
        -x - 1,
        R.zero(),
        (x + 1) * (z + 1),
    ),
    2 * x * z - x + 2 * z,
)

# (Column 3-column 2)/x in the same basis.  It is Laurent-integral on
# the torus, and its projector kills BC.
K = R.fraction_field()
G_BC = (
    (
        -(x + 1)
        * (2 * y * z**2 + y * z + 2 * z**2 - 4 * y + 6 * z + 1)
        / x,
        (y + 1)
        * (2 * x * z**2 + 5 * x * z + 2 * z**2 - 2 * x + 5 * z)
        / x,
        -(z + 1)
        * (
            4 * x * y
            - x * z
            + 2 * y * z
            + 2 * z**2
            - 3 * x
            + 5 * y
            + 2 * z
        )
        / x,
    ),
    -(4 * z**3 + 4 * z**2 + x) / x,
)

for data in (G_ABC, G_BC):
    assert vector_field(data, F) == data[1] * F


CURVE_SUBSTITUTIONS = {
    "AB": {x: -1, y: -1},
    "AC": {x: -1, z: -1},
    # On x=-1, D=0 is y+z+1=0.
    "AD": {x: -1, y: -z - 1},
    "BC": {y: -1, z: -1},
}


def restrict(polynomial, curve):
    return K(polynomial).subs(CURVE_SUBSTITUTIONS[curve])


# For T_{G,M}(f)=V(f)+(div(G)+M*weight(G))*f, G_ABC gives
# +(M+1) on AB,AC,AD and G_BC gives -(M+1) on BC.
for curve in ("AB", "AC", "AD"):
    assert all(restrict(entry, curve) == 0 for entry in G_ABC[0])
    assert restrict(logarithmic_weight(G_ABC), curve) == 1
    assert restrict(divergence(G_ABC), curve) == 1

assert all(restrict(entry, "BC") == 0 for entry in G_BC[0])
assert restrict(logarithmic_weight(G_BC), "BC") == -1
assert restrict(divergence(G_BC), "BC") == -1


def torus_saturation(ideal):
    return ideal.saturation(R.ideal(x * y * z))[0]


# BD and CD are empty on the torus: after B=0 one has D=-xz, and
# after C=0 one has D=-xy.
assert torus_saturation(R.ideal(B, D)).is_one()
assert torus_saturation(R.ideal(C, D)).is_one()

nonempty_pair_ideals = (
    torus_saturation(R.ideal(A, B)),
    torus_saturation(R.ideal(A, C)),
    torus_saturation(R.ideal(A, D)),
    torus_saturation(R.ideal(B, C)),
)
singular_pair_intersection = nonempty_pair_ideals[0]
for pair_ideal in nonempty_pair_ideals[1:]:
    singular_pair_intersection = singular_pair_intersection.intersection(
        pair_ideal
    )


# The logarithmic critical ideal is generated by theta_i(F)-F because
#
#     theta_i(F)-F = xyz*theta_i(Lambda).
#
# If a quotient recurrence has remainder
#     R = sum_i Q_i*theta_i(Lambda),
# then exact integration by parts gives
#
# CT[Lambda^M R]
#   = -1/(M+1) CT[Lambda^(M+1) sum_i theta_i(Q_i)].
#
# This is the moment-(M+1) Jacobian source that remains after the
# quotient recurrence.
JACOBIAN_SOURCE_IDENTITY = (
    "CT[Lambda^M sum_i Q_i theta_i(Lambda)] "
    "= -CT[Lambda^(M+1) sum_i theta_i(Q_i)]/(M+1)"
)

full_critical_ideal = torus_saturation(
    R.ideal(
        theta(F, x) - F,
        theta(F, y) - F,
        theta(F, z) - F,
    )
)
singular_component_ideal = full_critical_ideal + R.ideal(F)
assert all(
    singular_pair_intersection.reduce(generator) == 0
    for generator in singular_component_ideal.gens()
)
assert all(
    singular_component_ideal.reduce(generator) == 0
    for generator in singular_pair_intersection.gens()
)

smooth_critical_ideal = full_critical_ideal.saturation(R.ideal(F))[0]
critical_intersection = singular_component_ideal.intersection(
    smooth_critical_ideal
)
assert all(
    critical_intersection.reduce(generator) == 0
    for generator in full_critical_ideal.gens()
)
assert all(
    full_critical_ideal.reduce(generator) == 0
    for generator in critical_intersection.gens()
)
assert smooth_critical_ideal.dimension() == 0
assert smooth_critical_ideal.vector_space_dimension() == 2
assert smooth_critical_ideal.groebner_basis() == [
    z**2 - QQ(1) / 2,
    x - 2 * z - 1,
    y - z,
]


# The four weights of a full logarithmic-syzygy basis generate the
# smooth critical ideal directly.  This supplies a same-moment lift:
#
# CT[Lambda^M alpha_j*A]
#   = -CT[Lambda^M(V_j(A)+div(V_j)*A)]/M.
#
# Consequently the moment-(M+1) source above is a feature of the
# coordinate Jacobian lift, not an unavoidable source tower.
logarithmic_syzygies = R.ideal(
    x * F.derivative(x),
    y * F.derivative(y),
    z * F.derivative(z),
    -F,
).syzygy_module()
logarithmic_weights = []
logarithmic_divergences = []
for row in logarithmic_syzygies:
    coefficients = tuple(row[index] for index in range(3))
    multiplier_value = row[3]
    assert sum(
        coefficients[index]
        * theta(F, (x, y, z)[index])
        for index in range(3)
    ) == multiplier_value * F
    logarithmic_weights.append(
        multiplier_value - sum(coefficients)
    )
    logarithmic_divergences.append(
        sum(
            theta(coefficients[index], (x, y, z)[index])
            for index in range(3)
        )
    )

assert logarithmic_weights == [
    y - z,
    x * z - x + z,
    -2 * x * y + x * z + 2 * y * z - 2 * z**2
    - x + 2 * y + z + 2,
    -x * z**2 + 2 * y * z**2 - 2 * z**3 - 2 * x * z
    + 5 * y * z - 2 * z**2 - 2 * x + 3 * y + 4 * z + 3,
]
assert logarithmic_divergences == [
    y - z,
    x * z - x + z,
    -2 * x * y + x * z - 4 * z**2 - x - 3 * z,
    -2 * y * z**2 - 6 * z**3 - x * z - 2 * y * z
    - 12 * z**2 - 2 * x - 5 * z,
]

logarithmic_weight_ideal = torus_saturation(
    R.ideal(logarithmic_weights)
)
assert all(
    logarithmic_weight_ideal.reduce(generator) == 0
    for generator in smooth_critical_ideal.gens()
)
assert all(
    smooth_critical_ideal.reduce(generator) == 0
    for generator in logarithmic_weight_ideal.gens()
)
SAME_MOMENT_LOG_SOURCE_IDENTITY = (
    "CT[Lambda^M alpha_j*A] "
    "= -CT[Lambda^M(V_j(A)+div(V_j)*A)]/M"
)


# Work in the smooth torus algebra and compute multiplication
# recurrences for the 21 elements 1-X^kappa.
RC.<X, Y, Z, T> = PolynomialRing(QQ, order="degrevlex")
FC = (1 + X) * (1 + Y) * (1 + Z) * (
    (1 + Y) * (1 + Z) + X * Y * Z
)
smooth_inverse_ideal = RC.ideal(
    X * FC.derivative(X) - FC,
    Y * FC.derivative(Y) - FC,
    Z * FC.derivative(Z) - FC,
    1 - T * FC * X * Y * Z,
)
assert smooth_inverse_ideal.vector_space_dimension() == 2
normal_basis = smooth_inverse_ideal.normal_basis()
inverse_monomials = {
    X: T * FC * Y * Z,
    Y: T * FC * X * Z,
    Z: T * FC * X * Y,
}


def torus_monomial(point):
    out = RC.one()
    for variable, exponent in zip((X, Y, Z), point):
        if exponent == 1:
            out *= variable
        elif exponent == -1:
            out *= inverse_monomials[variable]
        else:
            assert exponent == 0
    return smooth_inverse_ideal.reduce(out)


def quotient_coordinates(polynomial):
    remainder = smooth_inverse_ideal.reduce(polynomial)
    return vector(
        QQ,
        [
            remainder.monomial_coefficient(basis_monomial)
            for basis_monomial in normal_basis
        ],
    )


def multiplication_matrix(element):
    return matrix(
        QQ,
        [
            list(quotient_coordinates(element * basis_monomial))
            for basis_monomial in normal_basis
        ],
    ).transpose()


PE.<E> = PolynomialRing(QQ)
characteristic_polynomials = {}
for point in polytope_points(1):
    if point == (0, 0, 0):
        continue
    base = smooth_inverse_ideal.reduce(1 - torus_monomial(point))
    characteristic = multiplication_matrix(base).charpoly(E)
    characteristic_polynomials.setdefault(characteristic, []).append(point)

assert len(characteristic_polynomials) == 12
smooth_annihilator = PE.one()
for characteristic in characteristic_polynomials:
    smooth_annihilator = lcm(smooth_annihilator, characteristic)
assert smooth_annihilator.degree() == 24
assert smooth_annihilator.valuation() == 2

# Two first-order projectors create polynomial factors in L of degree
# at most two.  Cubing each primary recurrence therefore suffices.
# The E^2 class is eventually zero after the two derivatives, so it
# drops from the stable operator.
stable_annihilator = (smooth_annihilator // E**2) ** 3
assert stable_annihilator.degree() == 66

coefficient_denominator = lcm(
    coefficient.denominator() for coefficient in stable_annihilator
)
integral_operator = coefficient_denominator * stable_annihilator
operator_content = gcd(ZZ(coefficient) for coefficient in integral_operator)
primitive_operator = PE(integral_operator / operator_content)
assert primitive_operator[0] == -21952  # -2^6*7^3
assert primitive_operator.leading_coefficient() == 16777216  # 2^24

print("Q32_LOG_DERIVATION_REDUCTION=PASS")
print("PROJECTOR_DENOMINATOR_BOUND", "(M+1)^2")
print("NONEMPTY_TORUS_CURVES", len(nonempty_pair_ideals))
print(
    "SMOOTH_CRITICAL_DIMENSION",
    smooth_critical_ideal.vector_space_dimension(),
)
print("SMOOTH_CHARACTERISTIC_CLASSES", len(characteristic_polynomials))
print("SMOOTH_L_RECURRENCE_ORDER", smooth_annihilator.degree())
print("STABLE_PROJECTED_L_RECURRENCE_ORDER", primitive_operator.degree())
print(
    "STABLE_OPERATOR_ENDPOINTS",
    primitive_operator[0],
    primitive_operator.leading_coefficient(),
)
