#!/usr/bin/env python3
"""Search tangent gauges which kill the entire zero-shift connection block.

The earlier explicit gauges killed only the three diagonal entries.  A
zero-shift y<->x two-cycle remained.  Here the target for each weight
field is the full 12-vector consisting of the coefficients of
aa,bb,cc,1 in all three zero-shift Groebner quotients.

The tangent search space is generated by Laurent monomial multiples of

    K_ij = g_j H_i - g_i H_j.

Everything is exact rational linear algebra; no Groebner-basis process
is invoked.
"""

from pathlib import Path

import sympy as sp


HELPER = Path(__file__).with_name("q32_log_weight_pair_gauge.py")
prefix = HELPER.read_text().split('print("PAIR_GAUGE_DIAGONAL_SIGNATURES")')[0]
namespace = {}
exec(prefix, namespace)

x, y, z = namespace["x"], namespace["y"], namespace["z"]
a, b, c = namespace["a"], namespace["b"], namespace["c"]
fields = namespace["fields"]
pair_fields = namespace["pair_fields"]
theta = namespace["theta"]

g_y = y - z
g_x = x - 2 * z - 1
g_z = z**2 - sp.Rational(1, 2)


def laurent_ledger(polynomial):
    ledger = {}
    for term in sp.Add.make_args(sp.expand(polynomial)):
        powers = term.as_powers_dict()
        exponent = tuple(int(powers.get(variable, 0)) for variable in (x, y, z))
        coefficient = sp.cancel(
            term / (x**exponent[0] * y**exponent[1] * z**exponent[2])
        )
        assert not ({x, y, z} & coefficient.free_symbols)
        ledger[exponent] = sp.expand(ledger.get(exponent, 0) + coefficient)
    return {
        exponent: sp.factor(coefficient)
        for exponent, coefficient in ledger.items()
        if coefficient != 0
    }


def laurent_divide_z(polynomial):
    quotient = 0
    remainder = 0
    for term in sp.Add.make_args(sp.expand(polynomial)):
        power = int(term.as_powers_dict().get(z, 0))
        coefficient = sp.cancel(term / z**power)
        assert z not in coefficient.free_symbols
        if power >= 2:
            current = power
            scale = sp.Rational(1)
            while current >= 2:
                quotient += coefficient * scale * z**(current - 2)
                scale /= 2
                current -= 2
            remainder += coefficient * scale * z**current
        elif power >= 0:
            remainder += coefficient * z**power
        else:
            current = power
            scale = sp.Rational(1)
            while current < 0:
                quotient -= 2 * coefficient * scale * z**current
                scale *= 2
                current += 2
            remainder += coefficient * scale * z**current
    return sp.expand(quotient), sp.expand(remainder)


def canonical_division(polynomial):
    polynomial = sp.expand(polynomial)
    after_y = sp.expand(polynomial.subs(y, z))
    quotient_y = sp.expand(sp.cancel((polynomial - after_y) / g_y))
    after_x = sp.expand(after_y.subs(x, 2 * z + 1))
    quotient_x = sp.expand(sp.cancel((after_y - after_x) / g_x))
    quotient_z, remainder = laurent_divide_z(after_x)
    assert sp.cancel(
        polynomial
        - g_y * quotient_y
        - g_x * quotient_x
        - g_z * quotient_z
        - remainder
    ) == 0
    return (quotient_y, quotient_x, quotient_z), remainder


def scale_field(scalar, field):
    return tuple(sp.expand(scalar * entry) for entry in field)


def ell_y(polynomial):
    """Zero monomial in (P-P|y=z)/(y-z), for z-Laurent P."""

    return sp.factor(sum(
        coefficient
        for (ix, iy, iz), coefficient in laurent_ledger(polynomial).items()
        if ix == 0 and iy >= 1 and iz == 1 - iy
    ))


def ell_x(polynomial):
    """Zero monomial in (P|y=z-P|x=2z+1,y=z)/(x-2z-1)."""

    out = 0
    for (ix, iy, iz), coefficient in laurent_ledger(polynomial).items():
        if ix < 1:
            continue
        needed = -(iy + iz)
        if 0 <= needed <= ix - 1:
            out += (
                coefficient
                * sp.binomial(ix - 1, needed)
                * 2**needed
            )
    return sp.factor(out)


def ell_z(polynomial):
    """Zero monomial of the z^2-1/2 quotient after x=2z+1,y=z."""

    out = 0
    for (ix, iy, iz), coefficient in laurent_ledger(polynomial).items():
        assert ix >= 0
        for selected in range(ix + 1):
            power = selected + iy + iz
            if power >= 2 and power % 2 == 0:
                out += (
                    coefficient
                    * sp.binomial(ix, selected)
                    * 2**selected
                    * sp.Rational(1, 2)**(power // 2 - 1)
                )
    return sp.factor(out)


def zero_block_signature(field):
    beta = sum(
        theta(field[index], (x, y, z)[index])
        for index in range(3)
    )
    signature = []
    for functional in (ell_y, ell_x, ell_z):
        signature.extend([
            functional(field[0]),
            functional(field[1]),
            functional(field[2]),
            functional(beta),
        ])
    return sp.Matrix(signature)


original = [zero_block_signature(field) for field in fields]
for name, signature in zip(("y", "x", "z"), original):
    print("ORIGINAL", name, tuple(signature))


def polynomial_monomials(degree):
    return [
        x**i * y**j * z**k
        for i in range(degree + 1)
        for j in range(degree + 1 - i)
        for k in range(degree + 1 - i - j)
    ]


def choose_sparse_zero_parameter_solution(solution_set):
    if solution_set is sp.EmptySet:
        return None
    candidate = next(iter(solution_set))
    parameters = set().union(*(entry.free_symbols for entry in candidate))
    parameters.difference_update({x, y, z, a, b, c})
    return tuple(
        sp.expand(entry.subs({parameter: 0 for parameter in parameters}))
        for entry in candidate
    )


def audit_basis(label, decorated):
    print("BASIS", label, "SIZE", len(decorated))
    columns = [
        zero_block_signature(field)
        for _, _, field in decorated
    ]
    matrix = sp.Matrix.hstack(*columns)
    print(" RANK", matrix.rank())
    all_solved = True
    for source_index, source_name in enumerate(("y", "x", "z")):
        solution_set = sp.linsolve((matrix, -original[source_index]))
        candidate = choose_sparse_zero_parameter_solution(solution_set)
        print(" SOURCE", source_name, "EXISTS", candidate is not None)
        if candidate is None:
            all_solved = False
            left_kernel = matrix.T.nullspace()
            nonzero_pairings = [
                (
                    tuple(vector),
                    sp.factor((vector.T * original[source_index])[0]),
                )
                for vector in left_kernel
                if (vector.T * original[source_index])[0] != 0
            ]
            print("  OBSTRUCTING_LEFT_INVARIANTS", nonzero_pairings[:4])
            continue
        assert (
            original[source_index] + matrix * sp.Matrix(candidate)
            == sp.zeros(12, 1)
        )
        nonzero = [
            (decorated[index][0], decorated[index][1], coefficient)
            for index, coefficient in enumerate(candidate)
            if coefficient != 0
        ]
        print("  NONZERO", nonzero)
    return all_solved


for degree in range(4):
    monomials = polynomial_monomials(degree)
    decorated = [
        (name, monomial, scale_field(monomial, field))
        for name, field in zip(("yx", "yz", "xz"), pair_fields)
        for monomial in monomials
    ]
    if audit_basis(f"POLY_DEG_{degree}", decorated):
        break
else:
    # Add the pure negative-z Laurent multiples which already removed the
    # z-channel diagonal residue.
    monomials = polynomial_monomials(3) + [
        z**power for power in range(-6, 0)
    ]
    decorated = [
        (name, monomial, scale_field(monomial, field))
        for name, field in zip(("yx", "yz", "xz"), pair_fields)
        for monomial in monomials
    ]
    audit_basis("POLY_DEG_3_PLUS_Z_NEG_6", decorated)

print("Q32_LOG_WEIGHT_ZERO_BLOCK_GAUGE=PASS")
