#!/usr/bin/env sage
"""Scratch probe for the correct Apéry Laurent polynomial.

This file intentionally contains only exact ideal computations.  It is
used to rebuild the logarithmic-reduction claims after correcting

    D = (1+y)(1+z) + xyz.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_correct_log_probe.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
from itertools import combinations
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(_sage_const_0 , str(HERE))
from q32_cartier_packet_audit import polytope_points

R = PolynomialRing(QQ, order="degrevlex", names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)
A = _sage_const_1  + x
B = _sage_const_1  + y
C = _sage_const_1  + z
D = (_sage_const_1  + y) * (_sage_const_1  + z) + x * y * z
FACTORS = (A, B, C, D)
F = prod(FACTORS)


def torus_saturation(ideal):
    return ideal.saturation(R.ideal(x * y * z))[_sage_const_0 ]


critical = torus_saturation(
    R.ideal(
        x * F.derivative(x) - F,
        y * F.derivative(y) - F,
        z * F.derivative(z) - F,
    )
)
singular = critical + R.ideal(F)
smooth = critical.saturation(R.ideal(F))[_sage_const_0 ]
intersection = singular.intersection(smooth)

print("critical dimension", critical.dimension())
print("singular dimension", singular.dimension())
print("smooth dimension", smooth.dimension())
if smooth.dimension() == _sage_const_0 :
    print("smooth vector dimension", smooth.vector_space_dimension())
print("critical == intersection",
      all(intersection.reduce(g) == _sage_const_0  for g in critical.gens())
      and all(critical.reduce(g) == _sage_const_0  for g in intersection.gens()))
print("singular radical", singular.radical() == singular)
print("singular minimal associated primes")
for prime in singular.minimal_associated_primes():
    print(" ", prime.dimension(), list(prime.gens()))

pair_intersection = None
for left, right in combinations(range(_sage_const_4 ), _sage_const_2 ):
    pair = torus_saturation(R.ideal(FACTORS[left], FACTORS[right]))
    print("pair", left, right, "dim", pair.dimension(),
          "gens", list(pair.gens()))
    pair_intersection = (
        pair if pair_intersection is None
        else pair_intersection.intersection(pair)
    )
print("singular == pair intersection",
      all(pair_intersection.reduce(g) == _sage_const_0  for g in singular.gens())
      and all(singular.reduce(g) == _sage_const_0  for g in pair_intersection.gens()))

# Direct smooth algebra with an inverse of xyzF.
RC = PolynomialRing(QQ, order="degrevlex", names=('X', 'Y', 'Z', 'T',)); (X, Y, Z, T,) = RC._first_ngens(4)
FC = (_sage_const_1  + X) * (_sage_const_1  + Y) * (_sage_const_1  + Z) * (
    (_sage_const_1  + Y) * (_sage_const_1  + Z) + X * Y * Z
)
smooth_inverse = RC.ideal(
    X * FC.derivative(X) - FC,
    Y * FC.derivative(Y) - FC,
    Z * FC.derivative(Z) - FC,
    _sage_const_1  - T * FC * X * Y * Z,
)
print("inverse dimension", smooth_inverse.dimension())
if smooth_inverse.dimension() == _sage_const_0 :
    print("inverse vector dimension", smooth_inverse.vector_space_dimension())
    print("inverse normal basis", smooth_inverse.normal_basis())


def theta(poly, variable):
    return variable * poly.derivative(variable)


syzygies = R.ideal(
    x * F.derivative(x),
    y * F.derivative(y),
    z * F.derivative(z),
    -F,
).syzygy_module()
print("syzygies")
for index, row in enumerate(syzygies):
    H = tuple(row[j] for j in range(_sage_const_3 ))
    h = row[_sage_const_3 ]
    aa = h - sum(H)
    bb = sum(theta(H[j], (x, y, z)[j]) for j in range(_sage_const_3 ))
    print(" G", index, "H", H, "h", h, "a", aa, "b", bb)
    assert sum(H[j] * theta(F, (x, y, z)[j])
               for j in range(_sage_const_3 )) == h * F
    for name, ideal in (
        ("AB", torus_saturation(R.ideal(A, B))),
        ("AC", torus_saturation(R.ideal(A, C))),
        ("AD", torus_saturation(R.ideal(A, D))),
        ("BC", torus_saturation(R.ideal(B, C))),
    ):
        print("   ", name,
              "H", [ideal.reduce(entry) for entry in H],
              "a", ideal.reduce(aa),
              "b", ideal.reduce(bb))


normal_basis = smooth_inverse.normal_basis()
inverse_monomials = {
    X: T * FC * Y * Z,
    Y: T * FC * X * Z,
    Z: T * FC * X * Y,
}


def torus_monomial(point):
    out = RC.one()
    for variable, exponent in zip((X, Y, Z), point):
        if exponent == _sage_const_1 :
            out *= variable
        elif exponent == -_sage_const_1 :
            out *= inverse_monomials[variable]
        else:
            assert exponent == _sage_const_0 
    return smooth_inverse.reduce(out)


def quotient_coordinates(polynomial):
    remainder = smooth_inverse.reduce(polynomial)
    return vector(
        QQ,
        [remainder.monomial_coefficient(monomial)
         for monomial in normal_basis],
    )


def multiplication_matrix(element):
    return matrix(
        QQ,
        [list(quotient_coordinates(element * monomial))
         for monomial in normal_basis],
    ).transpose()


PE = PolynomialRing(QQ, names=('E',)); (E,) = PE._first_ngens(1)
charpolys = {}
for point in polytope_points(_sage_const_1 ):
    if point == (_sage_const_0 , _sage_const_0 , _sage_const_0 ):
        continue
    base = smooth_inverse.reduce(_sage_const_1  - torus_monomial(point))
    charpoly = multiplication_matrix(base).charpoly(E)
    charpolys.setdefault(charpoly, []).append(point)

annihilator = PE.one()
for charpoly in charpolys:
    annihilator = lcm(annihilator, charpoly)
print("characteristic classes", len(charpolys))
for charpoly, points in charpolys.items():
    print(" ", charpoly, points)
print("annihilator", annihilator)
print("annihilator degree", annihilator.degree())
print("annihilator valuation", annihilator.valuation())
print("annihilator endpoints", annihilator[_sage_const_0 ],
      annihilator.leading_coefficient())

