#!/usr/bin/env sage
"""Audit the exact Ore syzygy between the origin and ghost operators.

The origin operator ``U`` constructed in
``q32_doubled_period_gauge_audit.sage`` satisfies

    U(J)_n = M(n) b_n,       U(b)_n = 0.

Twisting the Apéry operator by ``M`` gives an order-two operator
``A_M`` annihilating ``M(n)b_n``.  Hence ``A_M U`` should factor
through the order-five common annihilator ``L = lclm(P,A)``.  This
script checks that statement in exact Ore arithmetic and records the
primitive order-one quotient.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_operator_syzygy_audit.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0)
from pathlib import Path

from ore_algebra import *


HERE = Path(__file__).resolve().parent
load(str(HERE / "q32_doubled_period_gauge_audit.sage"))


def primitive_operator_data(operator):
    """Clear a rational Ore operator to primitive polynomial data."""

    denominator = lcm(
        K(operator[shift]).denominator()
        for shift in range(operator.order() + _sage_const_1 )
    )
    polynomials = [
        R(denominator * K(operator[shift]))
        for shift in range(operator.order() + _sage_const_1 )
    ]
    rational_denominator = lcm(
        coefficient.denominator()
        for polynomial in polynomials
        for coefficient in polynomial.list()
    )
    polynomials = [
        R(rational_denominator * polynomial)
        for polynomial in polynomials
    ]
    integer_content = gcd(
        [
            ZZ(coefficient)
            for polynomial in polynomials
            for coefficient in polynomial.list()
        ]
    )
    primitive_polynomials = tuple(
        R(polynomial / integer_content) for polynomial in polynomials
    )
    primitive_denominator = R(
        rational_denominator * denominator / integer_content
    )
    assert (
        primitive_denominator * operator
        == sum(
            primitive_polynomials[shift] * OAK(Sn)**shift
            for shift in range(len(primitive_polynomials))
        )
    )
    assert (
        gcd(list(primitive_polynomials) + [primitive_denominator]) == _sage_const_1 
    )
    return primitive_polynomials, primitive_denominator


twisted_apery_operator = sum(
    K(apery_operator[shift])
    / K(multiplier(n=n + shift))
    * OAK(Sn)**shift
    for shift in range(apery_operator.order() + _sage_const_1 )
)
common_operator = OAK(P.lclm(apery_operator))
composite_operator = twisted_apery_operator * integral_operator
quotient_operator, remainder_operator = composite_operator.quo_rem(
    common_operator
)
common_polynomials, common_denominator = primitive_operator_data(
    common_operator
)
integral_common_operator = sum(
    common_polynomials[shift] * OAK(Sn)**shift
    for shift in range(len(common_polynomials))
)
integral_quotient, integral_remainder = composite_operator.quo_rem(
    integral_common_operator
)

assert twisted_apery_operator.order() == _sage_const_2 
assert common_operator.order() == _sage_const_5 
assert composite_operator.order() == _sage_const_6 
assert quotient_operator.order() == _sage_const_1 
assert remainder_operator == _sage_const_0 
assert integral_quotient.order() == _sage_const_1 
assert integral_remainder == _sage_const_0 

primitive_quotient, primitive_denominator = primitive_operator_data(
    quotient_operator
)
integral_primitive_quotient, integral_primitive_denominator = (
    primitive_operator_data(integral_quotient)
)

assert (
    primitive_denominator * composite_operator
    == sum(
        primitive_quotient[shift] * OAK(Sn)**shift
        for shift in range(len(primitive_quotient))
    )
    * common_operator
)
assert (
    integral_primitive_denominator * composite_operator
    == sum(
        integral_primitive_quotient[shift] * OAK(Sn)**shift
        for shift in range(len(integral_primitive_quotient))
    )
    * integral_common_operator
)


def factor_degree_pattern(polynomial):
    """Return degrees and multiplicities of nonconstant factors."""

    return tuple(
        (factor_polynomial.degree(), multiplicity)
        for factor_polynomial, multiplicity in factor(polynomial)
        if factor_polynomial.degree() > _sage_const_0 
    )

print("TWISTED_APERY_ORDER", twisted_apery_operator.order())
print("COMMON_OPERATOR_ORDER", common_operator.order())
print("COMPOSITE_ORDER", composite_operator.order())
print("ORE_REMAINDER_ZERO", remainder_operator == _sage_const_0 )
print("INTEGRAL_ORE_REMAINDER_ZERO", integral_remainder == _sage_const_0 )
print(
    "INTEGRAL_COMMON_DEGREES",
    tuple(polynomial.degree() for polynomial in common_polynomials),
)
print("INTEGRAL_COMMON_DENOMINATOR_DEGREE", common_denominator.degree())
print(
    "PRIMITIVE_QUOTIENT_DEGREES",
    tuple(polynomial.degree() for polynomial in primitive_quotient),
)
print("PRIMITIVE_DENOMINATOR_DEGREE", primitive_denominator.degree())
print(
    "PRIMITIVE_QUOTIENT_FACTOR_DEGREES",
    tuple(
        factor_degree_pattern(polynomial)
        for polynomial in primitive_quotient
    ),
)
print(
    "PRIMITIVE_DENOMINATOR_FACTOR_DEGREES",
    factor_degree_pattern(primitive_denominator),
)
print(
    "INTEGRAL_PRIMITIVE_QUOTIENT_DEGREES",
    tuple(
        polynomial.degree() for polynomial in integral_primitive_quotient
    ),
)
print(
    "INTEGRAL_PRIMITIVE_DENOMINATOR_DEGREE",
    integral_primitive_denominator.degree(),
)
print(
    "INTEGRAL_PRIMITIVE_QUOTIENT_FACTOR_DEGREES",
    tuple(
        factor_degree_pattern(polynomial)
        for polynomial in integral_primitive_quotient
    ),
)
print(
    "INTEGRAL_PRIMITIVE_DENOMINATOR_FACTOR_DEGREES",
    factor_degree_pattern(integral_primitive_denominator),
)
print("Q32_OPERATOR_SYZYGY_AUDIT=PASS")

