#!/usr/bin/env sage
"""Search minimum-degree logarithmic fields with prescribed weights.

A field H has logarithmic weight alpha exactly when

    sum_i H_i (theta_i(F)-F) = alpha*F.

This is a finite linear system for polynomial (or bounded Laurent)
coefficients H_i.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_lowdegree_weight_fields.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)
from itertools import product

R = PolynomialRing(QQ, order="degrevlex", names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)
F = (
    (_sage_const_1  + x) * (_sage_const_1  + y) * (_sage_const_1  + z)
    * ((_sage_const_1  + y) * (_sage_const_1  + z) + x * y * z)
)


def theta(polynomial, variable):
    return variable * polynomial.derivative(variable)


critical = tuple(
    theta(F, variable) - F for variable in (x, y, z)
)
targets = (y - z, x - _sage_const_2  * z - _sage_const_1 , z**_sage_const_2  - QQ(_sage_const_1 ) / _sage_const_2 )


def monomials_up_to(degree):
    return [
        x**a * y**b * z**c
        for a in range(degree + _sage_const_1 )
        for b in range(degree + _sage_const_1  - a)
        for c in range(degree + _sage_const_1  - a - b)
    ]


def solve_polynomial_field(target, degree):
    monomials = monomials_up_to(degree)
    columns = [
        monomial * critical[coordinate]
        for coordinate in range(_sage_const_3 )
        for monomial in monomials
    ]
    rhs_polynomial = target * F
    support = sorted(
        set(rhs_polynomial.dict()).union(
            *(set(column.dict()) for column in columns)
        )
    )
    coefficient_matrix = matrix(
        QQ,
        [
            [column.dict().get(exponent, _sage_const_0 )
             for column in columns]
            for exponent in support
        ],
    )
    rhs = vector(
        QQ,
        [rhs_polynomial.dict().get(exponent, _sage_const_0 )
         for exponent in support],
    )
    if coefficient_matrix.rank() != coefficient_matrix.augment(rhs).rank():
        return None
    solution = coefficient_matrix.solve_right(rhs)
    H = tuple(
        sum(
            solution[coordinate * len(monomials) + index] * monomial
            for index, monomial in enumerate(monomials)
        )
        for coordinate in range(_sage_const_3 )
    )
    assert sum(H[index] * critical[index] for index in range(_sage_const_3 )) == target * F
    beta = sum(
        theta(H[index], (x, y, z)[index])
        for index in range(_sage_const_3 )
    )
    return H, beta


for target in targets:
    print("TARGET", target)
    for degree in range(_sage_const_5 ):
        solution = solve_polynomial_field(target, degree)
        print(" DEGREE", degree, "EXISTS", solution is not None)
        if solution is not None:
            H, beta = solution
            print(" H", H)
            print(" beta", beta)
            print(" beta_minus_alpha", beta - target)
            break

print("Q32_LOWDEGREE_WEIGHT_FIELDS=PASS")

