#!/usr/bin/env sage
"""Exact factor scan for the fixed terminal exterior prefix.

This is diagnostic only.  It reuses the certified Y/W terminal packet
definitions and records

    gcd_{1 <= L <= K} det(B_L, V_{L-1})

for a fixed small K.  The scan is intended to reveal the polynomial
boundary factors that a later symbolic Bezout certificate must explain.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_terminal_prefix_gcd_scan.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_37 = Integer(37); _sage_const_43 = Integer(43); _sage_const_53 = Integer(53); _sage_const_61 = Integer(61); _sage_const_71 = Integer(71); _sage_const_83 = Integer(83); _sage_const_97 = Integer(97); _sage_const_109 = Integer(109); _sage_const_127 = Integer(127); _sage_const_149 = Integer(149); _sage_const_173 = Integer(173); _sage_const_199 = Integer(199); _sage_const_223 = Integer(223); _sage_const_251 = Integer(251); _sage_const_271 = Integer(271); _sage_const_299 = Integer(299); _sage_const_320 = Integer(320); _sage_const_3 = Integer(3)
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
load(str(HERE / "q32_terminal_ct_packet_audit.sage"))


def exterior_prefix_gcd(moment, prefix_length=_sage_const_7 ):
    by, bw = terminal_yw_table(moment, prefix_length)
    fy = [terminal_packet(moment, moment, _sage_const_0 )]
    fw = [terminal_origin_coordinate(moment + _sage_const_1 , moment, _sage_const_0 )]
    exterior = []
    for order in range(_sage_const_1 , prefix_length + _sage_const_1 ):
        exterior.append(
            by[order] * fw[order - _sage_const_1 ]
            - bw[order] * fy[order - _sage_const_1 ]
        )
        pascal = (-_sage_const_1 ) ** order * binomial(moment + _sage_const_1 , order)
        fy.append(fy[-_sage_const_1 ] + pascal * by[order])
        fw.append(fw[-_sage_const_1 ] + pascal * bw[order])
    raw = []
    for residue in range(prefix_length + _sage_const_1 ):
        raw.append(
            (
                sum(
                    (-_sage_const_1 ) ** order
                    * binomial(residue, order)
                    * by[order]
                    for order in range(residue + _sage_const_1 )
                ),
                sum(
                    (-_sage_const_1 ) ** order
                    * binomial(residue, order)
                    * bw[order]
                    for order in range(residue + _sage_const_1 )
                ),
            )
        )
    raw_minors = {
        (left, right):
        raw[left][_sage_const_0 ] * raw[right][_sage_const_1 ]
        - raw[left][_sage_const_1 ] * raw[right][_sage_const_0 ]
        for left in range(prefix_length + _sage_const_1 )
        for right in range(left + _sage_const_1 , prefix_length + _sage_const_1 )
    }
    return gcd(exterior), exterior, gcd(raw_minors.values()), raw_minors


moments = (
    _sage_const_23 , _sage_const_29 , _sage_const_37 , _sage_const_43 , _sage_const_53 , _sage_const_61 , _sage_const_71 , _sage_const_83 , _sage_const_97 , _sage_const_109 ,
    _sage_const_127 , _sage_const_149 , _sage_const_173 , _sage_const_199 , _sage_const_223 , _sage_const_251 , _sage_const_271 , _sage_const_299 , _sage_const_320 ,
)
if "--short" in sys.argv:
    moments = (_sage_const_199 , _sage_const_320 )
for moment in moments:
    value, exterior, raw_gcd, raw_minors = exterior_prefix_gcd(moment)
    assert value % raw_gcd == _sage_const_0 
    smallest_pairs = sorted(
        raw_minors,
        key=lambda pair: abs(raw_minors[pair]).nbits(),
    )[:_sage_const_3 ]
    print(
        "PREFIX_GCD",
        "M", moment,
        "N", moment + _sage_const_1 ,
        "BITS", abs(value).nbits(),
        "FACTOR", factor(value),
        "RAW_GCD_FACTOR", factor(raw_gcd),
        "RATIO_FACTOR", factor(value // raw_gcd),
        "SMALLEST_RAW_PAIRS", tuple(
            (pair, abs(raw_minors[pair]).nbits())
            for pair in smallest_pairs
        ),
        "EXTERIOR_BITS", tuple(abs(entry).nbits() for entry in exterior),
    )
    if moment in (_sage_const_199 , _sage_const_320 ):
        running = ZZ.zero()
        ledger = []
        for residue in range(_sage_const_7 ):
            minor = raw_minors[(residue, residue + _sage_const_1 )]
            running = gcd(running, minor)
            ledger.append(
                (
                    residue,
                    abs(minor).nbits(),
                    factor(running),
                )
            )
        print("ADJACENT_RAW_GCD_LEDGER", "M", moment, ledger)

print("Q32_TERMINAL_PREFIX_GCD_SCAN=PASS")

