#!/usr/bin/env python3
"""Audit an integral left inverse for every Franel tail matrix.

For a cutoff J, put

    a(k,d) = (-1)^(J-i) binom(k,i) binom(k-i-1,J-i) F_i,
    i = k-d,

when 0 <= i <= J, and put a(k,d)=0 otherwise.  If integers z_d satisfy

    F_k = sum_d a(k,d) z_d                 (k > J),

then every integer linear combination of the Franel tail is in the ideal
generated by the corresponding nonconstant Legendre--Euler coefficients.
This would prove the experimental tail-ideal inclusion, hence
content(T_(n,J)) | A_n, for arbitrary cutoffs.

The system is banded.  Setting z_1,...,z_J to zero determines z_k
recursively, but a priori divides by binom(k-1,J).  This script checks the
surprising exact divisibility and the resulting identities.  It is
experimental evidence, not a proof of integrality for all J and k.
"""

from __future__ import annotations

from math import comb

from q32_strehl_gcd import franel_numbers


LIMIT = 250


def matrix_entry(
    cutoff: int, row: int, degree: int, franel: list[int]
) -> int:
    index = row - degree
    if not 0 <= index <= cutoff:
        return 0
    return (
        (-1) ** (cutoff - index)
        * comb(row, index)
        * comb(row - index - 1, cutoff - index)
        * franel[index]
    )


def integral_left_inverse_moments(
    cutoff: int, limit: int, franel: list[int]
) -> list[int]:
    moments = [0] * (limit + 1)
    for row in range(cutoff + 1, limit + 1):
        residual = franel[row]
        for index in range(1, cutoff + 1):
            degree = row - index
            residual -= (
                (-1) ** (cutoff - index)
                * comb(row, index)
                * comb(degree - 1, cutoff - index)
                * franel[index]
                * moments[degree]
            )
        leading = (-1) ** cutoff * comb(row - 1, cutoff)
        assert residual % leading == 0, (
            cutoff,
            row,
            residual,
            leading,
        )
        moments[row] = residual // leading
    return moments


def main() -> None:
    franel = franel_numbers(LIMIT)
    for cutoff in range(LIMIT):
        moments = integral_left_inverse_moments(cutoff, LIMIT, franel)
        for row in range(cutoff + 1, LIMIT + 1):
            reconstructed = sum(
                matrix_entry(cutoff, row, degree, franel)
                * moments[degree]
                for degree in range(1, LIMIT + 1)
            )
            assert reconstructed == franel[row], (
                cutoff,
                row,
                reconstructed,
                franel[row],
            )
    print(
        "verified integral Franel tail left inverses for "
        f"0 <= J < k <= {LIMIT}"
    )


if __name__ == "__main__":
    main()
