#!/usr/bin/env sage
"""Lift the simple smooth-critical generators to logarithmic fields.

For the correct Apéry polynomial, the logarithmic weights of a Singular
syzygy basis generate the smooth critical ideal after torus saturation.
This script expresses the simple Groebner generators

    y-z, x-2z-1, z^2-1/2

as Laurent combinations of those weights, constructs the corresponding
logarithmic vector fields, and records their divergences.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_log_weight_fields.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
R = PolynomialRing(QQ, order="degrevlex", names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)
F = (
    (_sage_const_1  + x) * (_sage_const_1  + y) * (_sage_const_1  + z)
    * ((_sage_const_1  + y) * (_sage_const_1  + z) + x * y * z)
)


def theta(polynomial, variable):
    return variable * polynomial.derivative(variable)


rows = list(
    R.ideal(
        theta(F, x), theta(F, y), theta(F, z), -F
    ).syzygy_module()
)
fields = [tuple(row[index] for index in range(_sage_const_3 )) for row in rows]
multipliers = [row[_sage_const_3 ] for row in rows]
weights = [
    multipliers[index] - sum(fields[index])
    for index in range(len(rows))
]

R4 = PolynomialRing(QQ, order="degrevlex", names=('X', 'Y', 'Z', 'U',)); (X, Y, Z, U,) = R4._first_ngens(4)


def into_r4(polynomial):
    return R4(polynomial(x=X, y=Y, z=Z))


weight4 = [into_r4(weight) for weight in weights]
generators4 = tuple(weight4) + (_sage_const_1  - U * X * Y * Z,)
ideal4 = R4.ideal(generators4)
targets = (y - z, x - _sage_const_2  * z - _sage_const_1 , z**_sage_const_2  - QQ(_sage_const_1 ) / _sage_const_2 )

LR = LaurentPolynomialRing(QQ, _sage_const_3 , names=('lx', 'ly', 'lz',)); (lx, ly, lz,) = LR._first_ngens(3)


def inverse_substitution(polynomial):
    return sum(
        QQ(coefficient)
        * lx**(exponent[_sage_const_0 ] - exponent[_sage_const_3 ])
        * ly**(exponent[_sage_const_1 ] - exponent[_sage_const_3 ])
        * lz**(exponent[_sage_const_2 ] - exponent[_sage_const_3 ])
        for exponent, coefficient in polynomial.dict().items()
    )


def into_laurent(polynomial):
    return LR(polynomial(x=lx, y=ly, z=lz))


for target_index, target in enumerate(targets):
    lift_matrix = singular.lift(
        singular(ideal4), singular(into_r4(target))
    ).sage()
    lift4 = [
        R4(lift_matrix[index, _sage_const_0 ])
        for index in range(len(generators4))
    ]
    assert into_r4(target) == sum(
        lift4[index] * generators4[index]
        for index in range(len(generators4))
    )
    coefficients = [
        inverse_substitution(lift4[index])
        for index in range(len(rows))
    ]
    H = tuple(
        sum(
            coefficients[row_index]
            * into_laurent(fields[row_index][coordinate])
            for row_index in range(len(rows))
        )
        for coordinate in range(_sage_const_3 )
    )
    h = sum(
        coefficients[row_index]
        * into_laurent(multipliers[row_index])
        for row_index in range(len(rows))
    )
    alpha = h - sum(H)
    beta = sum(
        variable * H[index].derivative(variable)
        for index, variable in enumerate((lx, ly, lz))
    )
    assert alpha == into_laurent(target)
    assert sum(
        H[index]
        * variable
        * into_laurent(F).derivative(variable)
        for index, variable in enumerate((lx, ly, lz))
    ) == h * into_laurent(F)
    print("TARGET", target_index, target)
    print("COEFFICIENTS", coefficients)
    print("H", H)
    print("h", h)
    print("alpha", alpha)
    print("beta", beta)
    print("beta_minus_alpha", beta - alpha)

print("Q32_LOG_WEIGHT_FIELDS=PASS")

