#!/usr/bin/env python3
"""Audit the lattice generated by the universal fixed-q endpoint tail.

For K=J+1 and every fixed-q candidate prime p, L(n,k) is divisible by p for
all K<=k<p.  Thus the terms L(n,k)F_k through the smallest candidate prime
are universal certificates.  After dividing their common nuisance factor,
their integer span is exactly the candidate primorial times Z.  The best
unrestricted affine reduction is consequently the centered residue of S_n
modulo that primorial.
"""

from __future__ import annotations

from math import comb, gcd, log, prod

from q32_strehl_gcd import franel_numbers, primes_up_to


INDICES = (120, 240, 480, 960, 1200)


def main() -> None:
    limit = max(INDICES)
    franel = franel_numbers(limit)
    primes = primes_up_to(limit)

    for quotient in (1, 3):
        print(f"q={quotient}")
        for n in INDICES:
            boundary = (n - quotient) // (2 * quotient + 1) + 1
            candidates = [
                prime for prime in primes if n // prime == quotient
            ]
            candidate_product = prod(candidates)
            first_prime = min(candidates)
            strehl = sum(
                comb(n, k) * comb(n + k, k) * franel[k]
                for k in range(boundary)
            )
            tail_gcd = 0
            for k in range(boundary, first_prime):
                tail_gcd = gcd(
                    tail_gcd,
                    comb(n, k) * comb(n + k, k) * franel[k],
                )
            assert tail_gcd % candidate_product == 0
            nuisance = tail_gcd // candidate_product
            normalized_gcd = 0
            for k in range(boundary, first_prime):
                normalized_gcd = gcd(
                    normalized_gcd,
                    (
                        comb(n, k)
                        * comb(n + k, k)
                        * franel[k]
                    )
                    // nuisance,
                )
            assert normalized_gcd == candidate_product

            residue = strehl % candidate_product
            centered = (
                min(residue, candidate_product - residue)
                if residue
                else candidate_product
            )
            print(
                f"n={n} tail={first_prime-boundary} "
                f"log_P/n={log(candidate_product)/n:.9f} "
                f"log_center/n={log(centered)/n:.9f}"
            )


if __name__ == "__main__":
    main()
