#!/usr/bin/env sage
"""Exact lower-packet observability after the top-half Freshman reduction.

For ``n = p + r`` and the terminal nodes

    d_t = n - 1 - t = p + (r - 1 - t),

the unique Freshman decomposition (away from the bounded borrow strip)
reduces the actual ``Y/W`` raw vector modulo ``p`` to the vector
constructed below.  This script computes the gcd of its 2-by-2 minors.

The calculation is diagnostic until the unique-decomposition lemma and
the resulting formulas are written out in the accompanying notes.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_lower_terminal_observability.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_12 = Integer(12); _sage_const_61 = Integer(61); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_11 = Integer(11)
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(_sage_const_0 , str(HERE))

load(str(HERE / "q32_doubled_period_gauge_audit.sage"))

from q32_cartier_packet_audit import LAMBDA, coefficient


def weighted_correlation(moment, exponent, modulus=None):
    """Return sum_k [k]Lambda * [exponent*k]Lambda^moment."""

    total = _sage_const_0 
    for point, weight in LAMBDA.items():
        total += weight * coefficient(
            moment,
            exponent * point[_sage_const_0 ],
            exponent * point[_sage_const_1 ],
            exponent * point[_sage_const_2 ],
            modulus,
        )
        if modulus:
            total %= modulus
    return ZZ(total if modulus is None else total % modulus)


def lower_raw_vector(residue, terminal_offset, modulus=None):
    """The reduced terminal vector at d=p+r-1-terminal_offset."""

    exponent = residue - _sage_const_1  - terminal_offset
    y_value = weighted_correlation(
        residue - _sage_const_1 , exponent, modulus
    )
    z_value = _sage_const_0 
    for shift in range(origin_operator.order() + _sage_const_1 ):
        scalar = ZZ(
            integer_coefficients[shift](n=residue)
        )
        z_value += scalar * (
            weighted_correlation(
                residue + shift, exponent - _sage_const_1 , modulus
            )
            + weighted_correlation(
                residue + shift, exponent + _sage_const_1 , modulus
            )
        )
        if modulus:
            z_value %= modulus
    w_value = z_value - ZZ(multiplier(n=residue)) * y_value
    if modulus:
        w_value %= modulus
    return vector(
        ZZ,
        (
            y_value if modulus is None else y_value % modulus,
            w_value if modulus is None else w_value % modulus,
        ),
    )


def observability_content(residue, width=_sage_const_7 ):
    """Return the raw vectors, all minors, and their exact gcd."""

    vectors = [
        lower_raw_vector(residue, offset)
        for offset in range(width + _sage_const_1 )
    ]
    minors = {
        (left, right):
        vectors[left][_sage_const_0 ] * vectors[right][_sage_const_1 ]
        - vectors[left][_sage_const_1 ] * vectors[right][_sage_const_0 ]
        for left in range(width + _sage_const_1 )
        for right in range(left + _sage_const_1 , width + _sage_const_1 )
    }
    return vectors, minors, gcd(minors.values())


def origin_content(index):
    return gcd(
        [
            ZZ(multiplier(n=index)),
            *[
                ZZ(polynomial(n=index))
                for polynomial in integer_coefficients
            ],
        ]
    )


def origin_bezout_constant():
    """Return a fixed integer containing every pointwise origin content."""

    polynomials = [*integer_coefficients, multiplier]
    bezout = [R.one()] + [R.zero()] * (len(polynomials) - _sage_const_1 )
    running_gcd = polynomials[_sage_const_0 ]
    for index in range(_sage_const_1 , len(polynomials)):
        new_gcd, left, right = running_gcd.xgcd(
            polynomials[index]
        )
        bezout = [left * entry for entry in bezout]
        bezout[index] += right
        running_gcd = new_gcd
    assert running_gcd == _sage_const_1 
    assert sum(
        bezout[index] * polynomials[index]
        for index in range(len(polynomials))
    ) == _sage_const_1 
    denominator = lcm(
        coefficient.denominator()
        for polynomial in bezout
        for coefficient in polynomial.list()
    )
    return ZZ(denominator), bezout


if "--origin-bezout" in sys.argv:
    constant, _ = origin_bezout_constant()
    print("ORIGIN_BEZOUT_CONSTANT_BITS", constant.nbits())
    if "--factor-origin-bezout" in sys.argv:
        print("ORIGIN_BEZOUT_CONSTANT_FACTOR", factor(constant))


residues = tuple(range(_sage_const_12 , _sage_const_61 ))
if "--short" in sys.argv:
    residues = (_sage_const_12 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 , _sage_const_31 , _sage_const_37 )

for residue in residues:
    _, minors, content = observability_content(residue)
    local_origin_content = origin_content(residue)
    quotient = content // gcd(content, local_origin_content)
    predicted_support = ZZ(_sage_const_2  * _sage_const_3  * _sage_const_5  * _sage_const_7 ) * prod(
        residue + shift for shift in range(_sage_const_2 , _sage_const_8 )
    )
    unsupported_factors = tuple(
        (ZZ(prime), exponent)
        for prime, exponent in factor(quotient)
        if predicted_support % prime
    )
    large_factors = tuple(
        (ZZ(prime), exponent)
        for prime, exponent in factor(quotient)
        if prime > residue + _sage_const_11 
    )
    smallest = sorted(
        minors,
        key=lambda pair: abs(minors[pair]).nbits(),
    )[:_sage_const_3 ]
    print(
        "LOWER_OBSERVABILITY",
        "r", residue,
        "bits", abs(content).nbits(),
        "factor", factor(content),
        "origin_content", factor(local_origin_content),
        "quotient_factor", factor(quotient),
        "unsupported_factors", unsupported_factors,
        "prime_above_unique_range", large_factors,
        "smallest_minors", tuple(
            (pair, abs(minors[pair]).nbits())
            for pair in smallest
        ),
    )
    assert not unsupported_factors

print("Q32_LOWER_TERMINAL_OBSERVABILITY=PASS")

