#!/usr/bin/env sage
"""Exact signed-binomial transforms of the first-cell ray recurrences.

For a nonzero Newton ray ``kappa`` put

    R_kappa(M,r) = [X^((M-r)kappa)] Lambda^M,
    B_kappa(M,L) = sum_{r=0}^L (-1)^r binom(L,r) R_kappa(M,r).

The script derives a certified telescoper for ``R_kappa`` and transports
it through the exact ordinary-generating-function identity

    sum_L B_kappa(M,L) z^L
      = (1-z)^(-1) A_kappa(M,-z/(1-z)),

where ``A_kappa(M,u)=sum_r R_kappa(M,r)u^r``.  The resulting operators
are genuine recurrences for the constant-term ray packets, not
recurrences in a Jacobian quotient.

The fourteen y/z-orbits form an exact finite first-order system for the
summed terminal packet.  We print and audit every endpoint factor; this
is the denominator ledger needed at ``M=p+r-1, L=r``.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_terminal_binomial_telescopers.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_21 = Integer(21); _sage_const_16 = Integer(16); _sage_const_10 = Integer(10); _sage_const_23 = Integer(23); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37)
from math import comb

from ore_algebra import *
from ore_algebra import nullspace
from ore_algebra.ore_algebra import OreAlgebra_generic


def _associated_commutative_algebra(self):
    try:
        return self._commutative_ring
    except AttributeError:
        self._commutative_ring = PolynomialRing(
            self.base_ring(), self.variable_names()
        )
        return self._commutative_ring


OreAlgebra_generic.associated_commutative_algebra = (
    _associated_commutative_algebra
)

_original_kronecker = nullspace.kronecker


def _qq_safe_kronecker(subsolver, presolver=None):
    return nullspace.clear(_original_kronecker(subsolver, presolver))


nullspace.kronecker = _qq_safe_kronecker

R = QQ['M, r, t']; (M, r, t,) = R._first_ngens(3)
OA = OreAlgebra(R, names=('Sr', 'St',)); (Sr, St,) = OA._first_ngens(2)
d = M - r

RAY_CLASSES = (
    ((-_sage_const_1 , -_sage_const_1 , -_sage_const_1 ), _sage_const_1 ),
    ((-_sage_const_1 , -_sage_const_1 , _sage_const_0 ), _sage_const_2 ),
    ((-_sage_const_1 , -_sage_const_1 , _sage_const_1 ), _sage_const_2 ),
    ((-_sage_const_1 , _sage_const_0 , _sage_const_0 ), _sage_const_1 ),
    ((-_sage_const_1 , _sage_const_0 , _sage_const_1 ), _sage_const_2 ),
    ((-_sage_const_1 , _sage_const_1 , _sage_const_1 ), _sage_const_1 ),
    ((_sage_const_0 , -_sage_const_1 , -_sage_const_1 ), _sage_const_1 ),
    ((_sage_const_0 , -_sage_const_1 , _sage_const_0 ), _sage_const_2 ),
    ((_sage_const_0 , -_sage_const_1 , _sage_const_1 ), _sage_const_2 ),
    ((_sage_const_0 , _sage_const_0 , _sage_const_1 ), _sage_const_2 ),
    ((_sage_const_0 , _sage_const_1 , _sage_const_1 ), _sage_const_1 ),
    ((_sage_const_1 , _sage_const_0 , _sage_const_0 ), _sage_const_1 ),
    ((_sage_const_1 , _sage_const_0 , _sage_const_1 ), _sage_const_2 ),
    ((_sage_const_1 , _sage_const_1 , _sage_const_1 ), _sage_const_1 ),
)
assert sum(multiplicity for _, multiplicity in RAY_CLASSES) == _sage_const_21 


def shifted_binomial_ratio(upper, lower, shift):
    if shift == _sage_const_1 :
        return (upper - lower) / (lower + _sage_const_1 )
    if shift == -_sage_const_1 :
        return lower / (upper - lower + _sage_const_1 )
    assert shift == _sage_const_0 
    return R.one()


def ray_operator(point):
    """Return a certified r-telescoper for one coefficient ray."""

    u, v, w = point
    kx = t - u * d
    upper = _sage_const_2  * M - t
    ky = M - v * d
    kz = M - w * d
    t_ratio = (
        (M - t)
        / (t + _sage_const_1 )
        * (M - kx)
        / (kx + _sage_const_1 )
        * (upper - ky)
        / upper
        * (upper - kz)
        / upper
    )
    r_ratio = (
        shifted_binomial_ratio(M, kx, u)
        * shifted_binomial_ratio(upper, ky, v)
        * shifted_binomial_ratio(upper, kz, w)
    )
    ideal = OA.ideal(
        [
            t_ratio.denominator() * St - t_ratio.numerator(),
            r_ratio.denominator() * Sr - r_ratio.numerator(),
        ]
    )
    telescopers, certificates = ideal.ct(
        St - _sage_const_1 ,
        certificates=True,
        early_termination=True,
        iteration_limit=_sage_const_16 ,
    )
    assert len(telescopers) == len(certificates) == _sage_const_1 
    return telescopers[_sage_const_0 ], certificates[_sage_const_0 ]


# Use M as a constant parameter while converting recurrence -> ODE ->
# rational pullback -> recurrence.
PM = QQ['MM']; (MM,) = PM._first_ngens(1)
Rr = PM['rr']; (rr,) = Rr._first_ngens(1)
Ar = OreAlgebra(Rr, names=('Srr',)); (Srr,) = Ar._first_ngens(1)
Rz = PM['zz']; (zz,) = Rz._first_ngens(1)
Az = OreAlgebra(Rz, names=('Dzz',)); (Dzz,) = Az._first_ngens(1)
Kz = Rz.fraction_field()
AzK = OreAlgebra(
    Kz,
    ("DzzK", lambda value: value,
     lambda value: value.derivative(zz)),
, names=('DzzK',)); (DzzK,) = AzK._first_ngens(1)
RL = PM['LL']; (LL,) = RL._first_ngens(1)
AL = OreAlgebra(RL, names=('SLL',)); (SLL,) = AL._first_ngens(1)
to_parameter_recurrence = R.hom([MM, rr, _sage_const_0 ], Rr)


def signed_binomial_transform(operator):
    """Transport an r-recurrence to its signed binomial transform."""

    recurrence = Ar(
        sum(
            to_parameter_recurrence(operator[shift]) * Srr**shift
            for shift in range(operator.order() + _sage_const_1 )
        )
    )
    generating_ode = recurrence.to_D(Az)
    # Direct chain-rule pullback.  The generic composition routine uses
    # a costly nullspace solver and is fragile over the parameter ring
    # QQ[M].  If phi=-z/(1-z), then D_u acts on A(phi(z)) as
    # (phi'(z))^(-1) D_z.  Ore multiplication automatically differentiates
    # the variable coefficients in successive powers.
    phi = Kz(-zz / (_sage_const_1  - zz))
    pulled_derivative = Kz.one() / phi.derivative(zz) * DzzK
    pulled_ode_fraction = sum(
        Kz(generating_ode[index](zz=phi))
        * pulled_derivative**index
        for index in range(generating_ode.order() + _sage_const_1 )
    )
    # B(z)=C(z)/(1-z), so C(z)=(1-z)B(z).  Right multiplication
    # by 1-z is the exact gauge transform L(C)=L((1-z)B).
    transformed_fraction = pulled_ode_fraction * Kz(_sage_const_1  - zz)
    common_denominator = lcm(
        Kz(transformed_fraction[index]).denominator()
        for index in range(transformed_fraction.order() + _sage_const_1 )
    )
    transformed_ode = Az(
        sum(
            Rz(
                common_denominator
                * Kz(transformed_fraction[index])
            )
            * Dzz**index
            for index in range(transformed_fraction.order() + _sage_const_1 )
        )
    )
    transformed = transformed_ode.to_S(AL)
    if transformed.valuation():
        transformed = AL(
            sum(
                transformed[index + transformed.valuation()] * SLL**index
                for index in range(
                    transformed.order() - transformed.valuation() + _sage_const_1 
                )
            )
        )
    return transformed.primitive_part()


def C(n, k):
    return comb(n, k) if _sage_const_0  <= k <= n else _sage_const_0 


def ray_value(moment, residue, point):
    u, v, w = point
    node = moment - residue
    return sum(
        C(moment, index)
        * C(moment, index - node * u)
        * C(_sage_const_2  * moment - index, moment - node * v)
        * C(_sage_const_2  * moment - index, moment - node * w)
        for index in range(moment + _sage_const_1 )
    )


def ray_packet(moment, order, point):
    return sum(
        (-_sage_const_1 ) ** residue
        * C(order, residue)
        * ray_value(moment, residue, point)
        for residue in range(order + _sage_const_1 )
    )


def evaluate_coefficient(polynomial, moment, order):
    return QQ(polynomial(MM=moment, LL=order))


def audit_transformed(operator, point):
    for moment in tuple(range(_sage_const_10 , _sage_const_23 )) + (_sage_const_31 , _sage_const_37 ):
        values = [
            ray_packet(moment, order, point)
            for order in range(moment + _sage_const_1 )
        ]
        for order in range(moment - operator.order()):
            total = sum(
                evaluate_coefficient(operator[shift], moment, order)
                * values[order + shift]
                for shift in range(operator.order() + _sage_const_1 )
            )
            assert total == _sage_const_0 , (point, moment, order, total)


transformed_operators = []
trailing_product = RL.one()
leading_product = RL.one()
for point, multiplicity in RAY_CLASSES:
    recurrence, certificate = ray_operator(point)
    transformed = signed_binomial_transform(recurrence)
    audit_transformed(transformed, point)
    transformed_operators.append(transformed)
    trailing = factor(transformed[_sage_const_0 ])
    leading = factor(transformed[transformed.order()])
    trailing_product *= transformed[_sage_const_0 ]
    leading_product *= transformed[transformed.order()]
    print(
        "BINOMIAL_RAY",
        point,
        "MULTIPLICITY",
        multiplicity,
        "R_ORDER",
        recurrence.order(),
        "L_ORDER",
        transformed.order(),
    )
    print("  L_TRAILING", trailing)
    print("  L_LEADING", leading)

# The direct sum of the fourteen companion systems is an exact system
# for the all-rays-summed packet.  Its two transition determinants have
# these products.  We keep them factored rather than expanding a large
# scalar LCLM.
print("SUMMED_SYSTEM_DIMENSION", sum(op.order() for op in transformed_operators))
print("SUMMED_SYSTEM_TRAILING_PRODUCT", factor(trailing_product))
print("SUMMED_SYSTEM_LEADING_PRODUCT", factor(leading_product))

# At a target, M=p+r-1 and L=r.  Reducing the endpoint products modulo p
# is the exact singular-factor test requested by the arithmetic argument.
Rp = QQ['p, ell']; (p, ell,) = Rp._first_ngens(2)
target_substitution = {
    MM: p + ell - _sage_const_1 ,
    LL: ell,
}
target_trailing = Rp(trailing_product.subs(target_substitution))
target_leading = Rp(leading_product.subs(target_substitution))
print("TARGET_TRAILING_PRODUCT", factor(target_trailing))
print("TARGET_LEADING_PRODUCT", factor(target_leading))
print("Q32_TERMINAL_BINOMIAL_TELESCOPERS=PASS")

