#!/usr/bin/env sage
"""Conormal residue of the same-moment logarithmic reduction.

Let

    I = (y-z, x-2*z-1, z^2-1/2)

be the smooth critical ideal.  For logarithmic fields V_i of weights
g_i generating I, integration by parts gives

    0 = CT Lambda^M (M*g_i*A + V_i(A) + beta_i*A).

For a monomial A=x^a*y^b*z^c, reduce the second term modulo I^2.
This produces a connection on the six-dimensional conormal fibre

    (I/I^2) tensor_Q Q[z]/(z^2-1/2).

The determinant of ``M + connection`` is invariant under changing the
chosen lifts by tangent logarithmic fields (up to a unit and change of
conormal basis).  Its zero locus therefore detects genuine resonances,
not zero-shift artifacts of one reduction gauge.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_log_conormal_resonance.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6)
S = PolynomialRing(QQ, names=('aa', 'bb', 'cc', 'MM',)); (aa, bb, cc, MM,) = S._first_ngens(4)
K = S.fraction_field()
R = PolynomialRing(K, order="degrevlex", names=('x', 'y', 'z',)); (x, y, z,) = R._first_ngens(3)

g_y = y - z
g_x = x - _sage_const_2  * z - _sage_const_1 
g_z = z**_sage_const_2  - K(_sage_const_1 ) / _sage_const_2 
generators = (g_y, g_x, g_z)

H_y = (R.zero(), y + _sage_const_1 , -z - _sage_const_1 )
beta_y = y - z

H_x = (
    x * y * z + x * z + y * z + x + z + _sage_const_1 ,
    -x * y * z - x * z + y + _sage_const_1 ,
    -x * z + y * z - x + y - z - _sage_const_1 ,
)
beta_x = y * z + x + y - z

H_z = (
    -K(_sage_const_1 ) / _sage_const_2  * x * y**_sage_const_2  * z - K(_sage_const_1 ) / _sage_const_2  * y**_sage_const_2  * z,
    K(_sage_const_1 ) / _sage_const_2  * x * y**_sage_const_2  * z
    + K(_sage_const_1 ) / _sage_const_2  * x * y * z
    - K(_sage_const_1 ) / _sage_const_2  * y**_sage_const_2 
    - K(_sage_const_1 ) / _sage_const_2  * y * z
    - K(_sage_const_1 ) / _sage_const_2  * y
    - K(_sage_const_1 ) / _sage_const_2  * z,
    -K(_sage_const_1 ) / _sage_const_2  * y**_sage_const_2  * z
    - K(_sage_const_1 ) / _sage_const_2  * y**_sage_const_2 
    + K(_sage_const_1 ) / _sage_const_2  * y * z
    + z**_sage_const_2 
    + K(_sage_const_1 ) / _sage_const_2  * y
    + K(_sage_const_3 ) / _sage_const_2  * z
    + K(_sage_const_1 ) / _sage_const_2 ,
)
beta_z = (
    K(_sage_const_1 ) / _sage_const_2  * x * y**_sage_const_2  * z
    + K(_sage_const_1 ) / _sage_const_2  * x * y * z
    - K(_sage_const_1 ) / _sage_const_2  * y**_sage_const_2  * z
    - y**_sage_const_2 
    + _sage_const_2  * z**_sage_const_2 
    - K(_sage_const_1 ) / _sage_const_2  * y
    + K(_sage_const_3 ) / _sage_const_2  * z
)

fields = (H_y, H_x, H_z)
betas = (beta_y, beta_x, beta_z)


def canonical_division(polynomial):
    """Triangular division by the displayed smooth Groebner basis."""

    after_y = R(polynomial(y=z))
    quotient_y = R((polynomial - after_y) // g_y)
    after_x = R(after_y(x=_sage_const_2  * z + _sage_const_1 ))
    quotient_x = R((after_y - after_x) // g_x)
    quotient_z, remainder = after_x.quo_rem(g_z)
    assert polynomial == (
        g_y * quotient_y
        + g_x * quotient_x
        + g_z * quotient_z
        + remainder
    )
    return (quotient_y, quotient_x, quotient_z), remainder


def smooth_pair(polynomial):
    """Coordinates in B=K[z]/(z^2-1/2), basis (1,z)."""

    specialized = R(polynomial(x=_sage_const_2  * z + _sage_const_1 , y=z))
    _, remainder = specialized.quo_rem(g_z)
    assert remainder.degree(z) <= _sage_const_1 
    return vector(
        K,
        (
            remainder.monomial_coefficient(R.one()),
            remainder.monomial_coefficient(z),
        ),
    )


def multiplication_matrix(pair):
    """Multiplication by pair[0]+pair[1]*z in B."""

    return matrix(
        K,
        (
            (pair[_sage_const_0 ], pair[_sage_const_1 ] / _sage_const_2 ),
            (pair[_sage_const_1 ], pair[_sage_const_0 ]),
        ),
    )


blocks = [[None for _ in range(_sage_const_3 )] for _ in range(_sage_const_3 )]
pair_entries = [[None for _ in range(_sage_const_3 )] for _ in range(_sage_const_3 )]
remainders = []
for source, (field, beta) in enumerate(zip(fields, betas)):
    coefficient = (
        aa * field[_sage_const_0 ] + bb * field[_sage_const_1 ] + cc * field[_sage_const_2 ] + beta
    )
    quotients, remainder = canonical_division(coefficient)
    remainders.append(smooth_pair(remainder))
    for target, quotient in enumerate(quotients):
        pair = smooth_pair(quotient)
        if source == target:
            pair[_sage_const_0 ] += MM
        pair_entries[source][target] = pair
        block = multiplication_matrix(pair)
        blocks[source][target] = block

connection = block_matrix(K, blocks)


def pair_add(left, right):
    return vector(K, (left[_sage_const_0 ] + right[_sage_const_0 ], left[_sage_const_1 ] + right[_sage_const_1 ]))


def pair_scale(scalar, value):
    return vector(K, (scalar * value[_sage_const_0 ], scalar * value[_sage_const_1 ]))


def pair_mul(left, right):
    return vector(
        K,
        (
            left[_sage_const_0 ] * right[_sage_const_0 ] + left[_sage_const_1 ] * right[_sage_const_1 ] / _sage_const_2 ,
            left[_sage_const_0 ] * right[_sage_const_1 ] + left[_sage_const_1 ] * right[_sage_const_0 ],
        ),
    )


def determinant_three(entries):
    positive = (
        pair_mul(entries[_sage_const_0 ][_sage_const_0 ], pair_mul(entries[_sage_const_1 ][_sage_const_1 ], entries[_sage_const_2 ][_sage_const_2 ])),
        pair_mul(entries[_sage_const_0 ][_sage_const_1 ], pair_mul(entries[_sage_const_1 ][_sage_const_2 ], entries[_sage_const_2 ][_sage_const_0 ])),
        pair_mul(entries[_sage_const_0 ][_sage_const_2 ], pair_mul(entries[_sage_const_1 ][_sage_const_0 ], entries[_sage_const_2 ][_sage_const_1 ])),
    )
    negative = (
        pair_mul(entries[_sage_const_0 ][_sage_const_2 ], pair_mul(entries[_sage_const_1 ][_sage_const_1 ], entries[_sage_const_2 ][_sage_const_0 ])),
        pair_mul(entries[_sage_const_0 ][_sage_const_1 ], pair_mul(entries[_sage_const_1 ][_sage_const_0 ], entries[_sage_const_2 ][_sage_const_2 ])),
        pair_mul(entries[_sage_const_0 ][_sage_const_0 ], pair_mul(entries[_sage_const_1 ][_sage_const_2 ], entries[_sage_const_2 ][_sage_const_1 ])),
    )
    out = vector(K, (_sage_const_0 , _sage_const_0 ))
    for value in positive:
        out = pair_add(out, value)
    for value in negative:
        out = pair_add(out, pair_scale(-_sage_const_1 , value))
    return out


quadratic_determinant = determinant_three(pair_entries)
determinant_norm = (
    quadratic_determinant[_sage_const_0 ] ** _sage_const_2 
    - quadratic_determinant[_sage_const_1 ] ** _sage_const_2  / _sage_const_2 
)

print("CONORMAL_MATRIX")
print(connection)
print("CONORMAL_REMAINDERS", remainders)
print(
    "CONORMAL_QUADRATIC_DETERMINANT",
    tuple(factor(entry) for entry in quadratic_determinant),
)
print("CONORMAL_DETERMINANT_NORM", factor(determinant_norm))

# A change of conormal basis cannot alter the resonance divisor.
assert connection.nrows() == connection.ncols() == _sage_const_6 
assert determinant_norm != _sage_const_0 
print("Q32_LOG_CONORMAL_RESONANCE=PASS")

