#!/usr/bin/env sage
"""Audit the fixed origin/shift-one ghost minor at the first divided digit.

For a candidate prime ``p`` in a Newton core, every origin-cancelled or
common-annihilator ghost carrier is divisible by ``p``.  Dividing the two
endpoint carriers by ``p`` and reducing modulo ``p`` is equivalent, up to
the common unit ``Q_I / p``, to dividing by the complete core primorial.

This script computes those first divided digits directly modulo ``p^2``.
It audits the fixed minor

    det(R_{-1,m}, R_{1,m}),

where ``R_{-1,m}`` is the origin-cancelled column and ``R_{1,m}`` is the
shift-one common-annihilator ghost.  It also verifies the closed formula
for the divided Newton functional in ``divided_newton_formula``.

Examples:

    sage q32_fixed_minor_jet_audit.sage --central 300
    sage q32_fixed_minor_jet_audit.sage --random 40 --seed 320
    sage q32_fixed_minor_jet_audit.sage \
        --central-all 200 --all-ghosts --allow-failures

All shell arithmetic is performed modulo ``p^2``; no large exact shell
integers are constructed.
"""


# This file was *autogenerated* from the file problems/3.2/research/scripts/q32_fixed_minor_jet_audit.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_13 = Integer(13); _sage_const_60 = Integer(60); _sage_const_80 = Integer(80); _sage_const_8 = Integer(8); _sage_const_12 = Integer(12); _sage_const_320 = Integer(320); _sage_const_800 = Integer(800); _sage_const_200 = Integer(200); _sage_const_128 = Integer(128); _sage_const_63 = Integer(63); _sage_const_139 = Integer(139); _sage_const_181 = Integer(181); _sage_const_321 = Integer(321); _sage_const_168 = Integer(168); _sage_const_53 = Integer(53); _sage_const_179 = Integer(179); _sage_const_193 = Integer(193); _sage_const_211 = Integer(211)
from pathlib import Path
import argparse
import random
import sys

from ore_algebra import *


HERE = Path(__file__).resolve().parent
load(str(HERE / "q32_doubled_period_gauge_audit.sage"))


def primitive_integral_coefficients(operator):
    coefficients = [K(operator[i]) for i in range(operator.order() + _sage_const_1 )]
    polynomial_denominator = lcm(value.denominator() for value in coefficients)
    polynomials = [R(polynomial_denominator * value) for value in coefficients]
    rational_denominator = lcm(
        coefficient.denominator()
        for polynomial in polynomials
        for coefficient in polynomial.list()
    )
    polynomials = [R(rational_denominator * value) for value in polynomials]
    content = gcd(
        [
            ZZ(coefficient)
            for polynomial in polynomials
            for coefficient in polynomial.list()
        ]
    )
    answer = tuple(R(value / content) for value in polynomials)
    assert gcd(answer) == _sage_const_1 
    return answer


common_operator = P.lclm(apery_operator)
ghost_coefficients = primitive_integral_coefficients(common_operator)
integral_common_operator = sum(
    ghost_coefficients[shift] * OAK(Sn)**shift
    for shift in range(len(ghost_coefficients))
)
twisted_apery_operator = sum(
    K(apery_operator[shift])
    / K(multiplier(n=n + shift))
    * OAK(Sn)**shift
    for shift in range(apery_operator.order() + _sage_const_1 )
)
ore_quotient, ore_remainder = (
    (twisted_apery_operator * integral_operator).quo_rem(
        integral_common_operator
    )
)
assert ore_remainder == _sage_const_0 
assert ore_quotient.order() == _sage_const_1 


def margin_data(index, D, N):
    moment = index - _sage_const_1 
    maximum_margin = min(
        D - moment // _sage_const_2 ,
        moment - D - N + _sage_const_2 ,
    )
    assert maximum_margin >= _sage_const_2 
    return maximum_margin, (maximum_margin - _sage_const_1 , maximum_margin)


def newton_mod(values, lower_node, length, modulus):
    return ZZ(
        sum(
            (-_sage_const_1 )**offset
            * binomial(lower_node + offset, offset)
            * binomial(
                lower_node + length + _sage_const_1 ,
                length - offset,
            )
            * values[lower_node + offset]
            for offset in range(length + _sage_const_1 )
        )
        % modulus
    )


def divided_newton_formula(values, lower_node, length, prime):
    """Return ``G_{d,L}(F)/p mod p`` from the first divided node digit.

    This applies when ``L<p``, ``p-1=d+j`` is in the stencil, and
    ``F_{p-1}=0 mod p``.  Put ``s=L-j``.  The off-node coefficients are
    the once-divided Newton weights:

      i<j: (-1)^(j-i-1) C(j,i) s!(j-i-1)!/(s+j-i)!,
      i=j+t: (-1)^t C(s,t) (t-1)!j!/(j+t)!.
    """

    j = prime - _sage_const_1  - lower_node
    s = length - j
    assert _sage_const_0  <= j <= length < prime
    assert values[prime - _sage_const_1 ] % prime == _sage_const_0 
    answer = (values[prime - _sage_const_1 ] // prime) % prime

    for i in range(j):
        numerator = (
            (-_sage_const_1 )**(j - i - _sage_const_1 )
            * binomial(j, i)
            * factorial(s)
            * factorial(j - i - _sage_const_1 )
        )
        denominator = factorial(s + j - i)
        answer += (
            numerator
            * inverse_mod(denominator, prime)
            * values[lower_node + i]
        )

    for t in range(_sage_const_1 , s + _sage_const_1 ):
        numerator = (
            (-_sage_const_1 )**t
            * binomial(s, t)
            * factorial(t - _sage_const_1 )
            * factorial(j)
        )
        denominator = factorial(j + t)
        answer += (
            numerator
            * inverse_mod(denominator, prime)
            * values[prime - _sage_const_1  + t]
        )

    return ZZ(answer % prime)


def rational_mod(value, prime):
    value = QQ(value)
    numerator = ZZ(value.numerator()) % prime
    denominator = ZZ(value.denominator()) % prime
    if denominator == _sage_const_0 :
        return None
    return ZZ(numerator * inverse_mod(denominator, prime) % prime)


def apery_mod(index, prime):
    return ZZ(apery(index) % prime)


def build_node_functions(index, D, N, modulus):
    maximum_margin, margins = margin_data(index, D, N)

    terminal_d = D - maximum_margin + _sage_const_1 
    terminal_length = N + maximum_margin - _sage_const_2 
    lower_node = terminal_d
    upper_node = D + terminal_length
    nodes = tuple(range(lower_node, upper_node + _sage_const_1 ))
    neighbours = tuple(range(lower_node - _sage_const_1 , upper_node + _sage_const_2 ))

    y_values = shell_batch(index - _sage_const_1 , nodes, modulus=modulus)
    maximum_ghost_shift = _sage_const_4  if "--all-ghosts" in sys.argv else _sage_const_1 
    maximum_time_index = max(index + _sage_const_6 , index + maximum_ghost_shift + _sage_const_5 )
    time_shells = {
        time_index: shell_batch(
            time_index,
            neighbours,
            modulus=modulus,
        )
        for time_index in range(index, maximum_time_index + _sage_const_1 )
    }

    def shell_pair(time_index, node):
        return (
            time_shells[time_index][node - _sage_const_1 ]
            + time_shells[time_index][node + _sage_const_1 ]
        ) % modulus

    shifted_y = {
        _sage_const_0 : y_values,
        _sage_const_1 : {node: time_shells[index][node] for node in nodes},
        _sage_const_2 : {node: time_shells[index + _sage_const_1 ][node] for node in nodes},
    }
    origin_shifts = {
        time_shift: {
            node: ZZ(
                (
                    sum(
                        ZZ(
                            integer_coefficients[operator_shift](
                                n=index + time_shift
                            )
                        )
                        * shell_pair(
                            index + time_shift + operator_shift,
                            node,
                        )
                        for operator_shift in range(
                            len(integer_coefficients)
                        )
                    )
                    - ZZ(multiplier(n=index + time_shift))
                    * shifted_y[time_shift][node]
                )
                % modulus
            )
            for node in nodes
        }
        for time_shift in range(_sage_const_3 )
    }
    ghost_shifts = {
        time_shift: {
            node: ZZ(
                sum(
                    ZZ(
                        ghost_coefficients[operator_shift](
                            n=index + time_shift
                        )
                    )
                    * shell_pair(
                        index + time_shift + operator_shift,
                        node,
                    )
                    for operator_shift in range(
                        len(ghost_coefficients)
                    )
                )
                % modulus
            )
            for node in nodes
        }
        for time_shift in range(maximum_ghost_shift + _sage_const_1 )
    }
    apery_defect = {
        node: ZZ(
            sum(
                ZZ(apery_operator[time_shift](n=index))
                * shifted_y[time_shift][node]
                for time_shift in range(_sage_const_3 )
            )
            % modulus
        )
        for node in nodes
    }
    return (
        margins,
        nodes,
        origin_shifts[_sage_const_0 ],
        ghost_shifts[_sage_const_1 ],
        {
            "origin_shifts": origin_shifts,
            "ghost_zero": ghost_shifts[_sage_const_0 ],
            "ghost_shifts": ghost_shifts,
            "apery_defect": apery_defect,
        },
    )


def audit_candidate(index, D, N, prime, node_functions=None):
    assert D < prime <= D + N
    assert index - prime + _sage_const_9  <= prime - _sage_const_5 
    modulus = prime**_sage_const_2 
    if node_functions is None:
        (
            margins,
            nodes,
            origin,
            ghost_one,
            auxiliary,
        ) = build_node_functions(
            index,
            D,
            N,
            modulus,
        )
    else:
        margins, nodes, origin, ghost_one, auxiliary = node_functions

    assert origin[prime - _sage_const_1 ] % prime == _sage_const_0 
    assert ghost_one[prime - _sage_const_1 ] % prime == _sage_const_0 

    residue = index - prime
    records = []
    ore_elimination_records = []
    all_ghost_records = []
    for margin in margins:
        d = D - margin + _sage_const_1 
        length = N + margin - _sage_const_2 
        assert length < prime
        columns = []
        for values in (origin, ghost_one):
            left = newton_mod(values, d, length, modulus)
            right = newton_mod(values, D, length, modulus)
            assert left % prime == _sage_const_0 
            assert right % prime == _sage_const_0 
            divided = (left // prime % prime, right // prime % prime)
            formula = (
                divided_newton_formula(values, d, length, prime),
                divided_newton_formula(values, D, length, prime),
            )
            assert divided == formula
            columns.append(divided)

        determinant = ZZ(
            (
                columns[_sage_const_0 ][_sage_const_0 ] * columns[_sage_const_1 ][_sage_const_1 ]
                - columns[_sage_const_0 ][_sage_const_1 ] * columns[_sage_const_1 ][_sage_const_0 ]
            )
            % prime
        )
        records.append((margin, determinant, tuple(columns)))

        if "--all-ghosts" in sys.argv:
            all_columns = [columns[_sage_const_0 ]]
            all_columns.extend(
                (
                    divided_newton_formula(
                        auxiliary["ghost_shifts"][shift],
                        d,
                        length,
                        prime,
                    ),
                    divided_newton_formula(
                        auxiliary["ghost_shifts"][shift],
                        D,
                        length,
                        prime,
                    ),
                )
                for shift in range(_sage_const_5 )
            )
            all_minors = tuple(
                ZZ(
                    (
                        all_columns[left][_sage_const_0 ]
                        * all_columns[right][_sage_const_1 ]
                        - all_columns[left][_sage_const_1 ]
                        * all_columns[right][_sage_const_0 ]
                    )
                    % prime
                )
                for left in range(_sage_const_6 )
                for right in range(left + _sage_const_1 , _sage_const_6 )
            )
            all_ghost_records.append(
                (
                    margin,
                    any(all_minors),
                    tuple(
                        index
                        for index, value in enumerate(all_minors)
                        if value
                    ),
                )
            )

        alpha = tuple(
            rational_mod(
                twisted_apery_operator[shift](n=residue),
                prime,
            )
            for shift in range(_sage_const_3 )
        )
        q_values = tuple(
            rational_mod(ore_quotient[shift](n=residue), prime)
            for shift in range(_sage_const_2 )
        )
        if None not in alpha + q_values:
            def divided_vector(values):
                return vector(
                    GF(prime),
                    [
                        divided_newton_formula(
                            values,
                            lower,
                            length,
                            prime,
                        )
                        for lower in (d, D)
                    ],
                )

            origin_vectors = tuple(
                divided_vector(auxiliary["origin_shifts"][shift])
                for shift in range(_sage_const_3 )
            )
            ghost_zero_vector = divided_vector(
                auxiliary["ghost_zero"]
            )
            ghost_one_vector = divided_vector(ghost_one)
            defect_vector = divided_vector(
                auxiliary["apery_defect"]
            )
            left_side = sum(
                (
                    GF(prime)(alpha[shift])
                    * origin_vectors[shift]
                    for shift in range(_sage_const_3 )
                ),
                vector(GF(prime), [_sage_const_0 , _sage_const_0 ]),
            ) + defect_vector
            right_side = (
                GF(prime)(q_values[_sage_const_0 ]) * ghost_zero_vector
                + GF(prime)(q_values[_sage_const_1 ]) * ghost_one_vector
            )
            assert left_side == right_side

            def wedge(left, right):
                return ZZ(
                    left[_sage_const_0 ] * right[_sage_const_1 ] - left[_sage_const_1 ] * right[_sage_const_0 ]
                )

            wedge_residuals = (
                ZZ(
                    GF(prime)(alpha[_sage_const_1 ])
                    * wedge(origin_vectors[_sage_const_0 ], origin_vectors[_sage_const_1 ])
                ),
                ZZ(
                    GF(prime)(alpha[_sage_const_2 ])
                    * wedge(origin_vectors[_sage_const_0 ], origin_vectors[_sage_const_2 ])
                ),
                wedge(origin_vectors[_sage_const_0 ], defect_vector),
                ZZ(
                    -GF(prime)(q_values[_sage_const_0 ])
                    * wedge(origin_vectors[_sage_const_0 ], ghost_zero_vector)
                ),
            )
            assert (
                sum(wedge_residuals)
                - GF(prime)(q_values[_sage_const_1 ]) * determinant
            ) % prime == _sage_const_0 
            ore_elimination_records.append(
                (
                    margin,
                    alpha,
                    q_values,
                    tuple(value % prime for value in wedge_residuals),
                )
            )

    q0 = rational_mod(ore_quotient[_sage_const_0 ](n=residue), prime)
    q1 = rational_mod(ore_quotient[_sage_const_1 ](n=residue), prime)
    record = {
        "n": index,
        "core": (D, N),
        "p": prime,
        "r": residue,
        "target": apery_mod(residue, prime) == _sage_const_0 ,
        "b_next": apery_mod(residue + _sage_const_1 , prime),
        "ore_q": (q0, q1),
        "records": tuple(records),
        "ore_elimination": tuple(ore_elimination_records),
        "all_ghost_rank_two": tuple(all_ghost_records),
    }
    if "--profiles" in sys.argv:
        record["support_mod_p"] = {
            "origin": tuple(
                node - (prime - _sage_const_1 )
                for node in nodes
                if origin[node] % prime
            ),
            "ghost_one": tuple(
                node - (prime - _sage_const_1 )
                for node in nodes
                if ghost_one[node] % prime
            ),
        }
    return record


def audit_block(index, D, N):
    candidates = tuple(
        prime
        for prime in prime_range(D + _sage_const_1 , D + N + _sage_const_1 )
        if index - prime + _sage_const_9  <= prime - _sage_const_5 
    )
    if not candidates:
        return ()
    modulus = prod(prime**_sage_const_2  for prime in candidates)
    node_functions = build_node_functions(index, D, N, modulus)
    return tuple(
        audit_candidate(index, D, N, prime, node_functions)
        for prime in candidates
    )


def central_cases(limit, step=_sage_const_20 ):
    return tuple(
        (index, (_sage_const_13  * index) // _sage_const_20 , index // _sage_const_5 )
        for index in range(_sage_const_60 , limit + _sage_const_1 , step)
    )


def random_cases(count, seed, maximum_index):
    generator = random.Random(seed)
    cases = []
    while len(cases) < count:
        index = generator.randrange(_sage_const_80 , maximum_index + _sage_const_1 )
        N = generator.randrange(max(_sage_const_8 , index // _sage_const_12 ), max(_sage_const_9 , index // _sage_const_4 ))
        lower_D = (index - _sage_const_1 ) // _sage_const_2  + _sage_const_3 
        upper_D = index - N - _sage_const_2 
        if lower_D > upper_D:
            continue
        D = generator.randrange(lower_D, upper_D + _sage_const_1 )
        maximum_margin, _ = margin_data(index, D, N)
        if maximum_margin < _sage_const_2 :
            continue
        candidates = tuple(
            prime
            for prime in prime_range(D + _sage_const_1 , D + N + _sage_const_1 )
            if index - prime + _sage_const_9  <= prime - _sage_const_5 
        )
        if not candidates:
            continue
        prime = generator.choice(candidates)
        cases.append((index, D, N, prime))
    return tuple(cases)


def random_blocks(count, seed, maximum_index):
    generator = random.Random(seed)
    blocks = []
    while len(blocks) < count:
        index = generator.randrange(_sage_const_80 , maximum_index + _sage_const_1 )
        N = generator.randrange(max(_sage_const_8 , index // _sage_const_12 ), max(_sage_const_9 , index // _sage_const_4 ))
        lower_D = (index - _sage_const_1 ) // _sage_const_2  + _sage_const_3 
        upper_D = index - N - _sage_const_2 
        if lower_D > upper_D:
            continue
        D = generator.randrange(lower_D, upper_D + _sage_const_1 )
        maximum_margin, _ = margin_data(index, D, N)
        if maximum_margin < _sage_const_2 :
            continue
        if not any(
            index - prime + _sage_const_9  <= prime - _sage_const_5 
            for prime in prime_range(D + _sage_const_1 , D + N + _sage_const_1 )
        ):
            continue
        blocks.append((index, D, N))
    return tuple(blocks)


def balanced_blocks(count, seed, maximum_index):
    """Random cores whose left and right first-cell margins differ by <= 1."""

    generator = random.Random(seed)
    blocks = []
    while len(blocks) < count:
        index = generator.randrange(_sage_const_80 , maximum_index + _sage_const_1 )
        N = generator.randrange(max(_sage_const_8 , index // _sage_const_12 ), max(_sage_const_9 , index // _sage_const_4 ))
        midpoint = (index - _sage_const_1 ) // _sage_const_2 
        # Solve D-midpoint = index+1-D-N up to the nearest integer.
        D = (index + _sage_const_1  + midpoint - N) // _sage_const_2 
        if abs((D - midpoint) - (index + _sage_const_1  - D - N)) > _sage_const_1 :
            continue
        if margin_data(index, D, N)[_sage_const_0 ] < _sage_const_2 :
            continue
        if not any(
            index - prime + _sage_const_9  <= prime - _sage_const_5 
            for prime in prime_range(D + _sage_const_1 , D + N + _sage_const_1 )
        ):
            continue
        blocks.append((index, D, N))
    return tuple(blocks)


parser = argparse.ArgumentParser(add_help=False)
parser.add_argument("--central", type=int, default=_sage_const_0 )
parser.add_argument("--central-all", type=int, default=_sage_const_0 )
parser.add_argument("--random", type=int, default=_sage_const_0 )
parser.add_argument("--random-blocks", type=int, default=_sage_const_0 )
parser.add_argument("--balanced-blocks", type=int, default=_sage_const_0 )
parser.add_argument("--seed", type=int, default=_sage_const_320 )
parser.add_argument("--max-n", type=int, default=_sage_const_800 )
parser.add_argument("--case", nargs=_sage_const_4 , type=int, action="append")
arguments, _ = parser.parse_known_args()

records = []
work = []
if arguments.central:
    for index, D, N in central_cases(arguments.central):
        records.extend(audit_block(index, D, N))
if arguments.central_all:
    for index, D, N in central_cases(arguments.central_all, step=_sage_const_1 ):
        records.extend(audit_block(index, D, N))
if arguments.random:
    work.extend(
        random_cases(arguments.random, arguments.seed, arguments.max_n)
    )
if arguments.random_blocks:
    for block in random_blocks(
        arguments.random_blocks,
        arguments.seed,
        arguments.max_n,
    ):
        records.extend(audit_block(*block))
if arguments.balanced_blocks:
    for block in balanced_blocks(
        arguments.balanced_blocks,
        arguments.seed,
        arguments.max_n,
    ):
        records.extend(audit_block(*block))
if arguments.case:
    work.extend(tuple(case) for case in arguments.case)
if not records and not work:
    work = [
        (_sage_const_200 , _sage_const_128 , _sage_const_63 , _sage_const_139 ),
        (_sage_const_200 , _sage_const_128 , _sage_const_63 , _sage_const_181 ),
        (_sage_const_321 , _sage_const_168 , _sage_const_53 , _sage_const_179 ),
        (_sage_const_321 , _sage_const_168 , _sage_const_53 , _sage_const_193 ),
        (_sage_const_321 , _sage_const_168 , _sage_const_53 , _sage_const_211 ),
    ]

records.extend(audit_candidate(*case) for case in work)
failures = []
rank_failures = []
for record in records:
    if any(determinant == _sage_const_0  for _, determinant, _ in record["records"]):
        failures.append(record)
        print("FIXED_MINOR_FAILURE", record)
    else:
        print("FIXED_MINOR_PASS", record)
    rank_failures.extend(
        (record["n"], record["core"], record["p"], margin)
        for margin, rank_two, _ in record["all_ghost_rank_two"]
        if not rank_two
    )

print(
    "Q32_FIXED_MINOR_JET_AUDIT",
    {
        "candidate_incidences": len(records),
        "margin_incidences": _sage_const_2  * len(records),
        "failures": len(failures),
        "six_column_rank_failures": len(rank_failures),
    },
)
assert not failures or "--allow-failures" in sys.argv
assert not rank_failures

