#!/usr/bin/env python3
"""Q7730 exact finite-field audit for the canonical framed Apéry extension.

This is a finite algebraic verifier, NOT a proof of geometric monodromy or an
asymptotic sieve theorem.

For each test prime p it reconstructs, entirely in F_p:
  * the Apéry Hasse row b_r;
  * Q=(1-34t+t^2)^(-1/2);
  * g=Q/F^2, F=sum b_r t^r;
  * the canonical inhomogeneous companion kappa;
  * Xi_r=r^3(b_{r-1}kappa_r-b_r kappa_{r-1}).

It then checks three exact finite-field proxies required by any future framed
(parabolic) monodromy approach:
  FND1. The homogeneous 2-dimensional transfer system has no common invariant
        line over F_p (irreducibility of the generated linear action).
  FND2. The canonical source is not removable by a constant affine splitting:
        there is no v in F_p^2 with (I-A_r)v=c_r for every step r.
  FND3. The joint residual row r -> (b_r,Xi_r) is not contained in an affine
        line (rank of [1,b_r,Xi_r] is 3).
It also checks that the translation module generated by one source vector and
its linear orbit is 2-dimensional, and locks the known common/noncommon pairs.

These are necessary finite-field nondegeneracy checks only.  They do not make
Xi a conjugacy-invariant Frobenius trace and do not bypass the defining-
characteristic/moving-character quantifier obstruction.
"""

from __future__ import annotations


def P(n: int) -> int:
    return 34*n**3 + 51*n**2 + 27*n + 5


def apery_row(p: int) -> list[int]:
    b = [0]*p
    b[0], b[1] = 1, 5 % p
    for n in range(1, p-1):
        b[n+1] = (P(n)*b[n] - n**3*b[n-1]) * pow((n+1)**3, -1, p) % p
    return b


def legendre_q_row(p: int) -> list[int]:
    q = [0]*p
    q[0], q[1] = 1, 17 % p
    for n in range(1, p-1):
        q[n+1] = ((34*n+17)*q[n] - n*q[n-1]) * pow(n+1, -1, p) % p
    return q


def source_g_row(p: int, b: list[int], q: list[int]) -> list[int]:
    # H=F^2 modulo t^p, then solve H*g=Q coefficient by coefficient; H_0=1.
    h = [0]*p
    for n in range(p):
        total = 0
        for i in range(n+1):
            total += b[i]*b[n-i]
        h[n] = total % p
    assert h[0] == 1
    g = [0]*p
    for n in range(p):
        total = q[n]
        for i in range(1, n+1):
            total -= h[i]*g[n-i]
        g[n] = total % p
    return g


def kappa_xi_rows(p: int, b: list[int], g: list[int]) -> tuple[list[int], list[int]]:
    k = [0]*p
    k[0], k[1] = 0, (-36) % p
    for r in range(1, p-1):
        k[r+1] = (P(r)*k[r] - r**3*k[r-1] - 5*g[r+1]) * pow((r+1)**3, -1, p) % p

    xi = [0]*p
    xi[0] = (-1) % p
    for r in range(1, p):
        xi[r] = (xi[r-1] - 5*g[r]*b[r-1]) % p
        wr = r**3 * (b[r-1]*k[r] - b[r]*k[r-1]) % p
        assert xi[r] == wr, (p, r, xi[r], wr)
    return k, xi


def transfer(p: int, r: int, g: list[int]):
    inv = pow((r+1)**3, -1, p)
    A = (
        (P(r)*inv % p, (-r**3)*inv % p),
        (1, 0),
    )
    c = ((-5*g[r+1])*inv % p, 0)
    return A, c


def mat_vec(A, v, p):
    return ((A[0][0]*v[0]+A[0][1]*v[1]) % p,
            (A[1][0]*v[0]+A[1][1]*v[1]) % p)


def det2(u, v, p):
    return (u[0]*v[1]-u[1]*v[0]) % p


def common_invariant_line(p: int, As) -> tuple[int, int] | None:
    # Lines are represented by (1,t), t in F_p, plus the vertical line (0,1).
    candidates = [(1,t) for t in range(p)] + [(0,1)]
    # A handful of matrices almost always kills all candidates; if not, the
    # survivors are checked against the full list.
    for A in As[:min(8, len(As))]:
        candidates = [v for v in candidates if det2(v, mat_vec(A,v,p), p) == 0]
        if not candidates:
            return None
    for v in candidates:
        if all(det2(v, mat_vec(A,v,p), p) == 0 for A in As):
            return v
    return None


def affine_rank3(p: int, b: list[int], xi: list[int]) -> int:
    # Gaussian rank of rows [1,b_r,xi_r] for 1<=r<=p-2.
    basis = []
    for r in range(1, p-1):
        row = [1, b[r] % p, xi[r] % p]
        for pivot, vec in basis:
            if row[pivot]:
                factor = row[pivot] * pow(vec[pivot], -1, p) % p
                row = [(row[j]-factor*vec[j]) % p for j in range(3)]
        if any(row):
            pivot = next(j for j,x in enumerate(row) if x)
            basis.append((pivot,row))
            basis.sort(key=lambda x:x[0])
        if len(basis) == 3:
            return 3
    return len(basis)


def constant_coboundary_solution(p: int, As, cs):
    # Solve all equations (I-A_r)v=c_r by Gaussian elimination in 2 unknowns.
    equations = []
    for A,c in zip(As,cs):
        equations.append([(1-A[0][0])%p, (-A[0][1])%p, c[0]%p])
        equations.append([(-A[1][0])%p, (1-A[1][1])%p, c[1]%p])

    rows = [row[:] for row in equations]
    pivot_row = 0
    pivots = []
    for col in range(2):
        j = next((j for j in range(pivot_row,len(rows)) if rows[j][col] % p), None)
        if j is None:
            continue
        rows[pivot_row], rows[j] = rows[j], rows[pivot_row]
        inv = pow(rows[pivot_row][col] % p, -1, p)
        rows[pivot_row] = [(x*inv) % p for x in rows[pivot_row]]
        for j in range(len(rows)):
            if j != pivot_row and rows[j][col] % p:
                f = rows[j][col] % p
                rows[j] = [(rows[j][k]-f*rows[pivot_row][k]) % p for k in range(3)]
        pivots.append(col)
        pivot_row += 1
    if any(row[0] % p == 0 and row[1] % p == 0 and row[2] % p != 0 for row in rows):
        return None
    v = [0,0]
    for i,col in enumerate(pivots):
        v[col] = rows[i][2] % p
    if all(((1-A[0][0])*v[0]-A[0][1]*v[1]-c[0]) % p == 0 and
           (-A[1][0]*v[0]+(1-A[1][1])*v[1]-c[1]) % p == 0
           for A,c in zip(As,cs)):
        return tuple(v)
    return None


def translation_module_rank(p: int, As, cs) -> int:
    c0 = next((c for c in cs if c != (0,0)), None)
    if c0 is None:
        return 0
    vectors = [c0]
    for A in As[:min(16,len(As))]:
        vectors.append(mat_vec(A,c0,p))
    if any(det2(vectors[0],v,p) for v in vectors[1:]):
        return 2
    return 1


def audit_prime(p: int):
    b = apery_row(p)
    q = legendre_q_row(p)
    g = source_g_row(p,b,q)
    k,xi = kappa_xi_rows(p,b,g)
    assert g[0] == 1 % p and g[1] == 7 % p

    As,cs = [],[]
    for r in range(1,p-1):
        A,c = transfer(p,r,g)
        As.append(A); cs.append(c)
        lhs = (k[r+1],k[r])
        rhs0 = (A[0][0]*k[r]+A[0][1]*k[r-1]+c[0]) % p
        rhs1 = (A[1][0]*k[r]+A[1][1]*k[r-1]+c[1]) % p
        assert lhs == (rhs0,rhs1)

    inv_line = common_invariant_line(p,As)
    cob = constant_coboundary_solution(p,As,cs)
    trank = translation_module_rank(p,As,cs)
    arank = affine_rank3(p,b,xi)

    zeros = [r for r in range(1,p-1) if b[r] == 0]
    common = [r for r in zeros if k[r] == 0]
    for r in zeros:
        assert b[r-1] != 0
        assert (k[r] == 0) == (xi[r] == 0)

    assert inv_line is None, (p, inv_line)
    assert cob is None, (p, cob)
    assert trank == 2, (p, trank)
    assert arank == 3, (p, arank)

    print(
        f"p={p} bzeros={zeros} common={common} "
        f"FND1_irreducible=PASS FND2_nonconstant_split=PASS "
        f"translation_rank={trank} joint_affine_rank={arank}"
    )
    return common


def main():
    test_primes = [7,11,13,17,19,29,41,101,181,2237]
    results = {p:audit_prime(p) for p in test_primes}
    assert 13 in results[17]
    assert 492 in results[2237]
    assert 5 not in results[11]
    print("LOCKED_COMMON_17_13=PASS")
    print("LOCKED_COMMON_2237_492=PASS")
    print("LOCKED_NONCOMMON_11_5=PASS")
    print("Q7730_FRAMED_FINITE_FIELD_VERIFY PASS")


if __name__ == "__main__":
    main()
