

# This file was *autogenerated* from the file pin.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_12 = Integer(12); _sage_const_3 = Integer(3); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_14 = Integer(14); _sage_const_48 = Integer(48); _sage_const_13 = Integer(13); _sage_const_87 = Integer(87); _sage_const_133 = Integer(133); _sage_const_178 = Integer(178); _sage_const_211 = Integer(211); _sage_const_223 = Integer(223); _sage_const_400 = Integer(400); _sage_const_4080 = Integer(4080); _sage_const_60 = Integer(60); _sage_const_30 = Integer(30); _sage_const_85 = Integer(85); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20)# Final step: rational reconstruction with the proved denominator bound.
prec=_sage_const_1000 ; RRp=RealField(prec); CCp=ComplexField(prec)
R = PolynomialRing(QQ, names=('z',)); (z,) = R._first_ngens(1)
fa=z**_sage_const_12 -_sage_const_3 *z**_sage_const_11 +_sage_const_4 *z**_sage_const_10 -_sage_const_5 *z**_sage_const_9 +_sage_const_6 *z**_sage_const_8 -_sage_const_7 *z**_sage_const_7 +_sage_const_7 *z**_sage_const_6 -_sage_const_7 *z**_sage_const_5 +_sage_const_6 *z**_sage_const_4 -_sage_const_5 *z**_sage_const_3 +_sage_const_4 *z**_sage_const_2 -_sage_const_3 *z+_sage_const_1 
fb=(z**_sage_const_16 -_sage_const_7 *z**_sage_const_15 +_sage_const_22 *z**_sage_const_14 -_sage_const_48 *z**_sage_const_13 +_sage_const_87 *z**_sage_const_12 -_sage_const_133 *z**_sage_const_11 +_sage_const_178 *z**_sage_const_10 -_sage_const_211 *z**_sage_const_9 +_sage_const_223 *z**_sage_const_8 
    -_sage_const_211 *z**_sage_const_7 +_sage_const_178 *z**_sage_const_6 -_sage_const_133 *z**_sage_const_5 +_sage_const_87 *z**_sage_const_4 -_sage_const_48 *z**_sage_const_3 +_sage_const_22 *z**_sage_const_2 -_sage_const_7 *z+_sage_const_1 )
def sh(M,L):
    X=M**_sage_const_2 ; u=(L+X**_sage_const_3 )/(X*(L+X)); r=-(_sage_const_1 +sqrt(_sage_const_1 +_sage_const_4 *u**_sage_const_2 ))/(_sage_const_2 *u)
    return [_sage_const_1 -r**_sage_const_2 ,u,u/X,_sage_const_1 /(_sage_const_1 -u*X)]
def Rh(v):
    zc=CCp(v); return dilog(zc)+log(zc)*log(_sage_const_1 -zc)/_sage_const_2 -CCp.pi()**_sage_const_2 /_sage_const_6 
Ka = NumberField(fa,embedding=RealField(_sage_const_400 )("0.5909894286702564"), names=('aa',)); (aa,) = Ka._first_ngens(1)
Kb = NumberField(fb,embedding=RealField(_sage_const_400 )("0.4068130813367900"), names=('bb',)); (bb,) = Kb._first_ngens(1)
a=RRp(aa); b=RRp(bb)
D=(sum(Rh(t) for t in sh(b,b))-sum(Rh(t) for t in sh(a**_sage_const_2 ,a))).real()
q=RRp(D/CCp.pi()**_sage_const_2 )
Q=_sage_const_4080 
print("value      =", q.n(_sage_const_60 ))
print("bound Q    =", Q, "  (= 2*lcm(w2(F_alpha), w2(F_beta)) = 2*lcm(120,408);")
print("             the factor 2 is the flattening ambiguity, see flattening_ambiguity.py)")
print("1/(2Q^2)   =", (RRp(_sage_const_1 )/(_sage_const_2 *Q**_sage_const_2 )).n(_sage_const_30 ))
print()
# unique rational with denominator <= Q within err
best=None
for den in range(_sage_const_1 , Q+_sage_const_1 ):
    num=(q*den).round()
    if abs(q-RRp(num)/den) < RRp(_sage_const_1 )/(_sage_const_2 *Q**_sage_const_2 ):
        cand=QQ(num)/QQ(den)
        if best is None or cand.denominator()<best.denominator(): best=cand
print("unique rational with denominator <= Q :", best)
print("equals -4/85 :", best==QQ(-_sage_const_4 )/_sage_const_85 )
print()
print("consistency: does 85 divide Q?", Q % _sage_const_85  == _sage_const_0 , "  Q/85 =", Q//_sage_const_85 )
print("|value - (-4/85)| =", abs(q-QQ(-_sage_const_4 )/_sage_const_85 ).n(_sage_const_20 ))
print()
print("=> Re[Delta R] = -4 pi^2/85   PROVED")
print("=> integral    = +4 pi^2/85   PROVED")

