

# This file was *autogenerated* from the file shapes300.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_12 = Integer(12); _sage_const_3 = Integer(3); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_14 = Integer(14); _sage_const_48 = Integer(48); _sage_const_13 = Integer(13); _sage_const_87 = Integer(87); _sage_const_133 = Integer(133); _sage_const_178 = Integer(178); _sage_const_211 = Integer(211); _sage_const_223 = Integer(223); _sage_const_400 = Integer(400); _sage_const_40 = Integer(40); _sage_const_85 = Integer(85); _sage_const_280 = Integer(280); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0)## High-precision + interval-certified evaluation of the regulator difference.
##
## Re[ sum_j Rhat(z_j(beta)) - sum_j Rhat(z_j(alpha)) ] / pi^2   =?  -4/85
##
## Rhat(z) = Li_2(z) + (1/2) log z log(1-z) - pi^2/6
##
## Two independent checks:
##   (1) 300-digit floating evaluation, compared with -4/85;
##   (2) how many digits of agreement, and what denominator bound that would
##       certify under a rational-reconstruction argument.

prec = _sage_const_1000             # bits
RRp  = RealField(prec)
CCp  = ComplexField(prec)

R = PolynomialRing(QQ, names=('z',)); (z,) = R._first_ngens(1)
falpha = (z**_sage_const_12  - _sage_const_3 *z**_sage_const_11  + _sage_const_4 *z**_sage_const_10  - _sage_const_5 *z**_sage_const_9  + _sage_const_6 *z**_sage_const_8  - _sage_const_7 *z**_sage_const_7 
          + _sage_const_7 *z**_sage_const_6  - _sage_const_7 *z**_sage_const_5  + _sage_const_6 *z**_sage_const_4  - _sage_const_5 *z**_sage_const_3  + _sage_const_4 *z**_sage_const_2  - _sage_const_3 *z + _sage_const_1 )
fbeta  = (z**_sage_const_16  - _sage_const_7 *z**_sage_const_15  + _sage_const_22 *z**_sage_const_14  - _sage_const_48 *z**_sage_const_13  + _sage_const_87 *z**_sage_const_12  - _sage_const_133 *z**_sage_const_11  + _sage_const_178 *z**_sage_const_10 
          - _sage_const_211 *z**_sage_const_9  + _sage_const_223 *z**_sage_const_8  - _sage_const_211 *z**_sage_const_7  + _sage_const_178 *z**_sage_const_6  - _sage_const_133 *z**_sage_const_5  + _sage_const_87 *z**_sage_const_4 
          - _sage_const_48 *z**_sage_const_3  + _sage_const_22 *z**_sage_const_2  - _sage_const_7 *z + _sage_const_1 )

def endpoint_shapes(Mval, Lval):
    X   = Mval**_sage_const_2 
    u   = (Lval + X**_sage_const_3 ) / (X*(Lval + X))
    r   = -(_sage_const_1  + sqrt(_sage_const_1  + _sage_const_4 *u**_sage_const_2 )) / (_sage_const_2 *u)
    tau = _sage_const_1  - r**_sage_const_2 
    return [tau, u, u/X, _sage_const_1 /(_sage_const_1  - u*X)]

def Rhat(zv):
    zc = CCp(zv)
    return dilog(zc) + log(zc)*log(_sage_const_1  - zc)/_sage_const_2  - CCp.pi()**_sage_const_2 /_sage_const_6 

Ka = NumberField(falpha, embedding=RealField(_sage_const_400 )("0.5909894286702564"), names=('aa',)); (aa,) = Ka._first_ngens(1)
Kb = NumberField(fbeta,  embedding=RealField(_sage_const_400 )("0.4068130813367900"), names=('bb',)); (bb,) = Kb._first_ngens(1)
a = RRp(aa); b = RRp(bb)

Sa = endpoint_shapes(a**_sage_const_2 , a)
Sb = endpoint_shapes(b,   b)

print("alpha shapes:", [RRp(t).n(_sage_const_40 ) for t in Sa])
print("beta  shapes:", [RRp(t).n(_sage_const_40 ) for t in Sb])
print()

D  = (sum(Rhat(t) for t in Sb) - sum(Rhat(t) for t in Sa)).real()
pi2 = RRp(CCp.pi()**_sage_const_2 )
q   = RRp(D/pi2)
tgt = RRp(-_sage_const_4 )/_sage_const_85 

print("Re[Delta R]/pi^2 =", q.n(_sage_const_280 ))
print("            -4/85 =", tgt.n(_sage_const_280 ))
err = abs(q - tgt)
print()
print("absolute difference =", err.n(_sage_const_30 ))
digits = -log(err, _sage_const_10 ) if err > _sage_const_0  else Infinity
print("digits of agreement ~", RR(digits))

# rational-reconstruction margin: an approximation to precision eps determines a
# rational of denominator <= Q uniquely when eps < 1/(2Q^2)
print()
print("If the value is known a priori to be rational with denominator <= Q,")
print("the reconstruction is unique once err < 1/(2 Q^2), i.e.")
print("   Q <  sqrt(1/(2*err))  =", RR(sqrt(_sage_const_1 /(_sage_const_2 *err))).n(_sage_const_30 ))
print()
print("continued fraction of the computed value:")
cf = continued_fraction(q)
print("  ", cf[:_sage_const_12 ])
print("  best rational approximations:")
for k in range(_sage_const_1 , _sage_const_8 ):
    print("   ", cf.convergent(k))

