

# This file was *autogenerated* from the file SUBMIT/3.1/scripts/shapes.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12 = Integer(12); _sage_const_3 = Integer(3); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_200 = Integer(200); _sage_const_30 = Integer(30); _sage_const_14 = Integer(14); _sage_const_18 = Integer(18); _sage_const_16 = Integer(16); _sage_const_22 = Integer(22); _sage_const_20 = Integer(20); _sage_const_0p406813081336790 = RealNumber('0.406813081336790'); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_85 = Integer(85); _sage_const_74 = Integer(74); _sage_const_15 = Integer(15)## Exact algebraic computation of the four tetrahedron shapes at both endpoints,
## from the (T,U,V,W) twist-knot deformation chart in the project write-up:
##
##   X = M^2,  u = (L + X^3)/(X(L+X)),  r = -(1+sqrt(1+4u^2))/(2u),  tau = 1-r^2
##   T = tau,  U = u,  V = u/X,  W = 1/(1-uX)
##
## alpha endpoint:  M = a^2, L = a,  a = sqrt(alpha) root of the degree-12 f_alpha
## beta  endpoint:  M = L = b,       b root of A(x,x) near 0.406813

R = PolynomialRing(QQ, names=('z',)); (z,) = R._first_ngens(1)

falpha = (z**_sage_const_12  - _sage_const_3 *z**_sage_const_11  + _sage_const_4 *z**_sage_const_10  - _sage_const_5 *z**_sage_const_9  + _sage_const_6 *z**_sage_const_8  - _sage_const_7 *z**_sage_const_7 
          + _sage_const_7 *z**_sage_const_6  - _sage_const_7 *z**_sage_const_5  + _sage_const_6 *z**_sage_const_4  - _sage_const_5 *z**_sage_const_3  + _sage_const_4 *z**_sage_const_2  - _sage_const_3 *z + _sage_const_1 )

prec = _sage_const_200 
RRp = RealField(prec)

def shapes(Mval, Lval, label):
    X   = Mval**_sage_const_2 
    u   = (Lval + X**_sage_const_3 ) / (X*(Lval + X))
    disc = _sage_const_1  + _sage_const_4 *u**_sage_const_2 
    sq  = sqrt(RRp(disc))
    r   = -(_sage_const_1  + sq) / (_sage_const_2 *u)
    tau = _sage_const_1  - r**_sage_const_2 
    T = tau; U = u; V = u/X; W = _sage_const_1 /(_sage_const_1  - u*X)
    print("=== %s ===" % label)
    print("  X   =", RRp(X))
    print("  u   =", RRp(u))
    print("  r   =", RRp(r))
    print("  T   =", RRp(T))
    print("  U   =", RRp(U))
    print("  V   =", RRp(V))
    print("  W   =", RRp(W))
    return [RRp(T), RRp(U), RRp(V), RRp(W)]

# --- alpha ---
K = NumberField(falpha, embedding=RRp("0.590989428670256"), names=('aa',)); (aa,) = K._first_ngens(1)
a = RRp(aa)
Sa = shapes(a**_sage_const_2 , a, "alpha endpoint  (M=a^2, L=a),  a = %s" % RRp(a).n(_sage_const_30 ))
print("  expected  T=-0.15788  U=6.8158  V=55.872  W=5.9329")

# --- beta ---
R2 = PolynomialRing(QQ, names=('x',)); (x,) = R2._first_ngens(1)
Rb = PolynomialRing(QQ, _sage_const_2 , names=('M', 'L',)); (M, L,) = Rb._first_ngens(2)
A = (L**_sage_const_5 
     + L**_sage_const_4 *( M**_sage_const_14  - M**_sage_const_12  + _sage_const_3 *M**_sage_const_4  + _sage_const_4 *M**_sage_const_2  - _sage_const_2  )
     + L**_sage_const_3 *( -_sage_const_2 *M**_sage_const_18  + _sage_const_5 *M**_sage_const_16  + M**_sage_const_14  - _sage_const_4 *M**_sage_const_12  + _sage_const_6 *M**_sage_const_8  + _sage_const_5 *M**_sage_const_6  + _sage_const_2 *M**_sage_const_4  - _sage_const_4 *M**_sage_const_2  + _sage_const_1  )
     + L**_sage_const_2 *( M**_sage_const_22  - _sage_const_4 *M**_sage_const_20  + _sage_const_2 *M**_sage_const_18  + _sage_const_5 *M**_sage_const_16  + _sage_const_6 *M**_sage_const_14  - _sage_const_4 *M**_sage_const_10  + M**_sage_const_8  + _sage_const_5 *M**_sage_const_6  - _sage_const_2 *M**_sage_const_4  )
     + L  *( -_sage_const_2 *M**_sage_const_22  + _sage_const_4 *M**_sage_const_20  + _sage_const_3 *M**_sage_const_18  - M**_sage_const_10  + M**_sage_const_8  )
     + M**_sage_const_22 )
Abeta = R2(A.subs({M: x, L: x}))
bfac = None
for f, e in Abeta.factor():
    rr = [t for t in f.roots(RR, multiplicities=False) if abs(t - _sage_const_0p406813081336790 ) < _sage_const_1en9 ]
    if rr:
        bfac = f
print()
print("beta minimal polynomial degree:", bfac.degree(), " palindromic:",
      bfac.coefficients(sparse=False) == list(reversed(bfac.coefficients(sparse=False))))
print("  ", bfac)
Kb = NumberField(bfac, embedding=RRp("0.406813081336790"), names=('bb',)); (bb,) = Kb._first_ngens(1)
b = RRp(bb)
print()
Sb = shapes(b, b, "beta endpoint  (M=L=b),  b = %s" % RRp(b).n(_sage_const_30 ))
print("  expected  T=-0.25829  U=4.3430  V=26.242  W=3.5555")

# --- Rogers dilogarithm check ---
print()
print("=== extended Rogers dilogarithm sum ===")
CCp = ComplexField(prec)
def Rhat(zv):
    zc = CCp(zv)
    return dilog(zc) + log(zc)*log(_sage_const_1 -zc)/_sage_const_2  - CCp.pi()**_sage_const_2 /_sage_const_6 

Salpha = sum(Rhat(t) for t in Sa)
Sbeta  = sum(Rhat(t) for t in Sb)
D = (Sbeta - Salpha).real()
print("  Re[sum Rhat(beta) - sum Rhat(alpha)] =", RRp(D))
pi2 = RRp(CCp.pi()**_sage_const_2 )
print("  divided by pi^2 =", RRp(D/pi2))
for num, den in [(-_sage_const_4 ,_sage_const_85 ), (_sage_const_4 ,_sage_const_85 ), (-_sage_const_16 ,_sage_const_85 ), (_sage_const_16 ,_sage_const_85 ), (_sage_const_74 ,_sage_const_15 ), (-_sage_const_74 ,_sage_const_15 )]:
    print("     vs %4d/%-3d = %s" % (num, den, RRp(num)/den))

