

# This file was *autogenerated* from the file w2bound.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12 = Integer(12); _sage_const_3 = Integer(3); _sage_const_11 = Integer(11); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_14 = Integer(14); _sage_const_48 = Integer(48); _sage_const_13 = Integer(13); _sage_const_87 = Integer(87); _sage_const_133 = Integer(133); _sage_const_178 = Integer(178); _sage_const_211 = Integer(211); _sage_const_223 = Integer(223); _sage_const_64 = Integer(64); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_24 = Integer(24); _sage_const_60 = Integer(60); _sage_const_30 = Integer(30); _sage_const_20 = Integer(20)## Avenue (a): explicit denominator bound for the torsion of K_3^ind(F).
##
## Zickert (J. reine angew. Math. 704 (2015) 21-54, Thm 1.1): the extended Bloch
## group is isomorphic to K_3^ind(F).  Merkurjev-Suslin:
##      |K_3^ind(F)_tors| = w_2(F)
## where w_2(F) = prod_p p^{nu_p},  nu_p = max{ nu : Gal(F(mu_{p^nu})/F) is
## killed by 2 }, equivalently the largest p^nu with
## [F(zeta_{p^nu} + zeta_{p^nu}^{-1}) : F] = 1, i.e. the maximal real cyclotomic
## subfield contained in F.
##
## Practical computation: for each prime power p^nu whose maximal real
## cyclotomic field Q(zeta_{p^nu})^+ has degree dividing [F:Q], test whether
## that real cyclotomic field embeds in F.

R = PolynomialRing(QQ, names=('z',)); (z,) = R._first_ngens(1)
falpha = (z**_sage_const_12  - _sage_const_3 *z**_sage_const_11  + _sage_const_4 *z**_sage_const_10  - _sage_const_5 *z**_sage_const_9  + _sage_const_6 *z**_sage_const_8  - _sage_const_7 *z**_sage_const_7 
          + _sage_const_7 *z**_sage_const_6  - _sage_const_7 *z**_sage_const_5  + _sage_const_6 *z**_sage_const_4  - _sage_const_5 *z**_sage_const_3  + _sage_const_4 *z**_sage_const_2  - _sage_const_3 *z + _sage_const_1 )
fbeta  = (z**_sage_const_16  - _sage_const_7 *z**_sage_const_15  + _sage_const_22 *z**_sage_const_14  - _sage_const_48 *z**_sage_const_13  + _sage_const_87 *z**_sage_const_12  - _sage_const_133 *z**_sage_const_11  + _sage_const_178 *z**_sage_const_10 
          - _sage_const_211 *z**_sage_const_9  + _sage_const_223 *z**_sage_const_8  - _sage_const_211 *z**_sage_const_7  + _sage_const_178 *z**_sage_const_6  - _sage_const_133 *z**_sage_const_5  + _sage_const_87 *z**_sage_const_4 
          - _sage_const_48 *z**_sage_const_3  + _sage_const_22 *z**_sage_const_2  - _sage_const_7 *z + _sage_const_1 )

def w2_bound(f, name):
    K = NumberField(f, names=('t',)); (t,) = K._first_ngens(1)
    d = K.degree()
    disc = K.discriminant()
    print("="*_sage_const_64 )
    print(name, ": degree", d)
    print("  discriminant =", disc)
    print("  factored     =", factor(disc))
    print("  signature    =", K.signature())
    # Merkurjev-Suslin: w_2(F) = 2 * prod_p p^{nu_p}, where nu_p is the largest
    # nu with [F(zeta_{p^nu})^+ : F] = 1.  The LEADING FACTOR 2 is easy to drop
    # and was dropped in an earlier version of this script, giving 60 and 204
    # instead of 120 and 408 -- both of which fail the mandatory check 24 | w_2.
    w2 = _sage_const_2 
    details = ["2"]
    # candidate prime powers: the maximal real cyclotomic subfield
    # Q(zeta_m)^+ has degree phi(m)/2 (m>2); need phi(m)/2 | d
    for p in prime_range(_sage_const_2 , _sage_const_200 ):
        nu_max = _sage_const_0 
        for nu in range(_sage_const_1 , _sage_const_8 ):
            m = p**nu
            deg = euler_phi(m)//_sage_const_2  if m > _sage_const_2  else _sage_const_1 
            if deg == _sage_const_0 : deg = _sage_const_1 
            if d % deg != _sage_const_0 :
                break
            # necessary: p ramifies in F unless deg == 1
            if deg > _sage_const_1  and disc % p != _sage_const_0 :
                break
            # test embedding of Q(zeta_m)^+ into K
            if deg == _sage_const_1 :
                nu_max = nu
                continue
            g = (CyclotomicField(m).gen() + CyclotomicField(m).gen()**-_sage_const_1 ).minpoly()
            if len(g.roots(K)) > _sage_const_0 :
                nu_max = nu
            else:
                break
        if nu_max:
            w2 *= p**nu_max
            details.append("%d^%d" % (p, nu_max))
    print("  w_2(F) =", w2, "=", " * ".join(details) if details else "1")
    return w2

wa = w2_bound(falpha, "F_alpha = Q(a)")
wb = w2_bound(fbeta,  "F_beta  = Q(b)")

print()
print("="*_sage_const_64 )
print("Denominator bound for Re[Delta R]/pi^2")
print("="*_sage_const_64 )
Q = lcm(wa, wb)
print("  the difference of two torsion classes has order dividing lcm:")
print("  Q_0 = lcm(%d, %d) = %d" % (wa, wb, Q))
print("  sanity check 24 | w_2 :", wa % _sage_const_24  == _sage_const_0 , wb % _sage_const_24  == _sage_const_0 )
print()
print("  the flattening ambiguity contributes a further factor 2 (all four")
print("  endpoint shapes are real; see flattening_ambiguity.py), so")
Q = _sage_const_2 *Q
print("  Q = 2 * Q_0 =", Q)
print()
# The residual is numerical noise at the working precision, not a quantity:
# the value IS -4/85.  Two independent runs at 1000 bits give 1.11e-301 and
# 1.63e-301.  We use the larger as an upper bound.
err = RealField(_sage_const_60 )("2e-301")
print("  residual bound |value - (-4/85)| <", err, "(at 1000 bits of precision)")
print("  reconstruction is unique when err < 1/(2 Q^2):")
print("     1/(2 Q^2) =", RealField(_sage_const_60 )(_sage_const_1 )/(_sage_const_2 *Q**_sage_const_2 ))
print("     err       =", err)
ok = err < RealField(_sage_const_60 )(_sage_const_1 )/(_sage_const_2 *Q**_sage_const_2 )
print("     CONDITION SATISFIED:", ok)
print()
print("  margin: Q could be as large as", RealField(_sage_const_30 )(sqrt(_sage_const_1 /(_sage_const_2 *err))))
print("  actual Q =", Q, " -> margin factor", RealField(_sage_const_20 )(sqrt(_sage_const_1 /(_sage_const_2 *err))/Q))

