import RamanujanChallenge.Problem27BarnesClosure

namespace RamanujanChallenge.P27

#print axioms problem27_challenge_sequences
#print axioms zudilinBarnesErrorIntegral_tendsto_zero27
#print axioms zudilinBarnesErrorIntegral_zero27
#print axioms zudilinBarnesErrorIntegral_one27
#print axioms zudilinBarnesErrorIntegral_two27
#print axioms zudilinBarnesErrorIntegral_recC27
#print axioms zudilinCombinedError_eq_barnes27
#print axioms zudilinCombinedError_tendsto_zero_direct27
#print axioms problem27_zeta2_add_zeta3_direct

end RamanujanChallenge.P27
