import java.io.BufferedWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.BitSet;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Q4289 exact fixed two-value Apéry-gcd campaign.
 *
 * Only the Java 21 standard library is used.  BigInteger supplies exact
 * arbitrary-precision arithmetic and gcd.  Every reported carrier is formed
 * from exact integer Apéry numbers generated by the three-term recurrence.
 * No probabilistic step enters state selection, gcd formation, saturation,
 * or admissible-window factor detection.  Optional residual factor labels use
 * BigInteger.isProbablePrime and are marked explicitly as such.
 */
public final class Q4289GcdScan {
    private static final BigInteger ZERO = BigInteger.ZERO;
    private static final BigInteger ONE = BigInteger.ONE;
    private static final BigInteger TWO = BigInteger.TWO;
    private static final double LOG2 = Math.log(2.0);

    private record Options(int qmax, int minQ, int trialLimit, Path outDir) {}
    private record State(int q, int t, int zq) {}

    private static final class RecordData {
        final State state;
        final char sign;
        final int n1;
        final int n2;
        final boolean rawWindowNonempty;
        final int plusGeometricCandidates;
        final int minusGeometricCandidates;
        final int m5Candidates;
        final int m8PlusCandidates;
        final int m8MinusCandidates;
        final BigInteger rawGcd;
        final int qValuation;
        final BigInteger lowerCleanG;
        final BigInteger g;
        final String decimal;
        final String sha256;
        final double logG;
        final FactorInfo factorInfo;
        final List<Integer> rawAdmissible;
        final List<Integer> assignedAdmissible;

        RecordData(
                State state,
                char sign,
                int n1,
                int n2,
                boolean rawWindowNonempty,
                int plusGeometricCandidates,
                int minusGeometricCandidates,
                int m5Candidates,
                int m8PlusCandidates,
                int m8MinusCandidates,
                BigInteger rawGcd,
                int qValuation,
                BigInteger lowerCleanG,
                BigInteger g,
                FactorInfo factorInfo,
                List<Integer> rawAdmissible,
                List<Integer> assignedAdmissible
        ) throws NoSuchAlgorithmException {
            this.state = state;
            this.sign = sign;
            this.n1 = n1;
            this.n2 = n2;
            this.rawWindowNonempty = rawWindowNonempty;
            this.plusGeometricCandidates = plusGeometricCandidates;
            this.minusGeometricCandidates = minusGeometricCandidates;
            this.m5Candidates = m5Candidates;
            this.m8PlusCandidates = m8PlusCandidates;
            this.m8MinusCandidates = m8MinusCandidates;
            this.rawGcd = rawGcd;
            this.qValuation = qValuation;
            this.lowerCleanG = lowerCleanG;
            this.g = g;
            this.decimal = g.toString();
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            this.sha256 = HexFormat.of().formatHex(md.digest(decimal.getBytes(StandardCharsets.UTF_8)));
            this.logG = logBigInteger(g);
            this.factorInfo = factorInfo;
            this.rawAdmissible = List.copyOf(rawAdmissible);
            this.assignedAdmissible = List.copyOf(assignedAdmissible);
        }
    }

    private static final class FactorInfo {
        final TreeMap<BigInteger, Integer> knownFactors;
        final BigInteger unresolved;
        final String status;

        FactorInfo(TreeMap<BigInteger, Integer> knownFactors, BigInteger unresolved, String status) {
            this.knownFactors = knownFactors;
            this.unresolved = unresolved;
            this.status = status;
        }

        int knownOmega() {
            return knownFactors.size();
        }

        boolean complete() {
            return unresolved.equals(ONE) && status.equals("complete");
        }

        BigInteger largestKnownFactor() {
            return knownFactors.isEmpty() ? ONE : knownFactors.lastKey();
        }

        String factorString() {
            StringJoiner joiner = new StringJoiner("*");
            for (Map.Entry<BigInteger, Integer> e : knownFactors.entrySet()) {
                joiner.add(e.getKey() + (e.getValue() == 1 ? "" : "^" + e.getValue()));
            }
            if (!unresolved.equals(ONE)) {
                joiner.add("[residual " + unresolved.bitLength() + " bits; " + status + "]");
            }
            return joiner.length() == 0 ? "1" : joiner.toString();
        }
    }

    private static Options parseOptions(String[] args) {
        int qmax = 5000;
        int minQ = 17;
        int trialLimit = 10000;
        Path outDir = Path.of("q4289_results");
        for (int i = 0; i < args.length; ++i) {
            switch (args[i]) {
                case "--qmax" -> qmax = Integer.parseInt(requireValue(args, ++i, "--qmax"));
                case "--min-q" -> minQ = Integer.parseInt(requireValue(args, ++i, "--min-q"));
                case "--trial-limit" -> trialLimit = Integer.parseInt(requireValue(args, ++i, "--trial-limit"));
                case "--out-dir" -> outDir = Path.of(requireValue(args, ++i, "--out-dir"));
                default -> throw new IllegalArgumentException("unknown option: " + args[i]);
            }
        }
        if (qmax < 1000) throw new IllegalArgumentException("qmax must be at least 1000");
        if (minQ < 7 || minQ > qmax) throw new IllegalArgumentException("bad minQ");
        if (trialLimit < qmax) trialLimit = qmax;
        return new Options(qmax, minQ, trialLimit, outDir);
    }

    private static String requireValue(String[] args, int i, String option) {
        if (i >= args.length) throw new IllegalArgumentException("missing value for " + option);
        return args[i];
    }

    private static List<Integer> sievePrimes(int limit, BitSet primeBits) {
        primeBits.set(2, limit + 1);
        for (int p = 2; (long) p * p <= limit; ++p) {
            if (!primeBits.get(p)) continue;
            for (int k = p * p; k <= limit; k += p) primeBits.clear(k);
        }
        List<Integer> primes = new ArrayList<>();
        for (int p = primeBits.nextSetBit(2); p >= 0; p = primeBits.nextSetBit(p + 1)) primes.add(p);
        return primes;
    }

    private static int[] aperyZeroSet(int p) {
        if (p < 3) return new int[0];
        int half = (p - 1) / 2;
        long[] inv = new long[half + 1];
        if (half >= 1) inv[1] = 1;
        for (int a = 2; a <= half; ++a) {
            inv[a] = (p - ((long) (p / a) * inv[p % a]) % p) % p;
        }
        List<Integer> left = new ArrayList<>();
        long previous = 1 % p;
        long current = 5 % p;
        if (half >= 1 && current == 0) left.add(1);
        for (int n = 1; n < half; ++n) {
            long nn = n;
            long n2 = nn * nn % p;
            long n3 = n2 * nn % p;
            long middle = ((2 * nn + 1) % p) * ((17 * n2 + 17 * nn + 5) % p) % p;
            long rhs = (middle * current - n3 * previous) % p;
            if (rhs < 0) rhs += p;
            long u = inv[n + 1];
            long next = rhs * u % p * u % p * u % p;
            previous = current;
            current = next;
            if (current == 0) left.add(n + 1);
        }
        TreeSet<Integer> full = new TreeSet<>(left);
        for (int r : left) full.add(p - 1 - r);
        int[] result = full.stream().mapToInt(Integer::intValue).toArray();
        for (int r : result) {
            if (r == 0) throw new AssertionError("b_0 zero at p=" + p);
        }
        for (int i = 1; i < result.length; ++i) {
            if (result[i] == result[i - 1] + 1) {
                throw new AssertionError("consecutive zeros at p=" + p);
            }
        }
        return result;
    }

    private static Map<Integer, BigInteger> generateExactApery(boolean[] needed, int maxIndex) {
        Map<Integer, BigInteger> values = new HashMap<>();
        BigInteger previous = ONE;
        BigInteger current = BigInteger.valueOf(5);
        if (needed[0]) values.put(0, previous);
        if (maxIndex >= 1 && needed[1]) values.put(1, current);
        Instant start = Instant.now();
        for (int n = 1; n < maxIndex; ++n) {
            long nn = n;
            long n2 = Math.multiplyExact(nn, nn);
            long n3 = Math.multiplyExact(n2, nn);
            long poly2 = Math.addExact(Math.addExact(Math.multiplyExact(17L, n2), Math.multiplyExact(17L, nn)), 5L);
            long poly = Math.multiplyExact(Math.addExact(Math.multiplyExact(2L, nn), 1L), poly2);
            long np1 = nn + 1;
            long denominator = Math.multiplyExact(Math.multiplyExact(np1, np1), np1);
            BigInteger numerator = current.multiply(BigInteger.valueOf(poly))
                    .subtract(previous.multiply(BigInteger.valueOf(n3)));
            BigInteger[] qr = numerator.divideAndRemainder(BigInteger.valueOf(denominator));
            if (qr[1].signum() != 0) throw new AssertionError("nonexact recurrence division at n=" + n);
            BigInteger next = qr[0];
            previous = current;
            current = next;
            int index = n + 1;
            if (needed[index]) values.put(index, current);
            if (index % 5000 == 0 || index == maxIndex) {
                System.err.printf(Locale.ROOT,
                        "APERY_PROGRESS index=%d/%d bits=%d elapsed=%.3fs%n",
                        index, maxIndex, current.bitLength(),
                        Duration.between(start, Instant.now()).toMillis() / 1000.0);
            }
        }
        return values;
    }

    private static double logBigInteger(BigInteger n) {
        if (n.signum() <= 0) return Double.NEGATIVE_INFINITY;
        int bits = n.bitLength();
        if (bits <= 53) return Math.log(n.longValue());
        int shift = bits - 53;
        long top = n.shiftRight(shift).longValue();
        return Math.log(top) + shift * LOG2;
    }

    private static int valuation(BigInteger n, int p) {
        BigInteger bp = BigInteger.valueOf(p);
        int v = 0;
        while (n.mod(bp).signum() == 0) {
            n = n.divide(bp);
            ++v;
        }
        return v;
    }

    private static BigInteger removePrimary(BigInteger n, BigInteger p) {
        while (n.mod(p).signum() == 0) n = n.divide(p);
        return n;
    }

    private static BigInteger strip(BigInteger n, int q, Set<Integer> fixedPrimes) {
        BigInteger result = removePrimary(n, BigInteger.valueOf(q));
        for (int p : fixedPrimes) result = removePrimary(result, BigInteger.valueOf(p));
        return result;
    }

    private static boolean isPrime64Exact(BigInteger n) {
        if (n.compareTo(TWO) < 0 || n.bitLength() > 63) return false;
        int[] small = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37};
        for (int p : small) {
            BigInteger bp = BigInteger.valueOf(p);
            if (n.equals(bp)) return true;
            if (n.mod(bp).signum() == 0) return false;
        }
        BigInteger d = n.subtract(ONE);
        int s = d.getLowestSetBit();
        d = d.shiftRight(s);
        long[] bases = {2L, 325L, 9375L, 28178L, 450775L, 9780504L, 1795265022L};
        BigInteger nm1 = n.subtract(ONE);
        for (long base : bases) {
            BigInteger a = BigInteger.valueOf(base).mod(n);
            if (a.signum() == 0) continue;
            BigInteger x = a.modPow(d, n);
            if (x.equals(ONE) || x.equals(nm1)) continue;
            boolean witness = true;
            for (int r = 1; r < s; ++r) {
                x = x.multiply(x).mod(n);
                if (x.equals(nm1)) {
                    witness = false;
                    break;
                }
            }
            if (witness) return false;
        }
        return true;
    }

    private static BigInteger pollardRho64(BigInteger n) {
        if (n.mod(TWO).signum() == 0) return TWO;
        for (long cValue = 1; ; ++cValue) {
            BigInteger c = BigInteger.valueOf(cValue);
            BigInteger x = TWO;
            BigInteger y = TWO;
            BigInteger d = ONE;
            int guard = 0;
            while (d.equals(ONE) && guard++ < 2_000_000) {
                x = x.multiply(x).add(c).mod(n);
                y = y.multiply(y).add(c).mod(n);
                y = y.multiply(y).add(c).mod(n);
                d = x.subtract(y).abs().gcd(n);
            }
            if (!d.equals(ONE) && !d.equals(n)) return d;
        }
    }

    private static void factor64Exact(BigInteger n, TreeMap<BigInteger, Integer> factors) {
        if (n.equals(ONE)) return;
        if (n.bitLength() > 63) throw new IllegalArgumentException("factor64Exact input too large: " + n.bitLength());
        if (isPrime64Exact(n)) {
            factors.merge(n, 1, Integer::sum);
            return;
        }
        BigInteger d = pollardRho64(n);
        factor64Exact(d, factors);
        factor64Exact(n.divide(d), factors);
    }

    private static Set<Integer> distinctPrimeFactors64(BigInteger n) {
        TreeMap<BigInteger, Integer> f = new TreeMap<>();
        factor64Exact(n, f);
        Set<Integer> result = new TreeSet<>();
        for (BigInteger p : f.keySet()) result.add(p.intValueExact());
        return result;
    }

    private static FactorInfo factorForReport(BigInteger n, List<Integer> trialPrimes) {
        TreeMap<BigInteger, Integer> factors = new TreeMap<>();
        BigInteger residual = n;
        for (int p : trialPrimes) {
            BigInteger bp = BigInteger.valueOf(p);
            if (bp.multiply(bp).compareTo(residual) > 0) break;
            int e = 0;
            while (residual.mod(bp).signum() == 0) {
                residual = residual.divide(bp);
                ++e;
            }
            if (e > 0) factors.put(bp, e);
        }
        if (residual.equals(ONE)) return new FactorInfo(factors, ONE, "complete");
        if (residual.bitLength() <= 63) {
            factor64Exact(residual, factors);
            return new FactorInfo(factors, ONE, "complete");
        }
        if (residual.isProbablePrime(100)) {
            return new FactorInfo(factors, residual, "probable-prime-residual");
        }
        return new FactorInfo(factors, residual, "unfactored-composite");
    }

    private static boolean inPlusWindow(int q, int t, int p) {
        long n = 6L * q + t;
        long m = 12L * q + t;
        return 7L * p > n && 13L * p <= m;
    }

    private static boolean inMinusWindow(int q, int t, int p) {
        long n = 6L * q + t;
        int s = q - 1 - t;
        return 7L * p > n && p <= s;
    }

    private static boolean isZero(BitSet[] zeroBits, int p, int r) {
        return p >= 0 && p < zeroBits.length && r >= 0 && r < p && zeroBits[p] != null && zeroBits[p].get(r);
    }

    private static int minusType(int q, int t, int p) {
        int d = q - p;
        if (13L * d + 2L * t + 1 <= q) return 5;
        return q > 8L * d ? 81 : 82; // M8+ / M8-
    }

    private static List<Integer> admissibleFactors(BigInteger g, State state, char sign, List<Integer> primes) {
        List<Integer> result = new ArrayList<>();
        for (int p : primes) {
            if (p < 17 || p >= state.q()) continue;
            boolean window = sign == '+' ? inPlusWindow(state.q(), state.t(), p) : inMinusWindow(state.q(), state.t(), p);
            if (window && g.mod(BigInteger.valueOf(p)).signum() == 0) result.add(p);
        }
        return result;
    }

    private static String joinInts(List<Integer> values) {
        StringJoiner j = new StringJoiner(";");
        for (int x : values) j.add(Integer.toString(x));
        return j.toString();
    }

    private static double quantile(List<Double> values, double p) {
        if (values.isEmpty()) return Double.NaN;
        List<Double> x = new ArrayList<>(values);
        Collections.sort(x);
        double pos = p * (x.size() - 1);
        int lo = (int) Math.floor(pos);
        int hi = (int) Math.ceil(pos);
        if (lo == hi) return x.get(lo);
        double w = pos - lo;
        return x.get(lo) * (1.0 - w) + x.get(hi) * w;
    }

    private static double[] regression(List<double[]> points) {
        if (points.size() < 2) return new double[]{Double.NaN, Double.NaN, Double.NaN};
        double sx = 0, sy = 0;
        for (double[] p : points) { sx += p[0]; sy += p[1]; }
        double mx = sx / points.size(), my = sy / points.size();
        double sxx = 0, sxy = 0, syy = 0;
        for (double[] p : points) {
            double dx = p[0] - mx, dy = p[1] - my;
            sxx += dx * dx; sxy += dx * dy; syy += dy * dy;
        }
        double slope = sxx == 0 ? Double.NaN : sxy / sxx;
        double intercept = my - slope * mx;
        double r2 = (sxx == 0 || syy == 0) ? Double.NaN : (sxy * sxy) / (sxx * syy);
        return new double[]{slope, intercept, r2};
    }

    private static String summarize(String label, List<RecordData> records, int fitMinQ) {
        List<Double> logs = new ArrayList<>();
        List<Double> positiveLogs = new ArrayList<>();
        List<Double> ratiosQ = new ArrayList<>();
        List<Double> ratiosLogQ = new ArrayList<>();
        List<double[]> linearPoints = new ArrayList<>();
        List<double[]> powerPoints = new ArrayList<>();
        int ones = 0, complete = 0, prp = 0, unresolved = 0;
        int maxKnownOmega = 0;
        RecordData max = null;
        for (RecordData r : records) {
            logs.add(r.logG);
            if (r.g.equals(ONE)) ++ones;
            else {
                positiveLogs.add(r.logG);
                ratiosQ.add(r.logG / r.state.q());
                ratiosLogQ.add(r.logG / Math.log(r.state.q()));
                if (r.state.q() >= fitMinQ) {
                    linearPoints.add(new double[]{r.state.q(), r.logG});
                    powerPoints.add(new double[]{Math.log(r.state.q()), Math.log(r.logG)});
                }
            }
            if (r.factorInfo.complete()) ++complete;
            else if (r.factorInfo.status.equals("probable-prime-residual")) ++prp;
            else ++unresolved;
            maxKnownOmega = Math.max(maxKnownOmega, r.factorInfo.knownOmega());
            if (max == null || r.g.compareTo(max.g) > 0) max = r;
        }
        double[] lin = regression(linearPoints);
        double[] pow = regression(powerPoints);
        StringBuilder s = new StringBuilder();
        s.append("### ").append(label).append("\n\n");
        s.append("```text\n");
        s.append("records                         = ").append(records.size()).append('\n');
        s.append("G=1                             = ").append(ones).append('\n');
        s.append("positive G                      = ").append(records.size() - ones).append('\n');
        s.append(String.format(Locale.ROOT, "median log G                    = %.9f%n", quantile(logs, 0.5)));
        s.append(String.format(Locale.ROOT, "90%% / 99%% log G                = %.9f / %.9f%n", quantile(logs, 0.9), quantile(logs, 0.99)));
        s.append(String.format(Locale.ROOT, "median positive log G           = %.9f%n", quantile(positiveLogs, 0.5)));
        s.append(String.format(Locale.ROOT, "median log G / q                = %.9g%n", quantile(ratiosQ, 0.5)));
        s.append(String.format(Locale.ROOT, "median log G / log q            = %.9g%n", quantile(ratiosLogQ, 0.5)));
        if (max != null) {
            s.append("maximum at (q,t,sign)           = (").append(max.state.q()).append(',').append(max.state.t()).append(',').append(max.sign).append(")\n");
            s.append("maximum G decimal digits        = ").append(max.decimal.length()).append('\n');
            s.append(String.format(Locale.ROOT, "maximum log G                   = %.12f%n", max.logG));
            s.append("maximum G SHA-256               = ").append(max.sha256).append('\n');
        }
        s.append(String.format(Locale.ROOT, "fit range q >=                  = %d%n", fitMinQ));
        s.append(String.format(Locale.ROOT, "OLS log G = a*q+b: a,R^2        = %.9g, %.6f%n", lin[0], lin[2]));
        s.append(String.format(Locale.ROOT, "OLS log(log G)=rho*log q+c       = %.9g, %.6f%n", pow[0], pow[2]));
        s.append("complete factorizations          = ").append(complete).append('\n');
        s.append("probable-prime residuals          = ").append(prp).append('\n');
        s.append("unfactored composite residuals    = ").append(unresolved).append('\n');
        s.append("maximum known distinct factors    = ").append(maxKnownOmega).append('\n');
        s.append("```\n\n");
        return s.toString();
    }

    private static void writeTsv(Path path, List<RecordData> records) throws IOException {
        try (BufferedWriter out = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            out.write("q\tt\tzq\tsign\tn1\tn2\twindow_nonempty\tplus_geom\tminus_geom\tm5_geom\tm8plus_geom\tm8minus_geom\traw_g_digits\tq_valuation\tlower_clean_digits\tG_digits\tlogG\tG_sha256\tfactor_status\tknown_omega\tfactors\traw_admissible\tassigned_admissible\tG_decimal\n");
            for (RecordData r : records) {
                out.write(Integer.toString(r.state.q())); out.write('\t');
                out.write(Integer.toString(r.state.t())); out.write('\t');
                out.write(Integer.toString(r.state.zq())); out.write('\t');
                out.write(Character.toString(r.sign)); out.write('\t');
                out.write(Integer.toString(r.n1)); out.write('\t');
                out.write(Integer.toString(r.n2)); out.write('\t');
                out.write(Boolean.toString(r.rawWindowNonempty)); out.write('\t');
                out.write(Integer.toString(r.plusGeometricCandidates)); out.write('\t');
                out.write(Integer.toString(r.minusGeometricCandidates)); out.write('\t');
                out.write(Integer.toString(r.m5Candidates)); out.write('\t');
                out.write(Integer.toString(r.m8PlusCandidates)); out.write('\t');
                out.write(Integer.toString(r.m8MinusCandidates)); out.write('\t');
                out.write(Integer.toString(r.rawGcd.toString().length())); out.write('\t');
                out.write(Integer.toString(r.qValuation)); out.write('\t');
                out.write(Integer.toString(r.lowerCleanG.toString().length())); out.write('\t');
                out.write(Integer.toString(r.decimal.length())); out.write('\t');
                out.write(String.format(Locale.ROOT, "%.17g", r.logG)); out.write('\t');
                out.write(r.sha256); out.write('\t');
                out.write(r.factorInfo.status); out.write('\t');
                out.write(Integer.toString(r.factorInfo.knownOmega())); out.write('\t');
                out.write(r.factorInfo.factorString()); out.write('\t');
                out.write(joinInts(r.rawAdmissible)); out.write('\t');
                out.write(joinInts(r.assignedAdmissible)); out.write('\t');
                out.write(r.decimal);
                out.write('\n');
            }
        }
    }

    private static String setString(Set<Integer> set) {
        return set.toString();
    }

    public static void main(String[] args) throws Exception {
        Locale.setDefault(Locale.ROOT);
        Options options = parseOptions(args);
        Files.createDirectories(options.outDir());
        Instant totalStart = Instant.now();
        System.err.println("Q4289_START qmax=" + options.qmax() + " minQ=" + options.minQ() + " trialLimit=" + options.trialLimit());

        BitSet primeBits = new BitSet(options.trialLimit() + 1);
        List<Integer> trialPrimes = sievePrimes(options.trialLimit(), primeBits);
        List<Integer> qPrimes = new ArrayList<>();
        for (int p : trialPrimes) if (p <= options.qmax()) qPrimes.add(p);

        BitSet[] zeroBits = new BitSet[options.qmax() + 1];
        List<State> allStates = new ArrayList<>();
        long zeroRecords = 0;
        for (int q : qPrimes) {
            if (q < 5) continue;
            int[] zeros = aperyZeroSet(q);
            BitSet bits = new BitSet(q);
            for (int t : zeros) bits.set(t);
            zeroBits[q] = bits;
            zeroRecords += zeros.length;
            if (q >= 7) for (int t : zeros) allStates.add(new State(q, t, zeros.length));
        }
        long states1000 = allStates.stream().filter(s -> s.q() <= 1000).count();
        long states17to5000 = allStates.stream().filter(s -> s.q() >= 17 && s.q() <= 5000).count();
        if (states1000 != 163) throw new AssertionError("q<=1000 checkpoint: " + states1000);
        if (options.qmax() >= 5000 && states17to5000 != 605) throw new AssertionError("17<=q<=5000 checkpoint: " + states17to5000);
        List<State> states = allStates.stream().filter(s -> s.q() >= options.minQ()).toList();
        System.err.println("ZERO_DONE zeroRecords=" + zeroRecords + " states=" + states.size());

        int maxIndex = 13;
        for (State s : states) maxIndex = Math.max(maxIndex, 12 * s.q() + s.t());
        boolean[] needed = new boolean[maxIndex + 1];
        for (int index : new int[]{0, 1, 6, 12, 13}) needed[index] = true;
        for (State s : states) {
            needed[6 * s.q() + s.t()] = true;
            needed[12 * s.q() + s.t()] = true;
            needed[s.q() - 1 - s.t()] = true;
        }
        Map<Integer, BigInteger> exact = generateExactApery(needed, maxIndex);
        BigInteger b1 = exact.get(1), b6 = exact.get(6), b12 = exact.get(12), b13 = exact.get(13);
        if (b1 == null || b6 == null || b12 == null || b13 == null) throw new AssertionError("missing coefficients");

        Set<Integer> smallFixed = new TreeSet<>();
        for (int p : qPrimes) if (p < 17) smallFixed.add(p);
        Set<Integer> f1 = distinctPrimeFactors64(b1);
        Set<Integer> f6 = distinctPrimeFactors64(b6);
        Set<Integer> f12 = distinctPrimeFactors64(b12);
        Set<Integer> f13 = distinctPrimeFactors64(b13);
        Set<Integer> ePlusLower = new TreeSet<>(smallFixed);
        ePlusLower.addAll(f6); ePlusLower.addAll(f13);
        Set<Integer> ePlusFull = new TreeSet<>(ePlusLower);
        ePlusFull.addAll(f12);
        Set<Integer> eMinus = new TreeSet<>(smallFixed);
        eMinus.addAll(f6); eMinus.addAll(f1);
        System.err.println("COEFFICIENTS b1=" + b1 + " b6=" + b6 + " b12=" + b12 + " b13=" + b13);
        System.err.println("E_PLUS_LOWER=" + ePlusLower + " E_PLUS_FULL=" + ePlusFull + " E_MINUS=" + eMinus);

        List<RecordData> plusRecords = new ArrayList<>();
        List<RecordData> minusRecords = new ArrayList<>();
        int lowerVsFullDifferences = 0;
        int maxAssigned = 0;
        List<String> collisionWitnesses = new ArrayList<>();
        long rawPlusLeaves = 0, rawMinusLeaves = 0, assignedPlusLeaves = 0;

        int stateIndex = 0;
        for (State s : states) {
            int q = s.q(), t = s.t();
            int n = 6 * q + t;
            int mPlus = 12 * q + t;
            int mMinus = q - 1 - t;
            BigInteger bn = exact.get(n);
            BigInteger bp = exact.get(mPlus);
            BigInteger bm = exact.get(mMinus);
            if (bn == null || bp == null || bm == null) throw new AssertionError("missing exact index");
            BigInteger rawPlusG = bn.gcd(bp);
            BigInteger rawMinusG = bn.gcd(bm);
            if (rawPlusG.mod(BigInteger.valueOf(q)).signum() != 0) throw new AssertionError("q missing plus at " + s);
            if (rawMinusG.mod(BigInteger.valueOf(q)).signum() != 0) throw new AssertionError("q missing minus at " + s);

            BigInteger plusLower = strip(rawPlusG, q, ePlusLower);
            BigInteger plusG = strip(rawPlusG, q, ePlusFull);
            BigInteger minusG = strip(rawMinusG, q, eMinus);
            if (!plusLower.equals(plusG)) ++lowerVsFullDifferences;

            int plusGeom = 0, minusGeom = 0, m5 = 0, m8p = 0, m8m = 0;
            for (int p : qPrimes) {
                if (p < 17 || p >= q) continue;
                if (inPlusWindow(q, t, p)) ++plusGeom;
                if (inMinusWindow(q, t, p)) {
                    ++minusGeom;
                    int type = minusType(q, t, p);
                    if (type == 5) ++m5;
                    else if (type == 81) ++m8p;
                    else ++m8m;
                }
            }

            List<Integer> rawPlus = admissibleFactors(plusG, s, '+', qPrimes);
            List<Integer> rawMinus = admissibleFactors(minusG, s, '-', qPrimes);
            Set<Integer> minusSet = new HashSet<>(rawMinus);
            List<Integer> assignedPlus = new ArrayList<>();
            for (int p : rawPlus) if (!minusSet.contains(p)) assignedPlus.add(p);
            rawPlusLeaves += rawPlus.size();
            rawMinusLeaves += rawMinus.size();
            assignedPlusLeaves += assignedPlus.size();

            // Cross-check every gcd-detected leaf against the exact modular zero ledger.
            for (int p : rawPlus) {
                int d = q - p;
                int r6 = t + 6 * d;
                int rp = t + 13 * d - q;
                if (!isZero(zeroBits, p, r6) || !isZero(zeroBits, p, rp)) {
                    throw new AssertionError("plus gcd/zero mismatch q=" + q + " t=" + t + " p=" + p);
                }
            }
            for (int p : rawMinus) {
                int d = q - p;
                int r6 = t + 6 * d;
                int rm = d - t - 1;
                if (!isZero(zeroBits, p, r6) || !isZero(zeroBits, p, rm)) {
                    throw new AssertionError("minus gcd/zero mismatch q=" + q + " t=" + t + " p=" + p);
                }
            }

            FactorInfo plusFactor = factorForReport(plusG, trialPrimes);
            FactorInfo minusFactor = factorForReport(minusG, trialPrimes);
            RecordData plusRecord = new RecordData(s, '+', n, mPlus, true,
                    plusGeom, minusGeom, m5, m8p, m8m,
                    rawPlusG, valuation(rawPlusG, q), plusLower, plusG,
                    plusFactor, rawPlus, assignedPlus);
            RecordData minusRecord = new RecordData(s, '-', n, mMinus, minusGeom > 0,
                    plusGeom, minusGeom, m5, m8p, m8m,
                    rawMinusG, valuation(rawMinusG, q), minusG, minusG,
                    minusFactor, rawMinus, rawMinus);
            plusRecords.add(plusRecord);
            minusRecords.add(minusRecord);
            maxAssigned = Math.max(maxAssigned, Math.max(assignedPlus.size(), rawMinus.size()));
            if (assignedPlus.size() >= 2) collisionWitnesses.add("plus q=" + q + " t=" + t + " p=" + assignedPlus);
            if (rawMinus.size() >= 2) collisionWitnesses.add("minus q=" + q + " t=" + t + " p=" + rawMinus);

            if (++stateIndex % 100 == 0 || stateIndex == states.size()) {
                System.err.printf("GCD_PROGRESS states=%d/%d%n", stateIndex, states.size());
            }
        }

        List<RecordData> minusWindow = minusRecords.stream().filter(r -> r.rawWindowNonempty).toList();
        List<RecordData> minusM5Capable = minusRecords.stream().filter(r -> r.m5Candidates > 0).toList();
        List<RecordData> allRecords = new ArrayList<>(plusRecords);
        allRecords.addAll(minusRecords);
        allRecords.sort(Comparator.comparingInt((RecordData r) -> r.state.q())
                .thenComparingInt(r -> r.state.t()).thenComparingInt(r -> r.sign));

        writeTsv(options.outDir().resolve("gcd_records.tsv"), allRecords);

        int fitMin = Math.max(options.minQ(), options.qmax() / 4);
        StringBuilder report = new StringBuilder();
        report.append("# Q4289 exact fixed two-value Apéry gcd campaign\n\n");
        report.append("## Execution ledger\n\n```text\n");
        report.append("qmax                            = ").append(options.qmax()).append('\n');
        report.append("min selected q                  = ").append(options.minQ()).append('\n');
        report.append("primes through qmax             = ").append(qPrimes.size()).append('\n');
        report.append("selected states                 = ").append(states.size()).append('\n');
        report.append("selected states q<=1000         = ").append(states1000).append(" (checkpoint 163 includes q=11)\n");
        if (options.qmax() >= 5000) report.append("selected states 17<=q<=5000     = ").append(states17to5000).append(" (checkpoint 605)\n");
        report.append("largest exact Apéry index       = ").append(maxIndex).append('\n');
        report.append("trial-factor prime limit        = ").append(options.trialLimit()).append('\n');
        report.append(String.format(Locale.ROOT, "total wall seconds                = %.3f%n",
                Duration.between(totalStart, Instant.now()).toMillis() / 1000.0));
        report.append("```\n\n");

        report.append("## Fixed saturation audit\n\n```text\n");
        report.append("b_1  = ").append(b1).append('\n');
        report.append("b_6  = ").append(b6).append('\n');
        report.append("b_12 = ").append(b12).append('\n');
        report.append("b_13 = ").append(b13).append('\n');
        report.append("prime divisors b_1              = ").append(f1).append('\n');
        report.append("prime divisors b_6              = ").append(f6).append('\n');
        report.append("prime divisors b_12             = ").append(f12).append('\n');
        report.append("prime divisors b_13             = ").append(f13).append('\n');
        report.append("E_plus lower coefficients       = ").append(setString(ePlusLower)).append('\n');
        report.append("E_plus full fixed ledger        = ").append(setString(ePlusFull)).append('\n');
        report.append("E_minus fixed ledger            = ").append(setString(eMinus)).append('\n');
        report.append("plus rows changed by b_12 strip = ").append(lowerVsFullDifferences).append('\n');
        report.append("```\n\n");

        report.append(summarize("Plus: all actual selected states", plusRecords, fitMin));
        report.append(summarize("Minus: all actual selected states", minusRecords, fitMin));
        report.append(summarize("Minus: raw-window nonempty states", minusWindow, fitMin));
        report.append(summarize("Minus: geometrically M5-capable states", minusM5Capable, fitMin));

        report.append("## Exact admissible-window radical audit\n\n```text\n");
        report.append("raw plus leaves                  = ").append(rawPlusLeaves).append('\n');
        report.append("raw minus leaves                 = ").append(rawMinusLeaves).append('\n');
        report.append("minus-first assigned plus leaves = ").append(assignedPlusLeaves).append('\n');
        report.append("maximum assigned leaves/state    = ").append(maxAssigned).append('\n');
        report.append("Q6-SLUNI collision witnesses     = ").append(collisionWitnesses.size()).append('\n');
        report.append("```\n\n");
        if (!collisionWitnesses.isEmpty()) {
            report.append("### LOUD COUNTEREXAMPLE WITNESSES\n\n");
            for (String w : collisionWitnesses) report.append("- `").append(w).append("`\n");
            report.append('\n');
        }

        report.append("## Dyadic size profile\n\n");
        report.append("| sign/sector | q-range | records | G=1 | median log G | max log G |\n");
        report.append("|:---|:---|---:|---:|---:|---:|\n");
        List<Map.Entry<String, List<RecordData>>> sectors = List.of(
                Map.entry("plus", plusRecords),
                Map.entry("minus-window", minusWindow),
                Map.entry("minus-M5-capable", minusM5Capable));
        for (Map.Entry<String, List<RecordData>> sector : sectors) {
            for (int lo = 16; lo <= options.qmax(); lo *= 2) {
                int hi = Math.min(options.qmax() + 1, lo * 2);
                int flo = lo, fhi = hi;
                List<RecordData> bucket = sector.getValue().stream().filter(r -> r.state.q() >= flo && r.state.q() < fhi).toList();
                if (bucket.isEmpty()) continue;
                List<Double> values = bucket.stream().map(r -> r.logG).toList();
                long ones = bucket.stream().filter(r -> r.g.equals(ONE)).count();
                double maxLog = bucket.stream().mapToDouble(r -> r.logG).max().orElse(Double.NaN);
                report.append('|').append(sector.getKey()).append("|[").append(lo).append(',').append(hi).append(")|")
                        .append(bucket.size()).append('|').append(ones).append('|')
                        .append(String.format(Locale.ROOT, "%.9f", quantile(values, 0.5))).append('|')
                        .append(String.format(Locale.ROOT, "%.9f", maxLog)).append("|\n");
                if (lo > options.qmax() / 2) break;
            }
        }
        report.append('\n');

        report.append("## Interpretation guardrail\n\n");
        report.append("All gcds and saturations above are exact.  Admissible-window prime factors are exact because every possible lower prime is below q<=qmax and is tested directly.  A factor row marked `probable-prime-residual` or `unfactored-composite` is not advertised as a complete total factorization; the full exact decimal G remains in `gcd_records.tsv`.  Regression slopes are finite-range diagnostics, not theorems.\n\n");
        report.append("The state-level gcd has no intrinsic M5/M8 label: that label belongs to a hypothetical minus lower edge.  The `M5-capable` table therefore means that the selected state has at least one prime in the raw M5 geometric subwindow.  The actual M5 ledger is obtained from the exact admissible factors and is empty unless such a factor is listed.\n");

        Files.writeString(options.outDir().resolve("report.md"), report.toString(), StandardCharsets.UTF_8);
        String summaryJson = String.format(Locale.ROOT,
                "{\n  \"qmax\": %d,\n  \"selected_states\": %d,\n  \"raw_plus_leaves\": %d,\n  \"raw_minus_leaves\": %d,\n  \"assigned_plus_leaves\": %d,\n  \"max_assigned_per_state\": %d,\n  \"collision_witnesses\": %d,\n  \"total_seconds\": %.6f\n}\n",
                options.qmax(), states.size(), rawPlusLeaves, rawMinusLeaves, assignedPlusLeaves,
                maxAssigned, collisionWitnesses.size(), Duration.between(totalStart, Instant.now()).toMillis() / 1000.0);
        Files.writeString(options.outDir().resolve("summary.json"), summaryJson, StandardCharsets.UTF_8);

        System.out.println("Q4289_RESULT_BEGIN");
        System.out.print(report);
        System.out.println("Q4289_RESULT_END");
        System.err.printf(Locale.ROOT, "Q4289_DONE total=%.3fs records=%d%n",
                Duration.between(totalStart, Instant.now()).toMillis() / 1000.0, allRecords.size());
    }
}
