#!/usr/bin/env sage
"""
Core computation: compare the P2.7 error to the Zudilin error.

The key hypothesis:
  e_n^{P27} / (64^{-n} · e_n^Z) → polynomial gauge in n

If true, then c₀(e)=0 for P2.7 follows from c₀(e)=0 for Zudilin.

Step 1: Compute rec_a (the AESZ #209 inner recurrence) via guess()
Step 2: Compute p̃_n via rec_a with ICs p̃_0=0, p̃_1=20, p̃_2=7425/16
Step 3: Compute errors e_n^Z = p̃_n - L·a_n and e_n^{P27} = p_n - L·q_n
Step 4: Study the ratio e_n^{P27} / (64^{-n} · e_n^Z)
"""


# This file was *autogenerated* from the file scratchpad/error_ratio.sage
from sage.all_cmdline import *   # import sage library

_sage_const_200 = Integer(200); _sage_const_50 = Integer(50); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_40 = Integer(40); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20); _sage_const_7425 = Integer(7425); _sage_const_16 = Integer(16); _sage_const_1024 = Integer(1024); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_15 = Integer(15); _sage_const_25 = Integer(25); _sage_const_1en100 = RealNumber('1e-100'); _sage_const_64 = Integer(64); _sage_const_12 = Integer(12)
from ore_algebra import OreAlgebra, guess
import mpmath
mpmath.mp.dps = _sage_const_200 

# ============================================================
# Step 1: Compute a_n and find rec_a
# ============================================================
N = _sage_const_50 
a_list = []
for i in range(N):
    val = QQ(_sage_const_0 )
    for k in range(i+_sage_const_1 ):
        val += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
    a_list.append(val)

print("a_n:", a_list[:_sage_const_6 ])

Rn = PolynomialRing(QQ, 'nn')
nn = Rn.gen()
OS = OreAlgebra(Rn, 'Snn')
Snn = OS.gen()

print("\nGuessing rec_a...")
try:
    rec_a_op = guess(a_list[:_sage_const_40 ], OS, order=_sage_const_3 )
    print("Found rec_a!")
    # Extract coefficients: rec_a_op = P0 + P1*Snn + P2*Snn^2 + P3*Snn^3
    P = [rec_a_op[j] for j in range(_sage_const_4 )]
    for j in range(_sage_const_4 ):
        print("  P_%d(nn) = %s  (degree %d)" % (j, P[j], P[j].degree()))
except Exception as e:
    print("guess failed: %s" % e)
    print("Falling back to manual rec_a computation...")
    # Use the AESZ #209 inner recurrence computed elsewhere
    # The recurrence for a_n is the SAME as the Zudilin/rec_a recurrence
    # We know c_3 and c_0 from proof.tex; let me compute the full thing
    # by building the annihilating matrix directly

    # Build kernel matrix: P3(n) a_{n+3} + P2(n) a_{n+2} + P1(n) a_{n+1} + P0(n) a_n = 0
    # We seek P_j as polynomials in n of some degree d
    # For AESZ inner sum, the recurrence has order 3 and degree 6 per coefficient
    max_deg = _sage_const_8 
    nrows = _sage_const_30 
    rows = []
    for n_val in range(nrows):
        row = []
        for j in range(_sage_const_4 ):  # shifts 0,1,2,3
            for d in range(max_deg+_sage_const_1 ):  # polynomial degree
                row.append(QQ(n_val**d) * a_list[n_val + j])
        rows.append(row)

    M = matrix(QQ, rows)
    K = M.right_kernel()
    print("Kernel dimension: %d" % K.dimension())

    if K.dimension() >= _sage_const_1 :
        v = K.basis()[_sage_const_0 ]
        P = []
        for j in range(_sage_const_4 ):
            poly = sum(v[(max_deg+_sage_const_1 )*j + d] * nn**d for d in range(max_deg+_sage_const_1 ))
            P.append(poly)
            print("  P_%d(nn) = %s" % (j, poly))
    else:
        raise RuntimeError("Cannot find recurrence")

# Verify rec_a
print("\n=== Verify rec_a ===")
for n_val in range(_sage_const_5 ):
    val = sum(P[j](nn=n_val) * a_list[n_val + j] for j in range(_sage_const_4 ))
    print("  n=%d: residual = %s" % (n_val, val))

# ============================================================
# Step 2: Compute p̃_n (Zudilin companion)
# ============================================================
# From Q5048: p̃_n = b̃_n + b̃̃_n satisfies rec_a
# Initial conditions: p̃_0 = 0, p̃_1 = 20, p̃_2 = 7425/16
print("\n=== Computing Zudilin companion p̃_n ===")
p_zud = [QQ(_sage_const_0 )] * N
p_zud[_sage_const_0 ] = QQ(_sage_const_0 )
p_zud[_sage_const_1 ] = QQ(_sage_const_20 )
p_zud[_sage_const_2 ] = QQ(_sage_const_7425 ) / QQ(_sage_const_16 )

# rec_a: P0(n)·u_n + P1(n)·u_{n+1} + P2(n)·u_{n+2} + P3(n)·u_{n+3} = 0
# => u_{n+3} = -(P0(n)·u_n + P1(n)·u_{n+1} + P2(n)·u_{n+2}) / P3(n)
for n_val in range(N-_sage_const_3 ):
    val = sum(P[j](nn=n_val) * p_zud[n_val + j] for j in range(_sage_const_3 ))
    p_zud[n_val + _sage_const_3 ] = -val / P[_sage_const_3 ](nn=n_val)

# Verify: p̃_n / a_n should converge to ζ(2) + ζ(3)
L_mp = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
L_float = float(L_mp)

print("\np̃_n / a_n → ζ(2) + ζ(3):")
for n_val in range(min(_sage_const_20 , N)):
    if a_list[n_val] != _sage_const_0 :
        r = float(p_zud[n_val] / a_list[n_val])
        print("  n=%2d: p̃/a = %.15f, err = %.3e" % (n_val, r, abs(r - L_float)))

# ============================================================
# Step 3: Compute P2.7 sequences
# ============================================================
def A_p27(n_val):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n_val+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n_val+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n_val+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n_val**_sage_const_2 +_sage_const_6407 *n_val+_sage_const_10860 )

def B_p27(n_val):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n_val+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n_val+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n_val**_sage_const_6  + _sage_const_1745370 *n_val**_sage_const_5  +
        _sage_const_12145238 *n_val**_sage_const_4  + _sage_const_44886481 *n_val**_sage_const_3  + _sage_const_92943995 *n_val**_sage_const_2  + _sage_const_102256019 *n_val + _sage_const_46709052 )

def C_p27(n_val):
    return QQ(_sage_const_16 ) * (n_val+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n_val+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n_val**_sage_const_5  + _sage_const_57792 *n_val**_sage_const_4  +
        _sage_const_351019 *n_val**_sage_const_3  + _sage_const_1059230 *n_val**_sage_const_2  + _sage_const_1587211 *n_val + _sage_const_944620 )

def D_p27(n_val):
    return QQ(_sage_const_1 ) * (n_val+_sage_const_3 )**_sage_const_4  * (n_val+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n_val**_sage_const_2  + _sage_const_4515 *n_val + _sage_const_5399 )

# P2.7: A_n u_{n+1} = B_n u_n - C_{n-1} u_{n-1} + D_{n-2} u_{n-2}
q_p27 = [QQ(_sage_const_0 )] * N
q_p27[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q_p27[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q_p27[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

for n_val in range(_sage_const_2 , N-_sage_const_1 ):
    q_p27[n_val+_sage_const_1 ] = (B_p27(n_val) * q_p27[n_val] - C_p27(n_val-_sage_const_1 ) * q_p27[n_val-_sage_const_1 ] + D_p27(n_val-_sage_const_2 ) * q_p27[n_val-_sage_const_2 ]) / A_p27(n_val)

p_p27 = [QQ(_sage_const_0 )] * N
p_p27[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p_p27[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p_p27[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n_val in range(_sage_const_2 , N-_sage_const_1 ):
    p_p27[n_val+_sage_const_1 ] = (B_p27(n_val) * p_p27[n_val] - C_p27(n_val-_sage_const_1 ) * p_p27[n_val-_sage_const_1 ] + D_p27(n_val-_sage_const_2 ) * p_p27[n_val-_sage_const_2 ]) / A_p27(n_val)

# ============================================================
# Step 4: Compute errors using HIGH PRECISION
# ============================================================
print("\n=== Computing errors with mpmath ===")

# Convert to mpmath for high-precision error computation
L_val = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
print("L = ζ(2) + ζ(3) = %s" % mpmath.nstr(L_val, _sage_const_30 ))

# Zudilin error: e_n^Z = p̃_n - L · a_n
e_zud = []
for n_val in range(min(_sage_const_40 , N)):
    e = mpmath.mpf(p_zud[n_val]) - L_val * mpmath.mpf(a_list[n_val])
    e_zud.append(e)

print("\ne_n^Z = p̃_n - L·a_n:")
for n_val in range(min(_sage_const_15 , len(e_zud))):
    print("  n=%2d: e^Z = %s" % (n_val, mpmath.nstr(e_zud[n_val], _sage_const_20 )))

# P2.7 error: e_n^{P27} = p_n - L · q_n
e_p27 = []
for n_val in range(min(_sage_const_40 , N)):
    e = mpmath.mpf(p_p27[n_val]) - L_val * mpmath.mpf(q_p27[n_val])
    e_p27.append(e)

print("\ne_n^{P27} = p_n - L·q_n:")
for n_val in range(min(_sage_const_15 , len(e_p27))):
    print("  n=%2d: e^P27 = %s" % (n_val, mpmath.nstr(e_p27[n_val], _sage_const_20 )))

# ============================================================
# Step 5: Error ratios
# ============================================================
print("\n=== Error ratio: e^{P27}_n / e^Z_n ===")
for n_val in range(min(_sage_const_25 , len(e_zud))):
    if abs(e_zud[n_val]) > _sage_const_1en100  and abs(e_p27[n_val]) > _sage_const_1en100 :
        ratio = e_p27[n_val] / e_zud[n_val]
        print("  n=%2d: e^P27/e^Z = %s" % (n_val, mpmath.nstr(ratio, _sage_const_20 )))

print("\n=== Scaled error ratio: e^{P27}_n / (64^{-n} · e^Z_n) ===")
for n_val in range(min(_sage_const_25 , len(e_zud))):
    if abs(e_zud[n_val]) > _sage_const_1en100  and abs(e_p27[n_val]) > _sage_const_1en100 :
        ratio = e_p27[n_val] / (mpmath.power(_sage_const_64 , -n_val) * e_zud[n_val])
        print("  n=%2d: ratio = %s" % (n_val, mpmath.nstr(ratio, _sage_const_20 )))

# ============================================================
# Step 6: Error decay rates
# ============================================================
print("\n=== Error decay rates ===")
print("e^Z_{n+1} / e^Z_n (should → μ₁ ≈ 0.067):")
for n_val in range(min(_sage_const_20 , len(e_zud)-_sage_const_1 )):
    if abs(e_zud[n_val]) > _sage_const_1en100 :
        ratio = e_zud[n_val+_sage_const_1 ] / e_zud[n_val]
        print("  n=%2d: %s" % (n_val, mpmath.nstr(ratio, _sage_const_12 )))

print("\ne^{P27}_{n+1} / e^{P27}_n (should → μ₁/64 ≈ 0.00105):")
for n_val in range(min(_sage_const_20 , len(e_p27)-_sage_const_1 )):
    if abs(e_p27[n_val]) > _sage_const_1en100 :
        ratio = e_p27[n_val+_sage_const_1 ] / e_p27[n_val]
        print("  n=%2d: %s" % (n_val, mpmath.nstr(ratio, _sage_const_12 )))

# ============================================================
# Step 7: Gauge factor q_n^{P27} / (64^{-n} · a_n)
# ============================================================
print("\n=== Gauge: q^{P27}_n / (64^{-n} · a_n) = q^{P27}_n · 64^n / a_n ===")
gauge_vals = []
for n_val in range(min(_sage_const_25 , N)):
    if a_list[n_val] != _sage_const_0 :
        g = mpmath.mpf(q_p27[n_val]) * mpmath.power(_sage_const_64 , n_val) / mpmath.mpf(a_list[n_val])
        gauge_vals.append(g)
        print("  n=%2d: gauge = %s" % (n_val, mpmath.nstr(g, _sage_const_15 )))

print("\nGauge ratio g_{n+1}/g_n (should stabilize if g_n ~ n^α):")
for n_val in range(min(_sage_const_20 , len(gauge_vals)-_sage_const_1 )):
    if abs(gauge_vals[n_val]) > _sage_const_1en100 :
        ratio = gauge_vals[n_val+_sage_const_1 ] / gauge_vals[n_val]
        print("  n=%2d: %s" % (n_val, mpmath.nstr(ratio, _sage_const_12 )))

# Log of |gauge| to find power law
import math
print("\nlog|gauge|/log(n) for n >= 2:")
for n_val in range(_sage_const_2 , min(_sage_const_25 , len(gauge_vals))):
    if abs(gauge_vals[n_val]) > _sage_const_0 :
        lg = float(mpmath.log(abs(gauge_vals[n_val])))
        ln = math.log(n_val)
        print("  n=%2d: log|g| = %.6f, log|g|/log(n) = %.6f" % (n_val, lg, lg/ln))

