#!/usr/bin/env sage
"""
Find the degree-18 polynomial-coefficient operator annihilating q_n (P2.7).

The recurrence eq:rec has ratio form with different A denominators.
The standard polynomial form should have order 3, degree 18.

Approach: compute many q_n values, then use guess() or matrix kernel.
"""


# This file was *autogenerated* from the file scratchpad/find_deg18_operator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_120 = Integer(120); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_1 = Integer(1); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_0 = Integer(0); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_80 = Integer(80); _sage_const_18 = Integer(18); _sage_const_25 = Integer(25); _sage_const_30 = Integer(30); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_60 = Integer(60)
from ore_algebra import OreAlgebra, guess
import mpmath
mpmath.mp.dps = _sage_const_100 

# ============================================================
# Compute q_n with CORRECT recurrence
# ============================================================
N = _sage_const_120   # Plenty for guessing degree 18

def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

q = [QQ(_sage_const_0 )] * N
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

for n in range(_sage_const_2 , N-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ]

print("q_0 = %s" % q[_sage_const_0 ])
print("q_3 = %s" % q[_sage_const_3 ])
print("q_10 = %s (approx %e)" % (q[_sage_const_10 ], float(q[_sage_const_10 ])))
print("q_20 (approx) = %e" % float(q[_sage_const_20 ]))

# ============================================================
# Method 1: guess() with ore_algebra
# ============================================================
Rn = PolynomialRing(QQ, 'nn')
nn_var = Rn.gen()
OS = OreAlgebra(Rn, 'Snn')
Snn = OS.gen()

print("\n=== Method 1: guess() ===")
q_for_guess = q[:_sage_const_80 ]

# Try order 3
for max_deg in [_sage_const_18 , _sage_const_20 , _sage_const_25 , _sage_const_30 ]:
    try:
        rec = guess(q_for_guess, OS, order=_sage_const_3 , degree=max_deg)
        print("Found at order=3, max_deg=%d!" % max_deg)
        for j in range(_sage_const_4 ):
            print("  P_%d: degree %d" % (j, rec[j].degree()))
        # Print factored form of leading and trailing
        print("  P_3 = %s" % factor(rec[_sage_const_3 ]))
        print("  P_0 = %s" % factor(rec[_sage_const_0 ]))
        break
    except Exception as e:
        print("  order=3, max_deg=%d: %s" % (max_deg, e))

# ============================================================
# Method 2: Matrix kernel for specific degree
# ============================================================
print("\n=== Method 2: matrix kernel for degree 18 ===")
target_deg = _sage_const_18 
num_coeffs = _sage_const_4  * (target_deg + _sage_const_1 )  # 4 shift terms × 19 polynomial coeffs = 76

rows = []
for n_val in range(_sage_const_80 ):
    row = []
    for j_shift in range(_sage_const_4 ):
        idx = n_val + j_shift
        if idx < N:
            for d in range(target_deg + _sage_const_1 ):
                row.append(QQ(n_val**d) * q[idx])
        else:
            for d in range(target_deg + _sage_const_1 ):
                row.append(QQ(_sage_const_0 ))
    rows.append(row)

M = matrix(QQ, rows)
K = M.right_kernel()
print("Kernel dimension: %d (want 1)" % K.dimension())

if K.dimension() >= _sage_const_1 :
    v = K.basis()[_sage_const_0 ]
    P_poly = []
    for j_shift in range(_sage_const_4 ):
        poly = sum(v[(target_deg+_sage_const_1 )*j_shift + d] * nn_var**d for d in range(target_deg+_sage_const_1 ))
        P_poly.append(poly)
        print("  P_%d: degree %d" % (j_shift, poly.degree()))

    # Verify
    print("\n  Verification:")
    for n_val in range(_sage_const_5 ):
        val = sum(P_poly[j](nn=n_val) * q[n_val+j] for j in range(_sage_const_4 ))
        print("    n=%d: residual = %s" % (n_val, val))

    # Factor leading and trailing coefficients
    print("\n  P_3 factored: %s" % factor(P_poly[_sage_const_3 ]))
    print("  P_0 factored: %s" % factor(P_poly[_sage_const_0 ]))

    # Check if it also annihilates p_n
    p = [QQ(_sage_const_0 )] * N
    p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
    p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
    p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )
    for n in range(_sage_const_2 , N-_sage_const_1 ):
        p[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * p[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * p[n-_sage_const_2 ]

    print("\n  P operator on p_n:")
    for n_val in range(_sage_const_5 ):
        val = sum(P_poly[j](nn=n_val) * p[n_val+j] for j in range(_sage_const_4 ))
        print("    n=%d: residual = %s" % (n_val, val))

    # ============================================================
    # GCRD with rec_a
    # ============================================================
    print("\n=== GCRD with rec_a ===")
    a_list = []
    for i in range(N):
        val = QQ(_sage_const_0 )
        for k in range(i+_sage_const_1 ):
            val += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
        a_list.append(val)

    rec_a_op = guess(a_list[:_sage_const_60 ], OS, order=_sage_const_3 )
    print("rec_a:")
    for j in range(_sage_const_4 ):
        print("  P_%d: degree %d" % (j, rec_a_op[j].degree()))

    # Build L_P27 as ore_algebra operator
    L_P27 = sum(P_poly[j] * Snn**j for j in range(_sage_const_4 ))
    print("\nL_P27 = %s" % L_P27)

    try:
        gcrd = L_P27.gcrd(rec_a_op)
        print("GCRD order: %d" % gcrd.order())
        if gcrd.order() > _sage_const_0 :
            print("GCRD = %s" % gcrd)
    except Exception as e:
        print("GCRD failed: %s" % e)

    try:
        lclm = L_P27.lclm(rec_a_op)
        print("LCLM order: %d" % lclm.order())
    except Exception as e:
        print("LCLM failed: %s" % e)

    # ============================================================
    # Convert to theta/D operators and find GF ODE
    # ============================================================
    print("\n=== GF ODE from P2.7 ===")
    try:
        theta_op_p27 = L_P27.to_T('Tz')
        print("Theta operator order: %d" % theta_op_p27.order())

        diff_op_p27 = L_P27.to_D('Dz')
        print("Diff operator order: %d" % diff_op_p27.order())

        # Indicial polynomial
        ind = diff_op_p27.indicial_polynomial(_sage_const_0 )
        print("Indicial at z=0: %s" % ind)
        print("Roots: %s" % ind.roots(QQbar))
    except Exception as e:
        import traceback
        print("Conversion error:")
        traceback.print_exc()

    # ============================================================
    # GCRD in GF ODE form
    # ============================================================
    print("\n=== GCRD of GF ODEs ===")
    try:
        theta_a = rec_a_op.to_T('Tz')
        gcrd_gf = theta_op_p27.gcrd(theta_a)
        print("GCRD of GF theta operators: order %d" % gcrd_gf.order())
    except Exception as e:
        print("GF GCRD failed: %s" % e)

