#!/usr/bin/env sage
"""
1. Verify the two-step error ratio e_n/e_{n-2} → -|r±|²
2. Compute the Pochhammer-gauged sequence v_n = q_n / h_n
3. Try to identify v_n as a hypergeometric series
"""


# This file was *autogenerated* from the file scratchpad/hypergeometric_id.sage
from sage.all_cmdline import *   # import sage library

_sage_const_500 = Integer(500); _sage_const_60 = Integer(60); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_1 = Integer(1); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_0 = Integer(0); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_54p9637 = RealNumber('54.9637'); _sage_const_4096 = Integer(4096); _sage_const_40 = Integer(40); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_12 = Integer(12); _sage_const_14 = Integer(14); _sage_const_18 = Integer(18)
import mpmath
mpmath.mp.dps = _sage_const_500 

N = _sage_const_60 

def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

q = [QQ(_sage_const_0 )] * N
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

p = [QQ(_sage_const_0 )] * N
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n in range(_sage_const_2 , N-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ]
    p[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * p[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * p[n-_sage_const_2 ]

# Errors
L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
e = []
for n_val in range(N):
    p_mp = mpmath.mpf(p[n_val].numerator()) / mpmath.mpf(p[n_val].denominator())
    q_mp = mpmath.mpf(q[n_val].numerator()) / mpmath.mpf(q[n_val].denominator())
    e.append(p_mp - L * q_mp)

# ============================================================
# 1. Two-step ratio e_n / e_{n-2}
# ============================================================
print("=== Two-step ratio e_n / e_{n-2} ===")
print("Expected: -|r±|² = -1/(4μ₀·64²) ≈ -1.110e-6")

# Compute -1/(4 μ₀ · 64²) exactly
# μ₀ is root of 4μ³ - 220μ² + 8μ - 1 = 0
# μ₀ ≈ 54.9637
# |r±|² = 1/(4μ₀ · 64²) = 1/(4 · 54.9637 · 4096) = 1/900698.06 ≈ 1.1103e-6
print("1/(4·54.9637·4096) = %e" % (_sage_const_1 /(_sage_const_4 *_sage_const_54p9637 *_sage_const_4096 )))

for n_val in range(_sage_const_2 , min(_sage_const_40 , len(e))):
    if abs(e[n_val-_sage_const_2 ]) > _sage_const_0 :
        r = e[n_val] / e[n_val-_sage_const_2 ]
        print("n=%2d: e_n/e_{n-2} = %s" % (n_val, mpmath.nstr(r, _sage_const_15 )))

# ============================================================
# 2. Pochhammer gauge
# ============================================================
print("\n=== Pochhammer gauge h_n ===")
def pochhammer(a, n):
    """Rising factorial (a)_n = a(a+1)...(a+n-1)"""
    return prod(a + j for j in range(n))

h = [QQ(_sage_const_0 )] * N
for i in range(N):
    h[i] = QQ(_sage_const_2 )**(-_sage_const_20 *i) * pochhammer(QQ(_sage_const_3 ), i)**_sage_const_4  * pochhammer(QQ(_sage_const_4 ), i)**_sage_const_6  /            (pochhammer(QQ(_sage_const_5 )/_sage_const_2 , i)**_sage_const_4  * pochhammer(QQ(_sage_const_7 )/_sage_const_2 , i)**_sage_const_3  * pochhammer(QQ(_sage_const_9 )/_sage_const_2 , i)**_sage_const_3 )

print("h_0 = %s" % h[_sage_const_0 ])
print("h_1 = %s" % h[_sage_const_1 ])
print("h_2 = %s" % h[_sage_const_2 ])

# Check D_n/A_n vs h_{n+1}/h_n
print("\nD_n/A_n vs h_{n+1}/h_n:")
for n_val in range(_sage_const_5 ):
    da = D_p27(n_val) / A_p27(n_val)
    hh = h[n_val+_sage_const_1 ] / h[n_val]
    print("  n=%d: D/A = %s, h_{n+1}/h_n = %s, match: %s" % (n_val, float(da), float(hh), da == hh))

# ============================================================
# 3. Gauged sequence v_n = q_n / h_n
# ============================================================
print("\n=== v_n = q_n / h_n ===")
v = [QQ(_sage_const_0 )] * N
for i in range(N):
    if h[i] != _sage_const_0 :
        v[i] = q[i] / h[i]

for n_val in range(min(_sage_const_10 , N)):
    print("v_%d = %s = %e" % (n_val, v[n_val], float(v[n_val])))

# Check ratios v_{n+1}/v_n
print("\nv_{n+1}/v_n:")
for n_val in range(min(_sage_const_15 , N-_sage_const_1 )):
    if v[n_val] != _sage_const_0 :
        r = float(v[n_val+_sage_const_1 ] / v[n_val])
        print("  n=%d: %.15f" % (n_val, r))

# ============================================================
# 4. Try to identify v_n as a hypergeometric sum
# ============================================================
# The Zudilin inner sum is a_n = Σ C(n,k)² C(n+k,k) C(n+2k,n)
# = ₄F₃(−n,−n,n+1,n+1; 1,1,1; 1) or similar.
# After Pochhammer gauge, v_n might be a similar ₄F₃.

# First, compute v_n directly from initial conditions and see structure
print("\n=== v_n factored ===")
for n_val in range(min(_sage_const_8 , N)):
    if v[n_val] != _sage_const_0 :
        num = v[n_val].numerator()
        den = v[n_val].denominator()
        print("v_%d num = %s" % (n_val, factor(ZZ(num)) if abs(num) < _sage_const_10 **_sage_const_30  else "too large"))
        print("v_%d den = %s" % (n_val, factor(ZZ(den)) if abs(den) < _sage_const_10 **_sage_const_30  else "too large"))

# ============================================================
# 5. Compute D_n/A_n to verify Pochhammer gauge
# ============================================================
print("\n=== D_{n-2}/A_{n-2} pattern ===")
for n_val in range(_sage_const_5 ):
    da = D_p27(n_val) / A_p27(n_val)
    # Factor
    num_d = D_p27(n_val)
    den_a = A_p27(n_val)
    print("D_%d/A_%d = %s" % (n_val, n_val, da))

# ============================================================
# 6. Recurrence for v_n
# ============================================================
print("\n=== Guessing recurrence for v_n ===")
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
nn_var = Rn.gen()
OS = OreAlgebra(Rn, 'Snn')
Snn = OS.gen()

v_list = v[:_sage_const_40 ]
for order in [_sage_const_3 , _sage_const_4 , _sage_const_5 ]:
    for deg in [_sage_const_12 , _sage_const_14 , _sage_const_16 , _sage_const_18 , _sage_const_20 ]:
        try:
            rec_v = guess(v_list, OS, order=order, degree=deg)
            print("Found for v: order=%d, degree=%d" % (order, deg))
            for j in range(order+_sage_const_1 ):
                print("  P_%d: degree %d" % (j, rec_v[j].degree()))
            print("  P_%d factored: %s" % (order, factor(rec_v[order])))
            print("  P_0 factored: %s" % factor(rec_v[_sage_const_0 ]))
            break
        except:
            pass
    else:
        continue
    break

# ============================================================
# 7. Compute the "well-poised" candidate
# ============================================================
# Try: w_n = Σ_{k=0}^n f(n,k) where f has Pochhammer structure
# related to the P2.7 parameters
print("\n=== Well-poised candidate ===")
# From Dauguet-Zudilin, the companion for ζ(2)+ζ(3) involves
# a ₅F₄ series with parameters related to the CY operator.
#
# The inner sum for AESZ #209 is:
# a_n = Σ C(n,k)² C(n+k,k) C(n+2k,k)
#     = ₄F₃(-n, -n, n+1, 1; 1, 1, 1; -1)  [not quite]
#
# The connection to ζ(2)+ζ(3) might come from a ε-derivative:
# d/dε [a_n(ε)]|_{ε=0} where a_n(ε) = Σ C(n,k)² C(n+k,k+ε) C(n+2k,n+ε)

# For now, let me check if q_n/h_n has a nice sum representation
# by examining the first few values.
print("v_0 = q_0/h_0 = q_0 = %s" % v[_sage_const_0 ])
print("v_1 = %s" % v[_sage_const_1 ])
print("v_2 = %s" % v[_sage_const_2 ])

# Check if v_n / (-215040420000) gives a clean sequence
c0 = v[_sage_const_0 ]
print("\nv_n / v_0:")
for n_val in range(min(_sage_const_8 , N)):
    if c0 != _sage_const_0 :
        r = v[n_val] / c0
        print("  n=%d: %s" % (n_val, r))

