#!/usr/bin/env sage
"""
Search for nonlocal transforms from AESZ #209 (a_n) to P2.7 (q_n).
Try: binomial, Euler, Hadamard, weighted binomial.
"""


# This file was *autogenerated* from the file scratchpad/nonlocal_transform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_50 = Integer(50); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_15 = Integer(15); _sage_const_2623 = Integer(2623); _sage_const_1830 = Integer(1830); _sage_const_83 = Integer(83); _sage_const_22 = Integer(22); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_0p01 = RealNumber('0.01'); _sage_const_43 = Integer(43)
import mpmath
mpmath.mp.dps = _sage_const_50 

# ============================================================
# AESZ #209 sequence
# ============================================================
N = _sage_const_30 
a = [QQ(_sage_const_0 )] * N
for n in range(N):
    val = QQ(_sage_const_0 )
    for k in range(n+_sage_const_1 ):
        val += binomial(n,k)**_sage_const_2  * binomial(n+k,n) * binomial(n+_sage_const_2 *k,n)
    a[n] = val

print("AESZ #209 first values:")
for i in range(_sage_const_10 ):
    print("  a_%d = %s" % (i, a[i]))

# ============================================================
# P2.7 sequences
# ============================================================
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )
def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )
def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

q = [QQ(_sage_const_0 )] * N
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

for n in range(_sage_const_2 , N-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n)*q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 )*q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 )*q[n-_sage_const_2 ]

print("\nP2.7 first values:")
for i in range(_sage_const_8 ):
    print("  q_%d = %s" % (i, float(q[i])))

# ============================================================
# Pochhammer gauge
# ============================================================
def gamma_gauge(n):
    """γ_n = 2^{-20n} · (3)_n^4 · (4)_n^6 / [(5/2)_n^4 · (7/2)_n^3 · (9/2)_n^3]"""
    if n == _sage_const_0 :
        return QQ(_sage_const_1 )
    num = QQ(_sage_const_2 )**(-_sage_const_20 *n)
    for j in range(n):
        num *= (_sage_const_3 +j)**_sage_const_4  * (_sage_const_4 +j)**_sage_const_6 
    den = QQ(_sage_const_1 )
    for j in range(n):
        den *= (QQ(_sage_const_5 )/_sage_const_2 +j)**_sage_const_4  * (QQ(_sage_const_7 )/_sage_const_2 +j)**_sage_const_3  * (QQ(_sage_const_9 )/_sage_const_2 +j)**_sage_const_3 
    return num / den

print("\nGauged P2.7: v_n = q_n / γ_n")
v = [QQ(_sage_const_0 )] * N
for i in range(min(_sage_const_15 , N)):
    g = gamma_gauge(i)
    if g != _sage_const_0 :
        v[i] = q[i] / g
        print("  v_%d = %s = %e" % (i, v[i] if abs(v[i]) < _sage_const_10 **_sage_const_20  else "...", float(v[i])))

# Q₂₀₉ factor
def Q209(x):
    return _sage_const_946 *x**_sage_const_2  - _sage_const_2623 *x + _sage_const_1830 

print("\nQ209(n+83/22) values:")
for n in range(_sage_const_8 ):
    val = Q209(n + QQ(_sage_const_83 )/_sage_const_22 )
    print("  n=%d: Q209 = %s" % (n, val))

# Further gauge: w_n = v_n / Q209(n+83/22)
print("\nFully gauged: w_n = q_n / (γ_n · Q209(n+83/22))")
w = [QQ(_sage_const_0 )] * N
for i in range(min(_sage_const_15 , N)):
    g = gamma_gauge(i)
    Q_val = Q209(i + QQ(_sage_const_83 )/_sage_const_22 )
    if g != _sage_const_0  and Q_val != _sage_const_0 :
        w[i] = q[i] / (g * Q_val)
        print("  w_%d = %e" % (i, float(w[i])))

# ============================================================
# Transform searches
# ============================================================

# 1. Binomial transform: b_n = Σ C(n,m) a_m
print("\n=== Binomial transform of a_n ===")
b_binom = []
for n in range(min(_sage_const_15 , N)):
    val = sum(binomial(n, m) * a[m] for m in range(n+_sage_const_1 ))
    b_binom.append(val)
    print("  b_%d = %s" % (n, val))

# Compare with v_n
print("\nb_n / v_n:")
for n in range(min(_sage_const_10 , len(b_binom))):
    if v[n] != _sage_const_0  and b_binom[n] != _sage_const_0 :
        print("  n=%d: %e" % (n, float(b_binom[n] / v[n])))

# 2. Euler transform: b_n = Σ (-1)^{n-m} C(n,m) a_m
print("\n=== Euler transform of a_n ===")
b_euler = []
for n in range(min(_sage_const_15 , N)):
    val = sum((-_sage_const_1 )**(n-m) * binomial(n, m) * a[m] for m in range(n+_sage_const_1 ))
    b_euler.append(val)
    print("  b_%d = %s" % (n, val))

# 3. Double binomial: b_n = Σ C(n,m)^2 a_m
print("\n=== Double binomial transform ===")
b_double = []
for n in range(min(_sage_const_15 , N)):
    val = sum(binomial(n, m)**_sage_const_2  * a[m] for m in range(n+_sage_const_1 ))
    b_double.append(val)
    print("  b_%d = %s" % (n, val))

# 4. Rising factorial weighted: b_n = Σ C(n,m) C(n+m,m) a_m
print("\n=== C(n,m)·C(n+m,m) transform ===")
b_rise = []
for n in range(min(_sage_const_15 , N)):
    val = sum(binomial(n, m) * binomial(n+m, m) * a[m] for m in range(n+_sage_const_1 ))
    b_rise.append(val)
    print("  b_%d = %s" % (n, val))

# 5. Check if any transform matches v_n up to normalization
print("\n=== Ratio checks ===")
for name, b_list in [("binom", b_binom), ("euler", b_euler),
                      ("double", b_double), ("rise", b_rise)]:
    ratios = []
    for n in range(min(_sage_const_8 , len(b_list))):
        if v[n] != _sage_const_0  and b_list[n] != _sage_const_0 :
            ratios.append(float(b_list[n] / v[n]))
    print("%s: ratios = %s" % (name, ["%.6e" % r for r in ratios]))
    if len(ratios) >= _sage_const_2 :
        const = all(abs(r - ratios[_sage_const_0 ]) / max(abs(ratios[_sage_const_0 ]), _sage_const_1en30 ) < _sage_const_0p01  for r in ratios[_sage_const_1 :])
        print("  constant? %s" % const)

# 6. Try convolution: b_n = Σ a_m * a_{n-m}
print("\n=== Convolution a*a ===")
b_conv = []
for n in range(min(_sage_const_15 , N)):
    val = sum(a[m] * a[n-m] for m in range(n+_sage_const_1 ))
    b_conv.append(val)
    print("  b_%d = %s" % (n, val))

# 7. Try Hadamard product: b_n = a_n * a_n
print("\n=== Hadamard square a_n^2 ===")
for n in range(_sage_const_8 ):
    print("  a_%d^2 = %s" % (n, a[n]**_sage_const_2 ))

# 8. Try to factor q_0
print("\n=== q_0 factored ===")
print("q_0 = %s" % q[_sage_const_0 ])
print("factored: %s" % factor(ZZ(q[_sage_const_0 ].numerator())))
print("\na_0 = %s, a_1 = %s, a_2 = %s" % (a[_sage_const_0 ], a[_sage_const_1 ], a[_sage_const_2 ]))
print("a_0·a_1·a_2·a_3 = %s" % (a[_sage_const_0 ]*a[_sage_const_1 ]*a[_sage_const_2 ]*a[_sage_const_3 ]))

# 9. Check: does q_0 divide into any simple expression?
q0 = ZZ(q[_sage_const_0 ])
# -215040420000 = -2^5 · 3^6 · 5^4 · 7^3 · 43
# Let's check: is q_0 related to factorials?
print("\nFactorial products:")
for p in range(_sage_const_1 , _sage_const_20 ):
    print("  %d! = %d" % (p, factorial(p)))

# 10. Try: does q_n / (some product of factorials) match a_n times something?
# The gauge γ_n involves (3)_n^4 (4)_n^6 / [(5/2)_n^4 (7/2)_n^3 (9/2)_n^3]
# At n=0, γ_0 = 1, so the normalization is all in q_0
# q_0 = -2^5 · 3^6 · 5^4 · 7^3 · 43
# The 43 is interesting — it appears in Q₂₀₉ factoring?
print("\n=== Q₂₀₉ at special values ===")
for x in range(_sage_const_20 ):
    val = _sage_const_946 *x**_sage_const_2  - _sage_const_2623 *x + _sage_const_1830 
    if val != _sage_const_0  and val % _sage_const_43  == _sage_const_0 :
        print("  Q209(%d) = %d = 43 * %d" % (x, val, val // _sage_const_43 ))
print("  Q209(0) = %d" % Q209(_sage_const_0 ))
print("  Q209(83/22) = %s" % Q209(QQ(_sage_const_83 )/_sage_const_22 ))

# 11. Explore: q_0 / Q209(83/22) · ...
q209_0 = Q209(QQ(_sage_const_83 )/_sage_const_22 )
print("\nQ209(83/22) = %s = %e" % (q209_0, float(q209_0)))
print("q_0 / Q209(83/22) = %s" % (q[_sage_const_0 ] / q209_0))

# 12. Try ore_algebra guess on gauged sequence
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
OS = OreAlgebra(Rn, 'Snn')

print("\n=== Recurrence guess for gauged v_n ===")
v_list = [v[i] for i in range(min(_sage_const_20 , N)) if v[i] != _sage_const_0 ]
for order in [_sage_const_2 , _sage_const_3 , _sage_const_4 ]:
    try:
        rec = guess(v_list[:_sage_const_15 ], OS, order=order)
        print("Found order-%d recurrence for v_n!" % order)
        for j in range(order+_sage_const_1 ):
            print("  P_%d: degree %d" % (j, rec[j].degree()))
        break
    except:
        print("  order=%d: no relation" % order)

