"""
Ore factorization of the P2.7 recurrence over K = Q(mu_0).

If a first-order right factor S - r(n) exists with r in K(n),
then the cubic-trace hypothesis is confirmed and the P2.7 module
decomposes into rank-one pieces over K.

Based on Q5102 §6, §10.
"""


# This file was *autogenerated* from the file scratchpad/ore_factor_K.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_220 = Integer(220); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_60 = Integer(60)
from sage.all import *
from ore_algebra import OreAlgebra

# Number field K = Q(mu) where mu is a root of the Poincare cubic
Qx = PolynomialRing(QQ, 'x')
x = Qx.gen()
P = _sage_const_4 *x**_sage_const_3  - _sage_const_220 *x**_sage_const_2  + _sage_const_8 *x - _sage_const_1 
assert P.is_irreducible()
print("Poincare cubic:", P)
print("Discriminant:", P.discriminant())

K = NumberField(P, 'mu')
mu = K.gen()
print("Field K = Q(mu), disc =", K.discriminant())
print("Signature:", K.signature())

# Verify mu satisfies the polynomial
assert _sage_const_4 *mu**_sage_const_3  - _sage_const_220 *mu**_sage_const_2  + _sage_const_8 *mu - _sage_const_1  == _sage_const_0 
print("mu satisfies P: OK")

# Set up Ore algebra K(n)<S>
Rn = PolynomialRing(K, 'n')
n = Rn.gen()
Fn = Rn.fraction_field()
Ore = OreAlgebra(Fn, 'S')
S = Ore.gen()

# P2.7 coefficient polynomials (in n)
def A(z):
    return Fn(_sage_const_1024 *(_sage_const_2 *z+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *z**_sage_const_2 +_sage_const_6407 *z+_sage_const_10860 ))

def B(z):
    return Fn(_sage_const_128 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *z**_sage_const_6 +_sage_const_1745370 *z**_sage_const_5 +_sage_const_12145238 *z**_sage_const_4 +_sage_const_44886481 *z**_sage_const_3 +_sage_const_92943995 *z**_sage_const_2 +_sage_const_102256019 *z+_sage_const_46709052 ))

def C(z):
    return Fn(_sage_const_16 *(z+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *z**_sage_const_5 +_sage_const_57792 *z**_sage_const_4 +_sage_const_351019 *z**_sage_const_3 +_sage_const_1059230 *z**_sage_const_2 +_sage_const_1587211 *z+_sage_const_944620 ))

def D(z):
    return Fn((z+_sage_const_3 )**_sage_const_4 *(z+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *z**_sage_const_2 +_sage_const_4515 *z+_sage_const_5399 ))

# Forward operator: A(n+2) u_{n+3} - B(n+2) u_{n+2} + C(n+1) u_{n+1} - D(n) u_n = 0
L = A(n+_sage_const_2 )*S**_sage_const_3  - B(n+_sage_const_2 )*S**_sage_const_2  + C(n+_sage_const_1 )*S - D(n)

print("\nOperator L constructed.")
print("Order:", L.order())

# Check leading coefficient
lc = L.leading_coefficient()
print("Leading coefficient degree:", Rn(lc.numerator()).degree())

# Attempt factorization
print("\n" + "="*_sage_const_60 )
print("Attempting factorization of L over K(n)<S>...")
print("="*_sage_const_60 )
import sys
sys.stdout.flush()

try:
    factors = L.factor()
    print("\nFactorization result:")
    print(factors)

    # Check if there's a first-order factor
    for f, mult in factors:
        print(f"\n  Factor of order {f.order()}, multiplicity {mult}")
        if f.order() == _sage_const_1 :
            # Extract r(n) from S - r(n)
            print("  FIRST-ORDER FACTOR FOUND!")
            print("  Factor:", f)
except Exception as e:
    print(f"\nFactorization raised an exception: {type(e).__name__}: {e}")
    print("\nTrying right_factor search instead...")
    try:
        rf = L.right_factor(_sage_const_1 )
        print("Right factor of order 1:", rf)
    except Exception as e2:
        print(f"Right factor search also failed: {type(e2).__name__}: {e2}")

print("\n" + "="*_sage_const_60 )
print("Also checking: does L factor over Q(n)?")
print("="*_sage_const_60 )

# Same operator over Q(n) for comparison
Rn_Q = PolynomialRing(QQ, 'n')
n_Q = Rn_Q.gen()
Fn_Q = Rn_Q.fraction_field()
Ore_Q = OreAlgebra(Fn_Q, 'S')
S_Q = Ore_Q.gen()

def AQ(z): return Fn_Q(_sage_const_1024 *(_sage_const_2 *z+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *z**_sage_const_2 +_sage_const_6407 *z+_sage_const_10860 ))
def BQ(z): return Fn_Q(_sage_const_128 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *z**_sage_const_6 +_sage_const_1745370 *z**_sage_const_5 +_sage_const_12145238 *z**_sage_const_4 +_sage_const_44886481 *z**_sage_const_3 +_sage_const_92943995 *z**_sage_const_2 +_sage_const_102256019 *z+_sage_const_46709052 ))
def CQ(z): return Fn_Q(_sage_const_16 *(z+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *z**_sage_const_5 +_sage_const_57792 *z**_sage_const_4 +_sage_const_351019 *z**_sage_const_3 +_sage_const_1059230 *z**_sage_const_2 +_sage_const_1587211 *z+_sage_const_944620 ))
def DQ(z): return Fn_Q((z+_sage_const_3 )**_sage_const_4 *(z+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *z**_sage_const_2 +_sage_const_4515 *z+_sage_const_5399 ))

L_Q = AQ(n_Q+_sage_const_2 )*S_Q**_sage_const_3  - BQ(n_Q+_sage_const_2 )*S_Q**_sage_const_2  + CQ(n_Q+_sage_const_1 )*S_Q - DQ(n_Q)

try:
    factors_Q = L_Q.factor()
    print("Factorization over Q(n):", factors_Q)
except Exception as e:
    print(f"Factorization over Q(n) failed: {e}")

print("\nDone.")

