"""
Riccati equation search for first-order right factor of P2.7 recurrence over Q(μ₀)(n).

KEY DISCOVERY: The quadratic factors of the leading (p₃) and trailing (p₀) coefficients
are related by an integer shift:
  Q_p₃(n) = n² + 149/22·n + 5430/473   (from A(n))
  Q_p₀(n) = n² + 105/22·n + 5399/946   (from D(n))
  Q_p₃(n-1) = Q_p₀(n)  ← VERIFIED

This is the ONLY integer-difference pair among the roots of p₃ and p₀.

ANSATZ for hypergeometric ratio r(n) = u_{n+1}/u_n:
  r(n) = λ₀ · Q_p₃(n) · P(n) / (Q_p₃(n-1) · P(n+1))
where P(n) is a degree-2 polynomial to be determined.

This gives σ = 2 - 2 = 0, consistent with the proved σ=0.
"""


# This file was *autogenerated* from the file scratchpad/riccati_search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_220 = Integer(220); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_149 = Integer(149); _sage_const_22 = Integer(22); _sage_const_5430 = Integer(5430); _sage_const_473 = Integer(473); _sage_const_105 = Integer(105); _sage_const_5399 = Integer(5399); _sage_const_946 = Integer(946); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11)
from sage.all import *
from ore_algebra import OreAlgebra

print("=== Riccati search for first-order factor over Q(μ₀)(n) ===\n")

# Define number field K = Q(μ₀)
Rx = PolynomialRing(QQ, names=('x',)); (x,) = Rx._first_ngens(1)
K = NumberField(_sage_const_4 *x**_sage_const_3  - _sage_const_220 *x**_sage_const_2  + _sage_const_8 *x - _sage_const_1 , names=('mu0',)); (mu0,) = K._first_ngens(1)
print(f"K = Q(μ₀), degree {K.degree()}")

# Poincaré root λ₀ = μ₀/64
lam0 = mu0 / K(_sage_const_64 )
print(f"λ₀ = μ₀/64")

# Verify: 1/μ₀ = 4μ₀²-220μ₀+8
inv_mu0 = _sage_const_4 *mu0**_sage_const_2  - _sage_const_220 *mu0 + _sage_const_8 
assert inv_mu0 * mu0 == _sage_const_1 

# The quadratic factors
Rn = PolynomialRing(K, names=('n',)); (n,) = Rn._first_ngens(1)

Q_p3 = n**_sage_const_2  + K(_sage_const_149 )/K(_sage_const_22 )*n + K(_sage_const_5430 )/K(_sage_const_473 )  # from p₃ = A(n)
Q_p0 = n**_sage_const_2  + K(_sage_const_105 )/K(_sage_const_22 )*n + K(_sage_const_5399 )/K(_sage_const_946 )  # from p₀ = -D(n)

# Verify Q_p3(n-1) = Q_p0(n)
Q_p3_shifted = Q_p3(n-_sage_const_1 )
print(f"\nQ_p₃(n) = {Q_p3}")
print(f"Q_p₀(n) = {Q_p0}")
print(f"Q_p₃(n-1) = {Q_p3_shifted}")
assert Q_p3_shifted == Q_p0, "SHIFT VERIFICATION FAILED"
print("✓ Q_p₃(n-1) = Q_p₀(n) verified!")

# Define the P2.7 recurrence coefficients
def A_K(z):
    return K(_sage_const_1024 )*(_sage_const_2 *z+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(K(_sage_const_946 )*z**_sage_const_2 +K(_sage_const_6407 )*z+K(_sage_const_10860 ))

def B_K(z):
    return K(_sage_const_128 )*(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(K(_sage_const_104060 )*z**_sage_const_6 +K(_sage_const_1745370 )*z**_sage_const_5 +K(_sage_const_12145238 )*z**_sage_const_4 +K(_sage_const_44886481 )*z**_sage_const_3 +K(_sage_const_92943995 )*z**_sage_const_2 +K(_sage_const_102256019 )*z+K(_sage_const_46709052 ))

def C_K(z):
    return K(_sage_const_16 )*(z+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(K(_sage_const_3784 )*z**_sage_const_5 +K(_sage_const_57792 )*z**_sage_const_4 +K(_sage_const_351019 )*z**_sage_const_3 +K(_sage_const_1059230 )*z**_sage_const_2 +K(_sage_const_1587211 )*z+K(_sage_const_944620 ))

def D_K(z):
    return (z+_sage_const_3 )**_sage_const_4 *(z+_sage_const_4 )**_sage_const_6 *(K(_sage_const_946 )*z**_sage_const_2 +K(_sage_const_4515 )*z+K(_sage_const_5399 ))

# The Riccati equation for r(n):
# p₃(n)·r(n)·r(n+1)·r(n+2) + p₂(n)·r(n)·r(n+1) + p₁(n)·r(n) + p₀(n) = 0
# where p₃=A, p₂=-B(n+2), p₁=C(n+1), p₀=-D(n)

p3 = Rn(A_K(n))
p2 = Rn(-B_K(n+_sage_const_2 ))
p1 = Rn(C_K(n+_sage_const_1 ))
p0 = Rn(-D_K(n))

print(f"\nDegrees: p₃={p3.degree()}, p₂={p2.degree()}, p₁={p1.degree()}, p₀={p0.degree()}")

# ANSATZ: r(n) = λ₀ · Q_p₃(n) · P(n) / (Q_p₃(n-1) · P(n+1))
# where P(n) = n² + p·n + q, p,q ∈ K
#
# Products:
# r(n)·r(n+1)·r(n+2) = λ₀³ · Q_p₃(n+2)·P(n) / (Q_p₃(n-1)·P(n+3))
# r(n)·r(n+1) = λ₀² · Q_p₃(n+1)·P(n) / (Q_p₃(n-1)·P(n+2))
# r(n) = λ₀ · Q_p₃(n)·P(n) / (Q_p₃(n-1)·P(n+1))

# Substitute into Riccati and clear denominator Q_p₃(n-1)·P(n+1)·P(n+2)·P(n+3):
# p₃·λ₀³·Q_p₃(n+2)·P(n)·P(n+1)·P(n+2)
# + p₂·λ₀²·Q_p₃(n+1)·P(n)·P(n+1)·P(n+3)
# + p₁·λ₀·Q_p₃(n)·P(n)·P(n+2)·P(n+3)
# + p₀·Q_p₃(n-1)·P(n+1)·P(n+2)·P(n+3) = 0

# Use symbolic p, q
K_pq = PolynomialRing(K, names=('pp', 'qq',)); (pp, qq,) = K_pq._first_ngens(2)
Rn_pq = PolynomialRing(K_pq, names=('nn',)); (nn,) = Rn_pq._first_ngens(1)

# P(n) = nn^2 + pp*nn + qq
def P_pq(z):
    return z**_sage_const_2  + pp*z + qq

def Q_p3_pq(z):
    return z**_sage_const_2  + K(_sage_const_149 )/K(_sage_const_22 )*z + K(_sage_const_5430 )/K(_sage_const_473 )

# Build the Riccati polynomial
print("\nBuilding Riccati polynomial (this may take a moment)...")

term1 = Rn_pq(p3(nn)) * lam0**_sage_const_3  * Q_p3_pq(nn+_sage_const_2 ) * P_pq(nn) * P_pq(nn+_sage_const_1 ) * P_pq(nn+_sage_const_2 )
term2 = Rn_pq(p2(nn)) * lam0**_sage_const_2  * Q_p3_pq(nn+_sage_const_1 ) * P_pq(nn) * P_pq(nn+_sage_const_1 ) * P_pq(nn+_sage_const_3 )
term3 = Rn_pq(p1(nn)) * lam0  * Q_p3_pq(nn)   * P_pq(nn) * P_pq(nn+_sage_const_2 ) * P_pq(nn+_sage_const_3 )
term4 = Rn_pq(p0(nn))         * Q_p3_pq(nn-_sage_const_1 )  * P_pq(nn+_sage_const_1 ) * P_pq(nn+_sage_const_2 ) * P_pq(nn+_sage_const_3 )

print("  Computing terms...")
F_riccati = term1 + term2 + term3 + term4
print(f"  Riccati polynomial degree in n: {F_riccati.degree()}")

# Extract coefficients of nn^k — each must be 0
coeffs_n = F_riccati.list()
print(f"  Number of coefficient equations: {len(coeffs_n)}")

# Each coefficient is a polynomial in pp, qq over K
# We need to solve the system coeffs_n[k](pp, qq) = 0 for all k

# Check the highest-degree coefficients first (they should involve the characteristic equation)
print("\n=== Checking coefficient equations ===")
for i, c in enumerate(reversed(coeffs_n)):
    if c == _sage_const_0 :
        print(f"  [n^{len(coeffs_n)-_sage_const_1 -i}]: = 0 (automatically satisfied)")
    else:
        # Show degree and a few terms
        deg_p = max([e[_sage_const_0 ] for e in c.exponents()] + [_sage_const_0 ]) if c != _sage_const_0  else -_sage_const_1 
        deg_q = max([e[_sage_const_1 ] for e in c.exponents()] + [_sage_const_0 ]) if c != _sage_const_0  else -_sage_const_1 
        print(f"  [n^{len(coeffs_n)-_sage_const_1 -i}]: nonzero, max pp-degree={deg_p}, max qq-degree={deg_q}")
    if i >= _sage_const_10 :
        remaining = sum(_sage_const_1  for c in coeffs_n if c != _sage_const_0 ) - sum(_sage_const_1  for c in reversed(coeffs_n[:len(coeffs_n)-_sage_const_11 ]) if c != _sage_const_0 )
        print(f"  ... (showing first 11 coefficient equations)")
        break

# Try to solve: collect all nonzero coefficients as a system in pp, qq
print("\n=== Solving the system ===")
nonzero_coeffs = [c for c in coeffs_n if c != _sage_const_0 ]
print(f"Number of nonzero equations: {len(nonzero_coeffs)}")

if len(nonzero_coeffs) == _sage_const_0 :
    print("All coefficients are zero — r(n) = λ₀ for ANY P(n)!")
else:
    # Try to find the ideal and solve
    I = K_pq.ideal(nonzero_coeffs)
    print(f"Ideal has {len(I.gens())} generators")

    # Compute Groebner basis
    print("Computing Groebner basis...")
    try:
        gb = I.groebner_basis()
        print(f"Groebner basis has {len(gb)} elements:")
        for g in gb:
            print(f"  {g}")

        if _sage_const_1  in gb or K_pq.one() in gb:
            print("\n★ RESULT: The ideal is the whole ring — NO SOLUTION EXISTS.")
            print("  There is NO first-order right factor with this ansatz.")
        else:
            print("\n★ RESULT: Solution(s) exist!")
            # Try to find the variety
            try:
                V = I.variety()
                print(f"Variety has {len(V)} points:")
                for pt in V:
                    print(f"  pp = {pt[pp]}, qq = {pt[qq]}")
            except Exception as e:
                print(f"  (Could not compute variety: {e})")
                print(f"  Groebner basis: {gb}")
    except Exception as e:
        print(f"Groebner basis failed: {e}")

        # Fallback: try resultant
        print("\nFallback: computing resultant...")
        try:
            # Take two nonzero coefficients and compute resultant wrt pp
            c1 = nonzero_coeffs[_sage_const_0 ]
            c2 = nonzero_coeffs[_sage_const_1 ]
            res_pp = c1.resultant(c2, pp)
            print(f"Resultant wrt pp: degree in qq = {res_pp.degree(qq) if res_pp != _sage_const_0  else 'zero'}")
            if res_pp == _sage_const_0 :
                print("Resultant is zero — equations share a common factor in pp")
            else:
                qq_roots = Rn(res_pp).roots(K)
                print(f"Roots in K: {qq_roots}")
        except Exception as e:
            print(f"Resultant failed: {e}")

# Also try the SIMPLER ansatz: r(n) = constant (sanity check)
print("\n=== Sanity check: r(n) = λ₀ ===")
F_const = p3 * lam0**_sage_const_3  + p2 * lam0**_sage_const_2  + p1 * lam0 + p0
print(f"p₃λ₀³ + p₂λ₀² + p₁λ₀ + p₀ = polynomial of degree {F_const.degree()}")
if F_const == _sage_const_0 :
    print("  ZERO — constant ratio works!")
else:
    print(f"  Nonzero — constant ratio fails (expected)")
    # Check leading coefficient
    lc_val = F_const.leading_coefficient()
    print(f"  Leading coefficient: {lc_val}")

print("\nDone.")

