#!/usr/bin/env sage
"""
Test: Does the shifted Barnes integral J_{n+17/22} satisfy the P2.7 recurrence?

R_ν(t) = Γ(ν+1-t)³ · Γ(t) / [Γ(1-t)³ · Γ(ν+1)² · Γ(t+ν+1)]

J_ν = (1/2πi) ∮ R_ν(t) · [π/sin(πt)]² · [πcot(πt) - 1] dt

For integer ν=n, this gives the Zudilin companion: J_n = p̃_n - (ζ(2)+ζ(3))a_n

Hypothesis: J_{n+17/22} is proportional to e_n = p_n - (ζ(2)+ζ(3))q_n (P2.7 error)
"""


# This file was *autogenerated* from the file scratchpad/shifted_barnes_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_40 = Integer(40); _sage_const_50 = Integer(50); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5'); _sage_const_17 = Integer(17); _sage_const_22 = Integer(22); _sage_const_30 = Integer(30); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4); _sage_const_7425 = Integer(7425); _sage_const_16 = Integer(16); _sage_const_7 = Integer(7); _sage_const_1024 = Integer(1024); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_8 = Integer(8); _sage_const_15 = Integer(15)
import mpmath
mpmath.mp.dps = _sage_const_100 

# ============================================================
# 1. Define the integrand for general ν
# ============================================================
def R_nu(nu, t):
    """R_ν(t) = Γ(ν+1-t)³ · Γ(t) / [Γ(1-t)³ · Γ(ν+1)² · Γ(t+ν+1)]"""
    return (mpmath.gamma(nu+_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(t) /
            (mpmath.gamma(_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(nu+_sage_const_1 )**_sage_const_2  * mpmath.gamma(t+nu+_sage_const_1 )))

def integrand(nu, t):
    """Full integrand: R_ν(t) · [π/sin(πt)]² · [πcot(πt) - 1]"""
    r = R_nu(nu, t)
    s = mpmath.pi / mpmath.sinpi(t)
    c = mpmath.pi * mpmath.cotpi(t) - _sage_const_1 
    return r * s**_sage_const_2  * c

# ============================================================
# 2. Compute via contour integration
# ============================================================
# The contour should separate left poles (t ≤ 0) from right poles.
# For ν non-integer, right poles are at t = ν+1+k (k=0,1,...) and integer t = 1,2,...
# For ν = 17/22 ≈ 0.773, ν+1 = 39/22 ≈ 1.773
# So contour at Re(t) = 1/2 separates t=0,-1,... from t=1,2,...,ν+1,...

def J_nu_contour(nu, N_poles=None):
    """Compute J_ν via vertical contour integral at Re(t) = 1/2.

    (1/2πi) ∫_{1/2-i∞}^{1/2+i∞} F(t) dt
    """
    def f(y):
        t = mpmath.mpf('0.5') + _sage_const_1j  * y
        return integrand(nu, t) / (_sage_const_2  * mpmath.pi * _sage_const_1j )

    result = mpmath.quad(f, [-_sage_const_40 , _sage_const_40 ], error=True)
    return result

# ============================================================
# 3. Alternative: compute via residue sum
# ============================================================
def J_nu_residues(nu, max_poles=_sage_const_50 ):
    """Compute J_ν by summing residues at poles to the RIGHT of contour Re(t) = 1/2.

    Right poles come from:
    (a) Integer poles t = m (m = 1, 2, 3, ...) where R_ν and [π/sin πt]² interact
    (b) Gamma poles t = ν+1+k (k = 0, 1, 2, ...) from Γ(ν+1-t)³
    """
    total = mpmath.mpf(_sage_const_0 )

    # Type (a): integer poles t = m ≥ 1
    # Near t = m: R_ν(t) is regular (for m ≤ floor(ν+1)) or has poles
    # [π/sin πt]² ~ 1/(t-m)², πcot πt ~ 1/(t-m) + O(t-m)
    # So [πcot πt - 1] ~ 1/(t-m) - 1 + O(t-m)
    # Full: R_ν · 1/(t-m)² · [1/(t-m) - 1] = R_ν/(t-m)³ - R_ν/(t-m)²
    #
    # Residue = (1/2) R_ν''(m) - R_ν'(m) + correction from cot expansion
    #
    # This is complex. Let me just use numerical differentiation.

    for m in range(_sage_const_1 , max_poles + _sage_const_1 ):
        # Compute residue of integrand at t = m numerically
        # The integrand has a pole of order ≤ 3 at integer points
        # Residue = (1/2πi) ∮ F(t) dt around t=m
        eps = mpmath.mpf('1e-15')

        def circle_integrand(theta):
            t = m + eps * mpmath.exp(_sage_const_1j  * theta)
            return integrand(nu, t) * eps * _sage_const_1j  * mpmath.exp(_sage_const_1j  * theta) / (_sage_const_2  * mpmath.pi * _sage_const_1j )

        try:
            res = mpmath.quad(circle_integrand, [_sage_const_0 , _sage_const_2 *mpmath.pi])
            if abs(res) > mpmath.mpf('1e-80'):
                total += res
        except:
            pass

    # Type (b): Gamma poles t = ν+1+k
    for k in range(max_poles):
        pole = nu + _sage_const_1  + k
        if pole <= _sage_const_0p5 :  # skip if on wrong side of contour
            continue
        eps = mpmath.mpf('1e-15')

        def circle_integrand_b(theta):
            t = pole + eps * mpmath.exp(_sage_const_1j  * theta)
            return integrand(nu, t) * eps * _sage_const_1j  * mpmath.exp(_sage_const_1j  * theta) / (_sage_const_2  * mpmath.pi * _sage_const_1j )

        try:
            res = mpmath.quad(circle_integrand_b, [_sage_const_0 , _sage_const_2 *mpmath.pi])
            if abs(res) > mpmath.mpf('1e-80'):
                total += res
        except:
            pass

    return total

# ============================================================
# 4. First test: compute J_{17/22} and compare with e_0
# ============================================================
print("=== Testing shifted Barnes integral ===")
print("Computing J_{17/22} (ν = 17/22)...")

nu_shift = mpmath.mpf(_sage_const_17 ) / _sage_const_22 

# Try contour integral first
print("\n--- Contour integral method ---")
try:
    result = J_nu_contour(nu_shift)
    print("J_{17/22} = %s" % mpmath.nstr(result[_sage_const_0 ], _sage_const_30 ))
    print("Error estimate: %s" % mpmath.nstr(result[_sage_const_1 ], _sage_const_5 ))
except Exception as ex:
    print("Contour failed: %s" % ex)

# ============================================================
# 5. Compare with known values
# ============================================================
# Zudilin at integer ν: J_0 = 0 (trivially), J_1, J_2 are known
print("\n--- Zudilin at integer ν (sanity check) ---")
for n_int in [_sage_const_1 , _sage_const_2 , _sage_const_3 ]:
    try:
        result = J_nu_contour(mpmath.mpf(n_int))
        print("J_%d = %s" % (n_int, mpmath.nstr(result[_sage_const_0 ], _sage_const_20 )))
    except Exception as ex:
        print("J_%d failed: %s" % (n_int, ex))

# Compare with known a_n and p̃_n
a_list = []
for i in range(_sage_const_10 ):
    val = QQ(_sage_const_0 )
    for k in range(i+_sage_const_1 ):
        val += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
    a_list.append(val)

print("\na_n values:")
for i in range(_sage_const_5 ):
    print("  a_%d = %s" % (i, a_list[i]))

L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
print("\nζ(2)+ζ(3) = %s" % mpmath.nstr(L, _sage_const_30 ))

# Zudilin companion p̃_n
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
OS = OreAlgebra(Rn, 'Snn')
rec_a_op = guess(a_list[:_sage_const_10 ], OS, order=_sage_const_3 )
P_rec = [rec_a_op[j] for j in range(_sage_const_4 )]

p_zud = [QQ(_sage_const_0 )] * _sage_const_10 
p_zud[_sage_const_0 ] = QQ(_sage_const_0 )
p_zud[_sage_const_1 ] = QQ(_sage_const_20 )
p_zud[_sage_const_2 ] = QQ(_sage_const_7425 ) / QQ(_sage_const_16 )

for n_val in range(_sage_const_7 ):
    val = sum(P_rec[j](nn=n_val) * p_zud[n_val + j] for j in range(_sage_const_3 ))
    p_zud[n_val + _sage_const_3 ] = -val / P_rec[_sage_const_3 ](nn=n_val)

print("\nZudilin errors e^Z_n = p̃_n - L·a_n:")
for i in range(_sage_const_5 ):
    ez = mpmath.mpf(p_zud[i]) - L * mpmath.mpf(a_list[i])
    print("  e^Z_%d = %s" % (i, mpmath.nstr(ez, _sage_const_20 )))

# ============================================================
# 6. P2.7 errors for comparison
# ============================================================
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

N = _sage_const_10 
q = [QQ(_sage_const_0 )] * N
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

p = [QQ(_sage_const_0 )] * N
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n in range(_sage_const_2 , N-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ]
    p[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * p[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * p[n-_sage_const_2 ]

print("\nP2.7 errors e^P_n = p_n - L·q_n:")
e_p27 = []
for i in range(min(_sage_const_8 , N)):
    ep = mpmath.mpf(p[i].numerator()) / mpmath.mpf(p[i].denominator()) -          L * mpmath.mpf(q[i].numerator()) / mpmath.mpf(q[i].denominator())
    e_p27.append(ep)
    print("  e^P_%d = %s" % (i, mpmath.nstr(ep, _sage_const_20 )))

# ============================================================
# 7. Compute J_{n+17/22} for n = 0, 1, 2, 3 and compare with e^P_n
# ============================================================
print("\n=== Shifted Barnes integral J_{n+17/22} ===")
J_shifted = []
for n_val in range(_sage_const_4 ):
    nu = n_val + mpmath.mpf(_sage_const_17 )/_sage_const_22 
    try:
        result = J_nu_contour(nu)
        J_shifted.append(result[_sage_const_0 ])
        print("J_{%d+17/22} = %s (err est: %s)" % (n_val, mpmath.nstr(result[_sage_const_0 ], _sage_const_20 ), mpmath.nstr(result[_sage_const_1 ], _sage_const_5 )))
    except Exception as ex:
        print("J_{%d+17/22} failed: %s" % (n_val, ex))
        J_shifted.append(None)

# Compare ratios
print("\n=== Ratio J_{n+17/22} / e^P_n ===")
for i in range(min(len(J_shifted), len(e_p27))):
    if J_shifted[i] is not None and abs(e_p27[i]) > _sage_const_0 :
        ratio = J_shifted[i] / e_p27[i]
        print("n=%d: J/e = %s" % (i, mpmath.nstr(ratio, _sage_const_15 )))

