#!/usr/bin/env sage
"""
Shifted Barnes integral test — fixed version.
"""


# This file was *autogenerated* from the file scratchpad/shifted_barnes_test3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_150 = Integer(150); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_50 = Integer(50); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0); _sage_const_25 = Integer(25); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_12 = Integer(12); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_20 = Integer(20); _sage_const_17 = Integer(17); _sage_const_22 = Integer(22); _sage_const_1en100 = RealNumber('1e-100'); _sage_const_64 = Integer(64); _sage_const_11 = Integer(11); _sage_const_39 = Integer(39)
import mpmath
mpmath.mp.dps = _sage_const_150 

def cotpi_mp(t):
    return mpmath.cos(mpmath.pi * t) / mpmath.sin(mpmath.pi * t)

def R_nu(nu, t):
    return (mpmath.gamma(nu+_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(t) /
            (mpmath.gamma(_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(nu+_sage_const_1 )**_sage_const_2  * mpmath.gamma(t+nu+_sage_const_1 )))

def integrand(nu, t):
    r = R_nu(nu, t)
    s = mpmath.pi / mpmath.sin(mpmath.pi * t)
    c = mpmath.pi * cotpi_mp(t) - _sage_const_1 
    return r * s**_sage_const_2  * c

def J_nu_contour(nu):
    def f(y):
        t = mpmath.mpf('0.5') + _sage_const_1j  * y
        return integrand(nu, t) / (_sage_const_2  * mpmath.pi * _sage_const_1j )
    result = mpmath.quad(f, [-_sage_const_50 , _sage_const_50 ], error=True, maxdegree=_sage_const_8 )
    return result

L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )

# ============================================================
# a_n and its recurrence
# ============================================================
a_list = []
for i in range(_sage_const_30 ):
    val = QQ(_sage_const_0 )
    for k in range(i+_sage_const_1 ):
        val += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
    a_list.append(val)

from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
OS = OreAlgebra(Rn, 'Snn')

# Try guessing without specifying order
rec_a_op = guess(a_list[:_sage_const_25 ], OS)
print("rec_a: order %d" % rec_a_op.order())
P_rec = [rec_a_op[j] for j in range(rec_a_op.order()+_sage_const_1 )]
for j in range(len(P_rec)):
    print("  P_%d: degree %d, value: %s" % (j, P_rec[j].degree(), P_rec[j]))

# Zudilin companion
# For order-2 recurrence: p̃_0 = 0, p̃_1 = ??
# The Zudilin companion for ζ(2)+ζ(3) with a_n is given by:
# p̃_n = Σ_{k=0}^n C(n,k)²C(n+k,k)C(n+2k,k) · H_n(k)
# where H_n(k) involves harmonic numbers.
#
# Let me compute p̃_n directly from the sum formula:
# p̃_n = Σ_{k=1}^n C(n,k)²C(n+k,k)C(n+2k,k) · [3·H_{n+k} - 3·H_k + (some digamma terms)]
#
# Actually, from the literature (Zudilin, Krattenthaler-Rivoal):
# The companion is more complex. Let me just use the known e_n values.
#
# For the SANITY CHECK, I'll compute J_n at integer n and verify it gives
# e_n = p̃_n - L·a_n for the Zudilin case. But I don't have the explicit
# p̃_n formula handy. Let me skip the sanity check and go directly to
# the shifted case — I can verify by checking if the J values satisfy
# any recurrence.

# ============================================================
# P2.7 errors
# ============================================================
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

N_p27 = _sage_const_12 
q = [QQ(_sage_const_0 )] * N_p27
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

p = [QQ(_sage_const_0 )] * N_p27
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n in range(_sage_const_2 , N_p27-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ]
    p[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * p[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * p[n-_sage_const_2 ]

print("\nP2.7 errors:")
e_p27 = []
for i in range(min(_sage_const_8 , N_p27)):
    ep = mpmath.mpf(p[i].numerator()) / mpmath.mpf(p[i].denominator()) -          L * mpmath.mpf(q[i].numerator()) / mpmath.mpf(q[i].denominator())
    e_p27.append(ep)
    print("  e^P_%d = %s" % (i, mpmath.nstr(ep, _sage_const_25 )))

# ============================================================
# First: compute J_n for integer n = 0, 1, 2, 3 (Zudilin case)
# ============================================================
print("\n=== Zudilin J_n (integer ν) ===")
J_zud = []
for n_int in range(_sage_const_5 ):
    nu = mpmath.mpf(n_int)
    print("Computing J_%d..." % n_int)
    try:
        result = J_nu_contour(nu)
        j_val = result[_sage_const_0 ]
        J_zud.append(j_val)
        print("  J_%d = %s (err: %s)" % (n_int, mpmath.nstr(j_val, _sage_const_25 ), mpmath.nstr(result[_sage_const_1 ], _sage_const_5 )))
    except Exception as ex:
        print("  FAILED: %s" % ex)
        J_zud.append(None)

# Check J_n / a_n ratio to extract the Zudilin error
print("\nJ_n / a_n (should give e^Z_n / a_n pattern):")
for i in range(min(len(J_zud), _sage_const_5 )):
    if J_zud[i] is not None and a_list[i] != _sage_const_0 :
        ratio = J_zud[i] / mpmath.mpf(a_list[i])
        print("  n=%d: J/a = %s" % (i, mpmath.nstr(ratio, _sage_const_20 )))

# ============================================================
# Shifted Barnes: J_{n+17/22}
# ============================================================
print("\n=== Shifted Barnes J_{n+17/22} ===")
J_shifted = []
for n_val in range(_sage_const_6 ):
    nu = n_val + mpmath.mpf(_sage_const_17 )/_sage_const_22 
    print("Computing J_{%d+17/22} (ν = %.6f)..." % (n_val, float(nu)))
    try:
        result = J_nu_contour(nu)
        j_val = result[_sage_const_0 ]
        J_shifted.append(j_val)
        print("  J = %s (err: %s)" % (mpmath.nstr(j_val, _sage_const_25 ), mpmath.nstr(result[_sage_const_1 ], _sage_const_5 )))
    except Exception as ex:
        print("  FAILED: %s" % ex)
        J_shifted.append(None)

# Compare with P2.7 errors
print("\n=== Ratio J_{n+17/22} / e^P_n ===")
for i in range(min(len(J_shifted), len(e_p27))):
    if J_shifted[i] is not None and abs(e_p27[i]) > _sage_const_1en100 :
        ratio = J_shifted[i] / e_p27[i]
        print("n=%d: %s" % (i, mpmath.nstr(ratio, _sage_const_20 )))

print("\n=== J_{n+17/22} / (64^{-n} · e^P_n) ===")
for i in range(min(len(J_shifted), len(e_p27))):
    if J_shifted[i] is not None and abs(e_p27[i]) > _sage_const_1en100 :
        ratio = J_shifted[i] / (mpmath.power(_sage_const_64 , -i) * e_p27[i])
        print("n=%d: %s" % (i, mpmath.nstr(ratio, _sage_const_20 )))

# Also try other fractional shifts
print("\n=== Try other shifts ===")
for shift_num in [_sage_const_5 , _sage_const_11 , _sage_const_17 , _sage_const_22 , _sage_const_39 ]:
    shift = mpmath.mpf(shift_num) / _sage_const_22 
    nu = _sage_const_0  + shift
    try:
        result = J_nu_contour(nu)
        j_val = result[_sage_const_0 ]
        print("J_{%d/22} = %s" % (shift_num, mpmath.nstr(j_val, _sage_const_20 )))
    except Exception as ex:
        print("J_{%d/22} failed: %s" % (shift_num, ex))

