"""
Test whether the type-II Hermite-Padé polynomials for measures
  mu_2 = -log(t) dt  (moments 1/(k+1)^2)
  mu_3 = (1/2) log^2(t) dt  (moments 1/(k+1)^3)
on (0,1) with step-line indices give the P2.7 recurrence.

The type-II polynomial Q_n(t) of degree 2n on the step line
(n,n) satisfies:
  int_0^1 t^j Q_n(t) (-log t) dt = 0  for j = 0,...,n-1
  int_0^1 t^j Q_n(t) (1/2 log^2 t) dt = 0  for j = 0,...,n-1

Equivalently, with moments:
  m2(k) = 1/(k+1)^2,  m3(k) = 1/(k+1)^3
The orthogonality conditions for monic Q_n(t) = t^(2n) + ... are:
  sum_{l=0}^{2n} q_l * m2(j+l) = 0  for j = 0,...,n-1
  sum_{l=0}^{2n} q_l * m3(j+l) = 0  for j = 0,...,n-1
"""


# This file was *autogenerated* from the file scratchpad/type2_mop.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_1024 = Integer(1024); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399)
from sage.all import *

Q = QQ

def m2(k):
    return Q(_sage_const_1 ) / Q(k+_sage_const_1 )**_sage_const_2 

def m3(k):
    return Q(_sage_const_1 ) / Q(k+_sage_const_1 )**_sage_const_3 

def type2_mop(n):
    """Compute the monic type-II polynomial Q_n(t) of degree 2n."""
    if n == _sage_const_0 :
        return [Q(_sage_const_1 )]  # Q_0 = 1

    deg = _sage_const_2 *n
    # Monic: coefficient of t^{2n} is 1
    # Unknowns: q_0, q_1, ..., q_{2n-1} (coefficients of t^0,...,t^{2n-1})
    # q_{2n} = 1

    num_unknowns = deg  # q_0, ..., q_{2n-1}
    num_equations = _sage_const_2 *n  # n from mu_2, n from mu_3

    # Build the linear system
    rows = []
    rhs = []

    # Orthogonality for mu_2
    for j in range(n):
        row = [m2(j+l) for l in range(deg)]
        rows.append(row)
        rhs.append(-m2(j + deg))  # from the monic term

    # Orthogonality for mu_3
    for j in range(n):
        row = [m3(j+l) for l in range(deg)]
        rows.append(row)
        rhs.append(-m3(j + deg))

    M = matrix(Q, rows)
    b = vector(Q, rhs)

    try:
        x = M.solve_right(b)
    except ValueError:
        print(f"  n={n}: system is singular!")
        return None

    coeffs = list(x) + [Q(_sage_const_1 )]  # q_0, ..., q_{2n-1}, 1
    return coeffs

# Compute type-II MOPs for small n
print("Computing type-II MOPs for n=0,...,6")
Rt = PolynomialRing(Q, 't')
t_var = Rt.gen()

for n in range(_sage_const_7 ):
    coeffs = type2_mop(n)
    if coeffs is None:
        continue
    Q_poly = sum(c * t_var**i for i, c in enumerate(coeffs))
    val_at_1 = Q_poly(_sage_const_1 )
    print(f"n={n}: Q_n(1) = {val_at_1}")
    if n <= _sage_const_3 :
        print(f"  Q_n(t) = {Q_poly}")

# P2.7 initial values for q_n
q_p27 = [
    Q(-_sage_const_215040420000 ),
    Q(-_sage_const_167282265043404 ) / Q(_sage_const_905 ),
    Q(-_sage_const_964185327658080 ) / Q(_sage_const_6071 ),
]

print(f"\nP2.7 initial values:")
print(f"  q_0 = {q_p27[_sage_const_0 ]}")
print(f"  q_1 = {q_p27[_sage_const_1 ]}")
print(f"  q_2 = {q_p27[_sage_const_2 ]}")

# Check if Q_n(1) matches P2.7 q_n (up to a common scaling)
print(f"\nChecking if Q_n(1) is proportional to P2.7 q_n:")
Q0_at_1 = type2_mop(_sage_const_0 )
Q1_at_1 = sum(c for c in type2_mop(_sage_const_1 ))
Q2_at_1 = sum(c for c in type2_mop(_sage_const_2 ))

vals = [Q0_at_1, Q1_at_1, Q2_at_1]
if isinstance(vals[_sage_const_0 ], list):
    vals = [sum(c for c in v) for v in [type2_mop(i) for i in range(_sage_const_3 )]]

print(f"  MOP Q_0(1) = {vals[_sage_const_0 ]}")
print(f"  MOP Q_1(1) = {vals[_sage_const_1 ]}")
print(f"  MOP Q_2(1) = {vals[_sage_const_2 ]}")

if vals[_sage_const_0 ] != _sage_const_0  and q_p27[_sage_const_0 ] != _sage_const_0 :
    ratio_0 = q_p27[_sage_const_0 ] / vals[_sage_const_0 ]
    print(f"\n  ratio q_0/Q_0(1) = {ratio_0}")
    if vals[_sage_const_1 ] != _sage_const_0 :
        ratio_1 = q_p27[_sage_const_1 ] / vals[_sage_const_1 ]
        print(f"  ratio q_1/Q_1(1) = {ratio_1}")
        if ratio_0 == ratio_1:
            print("  *** RATIOS MATCH! Same proportionality constant. ***")
        else:
            print(f"  Ratios differ: {float(ratio_0):.6e} vs {float(ratio_1):.6e}")

# Also try the alternating step line: (1,0), (1,1), (2,1), (2,2), ...
print("\n\n=== Alternating step line ===")
def type2_mop_step(r, s):
    """Type-II MOP for multi-index (r, s), degree r+s."""
    deg = r + s
    if deg == _sage_const_0 :
        return [Q(_sage_const_1 )]

    num_unknowns = deg
    rows = []
    rhs = []

    for j in range(r):
        row = [m2(j+l) for l in range(deg)]
        rows.append(row)
        rhs.append(-m2(j + deg))

    for j in range(s):
        row = [m3(j+l) for l in range(deg)]
        rows.append(row)
        rhs.append(-m3(j + deg))

    M = matrix(Q, rows)
    b = vector(Q, rhs)

    try:
        x = M.solve_right(b)
    except ValueError:
        print(f"  (r,s)=({r},{s}): system is singular!")
        return None

    return list(x) + [Q(_sage_const_1 )]

# Step line: (0,0), (1,0), (1,1), (2,1), (2,2), (3,2), (3,3), ...
step_indices = [(_sage_const_0 ,_sage_const_0 ), (_sage_const_1 ,_sage_const_0 ), (_sage_const_1 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_1 ), (_sage_const_2 ,_sage_const_2 ), (_sage_const_3 ,_sage_const_2 ), (_sage_const_3 ,_sage_const_3 ),
                (_sage_const_4 ,_sage_const_3 ), (_sage_const_4 ,_sage_const_4 ), (_sage_const_5 ,_sage_const_4 ), (_sage_const_5 ,_sage_const_5 ), (_sage_const_6 ,_sage_const_5 ), (_sage_const_6 ,_sage_const_6 )]

print("Step line evaluations:")
step_vals = []
for r, s in step_indices:
    coeffs = type2_mop_step(r, s)
    if coeffs is None:
        step_vals.append(None)
        continue
    val = sum(coeffs)  # Q(1)
    step_vals.append(val)
    print(f"  ({r},{s}): Q(1) = {val}")

# Check 4-term recurrence on step line values
print("\n=== Checking for 4-term recurrence on diagonal Q_n(1) ===")
diag_vals = []
for n in range(_sage_const_7 ):
    coeffs = type2_mop(n)
    if coeffs is None:
        break
    diag_vals.append(sum(coeffs))

print("Diagonal Q_n(1):", diag_vals)

# Try: a(n)*v(n+1) + b(n)*v(n) + c(n)*v(n-1) + d(n)*v(n-2) = 0
# for n = 2, 3, 4 with polynomial a, b, c, d
if len(diag_vals) >= _sage_const_6 :
    # Just check the recurrence residual with P2.7 coefficients
    def AA(n):
        return Q(_sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 
                *(_sage_const_946 *n**_sage_const_2  + _sage_const_6407 *n + _sage_const_10860 ))
    def BB(n):
        return Q(_sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 
                *(_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  + _sage_const_12145238 *n**_sage_const_4 
                  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2 
                  + _sage_const_102256019 *n + _sage_const_46709052 ))
    def CC(n):
        return Q(_sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 
                *(_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  + _sage_const_351019 *n**_sage_const_3 
                  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 ))
    def DD(n):
        return Q((n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 
                *(_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 ))

    print("\nChecking P2.7 recurrence on Q_n(1):")
    v = diag_vals
    for n in range(_sage_const_2 , min(len(v)-_sage_const_1 , _sage_const_6 )):
        # Monic: v[n+1] = B(n)/A(n)*v[n] - C(n-1)/A(n-1)*v[n-1] + D(n-2)/A(n-2)*v[n-2]
        predicted = BB(n)/AA(n)*v[n] - CC(n-_sage_const_1 )/AA(n-_sage_const_1 )*v[n-_sage_const_1 ] + DD(n-_sage_const_2 )/AA(n-_sage_const_2 )*v[n-_sage_const_2 ]
        residual = v[n+_sage_const_1 ] - predicted
        if residual == _sage_const_0 :
            print(f"  n={n}: P2.7 recurrence HOLDS")
        else:
            print(f"  n={n}: residual = {float(residual):.6e} (FAILS)")

print("\nDone.")

