

# This file was *autogenerated* from the file campaign3_scripts/sage_genus.sage
from sage.all_cmdline import *   # import sage library

_sage_const_34 = Integer(34); _sage_const_3 = Integer(3); _sage_const_51 = Integer(51); _sage_const_2 = Integer(2); _sage_const_27 = Integer(27); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4)
R = QQ['r, s']; (r, s,) = R._first_ngens(2)
def Ppoly(u): return _sage_const_34 *u**_sage_const_3  + _sage_const_51 *u**_sage_const_2  + _sage_const_27 *u + _sage_const_5 
def Npoly(h, v):
    if h == _sage_const_1 : return R(_sage_const_1 )
    N1, N2 = R(_sage_const_1 ), Ppoly(v+_sage_const_1 )
    if h == _sage_const_2 : return N2
    a, b = N1, N2
    for m in range(_sage_const_2 , h):
        a, b = b, Ppoly(v+m)*b - (v+m)**_sage_const_6 *a
    return b
def Dpoly(h, v): return prod([(v+j)**_sage_const_3  for j in range(_sage_const_1 , h+_sage_const_1 )])

for (h,k) in [(_sage_const_2 ,_sage_const_3 ),(_sage_const_2 ,_sage_const_4 ),(_sage_const_3 ,_sage_const_4 ),(_sage_const_2 ,_sage_const_5 )]:
    F = Npoly(h,r)*Dpoly(k,s) - Npoly(k,s)*Dpoly(h,r)
    A2 = AffineSpace(QQ,_sage_const_2 , names=('x', 'y',)); (x, y,) = A2._first_ngens(2)
    Faff = F.subs(r=x, s=y)
    C = Curve(Faff)
    try:
        g = C.geometric_genus()
    except Exception as e:
        g = f"ERR {e}"
    # geometric irreducibility
    Fbar = F.change_ring(QQbar)
    nfac = "?"
    print(f"X_{h},{k}: bidegree=({F.degree(r)},{F.degree(s)}) geometric_genus={g}")

