/-
  Ramanujan Challenge Problem 2.7: a four-term recurrence for ζ(2) + ζ(3).

  The challenge gives the rational recurrence

    u_{n+1} = (B_n / A_n) u_n
      - (C_{n-1} / A_{n-1}) u_{n-1}
      + (D_{n-2} / A_{n-2}) u_{n-2},                 n ≥ 2,

  together with three initial values for each of p and q.

  This file formalizes those coefficients, the two uniquely determined
  rational sequences, and the exact rational gauge from Zudilin's source
  recurrence.  The gauge identities, initial-value matching, coefficient
  limits, and analytic transfer are kernel-checked.  The final theorem exposes
  only Zudilin's source asymptotics as hypotheses; the desired challenge limit
  is not assumed.
-/
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.Polynomial.Basic
import Mathlib.Tactic.ComputeDegree

open Filter Topology
open scoped Polynomial

noncomputable section

namespace RamanujanChallenge.P27

/-! ## The challenge coefficients -/

def A (n : ℕ) : ℚ :=
  1024 * (2 * n + 5) ^ 4 * (2 * n + 7) ^ 3 * (2 * n + 9) ^ 3
    * (946 * n ^ 2 + 6407 * n + 10860)

def B (n : ℕ) : ℚ :=
  128 * (2 * n + 7) ^ 3 * (2 * n + 9) ^ 3
    * (104060 * n ^ 6 + 1745370 * n ^ 5 + 12145238 * n ^ 4
      + 44886481 * n ^ 3 + 92943995 * n ^ 2 + 102256019 * n + 46709052)

def C (n : ℕ) : ℚ :=
  16 * (n + 3) ^ 4 * (2 * n + 9) ^ 3
    * (3784 * n ^ 5 + 57792 * n ^ 4 + 351019 * n ^ 3
      + 1059230 * n ^ 2 + 1587211 * n + 944620)

def D (n : ℕ) : ℚ :=
  (n + 3) ^ 4 * (n + 4) ^ 6 * (946 * n ^ 2 + 4515 * n + 5399)

/-- The Problem 2.7 recurrence, reindexed by `n = k + 2` so no truncated
subtraction occurs in its formal statement. -/
def SatisfiesRec (u : ℕ → ℚ) : Prop :=
  ∀ k : ℕ,
    u (k + 3) =
      B (k + 2) / A (k + 2) * u (k + 2)
        - C (k + 1) / A (k + 1) * u (k + 1)
        + D k / A k * u k

/-! ## The two challenge sequences -/

/-- The unique sequence generated by the challenge recurrence from three
initial values. -/
def solution (u₀ u₁ u₂ : ℚ) : ℕ → ℚ
  | 0 => u₀
  | 1 => u₁
  | 2 => u₂
  | n + 3 =>
      B (n + 2) / A (n + 2) * solution u₀ u₁ u₂ (n + 2)
        - C (n + 1) / A (n + 1) * solution u₀ u₁ u₂ (n + 1)
        + D n / A n * solution u₀ u₁ u₂ n

def challengeP : ℕ → ℚ :=
  solution (-612218384750) (-9525021973931919 / 18100)
    (-29561828382772029 / 65380)

def challengeQ : ℕ → ℚ :=
  solution (-215040420000) (-167282265043404 / 905)
    (-964185327658080 / 6071)

theorem solution_satisfiesRec (u₀ u₁ u₂ : ℚ) :
    SatisfiesRec (solution u₀ u₁ u₂) :=
  fun _ => rfl

theorem challengeP_rec : SatisfiesRec challengeP :=
  solution_satisfiesRec _ _ _

theorem challengeQ_rec : SatisfiesRec challengeQ :=
  solution_satisfiesRec _ _ _

/-! ## Initial values and a forward recurrence check -/

theorem challengeP_zero : challengeP 0 = -612218384750 := rfl
theorem challengeP_one : challengeP 1 = -9525021973931919 / 18100 := rfl
theorem challengeP_two : challengeP 2 = -29561828382772029 / 65380 := rfl

theorem challengeQ_zero : challengeQ 0 = -215040420000 := rfl
theorem challengeQ_one : challengeQ 1 = -167282265043404 / 905 := rfl
theorem challengeQ_two : challengeQ 2 = -964185327658080 / 6071 := rfl

theorem challengeP_three :
    challengeP 3 = -96756337931563198337 / 249098976 := by
  norm_num [challengeP, solution, A, B, C, D]

theorem challengeQ_three :
    challengeQ 3 = -5619291355848500 / 41187 := by
  norm_num [challengeQ, solution, A, B, C, D]

/-! ## Uniqueness

This prevents the recurrence formalization from denoting an unrelated pair of
sequences: any rational sequences with the challenge's initial values and
recurrence are definitionally forced to be `challengeP` and `challengeQ`.
-/

theorem eq_of_satisfiesRec {u v : ℕ → ℚ}
    (hu : SatisfiesRec u) (hv : SatisfiesRec v)
    (h₀ : u 0 = v 0) (h₁ : u 1 = v 1) (h₂ : u 2 = v 2) :
    u = v := by
  funext m
  induction m using Nat.strong_induction_on with
  | h m ih =>
      match m with
      | 0 => exact h₀
      | 1 => exact h₁
      | 2 => exact h₂
      | k + 3 =>
        rw [hu k, hv k, ih (k + 2) (by omega), ih (k + 1) (by omega),
          ih k (by omega)]

theorem challengeP_eq_of_initial_and_rec {p : ℕ → ℚ}
    (hp : SatisfiesRec p)
    (h₀ : p 0 = -612218384750)
    (h₁ : p 1 = -9525021973931919 / 18100)
    (h₂ : p 2 = -29561828382772029 / 65380) :
    p = challengeP :=
  eq_of_satisfiesRec hp challengeP_rec h₀ h₁ h₂

theorem challengeQ_eq_of_initial_and_rec {q : ℕ → ℚ}
    (hq : SatisfiesRec q)
    (h₀ : q 0 = -215040420000)
    (h₁ : q 1 = -167282265043404 / 905)
    (h₂ : q 2 = -964185327658080 / 6071) :
    q = challengeQ :=
  eq_of_satisfiesRec hq challengeQ_rec h₀ h₁ h₂

/-- Faithful kernel-checked characterization of both sequences appearing in
Problem 2.7.  In particular, the witnesses are not arbitrary constant
sequences: they have the challenge's six initial values and satisfy its
four-term recurrence at every index. -/
theorem problem27_challenge_sequences :
    SatisfiesRec challengeP ∧ SatisfiesRec challengeQ
      ∧ challengeP 0 = -612218384750
      ∧ challengeP 1 = -9525021973931919 / 18100
      ∧ challengeP 2 = -29561828382772029 / 65380
      ∧ challengeQ 0 = -215040420000
      ∧ challengeQ 1 = -167282265043404 / 905
      ∧ challengeQ 2 = -964185327658080 / 6071 := by
  exact ⟨challengeP_rec, challengeQ_rec, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-! ## Zudilin's source recurrence

The source is Theorem 2 of W. Zudilin, *Approximations to -, di- and
tri-logarithms* (arXiv:math/0409023).  Its denominator `zudilinA` is the
coefficient of `v (k+3)` after putting the paper's index `n = k+2`.
-/

def zudilinQ (n : ℕ) : ℚ := 946 * n ^ 2 - 731 * n + 153

def zudilinM (n : ℕ) : ℚ :=
  104060 * n ^ 6 + 127710 * n ^ 5 + 12788 * n ^ 4 - 34525 * n ^ 3
    - 8482 * n ^ 2 + 3298 * n + 1071

def zudilinN (n : ℕ) : ℚ :=
  3784 * n ^ 5 - 1032 * n ^ 4 - 1925 * n ^ 3 + 853 * n ^ 2
    + 328 * n - 184

def zudilinR (n : ℕ) : ℚ := 946 * n ^ 2 + 1161 * n + 368

def zudilinA (n : ℕ) : ℚ :=
  zudilinQ n * (2 * n + 1) * (n + 1) ^ 3

def ZudilinSatisfiesRec (v : ℕ → ℚ) : Prop :=
  ∀ k : ℕ,
    v (k + 3) =
      zudilinM (k + 2) / zudilinA (k + 2) * v (k + 2)
        - (k + 2) * zudilinN (k + 2) / zudilinA (k + 2) * v (k + 1)
        + zudilinR (k + 2) * (k + 2) * (k + 1) ^ 3
            / (2 * zudilinA (k + 2)) * v k

def zudilinSolution (v₀ v₁ v₂ : ℚ) : ℕ → ℚ
  | 0 => v₀
  | 1 => v₁
  | 2 => v₂
  | k + 3 =>
      zudilinM (k + 2) / zudilinA (k + 2) * zudilinSolution v₀ v₁ v₂ (k + 2)
        - (k + 2) * zudilinN (k + 2) / zudilinA (k + 2)
            * zudilinSolution v₀ v₁ v₂ (k + 1)
        + zudilinR (k + 2) * (k + 2) * (k + 1) ^ 3
            / (2 * zudilinA (k + 2)) * zudilinSolution v₀ v₁ v₂ k

def zudilinB : ℕ → ℚ := zudilinSolution 1 7 163
def zudilinB₂ : ℕ → ℚ := zudilinSolution 0 (23 / 2) (2145 / 8)
def zudilinB₃ : ℕ → ℚ := zudilinSolution 0 (17 / 2) (3135 / 16)
def zudilinM23 (n : ℕ) : ℚ := zudilinB₂ n + zudilinB₃ n

theorem zudilinSolution_rec (v₀ v₁ v₂ : ℚ) :
    ZudilinSatisfiesRec (zudilinSolution v₀ v₁ v₂) :=
  fun _ => rfl

theorem zudilinB_rec : ZudilinSatisfiesRec zudilinB :=
  zudilinSolution_rec _ _ _

theorem zudilinB₂_rec : ZudilinSatisfiesRec zudilinB₂ :=
  zudilinSolution_rec _ _ _

theorem zudilinB₃_rec : ZudilinSatisfiesRec zudilinB₃ :=
  zudilinSolution_rec _ _ _

theorem ZudilinSatisfiesRec.add {v w : ℕ → ℚ}
    (hv : ZudilinSatisfiesRec v) (hw : ZudilinSatisfiesRec w) :
    ZudilinSatisfiesRec (fun n => v n + w n) := by
  intro k
  simp only []
  linear_combination hv k + hw k

theorem zudilinM23_rec : ZudilinSatisfiesRec zudilinM23 :=
  zudilinB₂_rec.add zudilinB₃_rec

/-! ## The exact scalar gauge

Only the third row of the `3 × 3` rational gauge is needed to recover the
scalar challenge sequences.  We divide the accompanying proof's gauge by the harmless
nonzero constant `1755433451520 / 223729`; this turns the three leading
coefficients into `-13281/64`, `47/8`, and `-1`.
-/

def gaugeQ71 (n : ℕ) : ℚ :=
  n ^ 2 + (71 / 22) * n + 225 / 86

def gaugeQ105 (n : ℕ) : ℚ :=
  n ^ 2 + (105 / 22) * n + 5399 / 946

def gaugeQ115 (n : ℕ) : ℚ :=
  n ^ 2 + (115 / 22) * n + 3237 / 473

def gaugeQ149 (n : ℕ) : ℚ :=
  n ^ 2 + (149 / 22) * n + 5430 / 473

def gaugeQ193 (n : ℕ) : ℚ :=
  n ^ 2 + (193 / 22) * n + 18213 / 946

def gaugeQ237 (n : ℕ) : ℚ :=
  n ^ 2 + (237 / 22) * n + 13729 / 473

def gaugeDen (n : ℕ) : ℚ :=
  (n + 3) ^ 3 * gaugeQ71 n * gaugeQ105 n

def gaugeCommon (n : ℕ) : ℚ := (n + 7 / 2) * (n + 5 / 2) ^ 2

def gaugeP20 (n : ℕ) : ℚ :=
  n ^ 4 + 8 * n ^ 3 + (1260571 / 53124) * n ^ 2
    + (410587 / 13281) * n + 793741 / 53124

def gaugeP21 (n : ℕ) : ℚ :=
  n ^ 2 + 3 * n + 110 / 47

def gaugeR20 (n : ℕ) : ℚ :=
  (-13281 / 64) * gaugeCommon n * gaugeP20 n / gaugeDen n

def gaugeR21 (n : ℕ) : ℚ :=
  (47 / 8) * gaugeCommon n * (n + 3 / 2) * (n + 2)
    * gaugeP21 n / gaugeDen n

def gaugeR22 (n : ℕ) : ℚ :=
  -gaugeCommon n * (n + 2) * (n + 1) ^ 3 / gaugeDen n

def twistRatio (n : ℕ) : ℚ :=
  (n + 4) ^ 3 / ((n + 5 / 2) * (n + 7 / 2) * (n + 9 / 2))

def twist : ℕ → ℚ
  | 0 => 1
  | n + 1 => twistRatio n * twist n

theorem twist_succ (n : ℕ) : twist (n + 1) = twistRatio n * twist n := rfl

/-- The third row of the scaled rational gauge, with its common
hypergeometric twist. -/
def gaugeScalar (v : ℕ → ℚ) (n : ℕ) : ℚ :=
  twist n * (gaugeR20 n * v (n + 2) + gaugeR21 n * v (n + 1) + gaugeR22 n * v n)

/-- Recurrence for `x_n = 64^n u_n`. -/
def ScaledSatisfiesRec (x : ℕ → ℚ) : Prop :=
  ∀ k : ℕ,
    x (k + 3) =
      64 * B (k + 2) / A (k + 2) * x (k + 2)
        - 64 ^ 2 * C (k + 1) / A (k + 1) * x (k + 1)
        + 64 ^ 3 * D k / A k * x k

theorem A_pos (n : ℕ) : 0 < A n := by
  simp only [A]
  positivity

theorem gaugeQ71_pos (n : ℕ) : 0 < gaugeQ71 n := by
  simp only [gaugeQ71]
  positivity

theorem gaugeQ105_pos (n : ℕ) : 0 < gaugeQ105 n := by
  simp only [gaugeQ105]
  positivity

theorem gaugeQ115_pos (n : ℕ) : 0 < gaugeQ115 n := by
  simp only [gaugeQ115]
  positivity

theorem gaugeQ149_pos (n : ℕ) : 0 < gaugeQ149 n := by
  simp only [gaugeQ149]
  positivity

theorem gaugeQ193_pos (n : ℕ) : 0 < gaugeQ193 n := by
  simp only [gaugeQ193]
  positivity

theorem gaugeQ237_pos (n : ℕ) : 0 < gaugeQ237 n := by
  simp only [gaugeQ237]
  positivity

theorem gaugeDen_pos (n : ℕ) : 0 < gaugeDen n := by
  simp only [gaugeDen]
  exact mul_pos (mul_pos (by positivity) (gaugeQ71_pos n)) (gaugeQ105_pos n)

theorem gaugeR21_nonneg (n : ℕ) : 0 ≤ gaugeR21 n := by
  rw [gaugeR21]
  apply div_nonneg
  · simp only [gaugeCommon, gaugeP21]
    positivity
  · exact le_of_lt (gaugeDen_pos n)

theorem gaugeR22_nonpos (n : ℕ) : gaugeR22 n ≤ 0 := by
  rw [gaugeR22]
  apply div_nonpos_of_nonpos_of_nonneg
  · exact mul_nonpos_of_nonpos_of_nonneg
      (mul_nonpos_of_nonpos_of_nonneg
        (neg_nonpos.mpr (by simp only [gaugeCommon]; positivity))
        (by positivity))
      (by positivity)
  · exact le_of_lt (gaugeDen_pos n)

theorem zudilinQ_pos (n : ℕ) : 0 < zudilinQ (n + 2) := by
  simp only [zudilinQ]
  push_cast
  nlinarith [sq_nonneg (n : ℚ)]

theorem zudilinA_pos (n : ℕ) : 0 < zudilinA (n + 2) := by
  simp only [zudilinA]
  exact mul_pos (mul_pos (zudilinQ_pos n) (by positivity)) (by positivity)

def zAlpha (n : ℕ) : ℚ :=
  zudilinM (n + 2) / zudilinA (n + 2)

def zBeta (n : ℕ) : ℚ :=
  -(n + 2) * zudilinN (n + 2) / zudilinA (n + 2)

def zGamma (n : ℕ) : ℚ :=
  zudilinR (n + 2) * (n + 2) * (n + 1) ^ 3
    / (2 * zudilinA (n + 2))

theorem zudilinN_nonneg (n : ℕ) : 0 ≤ zudilinN (n + 2) := by
  simp only [zudilinN]
  push_cast
  ring_nf
  positivity

theorem zudilinR_nonneg (n : ℕ) : 0 ≤ zudilinR (n + 2) := by
  simp only [zudilinR]
  positivity

theorem zBeta_nonpos (n : ℕ) : zBeta n ≤ 0 := by
  simp only [zBeta]
  exact div_nonpos_of_nonpos_of_nonneg
    (mul_nonpos_of_nonpos_of_nonneg
      (neg_nonpos.mpr (by positivity)) (zudilinN_nonneg n))
    (le_of_lt (zudilinA_pos n))

theorem zGamma_nonneg (n : ℕ) : 0 ≤ zGamma n := by
  simp only [zGamma]
  exact div_nonneg
    (mul_nonneg
      (mul_nonneg (zudilinR_nonneg n) (by positivity)) (by positivity))
    (mul_nonneg (by norm_num) (le_of_lt (zudilinA_pos n)))

theorem one_le_zAlpha_add_zBeta (n : ℕ) :
    1 ≤ zAlpha n + zBeta n := by
  rw [zAlpha, zBeta]
  rw [← add_div]
  apply (le_div_iff₀ (zudilinA_pos n)).mpr
  simp only [one_mul]
  simp only [zudilinM, zudilinN, zudilinA, zudilinQ]
  push_cast
  ring_nf
  have hn : (0 : ℚ) ≤ n := by positivity
  nlinarith [pow_nonneg hn 2, pow_nonneg hn 3, pow_nonneg hn 4,
    pow_nonneg hn 5, pow_nonneg hn 6]

theorem thirty_one_le_zAlpha_add_zBeta (n : ℕ) :
    31 ≤ zAlpha n + zBeta n := by
  rw [zAlpha, zBeta]
  rw [← add_div]
  apply (le_div_iff₀ (zudilinA_pos n)).mpr
  simp only [zudilinM, zudilinN, zudilinA, zudilinQ]
  push_cast
  ring_nf
  have hn : (0 : ℚ) ≤ n := by positivity
  nlinarith [pow_nonneg hn 2, pow_nonneg hn 3, pow_nonneg hn 4,
    pow_nonneg hn 5, pow_nonneg hn 6]

def targetBPoly (n : ℕ) : ℚ :=
  104060 * (n + 2) ^ 6 + 1745370 * (n + 2) ^ 5
    + 12145238 * (n + 2) ^ 4 + 44886481 * (n + 2) ^ 3
    + 92943995 * (n + 2) ^ 2 + 102256019 * (n + 2) + 46709052

def targetCPoly (n : ℕ) : ℚ :=
  3784 * (n + 1) ^ 5 + 57792 * (n + 1) ^ 4
    + 351019 * (n + 1) ^ 3 + 1059230 * (n + 1) ^ 2
    + 1587211 * (n + 1) + 944620

def pAlpha (n : ℕ) : ℚ :=
  (4 / 473) * targetBPoly n / ((2 * n + 9) ^ 4 * gaugeQ237 n)

def pBeta (n : ℕ) : ℚ :=
  (-32 / 473) * (n + 4) ^ 4 * targetCPoly n
    / ((2 * n + 7) ^ 4 * (2 * n + 9) ^ 3 * gaugeQ193 n)

def pGamma (n : ℕ) : ℚ :=
  256 * (n + 3) ^ 4 * (n + 4) ^ 6 * gaugeQ105 n
    / ((2 * n + 5) ^ 4 * (2 * n + 7) ^ 3 * (2 * n + 9) ^ 3
      * gaugeQ149 n)

def gaugeDen1 (n : ℕ) : ℚ :=
  (n + 3) ^ 3 * (n + 5 / 2) ^ 2
    * gaugeQ71 n * gaugeQ149 n

def gaugeP10 (n : ℕ) : ℚ :=
  n ^ 8 + 20 * n ^ 7 + (506565441 / 2920316) * n ^ 6
    + (2487928615 / 2920316) * n ^ 5
    + (15132298277 / 5840632) * n ^ 4
    + (3646435190 / 730079) * n ^ 3
    + (4350278543 / 730079) * n ^ 2
    + (23486500845 / 5840632) * n + 1715788917 / 1460158

def gaugeP11 (n : ℕ) : ℚ :=
  n ^ 7 + (33 / 2) * n ^ 6 + (12154175 / 105992) * n ^ 5
    + (92211659 / 211984) * n ^ 4
    + (206227733 / 211984) * n ^ 3
    + (68021143 / 52996) * n ^ 2
    + (49078551 / 52996) * n + 3740715 / 13249

def gaugeP12 (n : ℕ) : ℚ :=
  n ^ 4 + 12 * n ^ 3 + (2854291 / 53124) * n ^ 2
    + (941827 / 8854) * n + 347898 / 4427

def gaugeR10 (n : ℕ) : ℚ :=
  (-730079 / 64) * (n + 7 / 2) * gaugeP10 n / gaugeDen1 n

def gaugeR11 (n : ℕ) : ℚ :=
  (13249 / 32) * (n + 2) * (n + 7 / 2)
    * gaugeP11 n / gaugeDen1 n

def gaugeR12 (n : ℕ) : ℚ :=
  (-13281 / 256) * (n + 2) * (n + 7 / 2) * (n + 1) ^ 3
    * gaugeP12 n / gaugeDen1 n

def gaugeDen0 (n : ℕ) : ℚ :=
  (n + 3) ^ 3 * (n + 7 / 2) ^ 3 * (n + 5 / 2) ^ 2
    * gaugeQ71 n * gaugeQ193 n

def gaugeP00 (n : ℕ) : ℚ :=
  n ^ 12 + 36 * n ^ 11 + (47286344281 / 80255694) * n ^ 10
    + (77525447285 / 13375949) * n ^ 9
    + (24498736405883 / 642045552) * n ^ 8
    + (4737245262731 / 26751898) * n ^ 7
    + (127095949568429 / 214015184) * n ^ 6
    + (155135750901741 / 107007592) * n ^ 5
    + (820625243073257 / 321022776) * n ^ 4
    + (42456046545919 / 13375949) * n ^ 3
    + (845465544836747 / 321022776) * n ^ 2
    + (70132597254287 / 53503796) * n + 7914900905991 / 26751898

def gaugeP01 (n : ℕ) : ℚ :=
  n ^ 11 + (65 / 2) * n ^ 10 + (11058085471 / 23309404) * n ^ 9
    + (191286633721 / 46618808) * n ^ 8
    + (1088611348099 / 46618808) * n ^ 7
    + (4277705141833 / 46618808) * n ^ 6
    + (11836681211149 / 46618808) * n ^ 5
    + (23052247623749 / 46618808) * n ^ 4
    + (30953961110771 / 46618808) * n ^ 3
    + (27286667587391 / 46618808) * n ^ 2
    + (14212064972619 / 46618808) * n + 1657072707345 / 23309404

def gaugeP02 (n : ℕ) : ℚ :=
  n ^ 8 + 28 * n ^ 7 + (997178529 / 2920316) * n ^ 6
    + (988198811 / 417188) * n ^ 5
    + (59705834297 / 5840632) * n ^ 4
    + (2931024685 / 104297) * n ^ 3
    + (35085325154 / 730079) * n ^ 2
    + (38993868597 / 834376) * n + 57783653019 / 2920316

def gaugeR00 (n : ℕ) : ℚ :=
  (-40127847 / 64) * gaugeP00 n / gaugeDen0 n

def gaugeR01 (n : ℕ) : ℚ :=
  (5827351 / 256) * (n + 2) * gaugeP01 n / gaugeDen0 n

def gaugeR02 (n : ℕ) : ℚ :=
  (-730079 / 256) * (n + 2) * (n + 1) ^ 3
    * gaugeP02 n / gaugeDen0 n

theorem gaugeDen1_pos (n : ℕ) : 0 < gaugeDen1 n := by
  simp only [gaugeDen1]
  exact mul_pos
    (mul_pos (mul_pos (by positivity) (by positivity)) (gaugeQ71_pos n))
    (gaugeQ149_pos n)

theorem gaugeDen0_pos (n : ℕ) : 0 < gaugeDen0 n := by
  simp only [gaugeDen0]
  exact mul_pos
    (mul_pos
      (mul_pos (mul_pos (by positivity) (by positivity)) (by positivity))
      (gaugeQ71_pos n))
    (gaugeQ193_pos n)

theorem gaugeQ71_succ (n : ℕ) : gaugeQ71 (n + 1) = gaugeQ115 n := by
  simp only [gaugeQ71, gaugeQ115]
  push_cast
  ring

theorem gaugeQ105_succ (n : ℕ) : gaugeQ105 (n + 1) = gaugeQ149 n := by
  simp only [gaugeQ105, gaugeQ149]
  push_cast
  ring

theorem gaugeQ149_succ (n : ℕ) : gaugeQ149 (n + 1) = gaugeQ193 n := by
  simp only [gaugeQ149, gaugeQ193]
  push_cast
  ring

theorem gaugeQ193_succ (n : ℕ) : gaugeQ193 (n + 1) = gaugeQ237 n := by
  simp only [gaugeQ193, gaugeQ237]
  push_cast
  ring

theorem gaugeDen_succ (n : ℕ) :
    gaugeDen (n + 1) = (n + 4) ^ 3 * gaugeQ115 n * gaugeQ149 n := by
  simp only [gaugeDen, gaugeQ71_succ, gaugeQ105_succ]
  push_cast
  ring

theorem gaugeDen1_succ (n : ℕ) :
    gaugeDen1 (n + 1) =
      (n + 4) ^ 3 * (n + 7 / 2) ^ 2 * gaugeQ115 n * gaugeQ193 n := by
  simp only [gaugeDen1, gaugeQ71_succ, gaugeQ149_succ]
  push_cast
  ring

theorem gaugeDen0_succ (n : ℕ) :
    gaugeDen0 (n + 1) =
      (n + 4) ^ 3 * (n + 9 / 2) ^ 3 * (n + 7 / 2) ^ 2
        * gaugeQ115 n * gaugeQ237 n := by
  simp only [gaugeDen0, gaugeQ71_succ, gaugeQ193_succ]
  push_cast
  ring

theorem gaugeCommon_succ (n : ℕ) :
    gaugeCommon (n + 1) = (n + 9 / 2) * (n + 7 / 2) ^ 2 := by
  simp only [gaugeCommon]
  push_cast
  ring

theorem zudilinA_factor (n : ℕ) :
    zudilinA (n + 2) =
      1892 * (n + 5 / 2) * (n + 3) ^ 3 * gaugeQ71 n := by
  simp only [zudilinA, zudilinQ, gaugeQ71]
  push_cast
  ring

theorem A_factor (n : ℕ) :
    A n =
      1024 * (2 * n + 5) ^ 4 * (2 * n + 7) ^ 3 * (2 * n + 9) ^ 3
        * (946 * gaugeQ149 n) := by
  simp only [A, gaugeQ149]
  ring

theorem A_factor_one (n : ℕ) :
    A (n + 1) =
      1024 * (2 * n + 7) ^ 4 * (2 * n + 9) ^ 3 * (2 * n + 11) ^ 3
        * (946 * gaugeQ193 n) := by
  rw [A_factor]
  simp only [gaugeQ149_succ]
  push_cast
  ring

theorem A_factor_two (n : ℕ) :
    A (n + 2) =
      1024 * (2 * n + 9) ^ 4 * (2 * n + 11) ^ 3 * (2 * n + 13) ^ 3
        * (946 * gaugeQ237 n) := by
  rw [A_factor]
  have h := gaugeQ149_succ (n + 1)
  rw [h, gaugeQ193_succ]
  push_cast
  ring

theorem B_factor_two (n : ℕ) :
    B (n + 2) =
      128 * (2 * n + 11) ^ 3 * (2 * n + 13) ^ 3 * targetBPoly n := by
  simp only [B, targetBPoly]
  push_cast
  ring

theorem C_factor_one (n : ℕ) :
    C (n + 1) =
      16 * (n + 4) ^ 4 * (2 * n + 11) ^ 3 * targetCPoly n := by
  simp only [C, targetCPoly]
  push_cast
  ring

theorem D_factor (n : ℕ) :
    D n = (n + 3) ^ 4 * (n + 4) ^ 6 * (946 * gaugeQ105 n) := by
  simp only [D, gaugeQ105]
  ring

theorem pAlpha_eq (n : ℕ) :
    pAlpha n = 64 * B (n + 2) / A (n + 2) := by
  rw [A_factor_two, B_factor_two]
  simp only [pAlpha]
  field_simp [ne_of_gt (gaugeQ237_pos n)]
  ring

theorem pBeta_eq (n : ℕ) :
    pBeta n = -(64 ^ 2 * C (n + 1) / A (n + 1)) := by
  rw [A_factor_one, C_factor_one]
  simp only [pBeta]
  field_simp [ne_of_gt (gaugeQ193_pos n)]
  ring

theorem pGamma_eq (n : ℕ) :
    pGamma n = 64 ^ 3 * D n / A n := by
  rw [A_factor, D_factor]
  simp only [pGamma]
  field_simp [ne_of_gt (gaugeQ105_pos n), ne_of_gt (gaugeQ149_pos n)]
  ring

theorem gauge_bottom_num0 (n : ℕ) :
    (-13281 / 64) / 1892 * gaugeP20 (n + 1) * zudilinM (n + 2)
        + (47 / 8) * (n + 3) * gaugeP21 (n + 1)
          * ((n + 3) ^ 3 * (n + 5 / 2) ^ 2 * gaugeQ71 n) =
      (-730079 / 64) * gaugeP10 n * gaugeQ115 n := by
  simp only [gaugeP20, gaugeP21, gaugeP10, gaugeQ71, gaugeQ115, zudilinM]
  push_cast
  ring

theorem gauge_bottom_num1 (n : ℕ) :
    -(-13281 / 64) / 1892 * gaugeP20 (n + 1) * zudilinN (n + 2)
        - (n + 3) * (n + 2) ^ 2
          * ((n + 3) ^ 3 * (n + 5 / 2) * gaugeQ71 n) =
      (13249 / 32) * gaugeP11 n * gaugeQ115 n := by
  simp only [gaugeP20, gaugeP11, gaugeQ71, gaugeQ115, zudilinN]
  push_cast
  ring

theorem gauge_bottom_num2 (n : ℕ) :
    (-13281 / 64) / 3784 * gaugeP20 (n + 1) * zudilinR (n + 2) =
      (-13281 / 256) * gaugeP12 n * gaugeQ115 n := by
  simp only [gaugeP20, gaugeP12, gaugeQ115, zudilinR]
  push_cast
  ring

theorem gauge_middle_num0 (n : ℕ) :
    (-730079 / 64) / 1892 * gaugeP10 (n + 1) * zudilinM (n + 2)
        + (13249 / 32) * (n + 3) * gaugeP11 (n + 1)
          * ((n + 3) ^ 3 * (n + 5 / 2) * gaugeQ71 n) =
      (-40127847 / 64) * gaugeP00 n * gaugeQ115 n := by
  simp only [gaugeP10, gaugeP11, gaugeP00, gaugeQ71, gaugeQ115, zudilinM]
  push_cast
  ring

theorem gauge_middle_num1 (n : ℕ) :
    -(-730079 / 64) / 1892 * gaugeP10 (n + 1) * zudilinN (n + 2)
        + (-13281 / 256) * (n + 3) * (n + 2) ^ 2 * gaugeP12 (n + 1)
          * ((n + 3) ^ 3 * (n + 5 / 2) * gaugeQ71 n) =
      (5827351 / 256) * gaugeP01 n * gaugeQ115 n := by
  simp only [gaugeP10, gaugeP12, gaugeP01, gaugeQ71, gaugeQ115, zudilinN]
  push_cast
  ring

theorem gauge_middle_num2 (n : ℕ) :
    (-730079 / 64) / 3784 * gaugeP10 (n + 1) * zudilinR (n + 2) =
      (-730079 / 256) * gaugeP02 n * gaugeQ115 n := by
  simp only [gaugeP10, gaugeP02, gaugeQ115, zudilinR]
  push_cast
  ring

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_bottom_col0 (n : ℕ) :
    twistRatio n * (gaugeR20 (n + 1) * zAlpha n + gaugeR21 (n + 1)) =
      gaugeR10 n := by
  simp only [twistRatio, gaugeR20, gaugeR21, gaugeR10, zAlpha,
    gaugeCommon_succ, gaugeDen_succ, zudilinA_factor, gaugeDen1]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ149_pos n)]
  push_cast
  linear_combination 64 * 32 * 1892 * gauge_bottom_num0 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_bottom_col1 (n : ℕ) :
    twistRatio n
        * (gaugeR20 (n + 1) * zBeta n + gaugeR22 (n + 1)) =
      gaugeR11 n := by
  simp only [twistRatio, gaugeR20, gaugeR22, gaugeR11, zBeta,
    gaugeCommon_succ, gaugeDen_succ, zudilinA_factor, gaugeDen1]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ149_pos n)]
  push_cast
  linear_combination
    64 * 64 * 1892 * (n + 2) * gauge_bottom_num1 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_bottom_col2 (n : ℕ) :
    twistRatio n * (gaugeR20 (n + 1) * zGamma n) = gaugeR12 n := by
  simp only [twistRatio, gaugeR20, gaugeR12, zGamma,
    gaugeCommon_succ, gaugeDen_succ, zudilinA_factor, gaugeDen1]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ149_pos n)]
  linear_combination
    (256 * 64 * 3784 / 13281) * gauge_bottom_num2 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_middle_col0 (n : ℕ) :
    twistRatio n * (gaugeR10 (n + 1) * zAlpha n + gaugeR11 (n + 1)) =
      gaugeR00 n := by
  simp only [twistRatio, gaugeR10, gaugeR11, gaugeR00, zAlpha,
    gaugeDen1_succ, zudilinA_factor, gaugeDen0]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ193_pos n)]
  push_cast
  linear_combination
    (2 * n + 9) * 64 * 64 * 1892 * gauge_middle_num0 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_middle_col1 (n : ℕ) :
    twistRatio n
        * (gaugeR10 (n + 1) * zBeta n + gaugeR12 (n + 1)) =
      gaugeR01 n := by
  simp only [twistRatio, gaugeR10, gaugeR12, gaugeR01, zBeta,
    gaugeDen1_succ, zudilinA_factor, gaugeDen0]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ193_pos n)]
  push_cast
  linear_combination
    (2 * n + 9) * 512 * 64 * 1892 * (n + 2) * gauge_middle_num1 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_middle_col2 (n : ℕ) :
    twistRatio n * (gaugeR10 (n + 1) * zGamma n) = gaugeR02 n := by
  simp only [twistRatio, gaugeR10, gaugeR02, zGamma,
    gaugeDen1_succ, zudilinA_factor, gaugeDen0]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ115_pos n),
    ne_of_gt (gaugeQ193_pos n)]
  push_cast
  linear_combination
    (2 * n + 9) * (256 * 64 * 3784 / 730079) * gauge_middle_num2 n

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_top_col0 (n : ℕ) :
    twistRatio n * (gaugeR00 (n + 1) * zAlpha n + gaugeR01 (n + 1)) =
      pAlpha n * gaugeR00 n + pBeta n * gaugeR10 n
        + pGamma n * gaugeR20 n := by
  simp only [twistRatio, gaugeR00, gaugeR01, gaugeR10, gaugeR20, zAlpha,
    pAlpha, pBeta, pGamma, zudilinA_factor, gaugeDen0,
    gaugeDen1, gaugeDen, gaugeCommon, gaugeQ71_succ, gaugeQ193_succ]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ105_pos n),
    ne_of_gt (gaugeQ115_pos n), ne_of_gt (gaugeQ149_pos n),
    ne_of_gt (gaugeQ193_pos n), ne_of_gt (gaugeQ237_pos n)]
  simp only [gaugeP00, gaugeP01, gaugeP10, gaugeP20, targetBPoly,
    targetCPoly, zudilinM, gaugeQ71, gaugeQ115, gaugeQ149, gaugeQ193,
    gaugeQ237]
  push_cast
  ring

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_top_col1 (n : ℕ) :
    twistRatio n
        * (gaugeR00 (n + 1) * zBeta n + gaugeR02 (n + 1)) =
      pAlpha n * gaugeR01 n + pBeta n * gaugeR11 n
        + pGamma n * gaugeR21 n := by
  simp only [twistRatio, gaugeR00, gaugeR02, gaugeR01, gaugeR11, gaugeR21,
    zBeta, pAlpha, pBeta, pGamma, zudilinA_factor,
    gaugeDen0, gaugeDen1, gaugeDen, gaugeCommon, gaugeQ71_succ,
    gaugeQ193_succ]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ105_pos n),
    ne_of_gt (gaugeQ115_pos n), ne_of_gt (gaugeQ149_pos n),
    ne_of_gt (gaugeQ193_pos n), ne_of_gt (gaugeQ237_pos n)]
  simp only [gaugeP00, gaugeP02, gaugeP01, gaugeP11, gaugeP21,
    targetBPoly, targetCPoly, zudilinN, gaugeQ71, gaugeQ115, gaugeQ149,
    gaugeQ193, gaugeQ237]
  push_cast
  ring

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
theorem gauge_top_col2 (n : ℕ) :
    twistRatio n * (gaugeR00 (n + 1) * zGamma n) =
      pAlpha n * gaugeR02 n + pBeta n * gaugeR12 n
        + pGamma n * gaugeR22 n := by
  simp only [twistRatio, gaugeR00, gaugeR02, gaugeR12, gaugeR22, zGamma,
    pAlpha, pBeta, pGamma, zudilinA_factor, gaugeDen0,
    gaugeDen1, gaugeDen, gaugeCommon, gaugeQ71_succ, gaugeQ193_succ]
  field_simp [ne_of_gt (gaugeQ71_pos n), ne_of_gt (gaugeQ105_pos n),
    ne_of_gt (gaugeQ115_pos n), ne_of_gt (gaugeQ149_pos n),
    ne_of_gt (gaugeQ193_pos n), ne_of_gt (gaugeQ237_pos n)]
  simp only [gaugeP00, gaugeP02, gaugeP12, targetBPoly, targetCPoly,
    zudilinR, gaugeQ115, gaugeQ149, gaugeQ193, gaugeQ237]
  push_cast
  ring

def gaugeRow0 (v : ℕ → ℚ) (n : ℕ) : ℚ :=
  gaugeR00 n * v (n + 2) + gaugeR01 n * v (n + 1) + gaugeR02 n * v n

def gaugeRow1 (v : ℕ → ℚ) (n : ℕ) : ℚ :=
  gaugeR10 n * v (n + 2) + gaugeR11 n * v (n + 1) + gaugeR12 n * v n

def gaugeRow2 (v : ℕ → ℚ) (n : ℕ) : ℚ :=
  gaugeR20 n * v (n + 2) + gaugeR21 n * v (n + 1) + gaugeR22 n * v n

theorem ZudilinSatisfiesRec.step {v : ℕ → ℚ}
    (hv : ZudilinSatisfiesRec v) (n : ℕ) :
    v (n + 3) =
      zAlpha n * v (n + 2) + zBeta n * v (n + 1) + zGamma n * v n := by
  rw [hv n]
  simp only [zAlpha, zBeta, zGamma, sub_eq_add_neg]
  ring

/-- The marked Zudilin denominator is at least one and nondecreasing.  This is
proved directly from its exact recurrence, independently of any asymptotic
input. -/
theorem zudilinB_one_le_and_le_succ (n : ℕ) :
    1 ≤ zudilinB n ∧ zudilinB n ≤ zudilinB (n + 1) := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
      match n with
      | 0 => norm_num [zudilinB, zudilinSolution]
      | 1 => norm_num [zudilinB, zudilinSolution]
      | k + 2 =>
        have hk := ih k (by omega)
        have hk₁ := ih (k + 1) (by omega)
        have hBk : 0 ≤ zudilinB k := le_trans (by norm_num) hk.1
        have hBk₂ : 0 ≤ zudilinB (k + 2) :=
          le_trans (le_trans (by norm_num) hk₁.1) hk₁.2
        constructor
        · exact hk₁.1.trans hk₁.2
        · rw [zudilinB_rec.step k]
          have hmain :
              zudilinB (k + 2) ≤
                (zAlpha k + zBeta k) * zudilinB (k + 2) := by
            simpa only [one_mul] using
              mul_le_mul_of_nonneg_right (one_le_zAlpha_add_zBeta k) hBk₂
          have hbeta :
              zBeta k * zudilinB (k + 2) ≤
                zBeta k * zudilinB (k + 1) :=
            mul_le_mul_of_nonpos_left hk₁.2 (zBeta_nonpos k)
          have hgamma : 0 ≤ zGamma k * zudilinB k :=
            mul_nonneg (zGamma_nonneg k) hBk
          calc
            zudilinB (k + 2) ≤
                (zAlpha k + zBeta k) * zudilinB (k + 2) := hmain
            _ = zAlpha k * zudilinB (k + 2)
                  + zBeta k * zudilinB (k + 2) := by ring
            _ ≤ zAlpha k * zudilinB (k + 2)
                  + zBeta k * zudilinB (k + 1) :=
              add_le_add (le_refl _) hbeta
            _ ≤ zAlpha k * zudilinB (k + 2)
                  + zBeta k * zudilinB (k + 1)
                  + zGamma k * zudilinB k :=
              le_add_of_nonneg_right hgamma

theorem zudilinB_thirty_one_mul_le (n : ℕ) :
    31 * zudilinB (n + 2) ≤ zudilinB (n + 3) := by
  rw [zudilinB_rec.step n]
  have hBn : 0 ≤ zudilinB n :=
    le_trans (by norm_num) (zudilinB_one_le_and_le_succ n).1
  have hBn₂ : 0 ≤ zudilinB (n + 2) :=
    le_trans (by norm_num) (zudilinB_one_le_and_le_succ (n + 2)).1
  have hmain :
      31 * zudilinB (n + 2) ≤
        (zAlpha n + zBeta n) * zudilinB (n + 2) :=
    mul_le_mul_of_nonneg_right
      (thirty_one_le_zAlpha_add_zBeta n) hBn₂
  have hbeta :
      zBeta n * zudilinB (n + 2) ≤
        zBeta n * zudilinB (n + 1) :=
    mul_le_mul_of_nonpos_left
      (zudilinB_one_le_and_le_succ (n + 1)).2 (zBeta_nonpos n)
  have hgamma : 0 ≤ zGamma n * zudilinB n :=
    mul_nonneg (zGamma_nonneg n) hBn
  calc
    31 * zudilinB (n + 2) ≤
        (zAlpha n + zBeta n) * zudilinB (n + 2) := hmain
    _ = zAlpha n * zudilinB (n + 2)
          + zBeta n * zudilinB (n + 2) := by ring
    _ ≤ zAlpha n * zudilinB (n + 2)
          + zBeta n * zudilinB (n + 1) :=
      add_le_add (le_refl _) hbeta
    _ ≤ zAlpha n * zudilinB (n + 2)
          + zBeta n * zudilinB (n + 1)
          + zGamma n * zudilinB n :=
      le_add_of_nonneg_right hgamma

theorem gaugeScalar_shift_one {v : ℕ → ℚ} (hv : ZudilinSatisfiesRec v)
    (n : ℕ) :
    gaugeScalar v (n + 1) = twist n * gaugeRow1 v n := by
  rw [gaugeScalar, gaugeRow1, twist_succ, hv.step]
  simp only [Nat.add_comm, Nat.add_left_comm]
  linear_combination
    twist n * v (n + 2) * gauge_bottom_col0 n
      + twist n * v (n + 1) * gauge_bottom_col1 n
      + twist n * v n * gauge_bottom_col2 n

theorem gaugeScalar_shift_two {v : ℕ → ℚ} (hv : ZudilinSatisfiesRec v)
    (n : ℕ) :
    gaugeScalar v (n + 2) = twist n * gaugeRow0 v n := by
  rw [show n + 2 = (n + 1) + 1 by omega, gaugeScalar_shift_one hv,
    gaugeRow1, twist_succ, hv.step]
  simp only [gaugeRow0, Nat.add_comm, Nat.add_left_comm]
  linear_combination
    twist n * v (n + 2) * gauge_middle_col0 n
      + twist n * v (n + 1) * gauge_middle_col1 n
      + twist n * v n * gauge_middle_col2 n

theorem gaugeScalar_step {v : ℕ → ℚ} (hv : ZudilinSatisfiesRec v)
    (n : ℕ) :
    gaugeScalar v (n + 3) =
      pAlpha n * gaugeScalar v (n + 2)
        + pBeta n * gaugeScalar v (n + 1)
        + pGamma n * gaugeScalar v n := by
  have h₃ :
      gaugeScalar v (n + 3) =
        twist n
          * (pAlpha n * gaugeRow0 v n + pBeta n * gaugeRow1 v n
            + pGamma n * gaugeRow2 v n) := by
    rw [show n + 3 = (n + 1) + 2 by omega, gaugeScalar_shift_two hv,
      gaugeRow0, twist_succ, hv.step]
    simp only [gaugeRow0, gaugeRow1, gaugeRow2, Nat.add_comm,
      Nat.add_left_comm]
    linear_combination
      twist n * v (n + 2) * gauge_top_col0 n
        + twist n * v (n + 1) * gauge_top_col1 n
        + twist n * v n * gauge_top_col2 n
  rw [h₃, gaugeScalar_shift_two hv n, gaugeScalar_shift_one hv n]
  simp only [gaugeScalar, gaugeRow2]
  ring

theorem gaugeScalar_scaledRec {v : ℕ → ℚ} (hv : ZudilinSatisfiesRec v) :
    ScaledSatisfiesRec (gaugeScalar v) := by
  intro n
  rw [gaugeScalar_step hv, pAlpha_eq, pBeta_eq, pGamma_eq]
  ring

def gaugeScale : ℚ := 223729 / 1755433451520

def gaugeUnscaled (v : ℕ → ℚ) (n : ℕ) : ℚ :=
  gaugeScalar v n / (gaugeScale * 64 ^ n)

theorem gaugeScale_ne_zero : gaugeScale ≠ 0 := by
  norm_num [gaugeScale]

theorem gaugeUnscaled_rec {v : ℕ → ℚ} (hv : ZudilinSatisfiesRec v) :
    SatisfiesRec (gaugeUnscaled v) := by
  intro n
  simp only [gaugeUnscaled]
  rw [gaugeScalar_step hv, pAlpha_eq, pBeta_eq, pGamma_eq]
  simp only [pow_add]
  field_simp [gaugeScale_ne_zero, ne_of_gt (A_pos n),
    ne_of_gt (A_pos (n + 1)), ne_of_gt (A_pos (n + 2))]
  ring

theorem gaugeUnscaled_zudilinB_zero :
    gaugeUnscaled zudilinB 0 = -215040420000 := by
  norm_num [gaugeUnscaled, gaugeScalar, gaugeScale, twist, gaugeR20,
    gaugeR21, gaugeR22, gaugeCommon, gaugeP20, gaugeP21, gaugeDen,
    gaugeQ71, gaugeQ105, zudilinB, zudilinSolution]

theorem gaugeUnscaled_zudilinB_one :
    gaugeUnscaled zudilinB 1 = -167282265043404 / 905 := by
  rw [gaugeUnscaled, gaugeScalar_shift_one zudilinB_rec]
  norm_num [gaugeScale, twist, gaugeRow1, gaugeR10, gaugeR11, gaugeR12,
    gaugeP10, gaugeP11, gaugeP12, gaugeDen1, gaugeQ71, gaugeQ149,
    zudilinB, zudilinSolution]

theorem gaugeUnscaled_zudilinB_two :
    gaugeUnscaled zudilinB 2 = -964185327658080 / 6071 := by
  rw [gaugeUnscaled, gaugeScalar_shift_two zudilinB_rec]
  norm_num [gaugeScale, twist, gaugeRow0, gaugeR00, gaugeR01, gaugeR02,
    gaugeP00, gaugeP01, gaugeP02, gaugeDen0, gaugeQ71, gaugeQ193,
    zudilinB, zudilinSolution]

theorem gaugeUnscaled_zudilinM23_zero :
    gaugeUnscaled zudilinM23 0 = -612218384750 := by
  norm_num [gaugeUnscaled, gaugeScalar, gaugeScale, twist, gaugeR20,
    gaugeR21, gaugeR22, gaugeCommon, gaugeP20, gaugeP21, gaugeDen,
    gaugeQ71, gaugeQ105, zudilinM23, zudilinB₂, zudilinB₃,
    zudilinSolution]

theorem gaugeUnscaled_zudilinM23_one :
    gaugeUnscaled zudilinM23 1 = -9525021973931919 / 18100 := by
  rw [gaugeUnscaled, gaugeScalar_shift_one zudilinM23_rec]
  norm_num [gaugeScale, twist, gaugeRow1, gaugeR10, gaugeR11, gaugeR12,
    gaugeP10, gaugeP11, gaugeP12, gaugeDen1, gaugeQ71, gaugeQ149,
    zudilinM23, zudilinB₂, zudilinB₃, zudilinSolution]

theorem gaugeUnscaled_zudilinM23_two :
    gaugeUnscaled zudilinM23 2 = -29561828382772029 / 65380 := by
  rw [gaugeUnscaled, gaugeScalar_shift_two zudilinM23_rec]
  norm_num [gaugeScale, twist, gaugeRow0, gaugeR00, gaugeR01, gaugeR02,
    gaugeP00, gaugeP01, gaugeP02, gaugeDen0, gaugeQ71, gaugeQ193,
    zudilinM23, zudilinB₂, zudilinB₃, zudilinSolution]

theorem gaugeUnscaled_zudilinB_eq_challengeQ :
    gaugeUnscaled zudilinB = challengeQ :=
  challengeQ_eq_of_initial_and_rec (gaugeUnscaled_rec zudilinB_rec)
    gaugeUnscaled_zudilinB_zero gaugeUnscaled_zudilinB_one
    gaugeUnscaled_zudilinB_two

theorem gaugeUnscaled_zudilinM23_eq_challengeP :
    gaugeUnscaled zudilinM23 = challengeP :=
  challengeP_eq_of_initial_and_rec (gaugeUnscaled_rec zudilinM23_rec)
    gaugeUnscaled_zudilinM23_zero gaugeUnscaled_zudilinM23_one
    gaugeUnscaled_zudilinM23_two

/-! ## Limits of the rational gauge coefficients -/

def gaugePolyQ71 : ℝ[X] :=
  Polynomial.X ^ 2 + Polynomial.C (71 / 22) * Polynomial.X
    + Polynomial.C (225 / 86)

def gaugePolyQ105 : ℝ[X] :=
  Polynomial.X ^ 2 + Polynomial.C (105 / 22) * Polynomial.X
    + Polynomial.C (5399 / 946)

def gaugePolyCommon : ℝ[X] :=
  (Polynomial.X + Polynomial.C (7 / 2))
    * (Polynomial.X + Polynomial.C (5 / 2)) ^ 2

def gaugePolyP20 : ℝ[X] :=
  Polynomial.X ^ 4 + Polynomial.C 8 * Polynomial.X ^ 3
    + Polynomial.C (1260571 / 53124) * Polynomial.X ^ 2
    + Polynomial.C (410587 / 13281) * Polynomial.X
    + Polynomial.C (793741 / 53124)

def gaugePolyP21 : ℝ[X] :=
  Polynomial.X ^ 2 + Polynomial.C 3 * Polynomial.X + Polynomial.C (110 / 47)

def gaugePolyDen2 : ℝ[X] :=
  (Polynomial.X + Polynomial.C 3) ^ 3 * gaugePolyQ71 * gaugePolyQ105

def gaugePolyNum20 : ℝ[X] :=
  Polynomial.C (-13281 / 64) * gaugePolyCommon * gaugePolyP20

def gaugePolyNum21 : ℝ[X] :=
  Polynomial.C (47 / 8) * gaugePolyCommon
    * (Polynomial.X + Polynomial.C (3 / 2))
    * (Polynomial.X + Polynomial.C 2) * gaugePolyP21

def gaugePolyNum22 : ℝ[X] :=
  -gaugePolyCommon * (Polynomial.X + Polynomial.C 2)
    * (Polynomial.X + Polynomial.C 1) ^ 3

theorem gaugeR20_eval (n : ℕ) :
    (gaugeR20 n : ℝ) =
      Polynomial.eval (n : ℝ) gaugePolyNum20
        / Polynomial.eval (n : ℝ) gaugePolyDen2 := by
  simp only [gaugeR20, gaugeCommon, gaugeP20, gaugeDen, gaugeQ71, gaugeQ105,
    gaugePolyNum20, gaugePolyCommon, gaugePolyP20, gaugePolyDen2,
    gaugePolyQ71, gaugePolyQ105, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_X, Polynomial.eval_C, Polynomial.eval_add]
  push_cast
  ring

theorem gaugePolyDen2_degree : gaugePolyDen2.degree = 7 := by
  rw [gaugePolyDen2, gaugePolyQ71, gaugePolyQ105]
  compute_degree <;> norm_num
  all_goals change 7 ≤ 7
  all_goals omega

theorem gaugePolyDen2_monic : gaugePolyDen2.Monic := by
  rw [gaugePolyDen2, gaugePolyQ71, gaugePolyQ105]
  monicity <;> norm_num

theorem gaugeR20_tendsto :
    Tendsto (fun n : ℕ => (gaugeR20 n : ℝ)) atTop
      (𝓝 (-13281 / 64)) := by
  have hdeg : gaugePolyNum20.degree = gaugePolyDen2.degree := by
    have hn : gaugePolyNum20.degree = 7 := by
      rw [gaugePolyNum20, gaugePolyCommon, gaugePolyP20]
      compute_degree <;> norm_num
      all_goals change 7 ≤ 7
      all_goals omega
    have hd : gaugePolyDen2.degree = 7 := by
      rw [gaugePolyDen2, gaugePolyQ71, gaugePolyQ105]
      compute_degree <;> norm_num
      all_goals change 7 ≤ 7
      all_goals omega
    rw [hn, hd]
  have h :=
    Polynomial.div_tendsto_atTop_leadingCoeff_div_of_degree_eq
      gaugePolyNum20 gaugePolyDen2 hdeg
  have hc := h.comp (tendsto_natCast_atTop_atTop (R := ℝ))
  have hlc :
      gaugePolyNum20.leadingCoeff / gaugePolyDen2.leadingCoeff =
        (-13281 / 64 : ℝ) := by
    have hc : gaugePolyCommon.Monic := by
      rw [gaugePolyCommon]
      monicity <;> norm_num
    have hp : gaugePolyP20.Monic := by
      rw [gaugePolyP20]
      monicity <;> norm_num
    have hd : gaugePolyDen2.Monic := by
      rw [gaugePolyDen2, gaugePolyQ71, gaugePolyQ105]
      monicity <;> norm_num
    simp [gaugePolyNum20, hc.leadingCoeff, hp.leadingCoeff, hd.leadingCoeff]
  rw [hlc] at hc
  exact hc.congr' (Eventually.of_forall fun n => (gaugeR20_eval n).symm)

theorem gaugeR21_eval (n : ℕ) :
    (gaugeR21 n : ℝ) =
      Polynomial.eval (n : ℝ) gaugePolyNum21
        / Polynomial.eval (n : ℝ) gaugePolyDen2 := by
  simp only [gaugeR21, gaugeCommon, gaugeP21, gaugeDen, gaugeQ71, gaugeQ105,
    gaugePolyNum21, gaugePolyCommon, gaugePolyP21, gaugePolyDen2,
    gaugePolyQ71, gaugePolyQ105, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_X, Polynomial.eval_C, Polynomial.eval_add]
  push_cast
  ring

theorem gaugeR21_tendsto :
    Tendsto (fun n : ℕ => (gaugeR21 n : ℝ)) atTop (𝓝 (47 / 8)) := by
  have hn : gaugePolyNum21.degree = 7 := by
    rw [gaugePolyNum21, gaugePolyCommon, gaugePolyP21]
    compute_degree <;> norm_num
    all_goals change 7 ≤ 7
    all_goals omega
  have hdeg : gaugePolyNum21.degree = gaugePolyDen2.degree := by
    rw [hn, gaugePolyDen2_degree]
  have h :=
    Polynomial.div_tendsto_atTop_leadingCoeff_div_of_degree_eq
      gaugePolyNum21 gaugePolyDen2 hdeg
  have hc := h.comp (tendsto_natCast_atTop_atTop (R := ℝ))
  have hlc :
      gaugePolyNum21.leadingCoeff / gaugePolyDen2.leadingCoeff =
        (47 / 8 : ℝ) := by
    have hcommon : gaugePolyCommon.Monic := by
      rw [gaugePolyCommon]
      monicity <;> norm_num
    have hp : gaugePolyP21.Monic := by
      rw [gaugePolyP21]
      monicity <;> norm_num
    simp [gaugePolyNum21, hcommon.leadingCoeff, hp.leadingCoeff,
      gaugePolyDen2_monic.leadingCoeff]
  rw [hlc] at hc
  exact hc.congr' (Eventually.of_forall fun n => (gaugeR21_eval n).symm)

theorem gaugeR22_eval (n : ℕ) :
    (gaugeR22 n : ℝ) =
      Polynomial.eval (n : ℝ) gaugePolyNum22
        / Polynomial.eval (n : ℝ) gaugePolyDen2 := by
  simp only [gaugeR22, gaugeCommon, gaugeDen, gaugeQ71, gaugeQ105,
    gaugePolyNum22, gaugePolyCommon, gaugePolyDen2, gaugePolyQ71,
    gaugePolyQ105, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_X, Polynomial.eval_C, Polynomial.eval_add,
    Polynomial.eval_neg]
  push_cast
  ring

theorem gaugeR22_tendsto :
    Tendsto (fun n : ℕ => (gaugeR22 n : ℝ)) atTop (𝓝 (-1)) := by
  have hn : gaugePolyNum22.degree = 7 := by
    have hcommonDeg : gaugePolyCommon.degree = 3 := by
      rw [gaugePolyCommon,
        ((Polynomial.monic_X_add_C (5 / 2 : ℝ)).pow 2).degree_mul,
        Polynomial.degree_X_add_C]
      have hp :
          ((Polynomial.X + Polynomial.C (5 / 2 : ℝ)) ^ 2).degree = 2 := by
        rw [Polynomial.degree_eq_natDegree
          ((Polynomial.monic_X_add_C (5 / 2 : ℝ)).pow 2).ne_zero,
          Polynomial.natDegree_pow_X_add_C]
        rfl
      rw [hp]
      norm_num
    rw [gaugePolyNum22,
      ((Polynomial.monic_X_add_C (1 : ℝ)).pow 3).degree_mul,
      (Polynomial.monic_X_add_C (2 : ℝ)).degree_mul,
      Polynomial.degree_neg, hcommonDeg, Polynomial.degree_X_add_C]
    have hp :
        ((Polynomial.X + Polynomial.C (1 : ℝ)) ^ 3).degree = 3 := by
      rw [Polynomial.degree_eq_natDegree
        ((Polynomial.monic_X_add_C (1 : ℝ)).pow 3).ne_zero,
        Polynomial.natDegree_pow_X_add_C]
      rfl
    rw [hp]
    norm_num
  have hdeg : gaugePolyNum22.degree = gaugePolyDen2.degree := by
    rw [hn, gaugePolyDen2_degree]
  have h :=
    Polynomial.div_tendsto_atTop_leadingCoeff_div_of_degree_eq
      gaugePolyNum22 gaugePolyDen2 hdeg
  have hc := h.comp (tendsto_natCast_atTop_atTop (R := ℝ))
  have hlc :
      gaugePolyNum22.leadingCoeff / gaugePolyDen2.leadingCoeff =
        (-1 : ℝ) := by
    have hcommon : gaugePolyCommon.Monic := by
      rw [gaugePolyCommon]
      monicity <;> norm_num
    have htwo :
        (Polynomial.X + Polynomial.C (2 : ℝ)).Monic :=
      Polynomial.monic_X_add_C _
    have hone : (Polynomial.X + (1 : ℝ[X])).Monic := by
      monicity
    simp [gaugePolyNum22, hcommon.leadingCoeff,
      htwo.leadingCoeff, hone.leadingCoeff, gaugePolyDen2_monic.leadingCoeff]
  rw [hlc] at hc
  exact hc.congr' (Eventually.of_forall fun n => (gaugeR22_eval n).symm)

/-! ## Analytic transfer from Zudilin's source approximants -/

def zeta3 : ℝ := ∑' n : ℕ, (1 : ℝ) / (n + 1) ^ 3

def zudilinBReal (n : ℕ) : ℝ := (zudilinB n : ℝ)
def zudilinB₂Real (n : ℕ) : ℝ := (zudilinB₂ n : ℝ)
def zudilinB₃Real (n : ℕ) : ℝ := (zudilinB₃ n : ℝ)
def zudilinM23Real (n : ℕ) : ℝ := (zudilinM23 n : ℝ)

def gaugeRow2Real (v : ℕ → ℚ) (n : ℕ) : ℝ := (gaugeRow2 v n : ℝ)

theorem one_le_zudilinBReal (n : ℕ) : 1 ≤ zudilinBReal n := by
  change (1 : ℝ) ≤ ((zudilinB n : ℚ) : ℝ)
  exact_mod_cast (zudilinB_one_le_and_le_succ n).1

theorem zudilinBReal_le_succ (n : ℕ) :
    zudilinBReal n ≤ zudilinBReal (n + 1) := by
  change ((zudilinB n : ℚ) : ℝ) ≤ ((zudilinB (n + 1) : ℚ) : ℝ)
  exact_mod_cast (zudilinB_one_le_and_le_succ n).2

theorem zudilinBReal_thirty_one_mul_le (n : ℕ) :
    31 * zudilinBReal (n + 2) ≤ zudilinBReal (n + 3) := by
  change
    (31 : ℝ) * ((zudilinB (n + 2) : ℚ) : ℝ) ≤
      ((zudilinB (n + 3) : ℚ) : ℝ)
  exact_mod_cast zudilinB_thirty_one_mul_le n

theorem zudilinBReal_add_two_tendsto_atTop :
    Tendsto (fun n => zudilinBReal (n + 2)) atTop atTop := by
  apply tendsto_atTop_of_geom_le (c := 31)
  · norm_num [zudilinBReal, zudilinB, zudilinSolution]
  · norm_num
  · exact zudilinBReal_thirty_one_mul_le

theorem gaugeRow2Real_zudilinB_tendsto_atBot :
    Tendsto (gaugeRow2Real zudilinB) atTop atBot := by
  have hR20 :
      ∀ᶠ n in atTop, (gaugeR20 n : ℝ) ≤ -200 :=
    (gaugeR20_tendsto.eventually_lt_const (by norm_num)).mono
      fun _ hn => hn.le
  have hR21 :
      ∀ᶠ n in atTop, (gaugeR21 n : ℝ) ≤ 10 :=
    (gaugeR21_tendsto.eventually_lt_const (by norm_num)).mono
      fun _ hn => hn.le
  have hbound :
      ∀ᶠ n in atTop,
        gaugeRow2Real zudilinB n ≤ -190 * zudilinBReal (n + 2) := by
    filter_upwards [hR20, hR21] with n h20 h21
    have hB0 : 0 ≤ zudilinBReal n :=
      le_trans (by norm_num) (one_le_zudilinBReal n)
    have hB1 : 0 ≤ zudilinBReal (n + 1) :=
      le_trans (by norm_num) (one_le_zudilinBReal (n + 1))
    have hB2 : 0 ≤ zudilinBReal (n + 2) :=
      le_trans (by norm_num) (one_le_zudilinBReal (n + 2))
    have hB12 : zudilinBReal (n + 1) ≤ zudilinBReal (n + 2) :=
      zudilinBReal_le_succ (n + 1)
    have h20mul :
        (gaugeR20 n : ℝ) * zudilinBReal (n + 2) ≤
          -200 * zudilinBReal (n + 2) :=
      mul_le_mul_of_nonneg_right h20 hB2
    have h21mul :
        (gaugeR21 n : ℝ) * zudilinBReal (n + 1) ≤
          10 * zudilinBReal (n + 2) := by
      calc
        (gaugeR21 n : ℝ) * zudilinBReal (n + 1) ≤
            10 * zudilinBReal (n + 1) :=
          mul_le_mul_of_nonneg_right h21 hB1
        _ ≤ 10 * zudilinBReal (n + 2) :=
          mul_le_mul_of_nonneg_left hB12 (by norm_num)
    have hR22 : (gaugeR22 n : ℝ) ≤ 0 := by
      exact_mod_cast gaugeR22_nonpos n
    have h22mul :
        (gaugeR22 n : ℝ) * zudilinBReal n ≤ 0 :=
      mul_nonpos_of_nonpos_of_nonneg hR22 hB0
    simp only [zudilinBReal] at h20mul h21mul h22mul
    simp only [gaugeRow2Real, gaugeRow2, zudilinBReal]
    push_cast
    linarith
  have hminor :
      Tendsto (fun n => -190 * zudilinBReal (n + 2)) atTop atBot :=
    Tendsto.const_mul_atTop_of_neg (by norm_num)
      zudilinBReal_add_two_tendsto_atTop
  exact tendsto_atBot_mono' atTop hbound hminor

/-- If a denominator is uniformly at least one, convergence of the exact
linear-form error implies convergence of the associated rational
approximants. -/
theorem ratio_tendsto_of_error_tendsto
    (b m : ℕ → ℝ) (L : ℝ)
    (hb : ∀ n, 1 ≤ b n)
    (hError : Tendsto (fun n => L * b n - m n) atTop (𝓝 0)) :
    Tendsto (fun n => m n / b n) atTop (𝓝 L) := by
  have hinvBound :
      IsBoundedUnder (· ≤ ·) atTop (norm ∘ fun n => (b n)⁻¹) := by
    apply isBoundedUnder_of_eventually_le (a := 1)
    exact Eventually.of_forall fun n => by
      have hbpos : 0 < b n := lt_of_lt_of_le zero_lt_one (hb n)
      rw [Function.comp_apply, Real.norm_eq_abs, abs_inv, abs_of_pos hbpos]
      exact (inv_le_one₀ hbpos).2 (hb n)
  have hErrorDiv :
      Tendsto (fun n => (L * b n - m n) / b n) atTop (𝓝 0) := by
    have h := hinvBound.smul_tendsto_zero hError
    simpa only [smul_eq_mul, div_eq_mul_inv, mul_comm] using h
  have h :
      Tendsto
        (fun n : ℕ => L - (L * b n - m n) / b n)
        atTop (𝓝 (L - 0)) :=
    tendsto_const_nhds.sub hErrorDiv
  simp only [sub_zero] at h
  refine h.congr' (Eventually.of_forall fun n => ?_)
  have hb0 : b n ≠ 0 := ne_of_gt (lt_of_lt_of_le zero_lt_one (hb n))
  field_simp [hb0]
  ring

theorem twistRatio_pos (n : ℕ) : 0 < twistRatio n := by
  simp only [twistRatio]
  positivity

theorem twist_pos : ∀ n : ℕ, 0 < twist n
  | 0 => by norm_num [twist]
  | n + 1 => by
      rw [twist_succ]
      exact mul_pos (twistRatio_pos n) (twist_pos n)

theorem challenge_ratio_eq_gaugeRow2 (n : ℕ) :
    (challengeP n : ℝ) / (challengeQ n : ℝ) =
      gaugeRow2Real zudilinM23 n / gaugeRow2Real zudilinB n := by
  rw [← congrFun gaugeUnscaled_zudilinM23_eq_challengeP n,
    ← congrFun gaugeUnscaled_zudilinB_eq_challengeQ n]
  simp only [gaugeUnscaled, gaugeScalar, gaugeRow2Real, gaugeRow2]
  push_cast
  field_simp [gaugeScale_ne_zero, ne_of_gt (twist_pos n)]

/-- A nonzero one-step ratio limit determines the corresponding two-step
ratio limit.  This removes one of the four asymptotic assumptions in the
earlier transfer statement. -/
theorem tendsto_two_step_ratio_of_tendsto_step_ratio
    {b : ℕ → ℝ} {μ : ℝ} (hμ : μ ≠ 0)
    (h :
      Tendsto (fun n => b (n + 1) / b n) atTop (𝓝 μ)) :
    Tendsto (fun n => b (n + 2) / b n) atTop (𝓝 (μ ^ 2)) := by
  have hshift :
      Tendsto (fun n => b (n + 2) / b (n + 1)) atTop (𝓝 μ) := by
    simpa only [Nat.add_assoc, Nat.reduceAdd] using
      (tendsto_add_atTop_iff_nat 1).mpr h
  have hmiddle : ∀ᶠ n in atTop, b (n + 1) ≠ 0 :=
    h.eventually_ne hμ |>.mono fun _ hn => (div_ne_zero_iff.mp hn).1
  have hprod :
      Tendsto
        (fun n =>
          (b (n + 2) / b (n + 1)) * (b (n + 1) / b n))
        atTop (𝓝 (μ ^ 2)) := by
    simpa only [pow_two] using hshift.mul h
  refine hprod.congr' ?_
  filter_upwards [hmiddle] with n hn
  field_simp [hn]

/-- The two source limits actually used by the rational gauge: the dominant
denominator step ratio and the combined `ζ(2) + ζ(3)` approximation ratio. -/
def zudilinSourceRatios (n : ℕ) : ℝ × ℝ :=
  (zudilinBReal (n + 1) / zudilinBReal n,
    zudilinM23Real n / zudilinBReal n)

/-- Zudilin's combined exact linear-form error for `ζ(2) + ζ(3)`. -/
def zudilinCombinedError (n : ℕ) : ℝ :=
  (Real.pi ^ 2 / 6 + zeta3) * zudilinBReal n - zudilinM23Real n

def zudilinZeta2Error (n : ℕ) : ℝ :=
  (Real.pi ^ 2 / 6) * zudilinBReal n - zudilinB₂Real n

def zudilinZeta3Error (n : ℕ) : ℝ :=
  zeta3 * zudilinBReal n - zudilinB₃Real n

theorem zudilinCombinedError_eq_add (n : ℕ) :
    zudilinCombinedError n =
      zudilinZeta2Error n + zudilinZeta3Error n := by
  simp only [zudilinCombinedError, zudilinZeta2Error, zudilinZeta3Error,
    zudilinBReal, zudilinB₂Real, zudilinB₃Real, zudilinM23Real,
    zudilinM23]
  push_cast
  ring

/-- Exact analytic transfer through the rational gauge.  The source input has
only the two independent limits that the proof uses; the two-step denominator
limit is derived above, and the numerator enters only through the sum of
Zudilin's two companions. -/
theorem problem27_of_source_ratios
    (μ L : ℝ) (hμ : 1 ≤ μ)
    (hB :
      Tendsto
        (fun n => zudilinBReal (n + 1) / zudilinBReal n)
        atTop (𝓝 μ))
    (hM :
      Tendsto
        (fun n => zudilinM23Real n / zudilinBReal n)
        atTop (𝓝 L)) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 L) := by
  let K : ℝ := (-13281 / 64) * μ ^ 2 + (47 / 8) * μ - 1
  have hμ0 : μ ≠ 0 := by linarith
  have hμ20 : μ ^ 2 ≠ 0 := pow_ne_zero _ hμ0
  have hKneg : K < 0 := by
    have hsq : μ ≤ μ ^ 2 := by nlinarith
    dsimp only [K]
    nlinarith
  have hK0 : K ≠ 0 := ne_of_lt hKneg

  have hB₂ :
      Tendsto
        (fun n => zudilinBReal (n + 2) / zudilinBReal n)
        atTop (𝓝 (μ ^ 2)) :=
    tendsto_two_step_ratio_of_tendsto_step_ratio hμ0 hB
  have hM₁ :
      Tendsto
        (fun n => zudilinM23Real (n + 1) / zudilinBReal (n + 1))
        atTop (𝓝 L) :=
    (tendsto_add_atTop_iff_nat 1).mpr hM
  have hM₂ :
      Tendsto
        (fun n => zudilinM23Real (n + 2) / zudilinBReal (n + 2))
        atTop (𝓝 L) :=
    (tendsto_add_atTop_iff_nat 2).mpr hM

  have hquot₁_ne :
      ∀ᶠ n in atTop, zudilinBReal (n + 1) / zudilinBReal n ≠ 0 :=
    hB.eventually_ne hμ0
  have hquot₂_ne :
      ∀ᶠ n in atTop, zudilinBReal (n + 2) / zudilinBReal n ≠ 0 :=
    hB₂.eventually_ne hμ20
  have hB0_ne : ∀ᶠ n in atTop, zudilinBReal n ≠ 0 :=
    hquot₁_ne.mono fun _ h => (div_ne_zero_iff.mp h).2
  have hB1_ne : ∀ᶠ n in atTop, zudilinBReal (n + 1) ≠ 0 :=
    hquot₁_ne.mono fun _ h => (div_ne_zero_iff.mp h).1
  have hB2_ne : ∀ᶠ n in atTop, zudilinBReal (n + 2) ≠ 0 :=
    hquot₂_ne.mono fun _ h => (div_ne_zero_iff.mp h).1

  have hdenExpr :
      Tendsto
        (fun n =>
          (gaugeR20 n : ℝ) * (zudilinBReal (n + 2) / zudilinBReal n)
            + (gaugeR21 n : ℝ) * (zudilinBReal (n + 1) / zudilinBReal n)
            + (gaugeR22 n : ℝ))
        atTop (𝓝 K) := by
    have h :=
      ((gaugeR20_tendsto.mul hB₂).add (gaugeR21_tendsto.mul hB)).add
        gaugeR22_tendsto
    simpa only [K] using h
  have hden :
      Tendsto
        (fun n => gaugeRow2Real zudilinB n / zudilinBReal n)
        atTop (𝓝 K) := by
    refine hdenExpr.congr' ?_
    filter_upwards [hB0_ne] with n hn
    have hn' : ((zudilinB n : ℚ) : ℝ) ≠ 0 := by
      simpa only [zudilinBReal] using hn
    simp only [gaugeRow2Real, gaugeRow2, zudilinBReal]
    push_cast
    field_simp [hn']

  have hnumExpr :
      Tendsto
        (fun n =>
          (gaugeR20 n : ℝ)
              * ((zudilinM23Real (n + 2) / zudilinBReal (n + 2))
                * (zudilinBReal (n + 2) / zudilinBReal n))
            + (gaugeR21 n : ℝ)
              * ((zudilinM23Real (n + 1) / zudilinBReal (n + 1))
                * (zudilinBReal (n + 1) / zudilinBReal n))
            + (gaugeR22 n : ℝ)
              * (zudilinM23Real n / zudilinBReal n))
        atTop (𝓝 (L * K)) := by
    have h :=
      ((gaugeR20_tendsto.mul (hM₂.mul hB₂)).add
        (gaugeR21_tendsto.mul (hM₁.mul hB))).add
          (gaugeR22_tendsto.mul hM)
    have hval :
        (-13281 / 64) * (L * μ ^ 2) + (47 / 8) * (L * μ)
            + (-1) * L =
          L * K := by
      dsimp only [K]
      ring
    rw [hval] at h
    exact h
  have hnum :
      Tendsto
        (fun n => gaugeRow2Real zudilinM23 n / zudilinBReal n)
        atTop (𝓝 (L * K)) := by
    refine hnumExpr.congr' ?_
    filter_upwards [hB0_ne, hB1_ne, hB2_ne] with n h0 h1 h2
    have h0' : ((zudilinB n : ℚ) : ℝ) ≠ 0 := by
      simpa only [zudilinBReal] using h0
    have h1' : ((zudilinB (n + 1) : ℚ) : ℝ) ≠ 0 := by
      simpa only [zudilinBReal] using h1
    have h2' : ((zudilinB (n + 2) : ℚ) : ℝ) ≠ 0 := by
      simpa only [zudilinBReal] using h2
    simp only [gaugeRow2Real, gaugeRow2, zudilinM23Real, zudilinBReal]
    push_cast
    field_simp [h0', h1', h2']

  have hnormalized := hnum.div hden hK0
  have hLK : L * K / K = L := by
    field_simp [hK0]
  rw [hLK] at hnormalized
  have hcore :
      Tendsto
        (fun n =>
          gaugeRow2Real zudilinM23 n / gaugeRow2Real zudilinB n)
        atTop (𝓝 L) := by
    refine hnormalized.congr' ?_
    filter_upwards [hB0_ne] with n hn
    change
      (gaugeRow2Real zudilinM23 n / zudilinBReal n)
          / (gaugeRow2Real zudilinB n / zudilinBReal n) =
        gaugeRow2Real zudilinM23 n / gaugeRow2Real zudilinB n
    field_simp [hn]
  refine hcore.congr' (Eventually.of_forall fun n => ?_)
  exact (challenge_ratio_eq_gaugeRow2 n).symm

/-- Strong analytic transfer: decay of the single combined Zudilin linear
form is enough.  No asymptotic for the denominator ratio is required.  The
exact recurrence proves geometric growth of `zudilinB`, and the limiting
gauge coefficients then force the transformed denominator to tend to
negative infinity. -/
theorem problem27_of_source_error
    (L : ℝ)
    (hError :
      Tendsto
        (fun n => L * zudilinBReal n - zudilinM23Real n)
        atTop (𝓝 0)) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 L) := by
  let E : ℕ → ℝ := fun n => L * zudilinBReal n - zudilinM23Real n
  have hE : Tendsto E atTop (𝓝 0) := by
    simpa only [E] using hError
  have hE₁ : Tendsto (fun n => E (n + 1)) atTop (𝓝 0) :=
    (tendsto_add_atTop_iff_nat 1).mpr hE
  have hE₂ : Tendsto (fun n => E (n + 2)) atTop (𝓝 0) :=
    (tendsto_add_atTop_iff_nat 2).mpr hE
  have hGaugeError :
      Tendsto
        (fun n =>
          (gaugeR20 n : ℝ) * E (n + 2)
            + (gaugeR21 n : ℝ) * E (n + 1)
            + (gaugeR22 n : ℝ) * E n)
        atTop (𝓝 0) := by
    simpa only [mul_zero, add_zero] using
      ((gaugeR20_tendsto.mul hE₂).add
        (gaugeR21_tendsto.mul hE₁)).add
          (gaugeR22_tendsto.mul hE)
  have hDenInv :
      Tendsto
        (fun n => (gaugeRow2Real zudilinB n)⁻¹)
        atTop (𝓝 0) :=
    tendsto_inv_atBot_zero.comp gaugeRow2Real_zudilinB_tendsto_atBot
  have hErrorRatio :
      Tendsto
        (fun n =>
          ((gaugeR20 n : ℝ) * E (n + 2)
              + (gaugeR21 n : ℝ) * E (n + 1)
              + (gaugeR22 n : ℝ) * E n)
            / gaugeRow2Real zudilinB n)
        atTop (𝓝 0) := by
    simpa only [div_eq_mul_inv, mul_zero] using hGaugeError.mul hDenInv
  have hLimit :
      Tendsto
        (fun n =>
          L -
            ((gaugeR20 n : ℝ) * E (n + 2)
                + (gaugeR21 n : ℝ) * E (n + 1)
                + (gaugeR22 n : ℝ) * E n)
              / gaugeRow2Real zudilinB n)
        atTop (𝓝 L) := by
    simpa only [sub_zero] using tendsto_const_nhds.sub hErrorRatio
  have hDenNeg :
      ∀ᶠ n in atTop, gaugeRow2Real zudilinB n < 0 :=
    (tendsto_atBot.mp gaugeRow2Real_zudilinB_tendsto_atBot (-1)).mono
      fun _ hn => hn.trans_lt (by norm_num)
  refine hLimit.congr' ?_
  filter_upwards [hDenNeg] with n hn
  rw [challenge_ratio_eq_gaugeRow2]
  have hden0 : gaugeRow2Real zudilinB n ≠ 0 := ne_of_lt hn
  simp only [gaugeRow2Real, gaugeRow2] at hden0
  push_cast at hden0
  simp only [E, gaugeRow2Real, gaugeRow2, zudilinBReal,
    zudilinM23Real]
  push_cast
  field_simp [hden0, Nat.add_comm]
  ring

/-- Problem 2.7 from the equivalent joint source-ratio limit. -/
theorem problem27_zeta2_add_zeta3_of_joint_ratios
    (μ : ℝ) (hμ : 1 ≤ μ)
    (hSource :
      Tendsto zudilinSourceRatios atTop
        (𝓝 (μ, Real.pi ^ 2 / 6 + zeta3))) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 (Real.pi ^ 2 / 6 + zeta3)) := by
  apply problem27_of_source_ratios μ (Real.pi ^ 2 / 6 + zeta3) hμ
  · simpa only [zudilinSourceRatios] using hSource.fst_nhds
  · simpa only [zudilinSourceRatios] using hSource.snd_nhds

/-- Problem 2.7 from the single analytic input stated by Zudilin's
hypergeometric construction: the combined exact linear-form error tends to
zero.  All denominator growth and noncancellation needed by the gauge are
proved in this file from the exact recurrence. -/
theorem problem27_zeta2_add_zeta3
    (hError : Tendsto zudilinCombinedError atTop (𝓝 0)) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 (Real.pi ^ 2 / 6 + zeta3)) := by
  apply problem27_of_source_error (Real.pi ^ 2 / 6 + zeta3)
  simpa only [zudilinCombinedError] using hError

/-- Direct interface to the two error estimates printed in Zudilin's
Theorem 2. -/
theorem problem27_zeta2_add_zeta3_of_zudilin_errors
    (hZeta2Error : Tendsto zudilinZeta2Error atTop (𝓝 0))
    (hZeta3Error : Tendsto zudilinZeta3Error atTop (𝓝 0)) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 (Real.pi ^ 2 / 6 + zeta3)) := by
  apply problem27_zeta2_add_zeta3
  have heq :
      zudilinCombinedError =
        fun n => zudilinZeta2Error n + zudilinZeta3Error n :=
    funext zudilinCombinedError_eq_add
  rw [heq]
  simpa only [add_zero] using hZeta2Error.add hZeta3Error

/-- Backwards-compatible decomposition of the joint source asymptotic into
Zudilin's two separately named approximation ratios.  No independent
two-step denominator hypothesis is needed. -/
theorem problem27_zeta2_add_zeta3_of_separate_limits
    (μ : ℝ) (hμ : 1 ≤ μ)
    (hB :
      Tendsto
        (fun n => zudilinBReal (n + 1) / zudilinBReal n)
        atTop (𝓝 μ))
    (hZeta2 :
      Tendsto
        (fun n => zudilinB₂Real n / zudilinBReal n)
        atTop (𝓝 (Real.pi ^ 2 / 6)))
    (hZeta3 :
      Tendsto
        (fun n => zudilinB₃Real n / zudilinBReal n)
        atTop (𝓝 zeta3)) :
    Tendsto
      (fun n => (challengeP n : ℝ) / (challengeQ n : ℝ))
      atTop (𝓝 (Real.pi ^ 2 / 6 + zeta3)) := by
  have hM :
      Tendsto
        (fun n => zudilinM23Real n / zudilinBReal n)
        atTop (𝓝 (Real.pi ^ 2 / 6 + zeta3)) := by
    have h := hZeta2.add hZeta3
    have heq :
        (fun n => zudilinM23Real n / zudilinBReal n) =
          (fun n =>
            zudilinB₂Real n / zudilinBReal n
              + zudilinB₃Real n / zudilinBReal n) := by
      funext n
      simp only [zudilinM23Real, zudilinBReal, zudilinB₂Real,
        zudilinB₃Real, zudilinM23]
      push_cast
      ring
    rw [heq]
    exact h
  exact problem27_of_source_ratios μ _ hμ hB hM

end RamanujanChallenge.P27

end
