// Q4279: exact candidate-first search for an actual selected q6 Apéry leaf.
// Dedicated computation-branch artifact; no project source is modified.
// C++17 standard library only. Optional parallelism uses std::thread.

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <mutex>
#include <numeric>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <tuple>
#include <utility>
#include <vector>

namespace fs = std::filesystem;
namespace {
using u32=std::uint32_t; using u64=std::uint64_t; using i64=std::int64_t; using u128=__uint128_t;

struct Opt { u32 qlo=1000000,qhi=1250000,threads=0,block=25000; std::string out="q4279-out"; };
Opt opts(int ac,char**av){ Opt o; for(int i=1;i<ac;++i){std::string a=av[i]; auto need=[&](){if(++i>=ac)throw std::runtime_error("missing value");return std::string(av[i]);}; if(a=="--qmin-exclusive")o.qlo=std::stoul(need()); else if(a=="--qmax")o.qhi=std::stoul(need()); else if(a=="--threads")o.threads=std::stoul(need()); else if(a=="--block-width")o.block=std::stoul(need()); else if(a=="--out")o.out=need(); else if(a=="-h"||a=="--help"){std::cout<<"q4279_scan --qmin-exclusive N --qmax N [--threads N] [--block-width N] [--out DIR]\n";std::exit(0);} else throw std::runtime_error("unknown option "+a);} if(o.qhi<=o.qlo)throw std::runtime_error("qmax must exceed qmin-exclusive"); if(o.qhi>=20000000U)throw std::runtime_error("certified release cap is qmax<20000000"); if(!o.threads)o.threads=std::max(1u,std::thread::hardware_concurrency()); if(!o.block)o.block=25000; return o; }

std::vector<u32> primes_to(u32 n){ std::vector<std::uint8_t> c(n/2+1); u32 r=std::sqrt((long double)n); for(u32 p=3;p<=r;p+=2)if(!c[p>>1])for(u64 k=u64(p)*p;k<=n;k+=2ULL*p)c[k>>1]=1; std::vector<u32> v; if(n>=2)v.push_back(2); for(u32 x=3;x<=n;x+=2)if(!c[x>>1])v.push_back(x); return v; }

struct Mont {
 u32 p,nprime,r2;
 explicit Mont(u32 q):p(q){ if(!(p&1)||p>=(1U<<30))throw std::runtime_error("Mont modulus domain"); u32 x=p; for(int i=0;i<5;++i)x*=2-p*x; nprime=0U-x; r2=(u64(1ULL<<32)%p)*(u64(1ULL<<32)%p)%p; }
 inline u32 red(u64 t)const{u32 m=u32(t)*nprime;u64 u=(t+u64(m)*p)>>32;return u>=p?u-p:u;}
 inline u32 mul(u32 a,u32 b)const{return red(u64(a)*b);} inline u32 to(u32 a)const{return mul(a%p,r2);} inline u32 from(u32 a)const{return red(a);}
 inline u32 add(u32 a,u32 b)const{u32 s=a+b;return s>=p?s-p:s;} inline u32 sub(u32 a,u32 b)const{return a>=b?a-b:u32(u64(a)+p-b);}
};
inline void advance(const Mont&m,std::array<u32,4>&P,std::array<u32,7>&S){P[0]=m.add(P[0],P[1]);P[1]=m.add(P[1],P[2]);P[2]=m.add(P[2],P[3]);for(int i=0;i<6;++i)S[i]=m.add(S[i],S[i+1]);}
std::vector<u32> zeros_fast(u32 p,u64*steps=nullptr){ Mont m{p}; std::array<u32,4>P={m.to(117),m.to(418),m.to(510),m.to(204)}; std::array<u32,7>S={m.to(1),m.to(63),m.to(602),m.to(2100),m.to(3360),m.to(2520),m.to(720)}; u32 y0=m.to(1),y1=m.to(5),mid=(p-1)/2; std::vector<u32> lo; u64 st=0; for(u32 n=1;n<mid;++n){u32 y2=m.sub(m.mul(P[0],y1),m.mul(S[0],y0));++st;if(!m.from(y2))lo.push_back(n+1);y0=y1;y1=y2;advance(m,P,S);} std::vector<u32> z;z.reserve(2*lo.size());for(u32 r:lo){z.push_back(r);u32 s=p-1-r;if(s!=r)z.push_back(s);}std::sort(z.begin(),z.end());if(steps)*steps=st;return z;}
u64 ppoly(u64 n){return(2*n+1)*(17*n*n+17*n+5);} u64 modpow(u64 a,u64 e,u64 p){u64 r=1;while(e){if(e&1)r=u128(r)*a%p;a=u128(a)*a%p;e>>=1;}return r;}
std::vector<u32> zeros_full(u32 p){std::vector<u32>z;u64 b0=1%p,b1=5%p;if(!b0)z.push_back(0);if(!b1)z.push_back(1);for(u32 n=1;n<=p-2;++n){u64 n3=u128(n)*n%p*n%p,rhs=(u128(ppoly(n)%p)*b1+p-u128(n3)*b0%p)%p,den=u128(n+1)*(n+1)%p*(n+1)%p,b2=u128(rhs)*modpow(den,p-2,p)%p;if(!b2)z.push_back(n+1);b0=b1;b1=b2;}return z;}
bool has(const std::vector<u32>&z,u32 x){return std::binary_search(z.begin(),z.end(),x);}

struct Raw{char s;u32 q,t,p,r,a;};
bool operator<(const Raw&x,const Raw&y){return std::tie(x.q,x.t,x.p,x.s,x.r,x.a)<std::tie(y.q,y.t,y.p,y.s,y.r,y.a);} bool operator==(const Raw&x,const Raw&y){return std::tie(x.q,x.t,x.p,x.s,x.r,x.a)==std::tie(y.q,y.t,y.p,y.s,y.r,y.a);}
struct Occ{u32 q=0,t=0,p=0,r=0; i64 ap=-1,am=-1; bool rp=false,rm=false; char sign()const{return rm?'-':'+';} u64 raw_count()const{return rp+rm;} };

struct Proj {u64 primes=0,eligible=0,pairs=0,parity=0,gap=0,pint=0,pprime=0,mint=0,mprime=0;};
std::vector<Raw> project(const std::vector<u32>&pr,const std::vector<std::int32_t>&ix,const std::vector<std::vector<u32>>&Z,u32 pmin,u32 qlo,u32 qhi,Proj&st){std::vector<Raw>h;auto it=std::lower_bound(pr.begin(),pr.end(),pmin);for(;it!=pr.end();++it){u32 p=*it;const auto&z=Z[ix[p]];++st.primes;if(z.size()<3)continue;if(z.size()==3&&!has(z,(p-1)/2))continue;++st.eligible;for(u32 r:z)for(u32 a:z){++st.pairs;if(((r^a)&1U)==0){++st.parity;continue;}if(std::llabs(i64(r)-i64(a))<3){++st.gap;continue;}
 i64 np=7LL*p-r+a;if(np%6==0){++st.pint;i64 q=np/6,t=2LL*r-a-p;if(q>qlo&&q<=qhi&&t>=0&&t<q&&ix[q]>=0){++st.pprime;i64 n=6*q+t,N=12*q+t;if(n-6LL*p!=r||N-13LL*p!=a||n>=7LL*p||N<13LL*p||N>=14LL*p)throw std::runtime_error("plus inverse/window");h.push_back({'+',u32(q),u32(t),p,r,a});}}
 i64 dm=r+a+1;if(dm%7==0){i64 tn=r-6LL*a-6;if(tn%7==0){++st.mint;i64 q=p+dm/7,t=tn/7;if(q>qlo&&q<=qhi&&t>=0&&t<q&&ix[q]>=0){++st.mprime;i64 n=6*q+t,s=q-1-t;if(n-6LL*p!=r||s-i64(p)!=a||n>=7LL*p||s<p||s>=2LL*p)throw std::runtime_error("minus inverse/window");h.push_back({'-',u32(q),u32(t),p,r,a});}}}
 }}std::sort(h.begin(),h.end());h.erase(std::unique(h.begin(),h.end()),h.end());return h;}
std::vector<Occ> merge(const std::vector<Raw>&h){std::vector<Occ>v;for(std::size_t i=0;i<h.size();){std::size_t j=i;Occ o;o.q=h[i].q;o.t=h[i].t;o.p=h[i].p;o.r=h[i].r;while(j<h.size()&&h[j].q==o.q&&h[j].t==o.t&&h[j].p==o.p){if(h[j].s=='+'){o.rp=true;o.ap=h[j].a;}else{o.rm=true;o.am=h[j].a;}++j;}v.push_back(o);i=j;}std::sort(v.begin(),v.end(),[](auto&a,auto&b){return std::tie(a.q,a.t,a.sign(),a.p)<std::tie(b.q,b.t,b.sign(),b.p);});return v;}

struct Near{i64 lin=-1,cyc=-1,zero=-1;}; Near nearest(u32 q,u32 t,const std::vector<u32>&z){Near n;if(z.empty())return n;for(u32 x:z){i64 d=std::llabs(i64(t)-x),c=std::min<i64>(d,i64(q)-d);if(n.lin<0||d<n.lin){n.lin=d;n.zero=x;}if(n.cyc<0||c<n.cyc)n.cyc=c;}return n;}
struct Check{u64 mont=0,mfail=0,full=0,rfail=0,states=0,leaves=0,cgen=0,cdirect=0,cmis=0;};
Check validate(){Check c;auto pr=primes_to(5000);std::vector<std::int32_t>ix(5001,-1);for(std::size_t i=0;i<pr.size();++i)ix[pr[i]]=i;std::vector<std::vector<u32>>Z(pr.size());for(std::size_t i=0;i<pr.size();++i){u32 p=pr[i];if(p<7)continue;Mont m{p};for(u32 a=0;a<std::min<u32>(p,40);++a)for(u32 b=0;b<std::min<u32>(p,40);++b){++c.mont;if(m.from(m.mul(m.to(a),m.to(b)))!=u64(a)*b%p)++c.mfail;}Z[i]=zeros_fast(p);if(p<=300){++c.full;if(Z[i]!=zeros_full(p))++c.rfail;}if(p>=17)c.states+=Z[i].size();}
 Proj ps;auto rh=project(pr,ix,Z,17,16,5000,ps);auto oc=merge(rh);c.cgen=oc.size();for(const auto&o:oc)if(has(Z[ix[o.q]],o.t))++c.leaves;
 std::set<std::tuple<char,u32,u32,u32>>direct;for(u32 q:pr)if(q>=17)for(u32 t:Z[ix[q]]){u64 n=6ULL*q+t,N=12ULL*q+t,s=q-1-t;for(u32 p:pr){if(p<17||p>=q||n>=7ULL*p)continue;u32 r=u32(n-6ULL*p);if(!has(Z[ix[p]],r))continue;bool rm=false,rp=false;if(p<=s){u32 a=s-p;if(a<p&&has(Z[ix[p]],a))rm=true;}if(13ULL*p<=N&&N<14ULL*p){u32 a=u32(N-13ULL*p);if(has(Z[ix[p]],a))rp=true;}if(rm)direct.insert({'-',q,t,p});else if(rp)direct.insert({'+',q,t,p});}}
 c.cdirect=direct.size();std::set<std::tuple<char,u32,u32,u32>>gen;for(const auto&o:oc)if(has(Z[ix[o.q]],o.t))gen.insert({o.sign(),o.q,o.t,o.p});if(gen!=direct)c.cmis=1;if(c.mfail||c.rfail||c.states!=605||c.leaves||c.cmis)throw std::runtime_error("release validation failure");return c;}

struct Block{u32 lo=0,hi=0;u64 primes=0,qz=0,qa=0,sumz=0,suma=0,occ=0,hits=0,maxz=0,maxa=0,maxk=0;long double heur=0;std::vector<double>norm;std::vector<i64>lin;};
template<class T>double med(std::vector<T>v){if(v.empty())return std::numeric_limits<double>::quiet_NaN();std::sort(v.begin(),v.end());return v.size()%2?double(v[v.size()/2]):(double(v[v.size()/2-1])+double(v[v.size()/2]))/2;}
std::string u128s(u128 x){if(!x)return"0";std::string s;while(x){s.push_back(char('0'+int(x%10)));x/=10;}std::reverse(s.begin(),s.end());return s;}
}

int main(int ac,char**av){try{Opt o=opts(ac,av);fs::create_directories(o.out);auto T0=std::chrono::steady_clock::now();std::cerr<<"VALIDATE_BEGIN\n";Check ck=validate();std::cerr<<"VALIDATE_OK candidates="<<ck.cgen<<"\n";u32 qstart=o.qlo+1,pmin=u32(6ULL*qstart/7+1);auto pr=primes_to(o.qhi);std::vector<std::int32_t>ix(o.qhi+1,-1);for(std::size_t i=0;i<pr.size();++i)ix[pr[i]]=i;std::size_t first=std::lower_bound(pr.begin(),pr.end(),pmin)-pr.begin(),tasks=pr.size()-first;std::vector<std::vector<u32>>Z(pr.size());std::atomic<std::size_t>cur{0},done{0};std::atomic<u64>steps{0},zrec{0};std::mutex pm;auto zs=std::chrono::steady_clock::now();auto work=[&](){u64 ls=0,lz=0;for(;;){std::size_t k=cur.fetch_add(1);if(k>=tasks)break;std::size_t i=pr.size()-1-k;u64 st=0;Z[i]=zeros_fast(pr[i],&st);ls+=st;lz+=Z[i].size();std::size_t d=done.fetch_add(1)+1;if(d%5000==0||d==tasks){steps.fetch_add(ls);zrec.fetch_add(lz);ls=lz=0;std::lock_guard<std::mutex>g(pm);std::cerr<<"ZERO_PROGRESS "<<d<<'/'<<tasks<<" elapsed="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-zs).count()<<"\n";}}steps.fetch_add(ls);zrec.fetch_add(lz);};std::vector<std::thread>th;for(u32 i=0;i<o.threads;++i)th.emplace_back(work);for(auto&t:th)t.join();double zsec=std::chrono::duration<double>(std::chrono::steady_clock::now()-zs).count();
 u64 refl=0,rf=0,cons=0,cf=0,ge3=0,ge4=0,maxz=0,maxzp=0;for(std::size_t i=first;i<pr.size();++i){auto&z=Z[i];if(z.size()>=3)++ge3;if(z.size()>=4)++ge4;if(z.size()>maxz){maxz=z.size();maxzp=pr[i];}for(u32 r:z){++refl;if(!has(z,pr[i]-1-r))++rf;}for(std::size_t j=1;j<z.size();++j){++cons;if(z[j]==z[j-1]+1)++cf;}}if(rf||cf)throw std::runtime_error("large zero validation");
 Proj ps;auto raw=project(pr,ix,Z,pmin,o.qlo,o.qhi,ps);auto oc=merge(raw);u64 rawp=0,rawm=0,over=0,asp=0,asm=0;for(auto&x:oc){rawp+=x.rp;rawm+=x.rm;over+=x.rp&&x.rm;if(x.sign()=='+')++asp;else++asm;}
 std::ofstream coutf(fs::path(o.out)/"candidate_occurrences.csv");coutf<<"sign,q,t,p,r,a_plus,a_minus,raw_plus,raw_minus,zq,selected,nearest_zero,linear,cyclic\n";std::ofstream qf(fs::path(o.out)/"q_stats.csv");qf<<"q,Z,A,Ap,Am,rawO,O,Kpre,Ksel,actualP,actualM,dlin,dcyc,scaled,heur\n";std::ofstream zcf(fs::path(o.out)/"prime_zero_counts.csv");zcf<<"p,Z\n";std::ofstream zrf(fs::path(o.out)/"zero_records.csv");zrf<<"p,r\n";for(std::size_t i=first;i<pr.size();++i){zcf<<pr[i]<<','<<Z[i].size()<<'\n';for(u32 r:Z[i])zrf<<pr[i]<<','<<r<<'\n';}
 std::size_t nb=(o.qhi-o.qlo+o.block-1)/o.block;std::vector<Block>B(nb);for(std::size_t b=0;b<nb;++b){B[b].lo=o.qlo+b*o.block;B[b].hi=std::min<u32>(o.qhi,B[b].lo+o.block);}struct NR{u32 q,t,p;char s;i64 z,lin,cyc;u32 zc;bool hit;};std::vector<NR>near;std::vector<Occ>wit;std::size_t cp=0;u64 up=0,qA=0,sumA=0,maxK=0,maxKs=0,maxA=0,maxAq=0;long double H=0;qf<<std::setprecision(17);coutf<<std::setprecision(17);
 for(std::size_t qi=std::lower_bound(pr.begin(),pr.end(),qstart)-pr.begin();qi<pr.size();++qi){u32 q=pr[qi];++up;while(cp<oc.size()&&oc[cp].q<q)++cp;std::size_t b0=cp;while(cp<oc.size()&&oc[cp].q==q)++cp,b1=cp;const auto&zq=Z[qi];std::vector<u32>au,ap,am;u64 rawO=0,actp=0,actm=0,Kpre=0,Ksel=0;i64 dl=-1,dc=-1;std::map<std::pair<u32,char>,std::pair<u64,u64>>fib;for(std::size_t k=b0;k<b1;++k){auto&x=oc[k];bool sel=has(zq,x.t);Near n=nearest(q,x.t,zq);au.push_back(x.t);(x.sign()=='+'?ap:am).push_back(x.t);rawO+=x.raw_count();auto&f=fib[{x.t,x.sign()}];++f.first;if(sel)++f.second;if(sel){wit.push_back(x);if(x.sign()=='+')++actp;else++actm;}if(n.lin>=0&&(dl<0||n.lin<dl))dl=n.lin;if(n.cyc>=0&&(dc<0||n.cyc<dc))dc=n.cyc;near.push_back({q,x.t,x.p,x.sign(),n.zero,n.lin,n.cyc,u32(zq.size()),sel});coutf<<x.sign()<<','<<q<<','<<x.t<<','<<x.p<<','<<x.r<<','<<x.ap<<','<<x.am<<','<<x.rp<<','<<x.rm<<','<<zq.size()<<','<<sel<<','<<n.zero<<','<<n.lin<<','<<n.cyc<<'\n';}auto un=[](auto&v){std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());};un(au);un(ap);un(am);for(auto&kv:fib){Kpre=std::max(Kpre,kv.second.first);Ksel=std::max(Ksel,kv.second.second);}if(!au.empty())++qA;sumA+=au.size();if(au.size()>maxA){maxA=au.size();maxAq=q;}maxK=std::max(maxK,Kpre);maxKs=std::max(maxKs,Ksel);long double heur=static_cast<long double>(au.size())*zq.size()/q;H+=heur;double scaled=(dc>=0&&!zq.empty())?2.0*zq.size()*dc/q:-1;qf<<q<<','<<zq.size()<<','<<au.size()<<','<<ap.size()<<','<<am.size()<<','<<rawO<<','<<(b1-b0)<<','<<Kpre<<','<<Ksel<<','<<actp<<','<<actm<<','<<dl<<','<<dc<<','<<scaled<<','<<double(heur)<<'\n';Block&bb=B[std::min<std::size_t>(nb-1,(q-qstart)/o.block)];++bb.primes;bb.sumz+=zq.size();bb.suma+=au.size();bb.occ+=b1-b0;bb.hits+=actp+actm;bb.maxz=std::max<u64>(bb.maxz,zq.size());bb.maxa=std::max<u64>(bb.maxa,au.size());bb.maxk=std::max(bb.maxk,Kpre);if(!zq.empty())++bb.qz;if(!au.empty())++bb.qa;bb.heur+=heur;if(dl>=0){bb.lin.push_back(dl);bb.norm.push_back(double(dl)/q);} }
 std::sort(near.begin(),near.end(),[](auto&a,auto&b){i64 x=a.cyc<0?std::numeric_limits<i64>::max():a.cyc,y=b.cyc<0?std::numeric_limits<i64>::max():b.cyc;return std::tie(x,a.q,a.t,a.p,a.s)<std::tie(y,b.q,b.t,b.p,b.s);});std::ofstream nf(fs::path(o.out)/"near_misses.csv");nf<<"rank,cyclic,linear,nearest_zero,sign,q,t,p,Z,selected\n";for(std::size_t i=0;i<near.size();++i){auto&x=near[i];nf<<i+1<<','<<x.cyc<<','<<x.lin<<','<<x.z<<','<<x.s<<','<<x.q<<','<<x.t<<','<<x.p<<','<<x.zc<<','<<x.hit<<'\n';}
 std::ofstream bf(fs::path(o.out)/"block_stats.csv");bf<<"lo_exclusive,hi_inclusive,primes,qZ,qA,sumZ,sumA,occ,hits,maxZ,maxA,maxK,meanZ,meanA,meanAlog,heur_sum,heur_log,heur_log2,median_linear,median_norm\n";bf<<std::setprecision(17);for(auto&b:B)if(b.primes){long double mid=(b.lo+b.hi)/2.0L,L=std::log(mid),mz=static_cast<long double>(b.sumz)/b.primes,ma=static_cast<long double>(b.suma)/b.primes;bf<<b.lo<<','<<b.hi<<','<<b.primes<<','<<b.qz<<','<<b.qa<<','<<b.sumz<<','<<b.suma<<','<<b.occ<<','<<b.hits<<','<<b.maxz<<','<<b.maxa<<','<<b.maxk<<','<<double(mz)<<','<<double(ma)<<','<<double(ma*L)<<','<<double(b.heur)<<','<<double(b.heur*L)<<','<<double(b.heur*L*L)<<','<<med(b.lin)<<','<<med(b.norm)<<'\n';}
 std::ofstream wf(fs::path(o.out)/"witnesses.txt");if(wit.empty()){wf<<"NO RAW MINUS-FIRST SELECTED q6 LEAF FOUND FOR "<<o.qlo<<" < q <= "<<o.qhi<<"; p >= "<<pmin<<".\nFINITE EXHAUSTED RANGE, NOT A THEOREM.\n";}else for(auto&x:wit)wf<<x.sign()<<" q="<<x.q<<" t="<<x.t<<" p="<<x.p<<" r="<<x.r<<" ap="<<x.ap<<" am="<<x.am<<'\n';wf<<"MAX_PREMARK_K="<<maxK<<"\nMAX_SELECTED_K="<<maxKs<<'\n';
 double total=std::chrono::duration<double>(std::chrono::steady_clock::now()-T0).count();std::ofstream mf(fs::path(o.out)/"manifest.json");mf<<std::setprecision(17)<<"{\n  \"qmin_exclusive\": "<<o.qlo<<",\n  \"qmax\": "<<o.qhi<<",\n  \"pmin_complete\": "<<pmin<<",\n  \"threads\": "<<o.threads<<",\n  \"upper_primes\": "<<up<<",\n  \"lower_primes_scanned\": "<<tasks<<",\n  \"recurrence_steps\": \""<<steps.load()<<"\",\n  \"zero_records\": "<<zrec.load()<<",\n  \"eligible_Z_ge_3\": "<<ge3<<",\n  \"eligible_Z_ge_4\": "<<ge4<<",\n  \"max_Z\": "<<maxz<<",\n  \"max_Z_prime\": "<<maxzp<<",\n  \"raw_plus\": "<<rawp<<",\n  \"raw_minus\": "<<rawm<<",\n  \"raw_overlap\": "<<over<<",\n  \"assigned_plus\": "<<asp<<",\n  \"assigned_minus\": "<<asm<<",\n  \"candidate_states\": "<<sumA<<",\n  \"q_with_candidates\": "<<qA<<",\n  \"actual_leaf_occurrences\": "<<wit.size()<<",\n  \"max_premark_K\": "<<maxK<<",\n  \"max_selected_K\": "<<maxKs<<",\n  \"max_Aq\": "<<maxA<<",\n  \"max_Aq_prime\": "<<maxAq<<",\n  \"heuristic_sum\": "<<double(H)<<",\n  \"zero_seconds\": "<<zsec<<",\n  \"total_seconds\": "<<total<<",\n  \"steps_per_second\": "<<double(steps.load())/zsec<<",\n  \"projection\": {\"primes\": "<<ps.primes<<", \"eligible\": "<<ps.eligible<<", \"ordered_pairs\": "<<ps.pairs<<", \"parity_pruned\": "<<ps.parity<<", \"gap_pruned\": "<<ps.gap<<", \"plus_integral\": "<<ps.pint<<", \"plus_prime\": "<<ps.pprime<<", \"minus_integral\": "<<ps.mint<<", \"minus_prime\": "<<ps.mprime<<"},\n  \"checks\": {\"montgomery_products\": "<<ck.mont<<", \"montgomery_failures\": "<<ck.mfail<<", \"full_crosschecks\": "<<ck.full<<", \"recurrence_failures\": "<<ck.rfail<<", \"selected_states_le_5000\": "<<ck.states<<", \"selected_leaves_le_5000\": "<<ck.leaves<<", \"candidate_generated\": "<<ck.cgen<<", \"candidate_direct\": "<<ck.cdirect<<", \"candidate_mismatch\": "<<ck.cmis<<", \"reflection_checks\": "<<refl<<", \"reflection_failures\": "<<rf<<", \"consecutive_checks\": "<<cons<<", \"consecutive_failures\": "<<cf<<"},\n  \"complexity\": \"Theta(sum_{p in forced range} p/2 + sum_p |Z_p|^2)\"\n}\n";
 std::ofstream sf(fs::path(o.out)/"summary.md");sf<<"# Q4279 finite exact scan\n\n- Range: `"<<o.qlo<<" < q <= "<<o.qhi<<"`.\n- Complete lower range: `p >= "<<pmin<<"`.\n- Recurrence steps: `"<<steps.load()<<"`.\n- Wall clock: `"<<total<<" s`.\n- Candidate states: `"<<sumA<<"`.\n- Actual leaf occurrences: `"<<wit.size()<<"`.\n- Max pre-mark K: `"<<maxK<<"`.\n- Heuristic sum: `"<<double(H)<<"`.\n\nFinite computation, not a theorem.\n";
 std::cout<<"Q4279_COMPLETE qlo="<<o.qlo<<" qhi="<<o.qhi<<" steps="<<steps.load()<<" candidates="<<sumA<<" leaves="<<wit.size()<<" maxK="<<maxK<<" seconds="<<total<<"\n";return 0;
}catch(const std::exception&e){std::cerr<<"Q4279_FATAL "<<e.what()<<'\n';return 2;}}
