#!/usr/bin/env sage
"""P2.7: Search for rational function r_{n+1}/r_n where r_n = q_n/W_n."""


# This file was *autogenerated* from the file scripts/p27_ratio_pade.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_128 = Integer(128); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_16 = Integer(16); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_1 = Integer(1); _sage_const_28 = Integer(28); _sage_const_250 = Integer(250); _sage_const_8 = Integer(8); _sage_const_22 = Integer(22); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_256 = Integer(256); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_20 = Integer(20); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10)
# Problem 2.7 recurrence coefficients
def A27(n):
    return _sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B27(n):
    P6 = _sage_const_104060 *n**_sage_const_6 +_sage_const_1745370 *n**_sage_const_5 +_sage_const_12145238 *n**_sage_const_4 +_sage_const_44886481 *n**_sage_const_3 +_sage_const_92943995 *n**_sage_const_2 +_sage_const_102256019 *n+_sage_const_46709052
    return _sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *P6

def C27(n):
    P5 = _sage_const_3784 *n**_sage_const_5 +_sage_const_57792 *n**_sage_const_4 +_sage_const_351019 *n**_sage_const_3 +_sage_const_1059230 *n**_sage_const_2 +_sage_const_1587211 *n+_sage_const_944620
    return _sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *P5

def D27(n):
    return (n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *n**_sage_const_2 +_sage_const_4515 *n+_sage_const_5399 )

# Cooper T_k
T = [QQ(_sage_const_1 ), QQ(_sage_const_4 ), QQ(_sage_const_28 )]
for k in range(_sage_const_2 , _sage_const_250 ):
    t = (_sage_const_2 *(_sage_const_2 *k+_sage_const_1 )*(_sage_const_5 *k**_sage_const_2 +_sage_const_5 *k+_sage_const_2 )*T[k] - _sage_const_8 *k*(_sage_const_7 *k**_sage_const_2 +_sage_const_1 )*T[k-_sage_const_1 ] + _sage_const_22 *k*(_sage_const_2 *k-_sage_const_1 )*(k-_sage_const_1 )*T[k-_sage_const_2 ]) / (k+_sage_const_1 )**_sage_const_3
    T.append(t)

# W_n
NMAX = _sage_const_60
W = []
for n in range(NMAX):
    val = QQ(_sage_const_0 )
    for j in range(min(_sage_const_2 *n+_sage_const_1 , len(T))):
        val += binomial(_sage_const_2 *n, j) * QQ(-_sage_const_2 )**(_sage_const_2 *n-j) * T[j]
    W.append(val / QQ(_sage_const_256 )**n)

# q_n
q = [QQ(-_sage_const_215040420000 ), QQ(-_sage_const_167282265043404 )/QQ(_sage_const_905 ), QQ(-_sage_const_964185327658080 )/QQ(_sage_const_6071 )]
for n in range(_sage_const_2 , NMAX-_sage_const_1 ):
    q_next = (B27(n)*q[n] - C27(n)*q[n-_sage_const_1 ] + D27(n)*q[n-_sage_const_2 ]) / A27(n)
    q.append(q_next)

# r_n = q_n / W_n
r = [q[n]/W[n] for n in range(min(len(q), len(W)))]

# Consecutive ratios rr_n = r_{n+1}/r_n
rr = [r[n+_sage_const_1 ]/r[n] for n in range(len(r)-_sage_const_1 )]

print("=== r_{n+1}/r_n ===", flush=True)
for n in range(min(_sage_const_20 , len(rr))):
    print(f"  n={n}: {float(rr[n]):.15f}")

# Padé search: rr_n = P(n)/Q(n)
R_poly = PolynomialRing(QQ, names=('x',)); (x,) = R_poly._first_ngens(1)

for d in range(_sage_const_1 , _sage_const_12 ):
    n_unk = _sage_const_2 *d + _sage_const_1
    n_pts = min(n_unk + _sage_const_5 , len(rr) - _sage_const_2 )
    if n_pts < n_unk:
        print(f"  d={d}: not enough data"); break

    M = matrix(QQ, n_pts, n_unk)
    b = vector(QQ, n_pts)
    for i in range(n_pts):
        nn = QQ(i + _sage_const_1 )
        for k in range(d+_sage_const_1 ):
            M[i, k] = -nn**k
        for k in range(d):
            M[i, d+_sage_const_1 +k] = rr[i+_sage_const_1 ] * nn**k
        b[i] = -rr[i+_sage_const_1 ] * nn**d

    try:
        sol = M.solve_right(b)
    except ValueError:
        print(f"  d={d}: no solution"); continue

    # Verify holdout
    ok = True
    for i in range(n_pts, min(n_pts+_sage_const_10 , len(rr)-_sage_const_1 )):
        nn = QQ(i+_sage_const_1 )
        P_val = sum(sol[k]*nn**k for k in range(d+_sage_const_1 ))
        Q_val = nn**d + sum(sol[d+_sage_const_1 +k]*nn**k for k in range(d))
        if Q_val == _sage_const_0  or P_val/Q_val != rr[i+_sage_const_1 ]:
            ok = False; break

    if ok:
        P_poly = sum(sol[k]*x**k for k in range(d+_sage_const_1 ))
        Q_poly = x**d + sum(sol[d+_sage_const_1 +k]*x**k for k in range(d))
        print(f"\n*** MATCH at degree {d}: r_{{n+1}}/r_n = P(n)/Q(n) ***")
        print(f"  P(n) = {P_poly}")
        print(f"  Q(n) = {Q_poly}")
        print(f"  P factors: {P_poly.factor()}")
        print(f"  Q factors: {Q_poly.factor()}")

        # Full verification
        all_ok = True
        for i in range(_sage_const_1 , len(rr)):
            nn = QQ(i)
            P_val = P_poly(nn)
            Q_val = Q_poly(nn)
            if Q_val == _sage_const_0  or P_val/Q_val != rr[i]:
                all_ok = False
                print(f"  FAIL at n={i}")
                break
        if all_ok:
            print(f"  VERIFIED for all n=1..{len(rr)-_sage_const_1 }")
        break
    else:
        if d <= _sage_const_3 :
            print(f"  d={d}: holdout fails")

# Also try: is r_n itself a polynomial/rational function of n?
print("\n=== Is r_n = P(n)/Q(n)? ===")
for d in range(_sage_const_1 , _sage_const_8 ):
    n_unk = _sage_const_2 *d + _sage_const_1
    n_pts = min(n_unk + _sage_const_5 , len(r) - _sage_const_2 )
    if n_pts < n_unk: break

    M = matrix(QQ, n_pts, n_unk)
    b = vector(QQ, n_pts)
    for i in range(n_pts):
        nn = QQ(i)
        for k in range(d+_sage_const_1 ):
            M[i, k] = -nn**k
        for k in range(d):
            M[i, d+_sage_const_1 +k] = r[i] * nn**k
        b[i] = -r[i] * nn**d

    try:
        sol = M.solve_right(b)
    except ValueError:
        continue

    ok = True
    for i in range(n_pts, min(n_pts+_sage_const_5 , len(r))):
        nn = QQ(i)
        P_val = sum(sol[k]*nn**k for k in range(d+_sage_const_1 ))
        Q_val = nn**d + sum(sol[d+_sage_const_1 +k]*nn**k for k in range(d))
        if Q_val == _sage_const_0  or P_val/Q_val != r[i]:
            ok = False; break
    if ok:
        P_poly = sum(sol[k]*x**k for k in range(d+_sage_const_1 ))
        Q_poly = x**d + sum(sol[d+_sage_const_1 +k]*x**k for k in range(d))
        print(f"\n*** r_n = P(n)/Q(n) at degree {d} ***")
        print(f"  P(n) = {P_poly}")
        print(f"  Q(n) = {Q_poly}")
        break

# Check: is q_n / (h_n * W_n) a polynomial for specific h_n?
# Try h_n = product of (a_i + j) for j=0..n-1
print("\n=== Checking q_n / (W_n * Gamma-ratio) ===")
# Try h_n such that h_{n+1}/h_n matches certain patterns
# From the exponent gap analysis: need h_{n+1}/h_n ~ 1 + 3/(2n) + O(1/n^2)
# Central binomial: C(2n,n)/4^n has ratio (2n+1)/(2n+2) ~ 1 - 1/(2n)
# (3/2)_n/n! has ratio (n+1/2)/(n+1) ~ 1 - 1/(2n)
# Need opposite sign: (n+a)/(n+b) ~ 1 + (a-b)/n

# For 3/(2n): need (a-b) = 3/2 in ratio (n+a)/(n+b)
# E.g., h_n = (n+5/2)!/(n+1)! = (5/2)_n * ...
# Let's just compute h_n = prod_{j=0}^{n-1} (2j+5)/(2j+2) = (5/2)_n * 2^n / (2)_n
print("  h_n = prod (2j+5)/(2j+2) = (5/2)_n * 2^n / (2)_n")
h_vals = [QQ(_sage_const_1 )]
for n in range(_sage_const_1 , NMAX):
    h_vals.append(h_vals[-_sage_const_1 ] * QQ(_sage_const_2 *(n-_sage_const_1 )+_sage_const_5 ) / QQ(_sage_const_2 *(n-_sage_const_1 )+_sage_const_2 ))

rh = [q[n]/(W[n]*h_vals[n]) for n in range(min(len(q),len(W),len(h_vals)))]
print("  q/(W*h) ratios:")
for n in range(min(_sage_const_10 , len(rh))):
    print(f"    n={n}: {float(rh[n]):.10f}")

# Check finite diffs
print("  Diffs:")
for n in range(_sage_const_1 , min(_sage_const_8 , len(rh))):
    print(f"    Δ(n={n}) = {float(rh[n]-rh[n-_sage_const_1 ]):.10f}")

print("\nDone.")
