#!/usr/bin/env sage
"""P2.7: Ore algebra computation following Q4893's prescription.

1. Construct Cooper's operator and the two quadratic branch operators
2. Compute LCLM
3. Descend to even coordinates
4. Factor and test against q_n
"""


# This file was *autogenerated* from the file scripts/p27_ore_sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_128 = Integer(128); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_16 = Integer(16); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_22 = Integer(22); _sage_const_28 = Integer(28); _sage_const_250 = Integer(250); _sage_const_60 = Integer(60); _sage_const_0 = Integer(0); _sage_const_256 = Integer(256); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_20 = Integer(20); _sage_const_15 = Integer(15); _sage_const_40 = Integer(40); _sage_const_10 = Integer(10)
from sage.all import *

try:
    from ore_algebra import OreAlgebra
    HAS_ORE = True
except ImportError:
    HAS_ORE = False
    print("WARNING: ore_algebra not installed. Using manual construction.")

# Problem 2.7 recurrence coefficients
def A27(n):
    return _sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B27(n):
    P6 = _sage_const_104060 *n**_sage_const_6 +_sage_const_1745370 *n**_sage_const_5 +_sage_const_12145238 *n**_sage_const_4 +_sage_const_44886481 *n**_sage_const_3 +_sage_const_92943995 *n**_sage_const_2 +_sage_const_102256019 *n+_sage_const_46709052 
    return _sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *P6

def C27(n):
    P5 = _sage_const_3784 *n**_sage_const_5 +_sage_const_57792 *n**_sage_const_4 +_sage_const_351019 *n**_sage_const_3 +_sage_const_1059230 *n**_sage_const_2 +_sage_const_1587211 *n+_sage_const_944620 
    return _sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *P5

def D27(n):
    return (n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *n**_sage_const_2 +_sage_const_4515 *n+_sage_const_5399 )

# Cooper's level-11 recurrence
def Ac(k):
    return (k+_sage_const_1 )**_sage_const_3 

def Bc(k):
    return _sage_const_2 *(_sage_const_2 *k+_sage_const_1 )*(_sage_const_5 *k**_sage_const_2 +_sage_const_5 *k+_sage_const_2 )

def Cc(k):
    return -_sage_const_8 *k*(_sage_const_7 *k**_sage_const_2 +_sage_const_1 )

def Dc(k):
    return _sage_const_22 *k*(_sage_const_2 *k-_sage_const_1 )*(k-_sage_const_1 )

# Compute T_k (Cooper)
print("Computing Cooper's T_k...", flush=True)
T = [QQ(_sage_const_1 )]
# Need T_1: from k=0: 1*T_1 = 2*1*2*T_0 = 4. So T_1 = 4
T.append(QQ(_sage_const_4 ))
# k=1: 8*T_2 = 2*3*12*T_1 - 8*1*8*T_0 = 288 - 64 = 224. T_2 = 28
T.append(QQ(_sage_const_28 ))
KMAX = _sage_const_250 
for k in range(_sage_const_2 , KMAX):
    t_next = (Bc(k)*T[k] + Cc(k)*T[k-_sage_const_1 ] + Dc(k)*T[k-_sage_const_2 ]) / Ac(k)
    T.append(t_next)
print(f"  T_0..T_5 = {T[:_sage_const_6 ]}")

# Compute W_n via binomial transform
print("Computing W_n...", flush=True)
NMAX = _sage_const_60 
W = []
for n in range(NMAX):
    val = QQ(_sage_const_0 )
    for j in range(min(_sage_const_2 *n+_sage_const_1 , len(T))):
        val += binomial(_sage_const_2 *n, j) * QQ(-_sage_const_2 )**(_sage_const_2 *n-j) * T[j]
    W.append(val / QQ(_sage_const_256 )**n)
print(f"  W_0..W_3 = {W[:_sage_const_4 ]}")

# Compute q_n
print("Computing q_n...", flush=True)
q = [QQ(-_sage_const_215040420000 )]
q.append(QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 ))
q.append(QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 ))
for n in range(_sage_const_2 , NMAX):
    if n-_sage_const_1  >= _sage_const_1  and n-_sage_const_2  >= _sage_const_0 :
        q_next = (B27(n-_sage_const_1 )*q[n] - C27(n-_sage_const_2 )*q[n-_sage_const_1 ] + D27(n-_sage_const_3 )*q[n-_sage_const_2 ]) / A27(n-_sage_const_1 ) if n >= _sage_const_3  else None
        if q_next is None:
            # n=2 case: use the recurrence with n→n-1
            # A(0)q_1 = B(0)q_0 - ... but we already have q_0, q_1, q_2
            break
        q.append(q_next)

# Actually, let me use the standard form more carefully
# The recurrence is: A(n)q_{n+3} = B(n)q_{n+2} - C(n)q_{n+1} + D(n)q_n
# Wait, need to check the exact form from the comprehensive_2_7.py file

# Let me just compute from the 4-term recurrence directly
print("Recomputing q_n with exact recurrence...", flush=True)
q = [QQ(-_sage_const_215040420000 )]
q.append(QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 ))
q.append(QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 ))

# From comprehensive_2_7.py, the recurrence is:
# A(n)*q[n+1] = B(n)*q[n] - C(n)*q[n-1] + D(n)*q[n-2]
# for n >= 2
for n in range(_sage_const_2 , NMAX-_sage_const_1 ):
    q_next = (B27(n)*q[n] - C27(n)*q[n-_sage_const_1 ] + D27(n)*q[n-_sage_const_2 ]) / A27(n)
    q.append(q_next)

print(f"  q_0 = {q[_sage_const_0 ]}")
print(f"  q_1 = {q[_sage_const_1 ]}")
print(f"  len(q) = {len(q)}")

# Check ratio q_n/W_n
print("\n=== q_n / W_n ratios ===", flush=True)
for n in range(min(_sage_const_20 , len(q), len(W))):
    if W[n] != _sage_const_0 :
        r = q[n] / W[n]
        print(f"  n={n}: q/W = {float(r):.10f}")

# Check ratio q_n / (W_n * h_n) for various h_n
print("\n=== Testing h_n = (3/2)_n / n! (central binomial related) ===", flush=True)
from sage.functions.other import rising_factorial as rf

for n in range(min(_sage_const_15 , len(q), len(W))):
    if W[n] != _sage_const_0 :
        h = rf(QQ(_sage_const_3 )/QQ(_sage_const_2 ), n) / factorial(n)
        r = q[n] / (W[n] * h)
        print(f"  n={n}: q/(W*h) = {float(r):.10f}")

# Now check: can q_n be written as sum of u_j(n) * h_n * W_{n+j}?
# where h_n = sqrt(pi) * Gamma(n+3/2) / Gamma(n+1) = (2n+1)!! / 2^n
print("\n=== h_n = (2n+1)!! / 2^n ===", flush=True)
for n in range(min(_sage_const_15 , len(q), len(W))):
    if W[n] != _sage_const_0 :
        h = QQ(_sage_const_1 )
        for j in range(n):
            h *= QQ(_sage_const_2 *j+_sage_const_1 )
        h /= QQ(_sage_const_2 )**n
        r = q[n] / (W[n] * h)
        print(f"  n={n}: q/(W*h) = {float(r):.10f}")

# Now try the POINCARE APPROACH: compute the sequence q_n / W_n
# and see what recurrence IT satisfies
print("\n=== Recurrence for r_n = q_n / W_n ===", flush=True)
r_vals = []
for n in range(min(len(q), len(W))):
    if W[n] != _sage_const_0 :
        r_vals.append(q[n] / W[n])
    else:
        r_vals.append(None)

# Check: r_{n+1}/r_n
print("  r_{n+1}/r_n:")
for n in range(min(_sage_const_15 , len(r_vals)-_sage_const_1 )):
    if r_vals[n] and r_vals[n+_sage_const_1 ]:
        print(f"    n={n}: {float(r_vals[n+_sage_const_1 ]/r_vals[n]):.15f}")

# Search for a rational function of n matching r_{n+1}/r_n
# If r_{n+1}/r_n = P(n)/Q(n), then r_n = prod P(j)/Q(j) which is a hypergeometric twist
print("\n=== Searching for r_{n+1}/r_n = P(n)/Q(n) ===", flush=True)
rr = []
for n in range(min(len(r_vals)-_sage_const_1 , _sage_const_40 )):
    if r_vals[n] and r_vals[n+_sage_const_1 ]:
        rr.append(r_vals[n+_sage_const_1 ] / r_vals[n])

# Try Padé approximant for rr[n] as a function of n
# rr[n] ≈ P(n)/Q(n) where we search for deg P = deg Q = d
R = PolynomialRing(QQ, names=('x',)); (x,) = R._first_ngens(1)
for d in range(_sage_const_1 , _sage_const_10 ):
    # Build system: rr[n] * Q(n) = P(n)
    # P = a_0 + a_1*n + ... + a_d*n^d
    # Q = 1 + b_1*n + ... + b_d*n^d (monic constant term 1... actually let's make leading coeff 1)
    # Q = n^d + b_{d-1}*n^{d-1} + ... + b_0
    n_unk = _sage_const_2 *d + _sage_const_1   # d+1 for P, d for Q (leading coeff of Q fixed to 1)
    n_pts = min(n_unk + _sage_const_5 , len(rr))

    if n_pts < n_unk:
        break

    M = matrix(QQ, n_pts, n_unk)
    b = vector(QQ, n_pts)
    for i in range(n_pts):
        n = i + _sage_const_1   # start from n=1 to avoid issues
        # P coefficients: -n^0, -n^1, ..., -n^d
        for k in range(d+_sage_const_1 ):
            M[i, k] = -QQ(n)**k
        # Q coefficients: rr[i+1] * n^0, ..., rr[i+1] * n^{d-1}
        for k in range(d):
            M[i, d+_sage_const_1 +k] = rr[i+_sage_const_1 ] * QQ(n)**k
        # RHS: -rr[i+1] * n^d (from the leading term of Q)
        b[i] = -rr[i+_sage_const_1 ] * QQ(n)**d

    try:
        sol = M.solve_right(b)
    except ValueError:
        continue

    # Verify on holdout
    ok = True
    for i in range(n_pts, min(n_pts+_sage_const_5 , len(rr))):
        n = i + _sage_const_1 
        P_val = sum(sol[k] * QQ(n)**k for k in range(d+_sage_const_1 ))
        Q_val = QQ(n)**d + sum(sol[d+_sage_const_1 +k] * QQ(n)**k for k in range(d))
        if Q_val == _sage_const_0  or P_val/Q_val != rr[i+_sage_const_1 ]:
            ok = False
            break

    if ok:
        P_coeffs = [sol[k] for k in range(d+_sage_const_1 )]
        Q_coeffs = [sol[d+_sage_const_1 +k] for k in range(d)] + [QQ(_sage_const_1 )]
        P_poly = sum(P_coeffs[k] * x**k for k in range(d+_sage_const_1 ))
        Q_poly = sum(Q_coeffs[k] * x**k for k in range(d+_sage_const_1 ))
        print(f"\n*** MATCH at degree {d}: ***")
        print(f"  r_{{n+1}}/r_n = P(n)/Q(n)")
        print(f"  P(n) = {P_poly}")
        print(f"  Q(n) = {Q_poly}")

        # Extended verification
        all_ok = True
        for i in range(len(rr)):
            n = i + _sage_const_1 
            P_val = P_poly(n)
            Q_val = Q_poly(n)
            if Q_val == _sage_const_0  or P_val/Q_val != rr[i+_sage_const_1 ]:
                all_ok = False
                print(f"  FAIL at n={n}")
                break
        if all_ok:
            print(f"  VERIFIED for all n=1..{len(rr)-_sage_const_1 }")

            # Factor the polynomials
            print(f"  P factors: {P_poly.factor()}")
            print(f"  Q factors: {Q_poly.factor()}")

            # Express h_n = prod_{j=0}^{n-1} P(j)/Q(j) in closed form
            print(f"\n  h_n = r_0 * prod_{{j=0}}^{{n-1}} P(j)/Q(j)")
            print(f"  r_0 = q_0/W_0 = {r_vals[_sage_const_0 ]}")
        break

print("\nDone.")

