#!/usr/bin/env sage
"""P2.7: Find the polynomial-coefficient recurrence operator via ore_algebra,
then analyze its Ore structure: hypergeometric solutions, right factors, LCLM/GCRD."""


# This file was *autogenerated* from the file scripts/p27_ore_analysis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_300 = Integer(300); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_50 = Integer(50); _sage_const_200 = Integer(200); _sage_const_150 = Integer(150); _sage_const_100 = Integer(100); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380)
import sys, time
from ore_algebra import OreAlgebra, guess

t0 = time.time()

# Recurrence coefficients
def A(n): return _sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B(n): return _sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *n**_sage_const_6 +_sage_const_1745370 *n**_sage_const_5 +_sage_const_12145238 *n**_sage_const_4 +_sage_const_44886481 *n**_sage_const_3 +_sage_const_92943995 *n**_sage_const_2 +_sage_const_102256019 *n+_sage_const_46709052 )
def C(n): return _sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *n**_sage_const_5 +_sage_const_57792 *n**_sage_const_4 +_sage_const_351019 *n**_sage_const_3 +_sage_const_1059230 *n**_sage_const_2 +_sage_const_1587211 *n+_sage_const_944620 )
def D(n): return (n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *n**_sage_const_2 +_sage_const_4515 *n+_sage_const_5399 )

# Compute q_n exactly using QQ arithmetic
NMAX = _sage_const_300
q = [QQ(_sage_const_0 )] * (NMAX+_sage_const_1 )
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

print("Computing q_n for n=0..%d..." % NMAX, flush=True)
for n in range(_sage_const_2 , NMAX):
    An = QQ(A(n)); Bn = QQ(B(n))
    Cn1 = QQ(C(n-_sage_const_1 )); An1 = QQ(A(n-_sage_const_1 ))
    Dn2 = QQ(D(n-_sage_const_2 )); An2 = QQ(A(n-_sage_const_2 ))
    q[n+_sage_const_1 ] = (Bn/An)*q[n] - (Cn1/An1)*q[n-_sage_const_1 ] + (Dn2/An2)*q[n-_sage_const_2 ]
    if n % _sage_const_50  == _sage_const_0 :
        print("  n=%d done (%.1fs)" % (n, time.time()-t0), flush=True)

print("q_n computed (%.1fs)" % (time.time()-t0), flush=True)

# Step 1: Use ore_algebra.guess to find minimal polynomial recurrence
R = QQ['n']; n = R.gen()
Ore = OreAlgebra(R, 'Sn')
print("\nGuessing minimal polynomial-coefficient recurrence...", flush=True)
try:
    L = guess(q[:NMAX+_sage_const_1 ], Ore)
    print("Found operator L:")
    print("  order = %d" % L.order())
    print("  degree = %d" % L.degree())

    # Print the operator coefficients
    for i in range(L.order()+_sage_const_1 ):
        c = L[i]
        print("  L[%d] has degree %d" % (i, c.degree()))

    # Verify
    test = sum(L[i](n=k)*q[k+i] for i in range(L.order()+_sage_const_1 ) for k in [_sage_const_5 ])[_sage_const_0 ] if False else None
    # manual verify
    ok = True
    for k in range(NMAX - L.order()):
        val = sum(L[i](n=k)*q[k+i] for i in range(L.order()+_sage_const_1 ))
        if val != _sage_const_0 :
            print("  VERIFICATION FAILED at n=%d: val=%s" % (k, val))
            ok = False
            break
    if ok:
        print("  Verified for n=0..%d ✓" % (NMAX - L.order()))

except Exception as e:
    print("  guess failed: %s" % e)
    L = None

if L is None:
    print("\nFallback: trying with fewer terms...", flush=True)
    for nterms in [_sage_const_200 , _sage_const_150 , _sage_const_100 ]:
        try:
            L = guess(q[:nterms], Ore)
            print("  Found with %d terms: order=%d, degree=%d" % (nterms, L.order(), L.degree()))
            break
        except:
            continue

if L is None:
    print("FAILED to find recurrence operator. Exiting.")
    sys.exit(_sage_const_1 )

print("\n=== Operator analysis (%.1fs) ===" % (time.time()-t0), flush=True)

# Step 2: Poincaré polynomial
print("\nPoincaré polynomial (leading coefficients of L[i]):")
poincare_coeffs = []
max_deg = max(L[i].degree() for i in range(L.order()+_sage_const_1 ))
for i in range(L.order()+_sage_const_1 ):
    c = L[i]
    lc = c.leading_coefficient() if c.degree() == max_deg else _sage_const_0
    poincare_coeffs.append(lc)
    print("  L[%d]: degree %d, leading coeff = %s" % (i, c.degree(), lc))

Rx = QQ['x']
ppoly = Rx(poincare_coeffs)
print("Poincaré polynomial: %s" % ppoly)
print("Poincaré roots: %s" % [r[_sage_const_0 ] for r in ppoly.roots(QQbar)])

# Step 3: Search for hypergeometric (Petkovšek) solutions
print("\n=== Hypergeometric solution search (%.1fs) ===" % (time.time()-t0), flush=True)

# Method: try to find right factors of order 1
# A right factor of order 1 means L = Q * L1 where L1 = Sn - r(n) for some r(n) in QQ(n)
# This is equivalent to a hypergeometric solution v_n with v_{n+1}/v_n = r(n)
try:
    factors = L.right_factors(_sage_const_1 )
    if factors:
        print("Found %d right factor(s) of order 1:" % len(factors))
        for f in factors:
            print("  %s" % f)
            # Extract the rational function r(n) = coefficient of Sn^0, negated
            r_n = -f[_sage_const_0 ] / f[_sage_const_1 ]
            print("  => v_{n+1}/v_n = %s" % r_n)
    else:
        print("No right factors of order 1 found (no hypergeometric solutions).")
except Exception as e:
    print("right_factors failed: %s" % e)

# Step 4: Try to factor the operator
print("\n=== Operator factorization (%.1fs) ===" % (time.time()-t0), flush=True)
try:
    factored = L.factor()
    print("Factorization: %s" % factored)
    print("Number of factors: %d" % len(factored))
    for i, (fac, mult) in enumerate(factored):
        print("  Factor %d (mult %d): order %d, degree %d" % (i, mult, fac.order(), fac.degree()))
except Exception as e:
    print("Factorization failed: %s" % e)

# Step 5: Check if the operator is self-adjoint or has special structure
print("\n=== Adjoint analysis ===" , flush=True)
try:
    Ladj = L.adjoint()
    print("L adjoint: order %d, degree %d" % (Ladj.order(), Ladj.degree()))
    # Check if L is self-adjoint (up to scalar)
    if L.order() == Ladj.order():
        # Compare leading coefficients
        ratio = Ladj[L.order()] / L[L.order()]
        is_const = ratio.is_constant()
        print("L_adj / L leading ratio is constant: %s" % is_const)
except Exception as e:
    print("Adjoint analysis failed: %s" % e)

# Step 6: Compute p_n and check its relation
print("\n=== Computing p_n (%.1fs) ===" % (time.time()-t0), flush=True)
p = [QQ(_sage_const_0 )] * (NMAX+_sage_const_1 )
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for nn in range(_sage_const_2 , NMAX):
    An = QQ(A(nn)); Bn = QQ(B(nn))
    Cn1 = QQ(C(nn-_sage_const_1 )); An1 = QQ(A(nn-_sage_const_1 ))
    Dn2 = QQ(D(nn-_sage_const_2 )); An2 = QQ(A(nn-_sage_const_2 ))
    p[nn+_sage_const_1 ] = (Bn/An)*p[nn] - (Cn1/An1)*p[nn-_sage_const_1 ] + (Dn2/An2)*p[nn-_sage_const_2 ]

# Check that p_n also satisfies the same operator L
print("Checking p_n under operator L...", flush=True)
ok = True
for k in range(min(_sage_const_50 , NMAX - L.order())):
    val = sum(L[i](n=k)*p[k+i] for i in range(L.order()+_sage_const_1 ))
    if val != _sage_const_0 :
        print("  p_n FAILS at n=%d" % k)
        ok = False
        break
if ok:
    print("  p_n satisfies L ✓ (checked n=0..49)")

# Step 7: Look for an operator annihilating the "error" e_n = p_n - L*q_n
# Actually, e_n is also annihilated by L since both p_n and q_n are.
# But maybe e_n satisfies a LOWER order operator?
# e_n = p_n - (zeta(2)+zeta(3)) * q_n — this requires a specific value of L.
# Instead, check: does the operator have a right GCRD with a shifted version?

print("\n=== Summary ===" , flush=True)
print("Operator L: order %d, degree %d" % (L.order(), L.degree()))
print("Total time: %.1fs" % (time.time()-t0))
