import RamanujanChallenge.Problem26Assembly

#print axioms RamanujanChallenge.P26.problem26
#print axioms RamanujanChallenge.P26.problem26_of_spec
#print axioms RamanujanChallenge.P26.cyclotomicLogIntegralEvaluation26
#print axioms RamanujanChallenge.P26.inverseBinomialDTerm26_hasSum_cyclotomic_integral
#print axioms RamanujanChallenge.P26.recurrence26_unique
