#!/usr/bin/env sage
"""
Multiple Orthogonal Polynomial (MOP) computation for the mixed Beukers kernel.

K(x,y) = (1 - ½ log(xy)) / (1-xy)

Markov functions:
  f₂(z) = Σ_{m≥1} ψ₁(m) z^{-m}   where ψ₁(m) = Σ_{ℓ≥m} 1/ℓ²  (tail of ζ(2))
  f₃(z) = Σ_{m≥1} ψ₂(m) z^{-m}   where ψ₂(m) = Σ_{ℓ≥m} 1/ℓ³  (tail of ζ(3))

Type II MOP conditions:
  Σ_{k=0}^n c_{n,k} · ψ_j(k+s) = 0   for s = 1,...,n_j   (j=1,2)

with n₁ + n₂ = n (step-line).

This determines Q_n(t) = Σ c_{n,k} t^k up to normalization.

Goal: compute Q_n(1) and check if it matches P2.7 growth rate ~0.859^n.
"""


# This file was *autogenerated* from the file scratchpad/beukers_mop.sage
from sage.all_cmdline import *   # import sage library

_sage_const_300 = Integer(300); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_50 = Integer(50); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_19 = Integer(19); _sage_const_10 = Integer(10); _sage_const_70 = Integer(70); _sage_const_12 = Integer(12); _sage_const_200 = Integer(200); _sage_const_60 = Integer(60)
import mpmath
mpmath.mp.dps = _sage_const_300   # high precision for rational reconstruction

def psi_tail(j, m, prec=_sage_const_300 ):
    """ψ_j(m) = Σ_{ℓ≥m} 1/ℓ^j = ζ(j) - H_{m-1}^{(j)}"""
    old_dps = mpmath.mp.dps
    mpmath.mp.dps = prec
    if j == _sage_const_2 :
        val = mpmath.zeta(_sage_const_2 ) - sum(mpmath.mpf(_sage_const_1 )/k**_sage_const_2  for k in range(_sage_const_1 , m))
    elif j == _sage_const_3 :
        val = mpmath.zeta(_sage_const_3 ) - sum(mpmath.mpf(_sage_const_1 )/k**_sage_const_3  for k in range(_sage_const_1 , m))
    mpmath.mp.dps = old_dps
    return val

# ============================================================
# Build the MOP for several step-lines and degrees
# ============================================================
def compute_mop(n, n1, n2, prec=_sage_const_300 ):
    """
    Compute the type-II MOP Q_n for step-line (n1, n2).
    Returns the coefficient vector c = (c_0, ..., c_n) and Q_n(1).
    """
    assert n1 + n2 == n
    old_dps = mpmath.mp.dps
    mpmath.mp.dps = prec

    # Build the moment matrix M (n rows, n+1 columns)
    M = mpmath.matrix(int(n), int(n+_sage_const_1 ))

    # First n1 rows: ψ₁ conditions
    for row in range(int(n1)):
        s = int(row + _sage_const_1 )
        for k in range(int(n+_sage_const_1 )):
            M[row, k] = psi_tail(_sage_const_2 , int(k + s), prec)

    # Next n2 rows: ψ₂ conditions
    for row in range(int(n2)):
        s = int(row + _sage_const_1 )
        for k in range(int(n+_sage_const_1 )):
            M[int(n1) + row, k] = psi_tail(_sage_const_3 , int(k + s), prec)

    # Find the kernel (null space) of M
    # SVD to find the smallest singular value
    U, S, V = mpmath.svd(M)

    # The kernel vector is the last row of V (corresponding to smallest singular value)
    c = [V[n, j] for j in range(n+_sage_const_1 )]

    # Normalize so c_n = 1 (monic)
    if abs(c[n]) > mpmath.mpf('1e-50'):
        norm = c[n]
        c = [c[j] / norm for j in range(n+_sage_const_1 )]

    # Q_n(1)
    Qn1 = sum(c)

    mpmath.mp.dps = old_dps
    return c, Qn1

# ============================================================
# P2.7 recurrence coefficients
# ============================================================
def A_p27(n):
    return _sage_const_1024  * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B_p27(n):
    return _sage_const_128  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )
def C_p27(n):
    return _sage_const_16  * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )
def D_p27(n):
    return (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

# Compute P2.7 ratios for reference
print("=== P2.7 reference ratios ===")
mpmath.mp.dps = _sage_const_50
q = [mpmath.mpf(_sage_const_0 )] * _sage_const_20
q[_sage_const_0 ] = mpmath.mpf('-215040420000')
q[_sage_const_1 ] = mpmath.mpf('-167282265043404') / mpmath.mpf('905')
q[_sage_const_2 ] = mpmath.mpf('-964185327658080') / mpmath.mpf('6071')
for n in range(_sage_const_2 , _sage_const_19 ):
    q[n+_sage_const_1 ] = (mpmath.mpf(B_p27(n))/A_p27(n) * q[n]
              - mpmath.mpf(C_p27(n-_sage_const_1 ))/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ]
              + mpmath.mpf(D_p27(n-_sage_const_2 ))/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ])

print("P2.7 dominant root λ₀ ≈ 0.858808")
for n in range(min(_sage_const_10 , len(q)-_sage_const_1 )):
    if q[n] != _sage_const_0 :
        r = q[n+_sage_const_1 ] / q[n]
        print("  q_{n+1}/q_n at n=%d: %.12f" % (n, float(r)))

# ============================================================
# Main computation: try different step-lines
# ============================================================
print("\n" + "="*_sage_const_70 )
print("MOP with CORRECT polygamma moments")
print("="*_sage_const_70 )

max_n = _sage_const_12

for step_name, n1_fn, n2_fn in [
    ("balanced (⌈n/2⌉, ⌊n/2⌋)", lambda n: (n+_sage_const_1 )//_sage_const_2 , lambda n: n//_sage_const_2 ),
    ("ζ(2)-heavy (n-1, 1)", lambda n: n-_sage_const_1 , lambda n: _sage_const_1 ),
    ("ζ(3)-heavy (1, n-1)", lambda n: _sage_const_1 , lambda n: n-_sage_const_1 ),
    ("2:1 ratio (⌈2n/3⌉, ⌊n/3⌋)", lambda n: (_sage_const_2 *n+_sage_const_2 )//_sage_const_3 , lambda n: n - (_sage_const_2 *n+_sage_const_2 )//_sage_const_3 ),
]:
    print("\n--- Step-line: %s ---" % step_name)
    Qn1_list = []
    for n in range(_sage_const_2 , max_n + _sage_const_1 ):
        n1 = n1_fn(n)
        n2 = n - n1
        if n2 < _sage_const_1 :
            continue
        try:
            c, Qn1 = compute_mop(n, n1, n2, prec=_sage_const_200 )
            Qn1_list.append((n, Qn1))
            print("  n=%d (n1=%d,n2=%d): Q_n(1) = %.15e" % (n, n1, n2, float(Qn1)))
        except Exception as e:
            print("  n=%d: FAILED: %s" % (n, str(e)[:_sage_const_60 ]))

    # Compute ratios
    if len(Qn1_list) >= _sage_const_2 :
        print("  Ratios Q_{n+1}(1)/Q_n(1):")
        for i in range(len(Qn1_list) - _sage_const_1 ):
            n1_idx, v1 = Qn1_list[i]
            n2_idx, v2 = Qn1_list[i+_sage_const_1 ]
            if v1 != _sage_const_0  and n2_idx == n1_idx + _sage_const_1 :
                r = v2 / v1
                print("    n=%d→%d: ratio = %.12f  (P2.7 target: ~0.859)" % (n1_idx, n2_idx, float(r)))

# ============================================================
# Also compute the error: e_n = Q_n(1)·L - p_n
# where p_n = Σ c_{n,k} (H_k^{(2)} + H_k^{(3)})
# ============================================================
print("\n" + "="*_sage_const_70 )
print("Error decay for balanced step-line")
print("="*_sage_const_70 )

mpmath.mp.dps = _sage_const_200
L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )

for n in range(_sage_const_2 , min(max_n + _sage_const_1 , _sage_const_10 )):
    n1 = (n+_sage_const_1 )//_sage_const_2
    n2 = n - n1
    try:
        c, Qn1 = compute_mop(n, n1, n2, prec=_sage_const_200 )

        # Compute p_n = Σ c_k (H_k^{(2)} + H_k^{(3)})
        p_n = mpmath.mpf(_sage_const_0 )
        for k in range(n+_sage_const_1 ):
            Hk2 = sum(mpmath.mpf(_sage_const_1 )/j**_sage_const_2  for j in range(_sage_const_1 , k+_sage_const_1 ))  # H_k^{(2)}
            Hk3 = sum(mpmath.mpf(_sage_const_1 )/j**_sage_const_3  for j in range(_sage_const_1 , k+_sage_const_1 ))  # H_k^{(3)}
            p_n += c[k] * (Hk2 + Hk3)

        e_n = Qn1 * L - p_n
        print("  n=%d: |e_n| = %.6e, |e_n/Q_n(1)| = %.6e" % (n, float(abs(e_n)), float(abs(e_n/Qn1)) if Qn1 != _sage_const_0  else _sage_const_0 ))
    except Exception as e:
        print("  n=%d: %s" % (n, str(e)[:_sage_const_60 ]))

# Error decay ratios
print("\nError decay ratios |e_{n+1}|/|e_n|:")
errors = []
for n in range(_sage_const_2 , min(max_n + _sage_const_1 , _sage_const_10 )):
    n1 = (n+_sage_const_1 )//_sage_const_2
    n2 = n - n1
    try:
        c, Qn1 = compute_mop(n, n1, n2, prec=_sage_const_200 )
        p_n = mpmath.mpf(_sage_const_0 )
        for k in range(n+_sage_const_1 ):
            Hk2 = sum(mpmath.mpf(_sage_const_1 )/j**_sage_const_2  for j in range(_sage_const_1 , k+_sage_const_1 ))
            Hk3 = sum(mpmath.mpf(_sage_const_1 )/j**_sage_const_3  for j in range(_sage_const_1 , k+_sage_const_1 ))
            p_n += c[k] * (Hk2 + Hk3)
        e_n = Qn1 * L - p_n
        errors.append((n, e_n))
    except:
        pass

for i in range(len(errors)-_sage_const_1 ):
    n1_idx, e1 = errors[i]
    n2_idx, e2 = errors[i+_sage_const_1 ]
    if abs(e1) > _sage_const_0  and n2_idx == n1_idx + _sage_const_1 :
        r = abs(e2) / abs(e1)
        print("  n=%d→%d: |e_{n+1}|/|e_n| = %.12f  (P2.7 subdominant: ~0.067)" % (n1_idx, n2_idx, float(r)))
