#!/usr/bin/env sage
"""
Test: does the centered binomial transform of Cooper level-11 solutions
produce P2.7 solutions?

Cooper: (n+1)^3 T_{n+1} = 2(2n+1)(5n^2+5n+2) T_n - 8n(7n^2+1) T_{n-1}
        + 22n(2n-1)(n-1) T_{n-2}
P2.7:   A(n) q_{n+1} = B(n) q_n - C(n) q_{n-1} + D(n) q_{n-2}

Centered binomial transform: (KT)_n = (1/256^n) Σ_{k=0}^{2n} C(2n,k)(-2)^{2n-k} T_k

Spectral identity: 16 P27((t-2)^2/4) = -C11(t) C11(4-t)
"""


# This file was *autogenerated* from the file scratchpad/cooper_transform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_28 = Integer(28); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7); _sage_const_22 = Integer(22); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_256 = Integer(256); _sage_const_20 = Integer(20); _sage_const_1024 = Integer(1024); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_15 = Integer(15); _sage_const_64 = Integer(64); _sage_const_12 = Integer(12); _sage_const_1en10 = RealNumber('1e-10'); _sage_const_18 = Integer(18); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_19 = Integer(19)
import mpmath
mpmath.mp.dps = _sage_const_100

# ============================================================
# Cooper level-11 sequence
# ============================================================
N_COOP = _sage_const_100
T = [QQ(_sage_const_0 )] * N_COOP
T[_sage_const_0 ] = QQ(_sage_const_1 )
T[_sage_const_1 ] = QQ(_sage_const_4 )
T[_sage_const_2 ] = QQ(_sage_const_28 )

for n in range(_sage_const_2 , N_COOP - _sage_const_1 ):
    T[n+_sage_const_1 ] = (_sage_const_2 *(_sage_const_2 *n+_sage_const_1 )*(_sage_const_5 *n**_sage_const_2 +_sage_const_5 *n+_sage_const_2 )*T[n] - _sage_const_8 *n*(_sage_const_7 *n**_sage_const_2 +_sage_const_1 )*T[n-_sage_const_1 ]
              + _sage_const_22 *n*(_sage_const_2 *n-_sage_const_1 )*(n-_sage_const_1 )*T[n-_sage_const_2 ]) / (n+_sage_const_1 )**_sage_const_3

print("Cooper T_k first values:")
for k in range(_sage_const_10 ):
    print("  T_%d = %s" % (k, T[k]))

# Verify Cooper recurrence
print("\nVerification of Cooper recurrence:")
for n in range(_sage_const_2 , _sage_const_8 ):
    lhs = (n+_sage_const_1 )**_sage_const_3  * T[n+_sage_const_1 ]
    rhs = _sage_const_2 *(_sage_const_2 *n+_sage_const_1 )*(_sage_const_5 *n**_sage_const_2 +_sage_const_5 *n+_sage_const_2 )*T[n] - _sage_const_8 *n*(_sage_const_7 *n**_sage_const_2 +_sage_const_1 )*T[n-_sage_const_1 ] + _sage_const_22 *n*(_sage_const_2 *n-_sage_const_1 )*(n-_sage_const_1 )*T[n-_sage_const_2 ]
    print("  n=%d: match=%s" % (n, lhs == rhs))

# ============================================================
# Centered even binomial transform
# ============================================================
def centered_transform(T_seq, n, normalize=True):
    """(KT)_n = (1/256^n) Σ_{k=0}^{2n} C(2n,k) (-2)^{2n-k} T_k"""
    val = QQ(_sage_const_0 )
    for k in range(_sage_const_2 *n + _sage_const_1 ):
        val += binomial(_sage_const_2 *n, k) * (-_sage_const_2 )**(_sage_const_2 *n - k) * T_seq[k]
    if normalize:
        val /= QQ(_sage_const_256 )**n
    return val

print("\n=== Centered binomial transform (KT)_n ===")
KT = []
for n in range(_sage_const_20 ):
    val = centered_transform(T, n)
    KT.append(val)
    print("  (KT)_%d = %s" % (n, float(val)))

# ============================================================
# Check if (KT)_n satisfies P2.7
# ============================================================
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )
def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )
def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

print("\n=== P2.7 recurrence residual for (KT) ===")
for n in range(_sage_const_2 , min(_sage_const_15 , len(KT)-_sage_const_3 )):
    res = A_p27(n) * KT[n+_sage_const_1 ] - B_p27(n) * KT[n] + C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * KT[n-_sage_const_1 ]
    # Wait, the recurrence is: u_{n+1} = B/A u_n - C_{n-1}/A_{n-1} u_{n-1} + D_{n-2}/A_{n-2} u_{n-2}
    # Written as: A_n u_{n+1} - B_n u_n + C_{n-1} u_{n-1}/... no.
    #
    # The MONIC form: u_{n+1} = (B/A) u_n - (C_{n-1}/A_{n-1}) u_{n-1} + (D_{n-2}/A_{n-2}) u_{n-2}
    # The STANDARD form: P3(n) u_{n+3} + P2(n) u_{n+2} + P1(n) u_{n+1} + P0(n) u_n = 0
    # From the summary: A_n u_{n+1} = B_n u_n - C_{n-1}/A_{n-1} u_{n-1}...
    # Actually the recurrence is:
    # u_{n+1} = (B(n)/A(n)) u_n - (C(n-1)/A(n-1)) u_{n-1} + (D(n-2)/A(n-2)) u_{n-2}
    #
    # So the residual is:
    # u_{n+1} - (B(n)/A(n)) u_n + (C(n-1)/A(n-1)) u_{n-1} - (D(n-2)/A(n-2)) u_{n-2}
    pass

# Let me redo with the correct form
print("=== P2.7 residual: u_{n+1} - (B/A)u_n + (C_{n-1}/A_{n-1})u_{n-1} - (D_{n-2}/A_{n-2})u_{n-2} ===")
for n in range(_sage_const_2 , min(_sage_const_15 , len(KT)-_sage_const_1 )):
    pred = B_p27(n)/A_p27(n) * KT[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * KT[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * KT[n-_sage_const_2 ]
    actual = KT[n+_sage_const_1 ]
    res = actual - pred
    if actual != _sage_const_0 :
        rel = float(res / actual)
    else:
        rel = float(res)
    print("  n=%d: residual = %e (relative: %e)" % (n, float(res), rel))

# ============================================================
# Also try the UN-normalized transform: ΣC(2n,k)(-2)^{2n-k}T_k (no 256^n division)
# ============================================================
print("\n=== Un-normalized transform ===")
KT_unnorm = []
for n in range(_sage_const_20 ):
    val = centered_transform(T, n, normalize=False)
    KT_unnorm.append(val)

print("=== P2.7 residual for un-normalized ===")
for n in range(_sage_const_2 , min(_sage_const_15 , len(KT_unnorm)-_sage_const_1 )):
    pred = B_p27(n)/A_p27(n) * KT_unnorm[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * KT_unnorm[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * KT_unnorm[n-_sage_const_2 ]
    actual = KT_unnorm[n+_sage_const_1 ]
    res = actual - pred
    if actual != _sage_const_0 :
        rel = float(res / actual)
    else:
        rel = float(res)
    print("  n=%d: rel residual = %e" % (n, rel))

# ============================================================
# Try with Pochhammer gauge: v_n = 256^n * h_n * (KT)_n
# ============================================================
def gamma_gauge(n):
    if n == _sage_const_0 :
        return QQ(_sage_const_1 )
    num = QQ(_sage_const_2 )**(-_sage_const_20 *n)
    for j in range(n):
        num *= (_sage_const_3 +j)**_sage_const_4  * (_sage_const_4 +j)**_sage_const_6
    den = QQ(_sage_const_1 )
    for j in range(n):
        den *= (QQ(_sage_const_5 )/_sage_const_2 +j)**_sage_const_4  * (QQ(_sage_const_7 )/_sage_const_2 +j)**_sage_const_3  * (QQ(_sage_const_9 )/_sage_const_2 +j)**_sage_const_3
    return num / den

print("\n=== Gauged transform: g_n * (KT)_n ===")
# Try different gauge factors
for gauge_name, gauge_fn in [
    ("γ_n", gamma_gauge),
    ("256^n·γ_n", lambda n: QQ(_sage_const_256 )**n * gamma_gauge(n)),
    ("64^n·γ_n", lambda n: QQ(_sage_const_64 )**n * gamma_gauge(n)),
]:
    print("\nGauge: %s" % gauge_name)
    gauged = [gauge_fn(n) * KT[n] for n in range(min(_sage_const_15 , len(KT)))]
    for n in range(_sage_const_2 , min(_sage_const_12 , len(gauged)-_sage_const_1 )):
        pred = B_p27(n)/A_p27(n) * gauged[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * gauged[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * gauged[n-_sage_const_2 ]
        actual = gauged[n+_sage_const_1 ]
        res = actual - pred
        if actual != _sage_const_0 :
            rel = float(res / actual)
        else:
            rel = float(res)
        if abs(rel) < _sage_const_1en10 :
            print("  n=%d: *** MATCH! *** rel = %e" % (n, rel))
        else:
            print("  n=%d: rel = %e" % (n, rel))

# ============================================================
# Check what recurrence (KT)_n DOES satisfy
# ============================================================
print("\n=== Guess recurrence for (KT)_n ===")
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
OS = OreAlgebra(Rn, 'Snn')

try:
    rec = guess(KT[:_sage_const_18 ], OS)
    print("Found recurrence! Order %d" % rec.order())
    for j in range(rec.order()+_sage_const_1 ):
        print("  P_%d: degree %d" % (j, rec[j].degree()))
    # Check Poincaré polynomial
    P_leading = [rec[j].leading_coefficient() for j in range(rec.order()+_sage_const_1 )]
    print("Poincaré coefficients: %s" % P_leading)
    poin = sum(P_leading[j] * var('mu')**j for j in range(len(P_leading)))
    print("Poincaré polynomial: %s" % poin)
    print("P27: 4μ³ - 220μ² + 8μ - 1")
except Exception as e:
    print("No relation found: %s" % e)

# Also try with explicit order
for order in [_sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_6 ]:
    try:
        rec = guess(KT[:_sage_const_18 ], OS, order=order)
        print("Order %d: found!" % order)
        for j in range(rec.order()+_sage_const_1 ):
            print("  P_%d: degree %d" % (j, rec[j].degree()))
        break
    except:
        print("Order %d: no relation" % order)

# ============================================================
# Compare (KT) ratios with P2.7 ratios
# ============================================================
print("\n=== Growth comparison ===")
print("(KT)_{n+1}/(KT)_n vs q_{n+1}/q_n:")

q_p27 = [QQ(_sage_const_0 )] * _sage_const_20
q_p27[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q_p27[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q_p27[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )
for n in range(_sage_const_2 , _sage_const_19 ):
    q_p27[n+_sage_const_1 ] = B_p27(n)/A_p27(n)*q_p27[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 )*q_p27[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 )*q_p27[n-_sage_const_2 ]

for n in range(min(_sage_const_12 , len(KT)-_sage_const_1 )):
    if KT[n] != _sage_const_0 :
        r_kt = float(KT[n+_sage_const_1 ]/KT[n])
        r_p27 = float(q_p27[n+_sage_const_1 ]/q_p27[n])
        print("  n=%d: KT ratio = %.10f, P2.7 ratio = %.10f" % (n, r_kt, r_p27))
