#!/usr/bin/env sage
"""
Two-measure step-line Hermite-Padé for ζ(2)+ζ(3).

Measures:
  dμ₂ = -log(t) dt on (0,1), moments ψ₂(k) = 1/(k+1)²
  dμ₃ = ½log²(t) dt on (0,1), moments ψ₃(k) = 1/(k+1)³

Step-line type-II HP: find Q_n(t) of degree n such that:
  ∫₀¹ t^j Q_n(t) dμ₂ = 0 for j = 0,...,n₁-1
  ∫₀¹ t^j Q_n(t) dμ₃ = 0 for j = 0,...,n₂-1

where (n₁,n₂) follows a step-line path with n₁+n₂ = n.

The step-line path: (0,0) → (1,0) → (1,1) → (2,1) → (2,2) → ...
"""


# This file was *autogenerated* from the file scratchpad/hermite_pade.sage
from sage.all_cmdline import *   # import sage library

_sage_const_15 = Integer(15); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_12 = Integer(12); _sage_const_20 = Integer(20); _sage_const_4 = Integer(4); _sage_const_1024 = Integer(1024); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_11 = Integer(11)
N_MAX = _sage_const_15

# ============================================================
# Moment matrices
# ============================================================
def psi2(m, k):
    """Moment ψ₂(m+k) = 1/(m+k+1)²"""
    return QQ(_sage_const_1 ) / (m + k + _sage_const_1 )**_sage_const_2

def psi3(m, k):
    """Moment ψ₃(m+k) = 1/(m+k+1)³"""
    return QQ(_sage_const_1 ) / (m + k + _sage_const_1 )**_sage_const_3

# ============================================================
# Step-line path
# ============================================================
def step_line(n):
    """Return (n1, n2) for the n-th step.
    Path: (0,0),(1,0),(1,1),(2,1),(2,2),(3,2),(3,3),...
    """
    n1 = (n + _sage_const_1 ) // _sage_const_2
    n2 = n // _sage_const_2
    return (n1, n2)

# ============================================================
# Compute HP polynomial Q_n
# ============================================================
def hp_polynomial(n):
    """Compute the type-II HP polynomial Q_n of degree n.

    Orthogonality conditions:
      Σ_{m=0}^n c_m · ψ₂(m+k) = 0 for k = 0,...,n₁-1
      Σ_{m=0}^n c_m · ψ₃(m+k) = 0 for k = 0,...,n₂-1

    Returns coefficients [c_0, ..., c_n] with c_n = 1 (monic).
    """
    n1, n2 = step_line(n)
    assert n1 + n2 == n

    if n == _sage_const_0 :
        return [QQ(_sage_const_1 )]

    # Build the linear system: n equations for n unknowns (c_0,...,c_{n-1})
    # with c_n = 1 fixed
    rows = []
    rhs_vals = []

    # From μ₂: n₁ conditions
    for k in range(n1):
        row = [psi2(m, k) for m in range(n)]
        rows.append(row)
        rhs_vals.append(-psi2(n, k))

    # From μ₃: n₂ conditions
    for k in range(n2):
        row = [psi3(m, k) for m in range(n)]
        rows.append(row)
        rhs_vals.append(-psi3(n, k))

    M = matrix(QQ, rows)
    b = vector(QQ, rhs_vals)

    try:
        x = M.solve_right(b)
        coeffs = list(x) + [QQ(_sage_const_1 )]
        return coeffs
    except:
        return None

# ============================================================
# Compute Q_n for n = 0,...,N_MAX
# ============================================================
print("=== Step-line HP polynomials ===")
Q_vals_at_1 = []
Q_polys = []

Rt = PolynomialRing(QQ, 't')
t_var = Rt.gen()

for n in range(N_MAX + _sage_const_1 ):
    coeffs = hp_polynomial(n)
    if coeffs is None:
        print("n=%d: SINGULAR" % n)
        Q_vals_at_1.append(None)
        continue

    Q_at_1 = sum(coeffs)
    Q_vals_at_1.append(Q_at_1)
    Q_poly = sum(coeffs[m] * t_var**m for m in range(len(coeffs)))
    Q_polys.append(Q_poly)

    n1, n2 = step_line(n)
    print("n=%2d: (n1=%d,n2=%d), Q_n(1) = %s" % (n, n1, n2, Q_at_1))
    if n <= _sage_const_5 :
        print("       Q_n(t) = %s" % Q_poly)

# ============================================================
# Check: does Q_n satisfy a four-term recurrence?
# ============================================================
print("\n=== Four-term recurrence for Q_n(1) ===")
# Q_{n+1}(1) = alpha_n Q_n(1) + beta_n Q_{n-1}(1) + gamma_n Q_{n-2}(1)

print("Q_n(1) values:")
for n in range(min(_sage_const_10 , len(Q_vals_at_1))):
    if Q_vals_at_1[n] is not None:
        print("  Q_%d(1) = %s = %.15f" % (n, Q_vals_at_1[n], float(Q_vals_at_1[n])))

# Try to fit: look at ratios
print("\nRatios Q_{n+1}(1)/Q_n(1):")
for n in range(min(_sage_const_10 , len(Q_vals_at_1)-_sage_const_1 )):
    if Q_vals_at_1[n] is not None and Q_vals_at_1[n] != _sage_const_0  and Q_vals_at_1[n+_sage_const_1 ] is not None:
        print("  n=%d: %.15f" % (n, float(Q_vals_at_1[n+_sage_const_1 ] / Q_vals_at_1[n])))

# ============================================================
# Compute companion p_n from the HP system
# ============================================================
print("\n=== HP companion for ζ(2) + ζ(3) ===")
# For each n, the HP gives:
# Q_n(1)·f₂(1) - P₂(1) = r₂  (remainder for ζ(2))
# Q_n(1)·f₃(1) - P₃(1) = r₃  (remainder for ζ(3))
#
# But f₂(1) = Σ 1/(k+1)² = ζ(2), f₃(1) = Σ 1/(k+1)³ = ζ(3)
#
# The HP gives SEPARATE approximations to ζ(2) and ζ(3):
# P₂_n(1)/Q_n(1) → ζ(2) and P₃_n(1)/Q_n(1) → ζ(3)
#
# For ζ(2)+ζ(3), we take p_n = P₂_n(1) + P₃_n(1).
#
# Compute P₂ and P₃ from the HP system:
# [t^k](Q_n · f₂) = P₂[k] for k = 0,...,n₁-1
# [t^k](Q_n · f₃) = P₃[k] for k = 0,...,n₂-1

import mpmath
mpmath.mp.dps = _sage_const_100
L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
zeta2 = mpmath.zeta(_sage_const_2 )
zeta3 = mpmath.zeta(_sage_const_3 )

hp_q = []
hp_p = []
hp_p2 = []
hp_p3 = []
hp_e = []

for n in range(min(_sage_const_12 , len(Q_polys))):
    coeffs = list(Q_polys[n])
    while len(coeffs) <= n:
        coeffs.append(QQ(_sage_const_0 ))

    n1, n2 = step_line(n)

    # P₂(t) coefficients: [t^k](Q_n · f₂) for k = 0,...,n₁-1
    p2_coeffs = []
    for k in range(n1):
        val = sum(coeffs[m] * psi2(m, k) for m in range(n+_sage_const_1 ))
        p2_coeffs.append(val)
    P2_at_1 = sum(p2_coeffs)

    # P₃(t) coefficients: [t^k](Q_n · f₃) for k = 0,...,n₂-1
    p3_coeffs = []
    for k in range(n2):
        val = sum(coeffs[m] * psi3(m, k) for m in range(n+_sage_const_1 ))
        p3_coeffs.append(val)
    P3_at_1 = sum(p3_coeffs)

    q_n = sum(coeffs)  # Q_n(1)
    p_n = P2_at_1 + P3_at_1  # combined companion

    hp_q.append(q_n)
    hp_p.append(p_n)
    hp_p2.append(P2_at_1)
    hp_p3.append(P3_at_1)

    # Error: e_n = p_n - (ζ(2)+ζ(3))·q_n
    e_n = mpmath.mpf(p_n) - L * mpmath.mpf(q_n)

    # Also separate errors
    e2 = mpmath.mpf(P2_at_1) - zeta2 * mpmath.mpf(q_n)
    e3 = mpmath.mpf(P3_at_1) - zeta3 * mpmath.mpf(q_n)

    hp_e.append(e_n)

    print("n=%2d: q=%s, p2+p3=%s" % (n, q_n, p_n))
    print("       e = p-(ζ(2)+ζ(3))q = %s" % mpmath.nstr(e_n, _sage_const_20 ))
    print("       e₂ = P₂-ζ(2)q = %s" % mpmath.nstr(e2, _sage_const_15 ))
    print("       e₃ = P₃-ζ(3)q = %s" % mpmath.nstr(e3, _sage_const_15 ))

# ============================================================
# Check error decay and recurrence
# ============================================================
print("\n=== Error decay ===")
for n in range(_sage_const_1 , len(hp_e)):
    if abs(hp_e[n-_sage_const_1 ]) > _sage_const_0 :
        ratio = hp_e[n] / hp_e[n-_sage_const_1 ]
        print("n=%d: e_n/e_{n-1} = %s" % (n, mpmath.nstr(ratio, _sage_const_15 )))

# Guess recurrence for q_n
print("\n=== Recurrence guess for HP q_n ===")
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
OS = OreAlgebra(Rn, 'Snn')

q_list = hp_q[:_sage_const_12 ]
for order in [_sage_const_3 , _sage_const_4 , _sage_const_5 ]:
    try:
        rec = guess(q_list, OS, order=order)
        print("Found order-%d recurrence!" % order)
        for j in range(order+_sage_const_1 ):
            print("  P_%d: degree %d" % (j, rec[j].degree()))
        print("  P_%d factored: %s" % (order, factor(rec[order])))
        print("  P_0 factored: %s" % factor(rec[_sage_const_0 ]))
        break
    except:
        print("  order=%d: no relation found" % order)

# Compare P2.7 q_n with HP q_n
print("\n=== Comparison with P2.7 ===")
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )
def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )
def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

p27_q = [QQ(_sage_const_0 )] * _sage_const_12
p27_q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
p27_q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
p27_q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

for n in range(_sage_const_2 , _sage_const_11 ):
    p27_q[n+_sage_const_1 ] = B_p27(n)/A_p27(n)*p27_q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 )*p27_q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 )*p27_q[n-_sage_const_2 ]

print("P2.7 q_n / HP q_n ratio:")
for n in range(min(_sage_const_10 , len(hp_q))):
    if hp_q[n] != _sage_const_0  and p27_q[n] != _sage_const_0 :
        ratio = float(p27_q[n] / hp_q[n])
        print("  n=%d: P2.7/HP = %e" % (n, ratio))
