#!/usr/bin/env sage
"""
Hermite-Padé Type II polynomials for ζ(2)+ζ(3).

Two measures on (0,1):
  dμ₂ = -log(t) dt,   moments: ∫ t^k dμ₂ = 1/(k+1)²
  dμ₃ = ½ log²(t) dt, moments: ∫ t^k dμ₃ = 1/(k+1)³

Step-line multi-index: at step n, orthogonality constraints are
  ∫ t^i Q_n(t) dμ₂ = 0 for i=0,...,n₂-1
  ∫ t^i Q_n(t) dμ₃ = 0 for i=0,...,n₃-1
where n₂+n₃ = n (or n+1, depending on convention).

We try several conventions for the multi-index.
"""


# This file was *autogenerated* from the file scratchpad/hp_construction.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_20 = Integer(20); _sage_const_8 = Integer(8)
# Moments
def mu2(i, j):
    """∫₀¹ t^{i+j} (-log t) dt = 1/(i+j+1)²"""
    return QQ(_sage_const_1 ) / QQ(i+j+_sage_const_1 )**_sage_const_2

def mu3(i, j):
    """∫₀¹ t^{i+j} (½ log² t) dt = 1/(i+j+1)³"""
    return QQ(_sage_const_1 ) / QQ(i+j+_sage_const_1 )**_sage_const_3

def compute_HP(n, n2, n3, normalize_at=None):
    """
    Find Q_n(x) of degree n such that:
      ∫ t^i Q_n(t) dμ₂ = 0 for i=0,...,n2-1
      ∫ t^i Q_n(t) dμ₃ = 0 for i=0,...,n3-1
    Total conditions: n2+n3. Must equal n for a unique (up to scalar) solution.
    """
    assert n2 + n3 == n, f"Need n2+n3=n, got {n2}+{n3}={n2+n3} vs n={n}"

    # Build the n × (n+1) constraint matrix
    M = matrix(QQ, n, n+_sage_const_1 )
    for i in range(n2):
        for j in range(n+_sage_const_1 ):
            M[i, j] = mu2(i, j)
    for i in range(n3):
        for j in range(n+_sage_const_1 ):
            M[n2+i, j] = mu3(i, j)

    ker = M.right_kernel()
    if ker.dimension() != _sage_const_1 :
        return None, ker.dimension()

    v = ker.basis()[_sage_const_0 ]
    R_poly = PolynomialRing(QQ, 'x')
    x = R_poly.gen()
    Q_poly = sum(v[j] * x**j for j in range(n+_sage_const_1 ))

    if normalize_at is not None:
        val = Q_poly(normalize_at)
        if val != _sage_const_0 :
            Q_poly = Q_poly / val
    return Q_poly, _sage_const_1

# Try different step-line conventions
print("="*_sage_const_60 )
print("HP Type II for dμ₂, dμ₃")
print("="*_sage_const_60 )

N_max = _sage_const_10
results = {}

for convention in ['balanced', 'mu2_first', 'mu3_first']:
    print(f"\n--- Convention: {convention} ---")
    q_vals = []

    for n in range(_sage_const_1 , N_max+_sage_const_1 ):
        if convention == 'balanced':
            n2 = (n+_sage_const_1 ) // _sage_const_2
            n3 = n - n2
        elif convention == 'mu2_first':
            n2 = (n + _sage_const_1 ) // _sage_const_2
            n3 = n - n2
        elif convention == 'mu3_first':
            n3 = (n + _sage_const_1 ) // _sage_const_2
            n2 = n - n3

        Q_poly, dim = compute_HP(n, n2, n3)
        if Q_poly is not None:
            q0 = Q_poly(_sage_const_0 )
            q_vals.append(q0)
            print(f"  n={n}: n2={n2}, n3={n3}, Q_n(0) = {q0}")
        else:
            q_vals.append(None)
            print(f"  n={n}: n2={n2}, n3={n3}, kernel dim = {dim}")

    results[convention] = q_vals

# Now check: does q_n(0) satisfy any recognizable recurrence?
from ore_algebra import *
from ore_algebra import guess

R = PolynomialRing(QQ, names=('n',)); (n,) = R._first_ngens(1)
A = OreAlgebra(R, names=('Sn',)); (Sn,) = A._first_ngens(1)

for convention, vals in results.items():
    # Remove Nones
    clean = [v for v in vals if v is not None]
    if len(clean) < _sage_const_6 :
        continue
    print(f"\n{'='*_sage_const_60 }")
    print(f"Guessing recurrence for {convention} (values: {clean[:_sage_const_6 ]})")
    print(f"{'='*_sage_const_60 }")
    try:
        L = guess(clean, A)
        print(f"  Order: {L.order()}, Degree: {max(c.degree() for c in L.list())}")
        # Print the operator
        if L.order() <= _sage_const_3  and max(c.degree() for c in L.list()) <= _sage_const_20 :
            print(f"  L = {L}")
    except Exception as e:
        print(f"  Could not guess: {e}")

# Also try: compute remainders and check if ζ(2)+ζ(3) approximation works
print(f"\n{'='*_sage_const_60 }")
print("Remainder analysis (balanced convention)")
print(f"{'='*_sage_const_60 }")

for n in range(_sage_const_1 , min(N_max+_sage_const_1 , _sage_const_8 )):
    n2 = (n+_sage_const_1 ) // _sage_const_2
    n3 = n - n2
    Q_poly, dim = compute_HP(n, n2, n3)
    if Q_poly is None:
        continue

    # Compute ∫ Q_n(t) dμ₂ and ∫ Q_n(t) dμ₃
    coeffs = Q_poly.list()
    int2 = sum(coeffs[j] * QQ(_sage_const_1 )/(j+_sage_const_1 )**_sage_const_2  for j in range(len(coeffs)))
    int3 = sum(coeffs[j] * QQ(_sage_const_1 )/(j+_sage_const_1 )**_sage_const_3  for j in range(len(coeffs)))

    q0 = Q_poly(_sage_const_0 )
    if q0 != _sage_const_0 :
        # p_n ≈ (int2 + int3) * Q_n(0) if the approximation is good
        ratio = (int2 + int3) / q0
        print(f"  n={n}: (int2+int3)/Q(0) = {float(ratio):.15f}, "
              f"int2 = {float(int2):.10e}, int3 = {float(int3):.10e}")

print(f"\n  ζ(2)+ζ(3) ≈ {float(pi**_sage_const_2 /_sage_const_6  + zeta(_sage_const_3 )):.15f}")

# Also: HP with normalization Q_n(0) = 1
print(f"\n{'='*_sage_const_60 }")
print("Alternative: HP with Q_n(0) normalized to 1")
print(f"{'='*_sage_const_60 }")
for n in range(_sage_const_1 , min(N_max+_sage_const_1 , _sage_const_8 )):
    n2 = (n+_sage_const_1 ) // _sage_const_2
    n3 = n - n2
    Q_poly, dim = compute_HP(n, n2, n3, normalize_at=_sage_const_0 )
    if Q_poly is None:
        continue
    # Compute approximation
    coeffs = Q_poly.list()
    int2 = sum(coeffs[j] * QQ(_sage_const_1 )/(j+_sage_const_1 )**_sage_const_2  for j in range(len(coeffs)))
    int3 = sum(coeffs[j] * QQ(_sage_const_1 )/(j+_sage_const_1 )**_sage_const_3  for j in range(len(coeffs)))
    print(f"  n={n}: int2+int3 = {float(int2+int3):.15f}, "
          f"error = {float(int2+int3-pi**_sage_const_2 /_sage_const_6 -zeta(_sage_const_3 )):.6e}")
