#!/usr/bin/env sage
"""
Search for the nonlocal transform T(n,k) that maps Zudilin's a_k to P2.7's q_n:
  q_n = Σ_k T(n,k) · a_k

Step 1: Compute many P2.7 q_n values using the recurrence
Step 2: See if q_n = linear combination of a_0,...,a_n with structured coefficients
Step 3: Identify the structure of T(n,k)
"""


# This file was *autogenerated* from the file scratchpad/nonlocal_search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_40 = Integer(40); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_15 = Integer(15); _sage_const_10 = Integer(10); _sage_const_64 = Integer(64); _sage_const_30 = Integer(30); _sage_const_20 = Integer(20); _sage_const_7425 = Integer(7425); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8)
from ore_algebra import OreAlgebra, guess
import mpmath
mpmath.mp.dps = _sage_const_100

# ============================================================
# Step 1: Compute a_n (Zudilin inner sum)
# ============================================================
N = _sage_const_40
a_vals = []
for i in range(N):
    s = QQ(_sage_const_0 )
    for k in range(i+_sage_const_1 ):
        s += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
    a_vals.append(s)

# ============================================================
# Step 2: Compute P2.7 q_n values using the recurrence
# ============================================================
# Recurrence: A_n u_{n+1} = B_n u_n - C_{n-1} u_{n-1} + D_{n-2} u_{n-2}
def A(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

# Initial conditions
q = [QQ(_sage_const_0 )] * N
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

# Forward recurrence
for n in range(_sage_const_2 , N-_sage_const_1 ):
    q[n+_sage_const_1 ] = (B(n) * q[n] - C(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D(n-_sage_const_2 ) * q[n-_sage_const_2 ]) / A(n)

# Also compute p_n
p = [QQ(_sage_const_0 )] * N
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n in range(_sage_const_2 , N-_sage_const_1 ):
    p[n+_sage_const_1 ] = (B(n) * p[n] - C(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D(n-_sage_const_2 ) * p[n-_sage_const_2 ]) / A(n)

# Verify convergence to ζ(2)+ζ(3)
L = float(mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 ))
print("=== p_n/q_n convergence ===")
for n in range(min(_sage_const_15 , N)):
    if q[n] != _sage_const_0 :
        r = float(p[n]/q[n])
        print("n=%2d: p/q = %.15f, diff = %.3e" % (n, r, abs(r - L)))

# ============================================================
# Step 3: Try to express q_n as Σ T(n,k) a_k
# ============================================================
# The simplest nonlocal transforms:
# (a) q_n = c_n · a_n (diagonal gauge) — already know this fails
# (b) q_n = Σ_{k=0}^n C(n,k) · r^k · a_k (binomial transform)
# (c) q_n = Σ_{k=0}^n C(2n,2k) · a_k (even binomial)

print("\n=== Search for nonlocal kernel ===")

# First, compute the ratio q_n / a_n to see the gauge factor
print("\nq_n / a_n:")
for n in range(min(_sage_const_10 , N)):
    if a_vals[n] != _sage_const_0 :
        r = q[n] / a_vals[n]
        print("  n=%d: %.6e" % (n, float(r)))

# Check if q_n / (C(2n,n) * a_n) gives a pattern
print("\nq_n / (C(2n,n) * a_n) = q_n / A_n^{AESZ}:")
for n in range(min(_sage_const_10 , N)):
    An = binomial(_sage_const_2 *n,n) * a_vals[n]
    if An != _sage_const_0 :
        r = q[n] / An
        print("  n=%d: %s = %.6e" % (n, r, float(r)))

# Try binomial transform: does q_n = Σ C(n,k) · a_k?
print("\nBinomial transform Σ C(n,k) a_k:")
for n in range(min(_sage_const_10 , N)):
    bt = sum(binomial(n,k) * a_vals[k] for k in range(n+_sage_const_1 ))
    print("  n=%d: bt = %s, q = %.6e, bt/q = %.6e" %
          (n, bt, float(q[n]), float(bt/q[n]) if q[n] != _sage_const_0  else float('inf')))

# Try 64^n scaling: q_n / 64^n
print("\nq_n / 64^n:")
for n in range(min(_sage_const_10 , N)):
    print("  n=%d: %.6e" % (n, float(q[n] / QQ(_sage_const_64 )**n)))

# The ratio q_{n+1}/q_n (Poincaré)
print("\nq_{n+1}/q_n:")
for n in range(min(_sage_const_15 , N-_sage_const_1 )):
    if q[n] != _sage_const_0 :
        print("  n=%d: %.6f" % (n, float(q[n+_sage_const_1 ]/q[n])))

# ============================================================
# Step 4: Key insight from Q5048 — try the Zudilin v_n = 64^{-n} J_n^Z
# The scaled error ê = 64^{-n} e_n^Z should have rate ~0.00105
# The P2.7 error e_n^{P27} should also have rate ~0.00105
# If the RATES match but the recurrences differ, maybe
# e_n^{P27} = nonlocal transform of e_n^Z
# ============================================================

# Compute the Zudilin companion sequences using partial fractions
# R_n(t) = [(t-1)...(t-n)]^3 / [(n!)^2 * t*(t+1)*...*(t+n)]
print("\n=== Zudilin companion sequences ===")

def R_n(n_val, t):
    """R_n(t) = [(t-1)...(t-n)]^3 / [(n!)^2 * t*(t+1)*...*(t+n)]"""
    num = prod(t - j for j in range(_sage_const_1 , n_val+_sage_const_1 ))**_sage_const_3
    den = factorial(n_val)**_sage_const_2  * prod(t + j for j in range(n_val+_sage_const_1 ))
    return num / den

# Compute b̃_n and b̃̃_n from the partial fraction decomposition
# R_n(t) has poles at t = 0, -1, ..., -n
# r_n(z) = Σ_ν z^ν R_n(ν) = a_n Li_1(z) - b_n
# r̃_n(z) = -Σ_ν z^ν R_n'(ν) = a_n Li_2(z) - b̃_n
# r̃̃_n(z) = ½ Σ_ν z^ν R_n''(ν) = a_n Li_3(z) - b̃̃_n

# The b̃_n can be computed from the partial fraction coefficients at the POLES
# At t = -m (m = 0,...,n):
# R_n(t) = Σ_m Σ_{j=1}^{order} A_{m,j} / (t+m)^j + polynomial

# Actually, it's easier to compute b̃_n from the RESIDUE formula:
# b̃_n = a_n * ζ(2) - r̃_n
# But r̃_n at z=1 diverges...

# Alternative: compute b̃_n from the explicit formula
# b̃_n = partial fraction constant from R_n'
# Use the relation: b̃_n = Σ_{m=0}^n Res_{t=-m} [R_n(t) π²/sin²(πt)]

# For computational purposes, b̃_n can be extracted from:
# a_n ζ(2) - b̃_n = lim_{z→1-} [Σ_ν z^ν R_n'(ν) + (Σ_ν z^ν/ν²)] ... too complicated

# Let me instead compute b̃_n + b̃̃_n DIRECTLY from the initial conditions
# Zudilin: p̃_n = b̃_n + b̃̃_n, with p̃_0 = 0, p̃_1 = 20, p̃_2 = 7425/16
# These satisfy rec_a (same as a_n).

# Verify: do p̃ values satisfy rec_a?
Rn = PolynomialRing(QQ, 'n')
n_var = Rn.gen()
OS = OreAlgebra(Rn, 'Sn')
Sn = OS.gen()
rec_a = guess(list(a_vals[:_sage_const_30 ]), OS, order=_sage_const_3 )
P_rec = [rec_a[j] for j in range(_sage_const_4 )]

# Compute p̃ using rec_a with given initial conditions
p_zud = [QQ(_sage_const_0 )] * N
p_zud[_sage_const_0 ] = QQ(_sage_const_0 )
p_zud[_sage_const_1 ] = QQ(_sage_const_20 )
p_zud[_sage_const_2 ] = QQ(_sage_const_7425 ) / QQ(_sage_const_16 )

for nn in range(N-_sage_const_3 ):
    val = sum(QQ(P_rec[j](n=nn)) * p_zud[nn+j] for j in range(_sage_const_3 ))
    p_zud[nn+_sage_const_3 ] = -val / QQ(P_rec[_sage_const_3 ](n=nn))

# Verify convergence of p̃_n/a_n to ζ(2)+ζ(3)
print("p̃_n / a_n → ζ(2)+ζ(3) ?")
for n in range(min(_sage_const_20 , N)):
    if a_vals[n] != _sage_const_0 :
        r = float(p_zud[n] / a_vals[n])
        print("  n=%2d: p̃/a = %.15f, diff = %.3e" % (n, r, abs(r - L)))

# ============================================================
# Step 5: Core test — can q_n^{P27} be expressed in terms of a_k and p̃_k?
# ============================================================
# If q_n^{P27} = Σ T(n,k) a_k, then p_n^{P27} = Σ T(n,k) p̃_k
# And e_n^{P27} = p_n - L*q_n = Σ T(n,k) (p̃_k - L*a_k) = Σ T(n,k) e_k^Z → 0

# Try: q_n^{P27} = g(n) · Σ C(2n,2k) a_k
# Try: q_n^{P27} = g(n) · Σ C(n,k) 64^{-k} a_k
# Try: q_n^{P27} = g(n) · Σ h_k a_k  (Pochhammer-weighted)

# Most promising from Q5048: T(n,k) = C(αn+β, k) · c^k · Pochhammer ratio
# Let me search by solving for T(n,0), T(n,1), ... from q_n = Σ T(n,k) a_k

print("\n=== Solving for T(n,k) assuming q_n = Σ_{k=0}^n T(n,k) a_k ===")
# For each n, T(n,k) for k=0,...,n are unknowns. But we only have one equation per n.
# So T is underdetermined unless we impose structure.

# Instead: check if q_n / some_function = known transform of a_k
# Key: q_0 = -2^5 · 3^6 · 5^4 · 7^3 · 43 = -215040420000
# And a_0 = 1, so T(0,0) = q_0

# For n=1: q_1 = T(1,0)*a_0 + T(1,1)*a_1 = T(1,0) + 7*T(1,1)
# This has infinitely many solutions. We need structure.

# Try T(n,k) = g(n) · f(n,k) where f is a known combinatorial kernel
# and g(n) is a gauge.

# Try: q_n = q_0 · Σ C(n,k)^2 C(n+k,n) C(n+2k,n) · r^k / a_n · a_k
# i.e., q_n = q_0 · Σ (a_k F(n,k)/a_n) ... circular

# NEW IDEA: maybe q_n^{P27} = g(n) · C(2n,n) · a_n (i.e., proportional to A_n^{AESZ})
# with g(n) = some Pochhammer/polynomial gauge

# Check: q_n / A_n^{AESZ} = q_n / [C(2n,n) a_n]
print("\nq_n^{P27} / A_n^{AESZ} (= q_n / [C(2n,n) a_n]):")
gauge = []
for n in range(min(_sage_const_15 , N)):
    An = binomial(_sage_const_2 *n,n) * a_vals[n]
    g = q[n] / An
    gauge.append(g)
    print("  n=%d: %s" % (n, g))

# Check ratio of successive gauge values
print("\ng_{n+1}/g_n:")
for n in range(min(_sage_const_12 , len(gauge)-_sage_const_1 )):
    if gauge[n] != _sage_const_0 :
        r = gauge[n+_sage_const_1 ] / gauge[n]
        print("  n=%d: %s = %.6f" % (n, r, float(r)))

# Try to guess a recurrence for the gauge
print("\n=== Guessing recurrence for gauge ===")
try:
    rec_g = guess(gauge[:_sage_const_15 ], OS, order=_sage_const_2 )
    print("Found recurrence for gauge! %s" % rec_g)
except:
    print("No order-2 recurrence found")
    try:
        rec_g = guess(gauge[:_sage_const_15 ], OS, order=_sage_const_3 )
        print("Found order-3 recurrence for gauge! %s" % rec_g)
    except:
        print("No order-3 recurrence found either")

# Try to guess from the gauge values directly
print("\n=== Gauge values (exact) ===")
for n in range(min(_sage_const_8 , len(gauge))):
    print("  g_%d = %s" % (n, gauge[n]))
    if n > _sage_const_0 :
        print("    = %s / %s" % (gauge[n].numerator(), gauge[n].denominator()))
