#!/usr/bin/env sage
"""
P2.7 ODE via CORRECT operator (Q5107 monic form).

The STANDARD form A(n+2)u(n+3)-B(n+2)u(n+2)+C(n+1)u(n+1)-D(n)u(n) = 0
does NOT annihilate the P2.7 sequences (residuals ~10^25).

The CORRECT monic form (proof.tex eq 2.1, Q5107):
  u(n+1) = B(n)/A(n)*u(n) - C(n-1)/A(n-1)*u(n-1) + D(n-2)/A(n-2)*u(n-2)

As shift operator at index n:
  L = Sn^3 - B(n+2)/A(n+2)*Sn^2 + C(n+1)/A(n+1)*Sn - D(n)/A(n)

Clearing denominators (multiply by A(n)*A(n+1)*A(n+2)):
  p3 = A(n)*A(n+1)*A(n+2)
  p2 = -B(n+2)*A(n)*A(n+1)
  p1 = C(n+1)*A(n)*A(n+2)    # NOTE: A(n+2), not A(n+1)!
  p0 = -D(n)*A(n+1)*A(n+2)
"""


# This file was *autogenerated* from the file scratchpad/p27_correct_ode.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_55 = Integer(55); _sage_const_52 = Integer(52); _sage_const_60 = Integer(60); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_15 = Integer(15); _sage_const_18 = Integer(18); _sage_const_50 = Integer(50)
from ore_algebra import *
from ore_algebra import guess

# ============================================================
# Coefficient polynomials
# ============================================================
Rn = PolynomialRing(QQ, names=('n',)); (n,) = Rn._first_ngens(1)

A_fn = Rn(_sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 ))
B_fn = Rn(_sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *n**_sage_const_6 +_sage_const_1745370 *n**_sage_const_5 +_sage_const_12145238 *n**_sage_const_4 +_sage_const_44886481 *n**_sage_const_3 +_sage_const_92943995 *n**_sage_const_2 +_sage_const_102256019 *n+_sage_const_46709052 ))
C_fn = Rn(_sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *n**_sage_const_5 +_sage_const_57792 *n**_sage_const_4 +_sage_const_351019 *n**_sage_const_3 +_sage_const_1059230 *n**_sage_const_2 +_sage_const_1587211 *n+_sage_const_944620 ))
D_fn = Rn((n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *n**_sage_const_2 +_sage_const_4515 *n+_sage_const_5399 ))

# ============================================================
# CORRECT operator (Q5107 form)
# ============================================================
Qn = Rn.fraction_field()
A_rec = OreAlgebra(Qn, 'Sn', names=('Sn',)); (Sn,) = A_rec._first_ngens(1)

L_monic = (Sn**_sage_const_3
           - B_fn(n=n+_sage_const_2 )/A_fn(n=n+_sage_const_2 ) * Sn**_sage_const_2
           + C_fn(n=n+_sage_const_1 )/A_fn(n=n+_sage_const_1 ) * Sn
           - D_fn(n=n)/A_fn(n=n))

print("Monic operator constructed (Q5107 form)")
print(f"Order: {L_monic.order()}")

# Clear denominators and take primitive part
coeffs_monic = [Qn(L_monic[i]) for i in range(_sage_const_4 )]
den = Rn.one()
for c in coeffs_monic:
    den = lcm(den, Rn(c.denominator()))
nums = [Rn(den * c) for c in coeffs_monic]
g = nums[_sage_const_0 ]
for c in nums[_sage_const_1 :]:
    g = gcd(g, c)
pnums = [c // g for c in nums]

print(f"\nPrimitive polynomial coefficients:")
for i in range(_sage_const_4 ):
    print(f"  p{i} degree: {pnums[i].degree()}")

L_prim = sum((Qn(pnums[i]) * Sn**i for i in range(_sage_const_4 )), A_rec.zero())

# ============================================================
# Verify that this operator annihilates q_n
# ============================================================
def Af(nn):
    nn = QQ(nn)
    return QQ(_sage_const_1024 )*(_sage_const_2 *nn+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *nn+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *nn**_sage_const_2 +_sage_const_6407 *nn+_sage_const_10860 )
def Bf(nn):
    nn = QQ(nn)
    return QQ(_sage_const_128 )*(_sage_const_2 *nn+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *nn**_sage_const_6 +_sage_const_1745370 *nn**_sage_const_5 +_sage_const_12145238 *nn**_sage_const_4 +_sage_const_44886481 *nn**_sage_const_3 +_sage_const_92943995 *nn**_sage_const_2 +_sage_const_102256019 *nn+_sage_const_46709052 )
def Cf(nn):
    nn = QQ(nn)
    return QQ(_sage_const_16 )*(nn+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *nn**_sage_const_5 +_sage_const_57792 *nn**_sage_const_4 +_sage_const_351019 *nn**_sage_const_3 +_sage_const_1059230 *nn**_sage_const_2 +_sage_const_1587211 *nn+_sage_const_944620 )
def Df(nn):
    nn = QQ(nn)
    return (nn+_sage_const_3 )**_sage_const_4 *(nn+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *nn**_sage_const_2 +_sage_const_4515 *nn+_sage_const_5399 )

q = [QQ(-_sage_const_215040420000 ), QQ(-_sage_const_167282265043404 )/_sage_const_905 , QQ(-_sage_const_964185327658080 )/_sage_const_6071 ]
for nn in range(_sage_const_2 , _sage_const_55 ):
    q.append(Bf(nn)/Af(nn)*q[nn] - Cf(nn-_sage_const_1 )/Af(nn-_sage_const_1 )*q[nn-_sage_const_1 ] + Df(nn-_sage_const_2 )/Af(nn-_sage_const_2 )*q[nn-_sage_const_2 ])

print("\nVerifying operator annihilates q_n:")
ok = True
for nn in range(_sage_const_52 ):
    val = sum(QQ(pnums[i](n=nn)) * q[nn+i] for i in range(_sage_const_4 ))
    if val != _sage_const_0 :
        ok = False
        if nn < _sage_const_5 :
            print(f"  n={nn}: residual = {float(val):.3e}")
if ok:
    print("  *** ALL ZERO — operator is correct! ***")
else:
    print("  SOME NONZERO RESIDUALS")

# ============================================================
# Factor the primitive leading and trailing coefficients
# ============================================================
print(f"\nLeading coefficient (p3) factorization:")
print(f"  {pnums[_sage_const_3 ].factor()}")
print(f"\nTrailing coefficient (p0) factorization:")
print(f"  {pnums[_sage_const_0 ].factor()}")

# ============================================================
# Try to convert to ODE using ore_algebra
# ============================================================
print("\n" + "="*_sage_const_60 )
print("Converting to differential equation...")
print("="*_sage_const_60 )

try:
    # ore_algebra's to_D() converts a shift operator to differential
    R2 = PolynomialRing(QQ, names=('z',)); (z,) = R2._first_ngens(1)
    D_alg = OreAlgebra(R2, names=('Dz',)); (Dz,) = D_alg._first_ngens(1)

    L_ode = L_prim.to_D(D_alg)
    print(f"\nDifferential operator obtained!")
    print(f"Order: {L_ode.order()}")
    deg = max(c.degree() for c in L_ode.list())
    print(f"Max coefficient degree: {deg}")

    # Singular points
    lc = L_ode.leading_coefficient()
    tc = L_ode.list()[_sage_const_0 ]
    print(f"\nLeading coefficient factorization:")
    print(f"  {lc.factor()}")
    print(f"\nTrailing coefficient factorization:")
    print(f"  {tc.factor()}")

    # Local exponents at singular points
    print("\n" + "="*_sage_const_60 )
    print("Local exponents at singular points")
    print("="*_sage_const_60 )

    sing_roots = lc.roots(QQbar)
    print(f"Number of singular points (finite): {len(sing_roots)}")
    for rt, mult in sing_roots:
        print(f"  z = {rt} (multiplicity {mult})")
        if rt.abs() < _sage_const_10 :
            try:
                indicial = L_ode.indicial_polynomial(z - QQ(rt) if rt in QQ else None)
                print(f"    Indicial polynomial: {indicial}")
            except:
                pass

except Exception as e:
    print(f"to_D conversion failed: {e}")
    import traceback
    traceback.print_exc()

    # Fallback: try guessing ODE from numerical data
    print("\nFallback: guessing ODE from q_n sequence...")
    R2 = PolynomialRing(QQ, names=('z',)); (z,) = R2._first_ngens(1)
    D_alg = OreAlgebra(R2, names=('Dz',)); (Dz,) = D_alg._first_ngens(1)

    # Use ore_algebra's guess with exact rational q_n
    for ord in [_sage_const_3 , _sage_const_4 , _sage_const_6 , _sage_const_9 , _sage_const_12 , _sage_const_15 , _sage_const_18 ]:
        try:
            L_guess = guess(q[:_sage_const_50 ], D_alg, order=ord)
            deg = max(c.degree() for c in L_guess.list())
            print(f"  ODE found: order={ord}, degree={deg}")
            print(f"  Leading: {L_guess.leading_coefficient().factor()}")
            break
        except:
            print(f"  order={ord}: no ODE found")

# ============================================================
# Also compute AESZ #209 ODE for comparison
# ============================================================
print("\n" + "="*_sage_const_60 )
print("AESZ #209 for comparison")
print("="*_sage_const_60 )

inner = []
for nn in range(_sage_const_60 ):
    inner.append(sum(binomial(nn,k)**_sage_const_2  * binomial(nn+k,nn) * binomial(nn+_sage_const_2 *k,nn)
                     for k in range(nn+_sage_const_1 )))

R2 = PolynomialRing(QQ, names=('z',)); (z,) = R2._first_ngens(1)
D_alg = OreAlgebra(R2, names=('Dz',)); (Dz,) = D_alg._first_ngens(1)

try:
    L_aesz = guess(inner[:_sage_const_60 ], D_alg, order=_sage_const_4 )
    print(f"AESZ ODE: order={L_aesz.order()}, degree={max(c.degree() for c in L_aesz.list())}")
    print(f"Leading: {L_aesz.leading_coefficient().factor()}")

    if 'L_ode' in dir():
        print(f"\nGCRD(L_p27_ode, L_aesz):")
        try:
            G = L_ode.gcrd(L_aesz)
            print(f"  Order: {G.order()}")
            if G.order() > _sage_const_0 :
                print("  *** NONTRIVIAL GCRD! ***")
            else:
                print("  GCRD = 1 (no common factor)")
        except Exception as e:
            print(f"  Error: {e}")
except Exception as e:
    print(f"AESZ guess failed: {e}")

print("\nDone.")
