#!/usr/bin/env sage
"""
Find the MINIMAL-ORDER ODE annihilating the P2.7 generating function.

The to_D() conversion gave order 21 which is inflated. The true minimal
order should be much lower. Strategy:
1. Compute 150+ exact q_n terms
2. Try guessing a D-finite ODE of increasing order
3. Verify annihilation
"""


# This file was *autogenerated* from the file scratchpad/p27_min_ode.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_160 = Integer(160); _sage_const_0 = Integer(0); _sage_const_215040420000 = Integer(215040420000); _sage_const_1 = Integer(1); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_60 = Integer(60); _sage_const_80 = Integer(80); _sage_const_120 = Integer(120); _sage_const_150 = Integer(150); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_18 = Integer(18); _sage_const_20 = Integer(20)
from ore_algebra import *
from ore_algebra import guess

# Recurrence coefficients as functions of QQ
Rn = PolynomialRing(QQ, names=('n',)); (n,) = Rn._first_ngens(1)

def Af(nn):
    nn = QQ(nn)
    return QQ(_sage_const_1024 )*(_sage_const_2 *nn+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *nn+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *nn**_sage_const_2 +_sage_const_6407 *nn+_sage_const_10860 )
def Bf(nn):
    nn = QQ(nn)
    return QQ(_sage_const_128 )*(_sage_const_2 *nn+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *nn**_sage_const_6 +_sage_const_1745370 *nn**_sage_const_5 +_sage_const_12145238 *nn**_sage_const_4 +_sage_const_44886481 *nn**_sage_const_3 +_sage_const_92943995 *nn**_sage_const_2 +_sage_const_102256019 *nn+_sage_const_46709052 )
def Cf(nn):
    nn = QQ(nn)
    return QQ(_sage_const_16 )*(nn+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *nn+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *nn**_sage_const_5 +_sage_const_57792 *nn**_sage_const_4 +_sage_const_351019 *nn**_sage_const_3 +_sage_const_1059230 *nn**_sage_const_2 +_sage_const_1587211 *nn+_sage_const_944620 )
def Df(nn):
    nn = QQ(nn)
    return (nn+_sage_const_3 )**_sage_const_4 *(nn+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *nn**_sage_const_2 +_sage_const_4515 *nn+_sage_const_5399 )

# Compute q_n with exact rationals
N_TERMS = _sage_const_160
q = [QQ(_sage_const_0 )] * N_TERMS
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

for nn in range(_sage_const_2 , N_TERMS - _sage_const_1 ):
    q[nn+_sage_const_1 ] = Bf(nn)/Af(nn)*q[nn] - Cf(nn-_sage_const_1 )/Af(nn-_sage_const_1 )*q[nn-_sage_const_1 ] + Df(nn-_sage_const_2 )/Af(nn-_sage_const_2 )*q[nn-_sage_const_2 ]

print(f"Computed {N_TERMS} exact q_n values")
print(f"q[0] = {q[_sage_const_0 ]}")
print(f"q[1] denom digits: {len(str(q[_sage_const_1 ].denominator()))}")
print(f"q[50] numer digits: {len(str(q[_sage_const_50 ].numerator()))}")
print(f"q[50] denom digits: {len(str(q[_sage_const_50 ].denominator()))}")
print(f"q[100] numer digits: {len(str(q[_sage_const_100 ].numerator()))}")
print(f"q[100] denom digits: {len(str(q[_sage_const_100 ].denominator()))}")

# Try to guess the minimal ODE
R2 = PolynomialRing(QQ, names=('z',)); (z,) = R2._first_ngens(1)
D_alg = OreAlgebra(R2, names=('Dz',)); (Dz,) = D_alg._first_ngens(1)

# Also set up the Sn algebra for guessing recurrence
Qn2 = Rn.fraction_field()
Sn_alg = OreAlgebra(Qn2, 'Sn', names=('Sn',)); (Sn,) = Sn_alg._first_ngens(1)

print("\n" + "="*_sage_const_60 )
print("Guessing minimal ODE from sequence")
print("="*_sage_const_60 )

# Try increasing orders
for n_terms in [_sage_const_80 , _sage_const_120 , _sage_const_150 ]:
    seq = q[:n_terms]
    for ord in [_sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_6 , _sage_const_9 , _sage_const_12 ]:
        for max_deg in [_sage_const_6 , _sage_const_8 , _sage_const_10 , _sage_const_12 , _sage_const_15 , _sage_const_18 ]:
            try:
                L = guess(seq, D_alg, order=ord, degree=max_deg)
                deg = max(c.degree() for c in L.list())
                # Verify on remaining terms
                ver_ok = True
                for k in range(n_terms, min(n_terms + _sage_const_10 , N_TERMS)):
                    val = sum(QQ(L.list()[i](z=_sage_const_0 )) * q[k] for i in range(ord + _sage_const_1 ))
                    if val != _sage_const_0 :
                        ver_ok = False
                        break
                status = "VERIFIED" if ver_ok else "failed verification"
                print(f"  order={ord}, deg={max_deg}, terms={n_terms}: "
                      f"FOUND (actual deg={deg}) [{status}]")
                if ver_ok:
                    print(f"    Leading coeff: {L.leading_coefficient().factor()}")
                    print(f"    Full operator:")
                    for i in range(ord + _sage_const_1 ):
                        print(f"      Dz^{i}: {L.list()[i].factor()}")
                    # Done!
                    raise StopIteration
            except StopIteration:
                raise
            except:
                pass
    print(f"  No ODE found with {n_terms} terms for orders 3-12, degrees 6-18")

print("\n" + "="*_sage_const_60 )
print("Trying to guess with Sn algebra (recurrence) as cross-check")
print("="*_sage_const_60 )

for ord in [_sage_const_3 ]:
    for max_deg in [_sage_const_12 , _sage_const_15 , _sage_const_18 , _sage_const_20 ]:
        try:
            L = guess(q[:_sage_const_80 ], Sn_alg, order=ord, degree=max_deg)
            deg = max(c.degree() for c in L.list())
            print(f"  Recurrence found: order={ord}, degree={deg}")
            print(f"  Leading: {L.leading_coefficient().factor()}")
        except:
            pass

print("\nDone.")
