"""
P-curvature computation for M₁₆.

If the p-curvature is 0 for all good primes, M₁₆ is globally nilpotent
(comes from geometry), which would strongly support the period interpretation.

Algorithm: Compute D^p mod M₁₆ in F_p(t)[D].
"""


# This file was *autogenerated* from the file scratchpad/p_curvature_m16.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_105 = Integer(105); _sage_const_22 = Integer(22); _sage_const_17 = Integer(17); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23)
from sage.all import *
from ore_algebra import OreAlgebra

# Build M₁₆ over Q(t)
Rn = PolynomialRing(QQ, names=('n',)); (n,) = Rn._first_ngens(1)
Kn = Rn.fraction_field()
Rt = PolynomialRing(QQ, names=('t',)); (t,) = Rt._first_ngens(1)
Kt = Rt.fraction_field()
OD = OreAlgebra(Kt, 'Dt', names=('Dt',)); (Dt,) = OD._first_ngens(1)
theta = Kt(t)*Dt

def eval_poly_at_op(f, T):
    out = OD.zero()
    for a in reversed(Rn(f).list()):
        out = out*T + Kt(a)
    return out

def primitive_coefficients(c):
    c = [Kn(a) for a in c]
    den = Rn.one()
    for a in c:
        den = lcm(den, Rn(a.denominator()))
    nums = [Rn(den*a) for a in c]
    g = nums[_sage_const_0 ]
    for a in nums[_sage_const_1 :]:
        g = gcd(g, a)
    nums = [a.quo_rem(g)[_sage_const_0 ] for a in nums]
    scl = QQ(_sage_const_1 )/QQ(nums[-_sage_const_1 ].leading_coefficient())
    return [Rn(scl*a) for a in nums]

# Original P2.7 rational recurrence
def A(z): return _sage_const_1024 *(_sage_const_2 *z+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *z**_sage_const_2 +_sage_const_6407 *z+_sage_const_10860 )
def B(z): return _sage_const_128 *(_sage_const_2 *z+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *z**_sage_const_6 +_sage_const_1745370 *z**_sage_const_5 +_sage_const_12145238 *z**_sage_const_4 +_sage_const_44886481 *z**_sage_const_3 +_sage_const_92943995 *z**_sage_const_2 +_sage_const_102256019 *z+_sage_const_46709052 )
def C(z): return _sage_const_16 *(z+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *z+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *z**_sage_const_5 +_sage_const_57792 *z**_sage_const_4 +_sage_const_351019 *z**_sage_const_3 +_sage_const_1059230 *z**_sage_const_2 +_sage_const_1587211 *z+_sage_const_944620 )
def D(z): return (z+_sage_const_3 )**_sage_const_4 *(z+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *z**_sage_const_2 +_sage_const_4515 *z+_sage_const_5399 )

crat = [Kn(-D(n)/A(n)), Kn(C(n+_sage_const_1 )/A(n+_sage_const_1 )), Kn(-B(n+_sage_const_2 )/A(n+_sage_const_2 )), Kn(_sage_const_1 )]
p_coeff = primitive_coefficients(crat)

# Build Euler quotient M₁₆
Rx = PolynomialRing(QQ, names=('x',)); (x,) = Rx._first_ngens(1)
shifted = [Rx(p_coeff[j](x-j)) for j in range(_sage_const_4 )]
gshift = shifted[_sage_const_0 ]
for f in shifted[_sage_const_1 :]:
    gshift = gcd(gshift, f)
gshift = gshift.monic()
assert gshift == x**_sage_const_2  + QQ(_sage_const_105 )/_sage_const_22 *x + QQ(_sage_const_5399 )/_sage_const_946

Rpoly = []
for f in shifted:
    q, rem = f.quo_rem(gshift)
    assert rem == _sage_const_0
    Rpoly.append(q)

M16 = OD.zero()
for j in range(_sage_const_4 ):
    M16 += Kt(t**j)*eval_poly_at_op(Rpoly[j], -theta-_sage_const_1 )
assert M16.order() == _sage_const_16
print(f"M16 order = {M16.order()}")
print(f"M16 leading term degree = {Rt(M16[_sage_const_16 ].numerator()).degree()}")

# Extract polynomial coefficients of M16 = Σ c_k(t) Dt^k
# Clear denominators to work over Z[t]
coeffs_M16 = [M16[k] for k in range(_sage_const_17 )]  # c_0(t) through c_16(t)

# Find common denominator
denom = Rt.one()
for c in coeffs_M16:
    c = Kt(c)
    denom = lcm(denom, Rt(c.denominator()))

int_coeffs = [Rt(denom * Kt(c)) for c in coeffs_M16]
print(f"\nCommon denominator degree = {denom.degree()}")
print(f"Integer coefficient degrees = {[c.degree() for c in int_coeffs]}")

# P-curvature: compute D^p mod L in F_p(t)[D]
# For L = sum c_k(t) D^k of order d, the p-curvature is the remainder of D^p mod L.

def p_curvature_mod(L_int_coeffs, p_prime, verbose=True):
    """
    Compute the p-curvature of L (given by integer polynomial coefficients)
    modulo a prime p.

    Returns the rank of the p-curvature matrix (order of D^p mod L).
    If result is 0, the p-curvature vanishes at this prime.
    """
    Fp = GF(p_prime)
    Rp = PolynomialRing(Fp, names=('tp',)); (tp,) = Rp._first_ngens(1)
    Kp = Rp.fraction_field()
    ODp = OreAlgebra(Kp, 'Dp', names=('Dp',)); (Dp,) = ODp._first_ngens(1)

    d = len(L_int_coeffs) - _sage_const_1   # order of L

    # Reduce coefficients mod p
    L_mod = ODp.zero()
    for k in range(d+_sage_const_1 ):
        poly_mod = Rp([Fp(c) for c in Rt(L_int_coeffs[k]).list()])
        L_mod += Kp(poly_mod) * Dp**k

    if L_mod == _sage_const_0 :
        if verbose:
            print(f"  p={p_prime}: operator is ZERO mod p (bad prime)")
        return -_sage_const_1

    # Check if leading coefficient vanishes
    if L_mod[d] == _sage_const_0 :
        if verbose:
            print(f"  p={p_prime}: leading coefficient vanishes (bad prime)")
        return -_sage_const_1

    # Compute D^p mod L
    # Start with D^1, repeatedly multiply by D and reduce
    # In ore_algebra: D * f(t) = f(t)*D + f'(t) (Leibniz rule)

    # Actually, use the right_quo_rem from ore_algebra
    Dp_power = Dp  # D^1
    for i in range(_sage_const_2 , p_prime + _sage_const_1 ):
        Dp_power = Dp_power * Dp
        # Reduce mod L
        if Dp_power.order() >= d:
            _, Dp_power = Dp_power.quo_rem(L_mod)
        if i % max(_sage_const_1 , p_prime // _sage_const_10 ) == _sage_const_0  and verbose:
            print(f"    step {i}/{p_prime}, current order = {Dp_power.order()}")

    # The p-curvature is D^p mod L
    pc_order = Dp_power.order() if Dp_power != _sage_const_0  else -_sage_const_1

    if verbose:
        if Dp_power == _sage_const_0 :
            print(f"  p={p_prime}: p-curvature = 0 (GLOBALLY NILPOTENT at this prime!)")
        else:
            print(f"  p={p_prime}: p-curvature has order {pc_order}")

    return pc_order if Dp_power != _sage_const_0  else _sage_const_0

# Check which primes are "good"
# The leading coefficient is t^16 * chi(t) where chi = t^3 - 55/64*t^2 + ...
# Clearing denominators of chi: 2^20 * chi(t) = 2^20*t^3 - 55*2^14*t^2 + 2^10*t - 1
print(f"\nLeading coefficient involves 2^20 in denominators")
print(f"Bad primes for chi: 2 (denominator factor)")

# Compute p-curvature for small primes
# Note: p must be > order for meaningful results, and computation of D^p is O(p^2)
# For order 16, smallest useful primes are 17, 19, 23, ...
# But even p=5 can be informative (just need p > 0)

print("\n=== P-curvature of M16 ===")
# Start with small primes for speed
for pp in [_sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 ]:
    print(f"\nPrime p = {pp}:")
    try:
        rank = p_curvature_mod(int_coeffs, pp)
    except Exception as e:
        print(f"  FAILED: {e}")

print("\nDone.")
