#!/usr/bin/env sage
"""
Test shifted Barnes integral J_{n+17/22} against P2.7 errors.
"""


# This file was *autogenerated* from the file scratchpad/shifted_barnes_test2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_150 = Integer(150); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_50 = Integer(50); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_0 = Integer(0); _sage_const_25 = Integer(25); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_7425 = Integer(7425); _sage_const_16 = Integer(16); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_15 = Integer(15); _sage_const_1024 = Integer(1024); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_17 = Integer(17); _sage_const_22 = Integer(22); _sage_const_1en100 = RealNumber('1e-100'); _sage_const_64 = Integer(64)
import mpmath
mpmath.mp.dps = _sage_const_150

def cotpi(t):
    return mpmath.cos(mpmath.pi * t) / mpmath.sin(mpmath.pi * t)

def R_nu(nu, t):
    return (mpmath.gamma(nu+_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(t) /
            (mpmath.gamma(_sage_const_1 -t)**_sage_const_3  * mpmath.gamma(nu+_sage_const_1 )**_sage_const_2  * mpmath.gamma(t+nu+_sage_const_1 )))

def integrand(nu, t):
    r = R_nu(nu, t)
    s = mpmath.pi / mpmath.sin(mpmath.pi * t)
    c = mpmath.pi * cotpi(t) - _sage_const_1
    return r * s**_sage_const_2  * c

def J_nu_contour(nu):
    """Compute J_ν via vertical contour at Re(t) = 1/2."""
    def f(y):
        t = mpmath.mpf('0.5') + _sage_const_1j  * y
        val = integrand(nu, t)
        return val / (_sage_const_2  * mpmath.pi * _sage_const_1j )

    result = mpmath.quad(f, [-_sage_const_50 , _sage_const_50 ], error=True, maxdegree=_sage_const_8 )
    return result

# ============================================================
# Sanity check: Zudilin at integer ν
# ============================================================
print("=== Sanity check: Zudilin J_n for integer n ===")

L = mpmath.zeta(_sage_const_2 ) + mpmath.zeta(_sage_const_3 )
print("ζ(2)+ζ(3) = %s" % mpmath.nstr(L, _sage_const_30 ))

# Compute a_n
a_list = []
for i in range(_sage_const_30 ):
    val = QQ(_sage_const_0 )
    for k in range(i+_sage_const_1 ):
        val += binomial(i,k)**_sage_const_2  * binomial(i+k,i) * binomial(i+_sage_const_2 *k,i)
    a_list.append(val)

# Zudilin companion via explicit sum
# p̃_n = Σ_{k=0}^n C(n,k)²C(n+k,k)C(n+2k,k) · S_n(k) where S_n(k) involves harmonic sums
# Alternatively, use the recurrence with known initial conditions
# p̃_0 = 0, p̃_1 = 20, p̃_2 = 7425/16
#
# rec_a: P_0(n)a_n + P_1(n)a_{n+1} + P_2(n)a_{n+2} + P_3(n)a_{n+3} = 0
# a_n satisfies (n+1)⁴a_{n+1} = (2n+1)(3+34n²+51n³+17n⁴)a_n - n⁴a_{n-1}
# Wait, AESZ #209 is order 3, but the well-known recurrence for a_n is order 2!
# Let me check.

# Actually, AESZ #209 operator is order 4 as a differential operator (CY4).
# The recurrence for a_n is order 2 (Apéry-like):
# (n+1)⁴ a_{n+1} - (2n+1)(17n² + 17n + 5) a_n + n⁴ a_{n-1} = 0
# Wait, that's for a different sequence. Let me check AESZ #209 specifically.

# AESZ #209: a_n = Σ C(n,k)²C(n+k,n)C(n+2k,n)
# Actually this might have order 3 recurrence.

# Let me just compute using ore_algebra with more terms
from ore_algebra import OreAlgebra, guess
Rn = PolynomialRing(QQ, 'nn')
nn_var = Rn.gen()
OS = OreAlgebra(Rn, 'Snn')

rec_a_op = guess(a_list[:_sage_const_25 ], OS, order=_sage_const_3 )
print("rec_a order: %d" % rec_a_op.order())
P_rec = [rec_a_op[j] for j in range(rec_a_op.order()+_sage_const_1 )]
for j in range(len(P_rec)):
    print("  P_%d degree %d" % (j, P_rec[j].degree()))

# Compute Zudilin companion
N_zud = _sage_const_10
p_zud = [QQ(_sage_const_0 )] * N_zud
p_zud[_sage_const_0 ] = QQ(_sage_const_0 )
p_zud[_sage_const_1 ] = QQ(_sage_const_20 )
p_zud[_sage_const_2 ] = QQ(_sage_const_7425 ) / QQ(_sage_const_16 )

for n_val in range(N_zud - rec_a_op.order()):
    val = sum(P_rec[j](nn=n_val) * p_zud[n_val + j] for j in range(rec_a_op.order()))
    p_zud[n_val + rec_a_op.order()] = -val / P_rec[rec_a_op.order()](nn=n_val)

print("\nZudilin errors:")
e_zud = []
for i in range(min(_sage_const_6 , N_zud)):
    ez = mpmath.mpf(p_zud[i]) - L * mpmath.mpf(a_list[i])
    e_zud.append(ez)
    print("  e^Z_%d = %s" % (i, mpmath.nstr(ez, _sage_const_25 )))

# Now compute J_n for integer n=1,2,3 and compare
print("\n--- J_n via contour integral ---")
for n_int in [_sage_const_1 , _sage_const_2 , _sage_const_3 ]:
    try:
        result = J_nu_contour(mpmath.mpf(n_int))
        j_val = result[_sage_const_0 ]
        print("J_%d = %s (err: %s)" % (n_int, mpmath.nstr(j_val, _sage_const_25 ), mpmath.nstr(result[_sage_const_1 ], _sage_const_5 )))
        if n_int < len(e_zud):
            ratio = j_val / e_zud[n_int]
            print("  J_%d / e^Z_%d = %s" % (n_int, n_int, mpmath.nstr(ratio, _sage_const_15 )))
    except Exception as ex:
        print("J_%d failed: %s" % (n_int, ex))

# ============================================================
# P2.7 errors
# ============================================================
def A_p27(n):
    return QQ(_sage_const_1024 ) * (_sage_const_2 *n+_sage_const_5 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )

def B_p27(n):
    return QQ(_sage_const_128 ) * (_sage_const_2 *n+_sage_const_7 )**_sage_const_3  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_104060 *n**_sage_const_6  + _sage_const_1745370 *n**_sage_const_5  +
        _sage_const_12145238 *n**_sage_const_4  + _sage_const_44886481 *n**_sage_const_3  + _sage_const_92943995 *n**_sage_const_2  + _sage_const_102256019 *n + _sage_const_46709052 )

def C_p27(n):
    return QQ(_sage_const_16 ) * (n+_sage_const_3 )**_sage_const_4  * (_sage_const_2 *n+_sage_const_9 )**_sage_const_3  * (_sage_const_3784 *n**_sage_const_5  + _sage_const_57792 *n**_sage_const_4  +
        _sage_const_351019 *n**_sage_const_3  + _sage_const_1059230 *n**_sage_const_2  + _sage_const_1587211 *n + _sage_const_944620 )

def D_p27(n):
    return QQ(_sage_const_1 ) * (n+_sage_const_3 )**_sage_const_4  * (n+_sage_const_4 )**_sage_const_6  * (_sage_const_946 *n**_sage_const_2  + _sage_const_4515 *n + _sage_const_5399 )

N_p27 = _sage_const_10
q = [QQ(_sage_const_0 )] * N_p27
q[_sage_const_0 ] = QQ(-_sage_const_215040420000 )
q[_sage_const_1 ] = QQ(-_sage_const_167282265043404 ) / QQ(_sage_const_905 )
q[_sage_const_2 ] = QQ(-_sage_const_964185327658080 ) / QQ(_sage_const_6071 )

p = [QQ(_sage_const_0 )] * N_p27
p[_sage_const_0 ] = QQ(-_sage_const_612218384750 )
p[_sage_const_1 ] = QQ(-_sage_const_9525021973931919 ) / QQ(_sage_const_18100 )
p[_sage_const_2 ] = QQ(-_sage_const_29561828382772029 ) / QQ(_sage_const_65380 )

for n in range(_sage_const_2 , N_p27-_sage_const_1 ):
    q[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * q[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * q[n-_sage_const_2 ]
    p[n+_sage_const_1 ] = B_p27(n)/A_p27(n) * p[n] - C_p27(n-_sage_const_1 )/A_p27(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_p27(n-_sage_const_2 )/A_p27(n-_sage_const_2 ) * p[n-_sage_const_2 ]

print("\nP2.7 errors:")
e_p27 = []
for i in range(min(_sage_const_8 , N_p27)):
    ep = mpmath.mpf(p[i].numerator()) / mpmath.mpf(p[i].denominator()) -          L * mpmath.mpf(q[i].numerator()) / mpmath.mpf(q[i].denominator())
    e_p27.append(ep)
    print("  e^P_%d = %s" % (i, mpmath.nstr(ep, _sage_const_25 )))

# ============================================================
# Shifted Barnes: J_{n+17/22}
# ============================================================
print("\n=== Shifted Barnes J_{n+17/22} ===")
J_shifted = []
for n_val in range(_sage_const_5 ):
    nu = n_val + mpmath.mpf(_sage_const_17 )/_sage_const_22
    print("Computing J_{%d+17/22} (ν = %.6f)..." % (n_val, float(nu)))
    try:
        result = J_nu_contour(nu)
        j_val = result[_sage_const_0 ]
        J_shifted.append(j_val)
        print("  J = %s (err: %s)" % (mpmath.nstr(j_val, _sage_const_25 ), mpmath.nstr(result[_sage_const_1 ], _sage_const_5 )))
    except Exception as ex:
        print("  FAILED: %s" % ex)
        J_shifted.append(None)

# Compare
print("\n=== Ratio J_{n+17/22} / e^P_n ===")
for i in range(min(len(J_shifted), len(e_p27))):
    if J_shifted[i] is not None and abs(e_p27[i]) > _sage_const_1en100 :
        ratio = J_shifted[i] / e_p27[i]
        print("n=%d: %s" % (i, mpmath.nstr(ratio, _sage_const_20 )))

# Also check if there's a simple gauge
print("\n=== J_{n+17/22} / (64^n · e^P_n) ===")
for i in range(min(len(J_shifted), len(e_p27))):
    if J_shifted[i] is not None and abs(e_p27[i]) > _sage_const_1en100 :
        ratio = J_shifted[i] / (mpmath.power(_sage_const_64 , i) * e_p27[i])
        print("n=%d: %s" % (i, mpmath.nstr(ratio, _sage_const_20 )))
