"""
Verify σ=0 numerically by checking q_n / μ₀^n → constant.
If σ≠0, the ratio would grow/decay as n^{-σ}.

Also compute the adjoint bracket numerically.
"""


# This file was *autogenerated* from the file scratchpad/verify_sigma_zero.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1024 = Integer(1024); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_946 = Integer(946); _sage_const_6407 = Integer(6407); _sage_const_10860 = Integer(10860); _sage_const_128 = Integer(128); _sage_const_104060 = Integer(104060); _sage_const_6 = Integer(6); _sage_const_1745370 = Integer(1745370); _sage_const_12145238 = Integer(12145238); _sage_const_44886481 = Integer(44886481); _sage_const_92943995 = Integer(92943995); _sage_const_102256019 = Integer(102256019); _sage_const_46709052 = Integer(46709052); _sage_const_16 = Integer(16); _sage_const_3784 = Integer(3784); _sage_const_57792 = Integer(57792); _sage_const_351019 = Integer(351019); _sage_const_1059230 = Integer(1059230); _sage_const_1587211 = Integer(1587211); _sage_const_944620 = Integer(944620); _sage_const_4515 = Integer(4515); _sage_const_5399 = Integer(5399); _sage_const_612218384750 = Integer(612218384750); _sage_const_9525021973931919 = Integer(9525021973931919); _sage_const_18100 = Integer(18100); _sage_const_29561828382772029 = Integer(29561828382772029); _sage_const_65380 = Integer(65380); _sage_const_215040420000 = Integer(215040420000); _sage_const_167282265043404 = Integer(167282265043404); _sage_const_905 = Integer(905); _sage_const_964185327658080 = Integer(964185327658080); _sage_const_6071 = Integer(6071); _sage_const_300 = Integer(300); _sage_const_1 = Integer(1); _sage_const_500 = Integer(500); _sage_const_220 = Integer(220); _sage_const_8 = Integer(8); _sage_const_64 = Integer(64); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_99 = Integer(99); _sage_const_20 = Integer(20); _sage_const_30 = Integer(30); _sage_const_50 = Integer(50); _sage_const_80 = Integer(80); _sage_const_150 = Integer(150); _sage_const_200 = Integer(200); _sage_const_250 = Integer(250)
from sage.all import *

# Recurrence coefficients
def A_raw(n): return _sage_const_1024 *(_sage_const_2 *n+_sage_const_5 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_946 *n**_sage_const_2 +_sage_const_6407 *n+_sage_const_10860 )
def B_raw(n): return _sage_const_128 *(_sage_const_2 *n+_sage_const_7 )**_sage_const_3 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_104060 *n**_sage_const_6 +_sage_const_1745370 *n**_sage_const_5 +_sage_const_12145238 *n**_sage_const_4 +_sage_const_44886481 *n**_sage_const_3 +_sage_const_92943995 *n**_sage_const_2 +_sage_const_102256019 *n+_sage_const_46709052 )
def C_raw(n): return _sage_const_16 *(n+_sage_const_3 )**_sage_const_4 *(_sage_const_2 *n+_sage_const_9 )**_sage_const_3 *(_sage_const_3784 *n**_sage_const_5 +_sage_const_57792 *n**_sage_const_4 +_sage_const_351019 *n**_sage_const_3 +_sage_const_1059230 *n**_sage_const_2 +_sage_const_1587211 *n+_sage_const_944620 )
def D_raw(n): return (n+_sage_const_3 )**_sage_const_4 *(n+_sage_const_4 )**_sage_const_6 *(_sage_const_946 *n**_sage_const_2 +_sage_const_4515 *n+_sage_const_5399 )

# Initial conditions
p = [QQ(-_sage_const_612218384750 ), QQ(-_sage_const_9525021973931919 )/QQ(_sage_const_18100 ), QQ(-_sage_const_29561828382772029 )/QQ(_sage_const_65380 )]
q = [QQ(-_sage_const_215040420000 ), QQ(-_sage_const_167282265043404 )/QQ(_sage_const_905 ), QQ(-_sage_const_964185327658080 )/QQ(_sage_const_6071 )]

N_MAX = _sage_const_300
for _ in range(N_MAX - _sage_const_2 ):
    n = len(p) - _sage_const_1
    p_new = B_raw(n)/A_raw(n) * p[n] - C_raw(n-_sage_const_1 )/A_raw(n-_sage_const_1 ) * p[n-_sage_const_1 ] + D_raw(n-_sage_const_2 )/A_raw(n-_sage_const_2 ) * p[n-_sage_const_2 ]
    q_new = B_raw(n)/A_raw(n) * q[n] - C_raw(n-_sage_const_1 )/A_raw(n-_sage_const_1 ) * q[n-_sage_const_1 ] + D_raw(n-_sage_const_2 )/A_raw(n-_sage_const_2 ) * q[n-_sage_const_2 ]
    p.append(QQ(p_new))
    q.append(QQ(q_new))

print(f"Computed {len(p)} terms")

# Poincaré root
RR500 = RealField(_sage_const_500 )
R_poly = PolynomialRing(QQ, 'x')
x = R_poly.gen()
P_cubic = _sage_const_4 *x**_sage_const_3  - _sage_const_220 *x**_sage_const_2  + _sage_const_8 *x - _sage_const_1
CC500 = ComplexField(_sage_const_500 )
roots = P_cubic.change_ring(CC500).roots(multiplicities=False)
mu0_full = max(roots, key=lambda z: z.real())
mu0 = RR500(mu0_full.real())
mu_poincare = mu0 / _sage_const_64   # actual Poincaré root

print(f"\nμ₀ (root of 4x³-220x²+8x-1) = {float(mu0):.15f}")
print(f"μ_Poincaré = μ₀/64 = {float(mu_poincare):.15f}")
print(f"q_1/q_0 = {float(RR500(q[_sage_const_1 ])/RR500(q[_sage_const_0 ])):.15f}")
print(f"q_10/q_9 = {float(RR500(q[_sage_const_10 ])/RR500(q[_sage_const_9 ])):.15f}")
print(f"q_100/q_99 = {float(RR500(q[_sage_const_100 ])/RR500(q[_sage_const_99 ])):.15f}")

# Test: q_n / μ_Poincaré^n should converge to a constant if σ=0
print("\n=== Test σ=0: q_n / μ^n should converge ===")
print(f"{'n':>5} | {'q_n/μ**n':>30} | {'ratio(n)/ratio(n-_sage_const_1 )':>20}")
prev_ratio = None
for nn in [_sage_const_10 , _sage_const_20 , _sage_const_30 , _sage_const_50 , _sage_const_80 , _sage_const_100 , _sage_const_150 , _sage_const_200 , _sage_const_250 , _sage_const_300 ]:
    if nn >= len(q):
        break
    ratio = RR500(q[nn]) / mu_poincare**nn
    if prev_ratio is not None and prev_ratio != _sage_const_0 :
        change = ratio / prev_ratio
        print(f"{nn:5d} | {float(ratio):30.15e} | {float(change):20.15f}")
    else:
        print(f"{nn:5d} | {float(ratio):30.15e} | ---")
    prev_ratio = ratio

# If σ≠0, q_n/μ^n ~ C·n^{-σ}, so log(ratio_n/ratio_m) / log(n/m) → -σ
print("\n=== Extract effective σ from consecutive ratios ===")
ratios = []
for nn in range(_sage_const_50 , _sage_const_300 ):
    if nn >= len(q):
        break
    ratios.append((nn, RR500(q[nn]) / mu_poincare**nn))

for i in range(_sage_const_0 , len(ratios)-_sage_const_50 , _sage_const_50 ):
    n1, r1 = ratios[i]
    n2, r2 = ratios[i+_sage_const_50 ]
    if r1 != _sage_const_0  and r2 != _sage_const_0 :
        effective_sigma = -RR500(log(abs(r2/r1))) / RR500(log(RR500(n2)/RR500(n1)))
        print(f"  n={n1}→{n2}: effective σ = {float(effective_sigma):.10f}")

# Compute L = ζ(2) + ζ(3)
from mpmath import mp, zeta as mpzeta
mp.dps = _sage_const_200
L_mp = mpzeta(_sage_const_2 ) + mpzeta(_sage_const_3 )
L = RR500(L_mp)

# Compute the error ratio more carefully
print(f"\n=== Error e_n = p_n - L*q_n asymptotic ===")
mu_sub = min(roots, key=lambda z: abs(z))  # subdominant root
mu_sub_poincare = mu_sub / _sage_const_64
print(f"|μ±/64| = {float(abs(mu_sub_poincare)):.15f}")

for nn in [_sage_const_50 , _sage_const_100 , _sage_const_150 , _sage_const_200 , _sage_const_250 ]:
    if nn >= len(q):
        break
    e_n = RR500(p[nn]) - L * RR500(q[nn])
    rate = abs(e_n)**(QQ(_sage_const_1 )/nn)
    # e_n / (μ_sub_poincare^n) should converge if σ=0 for subdominant too
    print(f"  n={nn}: |e_n|^(1/n) = {float(rate):.12f}, target |μ±/64| = {float(abs(mu_sub_poincare)):.12f}")

# Direct ratio p_n/q_n convergence
print(f"\n=== p_n/q_n convergence to L ===")
for nn in [_sage_const_10 , _sage_const_50 , _sage_const_100 , _sage_const_200 , _sage_const_300 ]:
    if nn >= len(q):
        break
    if q[nn] != _sage_const_0 :
        ratio = RR500(p[nn]) / RR500(q[nn])
        diff = ratio - L
        if diff != _sage_const_0 :
            digits = -float(log(abs(diff), _sage_const_10 ))
            print(f"  n={nn}: p_n/q_n - L = {float(diff):.5e}, matching digits ≈ {digits:.0f}")

print("\nDone.")
