name = "Ramanujan23"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Ramanujan23"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "Ramanujan23"
